### PR TITLE
tools/ci: upgrade to the latest Xtensa ESP32 toolchains

### PR DESCRIPTION
**Pull request by pkarashchenko**
## Summary
Upgrade Xtensa ESP32 toolchains on CI

## Impact
Hope to be none

## Testing
Pass CI

### CODE REVIEW

**Comment by tmedicci** [comment]
Hi @pkarashchenko , could you test for thrown warnings during compilation? Just to make sure: our ci does not compile with `-Werror`, right?

**Comment by tmedicci** [comment]
Just a nitpick: the more appropriate title would be: "tools/ci: upgrade to the latest ESP32 **xtensa** toolchains"

**Comment by pkarashchenko** [comment]
> Hi @pkarashchenko , could you test for thrown warnings during compilation? Just to make sure: our ci does not compile with `-Werror`, right?  

Yes. I will rebuild locally and test configurations. Actually I'm using GCC 11 on MAC for ESP32 and some of the configurations that I use are compiled without errors.
I will upgrade to GCC 12 and run build for all ESP32 configurations. Let's mark this as Draft fro now

**Review by acassis — APPROVED** [review]

**Comment by acassis** [comment]
not only CI will fail when -Werror is enabled, but many configurations where #warning flag is used in the source code. i.e. bluetooth, flash, etc

**Comment by pkarashchenko** [comment]
I think we already upgraded to GCC 12 for ARM, so most of the common issues should be already fixed.

**Comment by tmedicci** [comment]
Hi @pkarashchenko !

I've caught some warnings regarding the defconfigs `esp32-devkitc:audio` and `:cxx`. Could you please take a look?

**Comment by pkarashchenko** [comment]
Yes, of course. I'm still traveling from EW2023, so can't even find the "concert to draft" option in the mobile version of the GitHub :(
I will take a look when I arrive

**Comment by tmedicci** [comment]
> Yes, of course. I'm still traveling from EW2023, so can't even find the "concert to draft" option in the mobile version of the GitHub :( I will take a look when I arrive

No problems at all! Have a nice conference and say hello to our community colleagues!

**Comment by pkarashchenko** [comment]
@tmedicci I've tested many Xtensa configurations today (definitely not all available). Could you please try this PR? The issues in `esp32-devkitc:audio` and `:cxx` are fixed now

**Comment by tmedicci** [comment]
> @tmedicci I've tested many Xtensa configurations today (definitely not all available). Could you please try this PR? The issues in `esp32-devkitc:audio` and `:cxx` are fixed now

I'll try it right now. Just a moment.

**Review by tmedicci — APPROVED** [review]
We've updated our internal CI and everything is building without warnings (we treat them as errors). Nice work, @pkarashchenko !

**Comment by tmedicci** [comment]
This PR may be reopened, @pkarashchenko !

@gustavonihei , Do you want to take a look at it?

**Review by gustavonihei — APPROVED** [review]

**Pull request merged**
