### PR TITLE
[ci] platforms: added toolchains

### PR DESCRIPTION
**Pull request by simbit18**
## Summary

add toolchains for macOS on Apple Intel

xtensa-esp32s2
xtensa-esp32s3

add toolchains for macOS on Apple Silicon

xtensa-esp32s2
xtensa-esp32s3

add install for ubuntu.sh

xtensa-esp32s2
xtensa-esp32s3

add install for linux.sh

xtensa-esp32s2
xtensa-esp32s3

## Impact

Impact on user: No changes to user-facing functionality
Impact on build: Build process remains the same

## Testing
github macos-13 and macos-14

macOS on Apple Silicon and Intel  esp32s3
```
====================================================================================
Configuration/Tool: esp32s3-devkit/cxx
2024-11-25 12:39:41
------------------------------------------------------------------------------------
  Cleaning...
  Configuring...
  Building NuttX...
  Normalize esp32s3-devkit/cxx
====================================================================================
Configuration/Tool: esp32s3-devkit/nsh
2024-11-25 12:41:02
------------------------------------------------------------------------------------
  Cleaning...
  Configuring...
  Building NuttX...
  Normalize esp32s3-devkit/nsh
====================================================================================
```
macOS on Apple Silicon and Intel  esp32s2

```
====================================================================================
Configuration/Tool: esp32s2-saola-1/watchdog
2024-11-25 12:20:22
------------------------------------------------------------------------------------
  Cleaning...
  Configuring...
  Building NuttX...
  Normalize esp32s2-saola-1/watchdog
====================================================================================
Configuration/Tool: esp32s2-saola-1/ostest
2024-11-25 12:22:52
------------------------------------------------------------------------------------
  Cleaning...
  Configuring...
  Building NuttX...
  Normalize esp32s2-saola-1/ostest
====================================================================================

```

### CODE REVIEW

**Comment by nuttxpr** [comment]
[**\[Experimental Bot, please feedback here\]**](https://github.com/search?q=repo%3Aapache%2Fnuttx+13552&type=issues)



This PR appears to mostly meet the NuttX requirements, but it's missing some crucial information and could be significantly improved.

**Strengths:**

* Provides a summary of the changes (adding toolchains for macOS and Ubuntu/Linux).
* Addresses the impact on the user and build process.
* Includes testing logs demonstrating successful builds on macOS for both ESP32S2 and ESP32S3.

**Weaknesses:**

* **Missing Key Impact Details:** The impact section is incomplete.  It needs to address:
    * **Impact on hardware:**  Does this affect any specific architectures, boards, or drivers?  Even if the answer is no, explicitly state it.
    * **Impact on documentation:** Does this change require documentation updates? If so, were they provided in the PR?
    * **Impact on security:**  Are there any security implications?  Even if the answer is no, explicitly state it.
    * **Impact on compatibility:** Are there any backward, forward, or interoperability compatibility concerns? Again, even if the answer is no, explicitly state it.
* **Vague Summary:** The summary mentions adding toolchains but doesn't explain *why* this is necessary. What problem does this solve?  Is it to support newer versions of macOS?  Is it to fix a bug? More context is needed.
* **Unclear "How it Works":** The summary lacks a description of *how* the change was implemented.  Where were these toolchains added? Were files modified?  New files added?
* **Missing Issue References:** Are there any related NuttX or NuttX Apps issues that prompted this change?  If so, they should be linked.
* **Insufficient Testing Details:** While testing logs are provided, they lack detail.  
    * Specify the *exact* macOS versions (e.g., macOS 13.5) and compiler versions used.
    * Specify the full paths to the configurations tested (e.g., `nuttx/configs/esp32s3-devkit/cxx`).
    * Ubuntu/Linux testing is mentioned but no logs are provided. Add those logs.
    * Consider adding a brief description of the tests performed.  Did you just build, or did you also run any functional tests on the target hardware?
* **"Anything else to consider?"** This important question from the template is omitted.

**Recommendations for Improvement:**

1. **Expand the Summary:** Explain the *motivation* for the change.  What problem does it solve?  Be more specific about *what* was changed (files, configurations, etc.).
2. **Complete the Impact Section:**  Address *all* the points listed in the template, even if the answer is "NO".  Provide justification for your answers.
3. **Provide More Detailed Testing Information:** Include specific versions of OS, compilers, and full paths to configurations. Add the missing Ubuntu/Linux testing logs. Describe the tests performed.
4. **Include Issue References:** Link any related issues.
5. **Address "Anything else to consider?":** Even if there's nothing else, explicitly state that.

By addressing these weaknesses, the PR will be much stronger and easier for reviewers to evaluate.  Clear, concise, and complete information is essential for a smooth and efficient review process.

**Review by xiaoxiang781216 — APPROVED** [review]

**Review by lupyuen — APPROVED** [review]
Thank you so much @simbit18! :-)

**Review by lupyuen — APPROVED** [review]
Tested OK on macOS M2 Pro thanks!
https://gist.github.com/lupyuen/6b51580a5df6d86872b529b9e0174626
```text
$ git clone https://github.com/simbit18/nuttx --branch simbit18-darwin
$ nuttx/tools/testbuild.sh -A -R -j 12 -e '-Wno-cpp -Werror' testlist/xtensa-02.dat
Configuration/Tool: esp32s2-saola-1/spiflash
  Building NuttX...
  Normalize esp32s2-saola-1/spiflash
```
Previously xtensa-02 fails with ["xtensa-esp32s2-elf-gcc: command not found"](https://gist.github.com/lupyuen/3fdc3bb0268cf8d8c95603cf906a02a2)

**Comment by simbit18** [comment]
@lupyuen Is there a particular reason why you do not use the -S option?

`nuttx/tools/testbuild.sh -A -R -j 12 -e '-Wno-cpp -Werror' testlist/xtensa-02.dat`

option -S 
`nuttx/tools/testbuild.sh -A -R  -S -j 12 -e '-Wno-cpp -Werror' testlist/xtensa-02.dat`

https://github.com/apache/nuttx/pull/13301#issuecomment-2333645542

PR https://github.com/apache/nuttx/pull/13301

**Comment by lupyuen** [comment]
Oops sorry should be this:
https://github.com/apache/nuttx/blob/master/.github/workflows/build.yml#L250
```text
  macOS: ...
          cd sources/nuttx/tools/ci
          ./cibuild.sh -i -c -A -R testlist/${{matrix.boards}}.dat
```

**Comment by simbit18** [comment]
now if you use it it saves you minutes of build time

**Comment by lupyuen** [comment]
Yep that should be helpful for normal builds. For macOS Build Farm: We're replicating the same Build Environment as GitHub Actions, so we'll stick to the current settings. Thanks!

**Pull request merged**
