### PR TITLE
Sync the modifications of the WiFi function in simulator.

### PR DESCRIPTION
**Pull request by liqinhuixm**
## Summary
When using the simwifi function, solved some problems  and need to synchronize to the community.
## Impact
N/A
## Testing
Locally verified.

### CODE REVIEW

**Comment by acassis** [comment]
@liqinhuixm there is not Documentation/ to simwifi please include an entry to it.

**Comment by liqinhuixm** [comment]
@acassis  [https://github.com/apache/nuttx/blob/master/tools/simwifi/README](url) This is a brief introduction to the simwifi function.

**Comment by acassis** [comment]
@liqinhuixm we don't use README inside the source code anymore, please convert this file to the format used currently by our Documentation/ to it will show up at https://nuttx.apache.org/docs/latest/index.html

**Comment by liqinhuixm** [comment]
@acassis OK. I'll finish the work later.

**Pull request merged**
