### PR TITLE
Modified  ESP32S3 chip names and added "ARCH_CHIP_ESP32S3CUSTOM" chip module

### PR DESCRIPTION
**Pull request by devansh-dp**
## Summary
ESP32S3 chips come with multiple configuration of PSRAM and SPI-Flash sizes. (Refer to Page no.: 3 of this datasheet https://www.espressif.com/sites/default/files/documentation/esp32-s3-wroom-1_wroom-1u_datasheet_en.pdf). By default the configuration in **arch/xtensa/src/esp32s3/Kconfig** uses **select** command based on chip selection. This command restricts the flash size and PSRAM based on selected chip. Because of this, they cannot be modified in menuconfig. In this case the correct configurations can be made by manually editing the .config file and declaring correct variables there. This process is not ideal when working on a project where configuration regenerates multiple times.
 Therefore some modifications were done to simplify the process:
1. Instead of using **select** statement with chip selection, **conditional default** is used in Flash size and PSRAM size. This ensures that user can select the correct FLASH and PSRAM size based on the chip specification after configuration is generated. 
2. Flash Size variables are now declared with a prompt so they are visible in menuconfig and can be modified easily based on chip specifications. Initially these variables were not declared with prompt message, hence they were skipped while .config file is generated from /tools/configure.sh script.
3. Flash size variables are moved under SPI Flash menu making easier to find SPI Flash configurations in one place.
4. ESP32S3-WROOM2 chips are set with 8 MB PSRAM by default. Selecting these chips/boards will enable SPI_RAM_SUPPORT by default. ESP32S3_PSRAM_8M variable is set with a prompt now and moved under SPIRAM Config Menu.

## Impact
ESP32S3 configuration can be set correctly based on chip specifications

## Testing
Tested /tools/checkpatch script and no errors
Tested ./tools/configure.sh with multiple esp32s3 targets and no errors found. Conditions added in Kconfig file are working as expected.

### CODE REVIEW

**Comment by tmedicci** [comment]
Hi! First of all, thanks for submitting this PR ;)

The proposed workaround has some design flaws: although I agree that the user may be able to select the Flash and PSRAM size, this change may lead to unexpected errors. We have two alternatives that are being mixed here:
1. Let the module name more generic (independent of the variants) (like `ARCH_CHIP_ESP32S3WROOM1`, `ARCH_CHIP_ESP32S3WROOM2`) and then select the flash size and psram;
**OR (mutually exclusive):**
2. Create the variants as modules and select the flash size/psram size automatically (by using `select`): this was partially done for `ARCH_CHIP_ESP32S3WROOM2_32M`.

See, both alternatives should not coexist. Particularly, I see a problem with the 1st approach: whenever we select a module which is not previously set for a specific `defconfig`, although we have changed the `default` for the flash size, it won't change (requiring the user to change it manually). For instance,  `esp32s3-devkit:sta_softap` selects `ARCH_CHIP_ESP32S3WROOM1` by default. In your implementation, the choice `FLASH_SIZE` will select `ESP32S3_FLASH_4M` by default (as expected). But if I change the module being used for `ARCH_CHIP_ESP32S3WROOM2`, the choice would not change accordingly (although the default is `ESP32S3_FLASH_16M` now, the selected choice will still be the `ESP32S3_FLASH_4M`).

My suggestion:
Let's keep with the 2nd approach: trying to cover all the possible chip modules. Instead of `ARCH_CHIP_ESP32S3WROOM2_32M`, lets define `ARCH_CHIP_ESP32S3WROOM2N32R8V` and `ARCH_CHIP_ESP32S3WROOM2N16R8V`. These variants select Flash Size and PSRAM size as previously (by using `select`). Then, we need to create a custom module that enables the user to select flash size and PSRAM. Something like `ARCH_CHIP_ESP32S3CUSTOM` and:
```
choice ESP32S3_FLASH_SIZE
	prompt "Custom Module Flash Size"
	depends on ARCH_CHIP_ES32S3CUSTOM
	default ESP32S3CUSTOM_FLASH_4M

	config ESP32S3CUSTOM_FLASH_4M
		bool "ESP32S3 Flash 4MB"
		select ESP32S3_FLASH_4M

	config ESP32S3CUSTOM_FLASH_8M
		bool "ESP32S3 Flash 8MB"
		select ESP32S3_FLASH_8M

	config ESP32S3CUSTOM_FLASH_16M
		bool "ESP32S3 Flash 16MB"
		select ESP32S3_FLASH_16M

	config ESP32S3CUSTOM_FLASH_32M
		bool "ESP32S3 Flash 32MB"
		select ESP32S3_FLASH_32M
		select ESP32S3_SPI_FLASH_USE_32BIT_ADDRESS
endchoice # FLASH_SIZE
```

**Review by tmedicci — CHANGES_REQUESTED** [review]
https://github.com/apache/nuttx/pull/12530#issuecomment-2178693051

**Comment by devansh-dp** [comment]
Hi @tmedicci , thank you for the suggestion. 
I see the flaw here, if I select a different chip it does not select its correct configuration automatically. Initially I was opting to create another chip module itself for custom configuration but I was worried about some dependencies might crash. Let me try once with the example you have mentioned.
I have a question:

If we change `ARCH_CHIP_ESP32S3WROOM2` to `ARCH_CHIP_ESP32S3WROOM2N16R8V` in that case we need to regenerate all the defconfig files associated with this configuration. Like in  /board/xtensa/esp32s3/esp32s3-lcd-ev/lvgl. Should I go ahead with the changes and regenerate defconfigs ?

**Comment by tmedicci** [comment]
> Hi @tmedicci , thank you for the suggestion. I see the flaw here, if I select a different chip it does not select its correct configuration automatically. Initially I was opting to create another chip module itself for custom configuration but I was worried about some dependencies might crash. Let me try once with the example you have mentioned. I have a question:
> 
> If we change `ARCH_CHIP_ESP32S3WROOM2` to `ARCH_CHIP_ESP32S3WROOM2N16R8V` in that case we need to regenerate all the defconfig files associated with this configuration. Like in /board/xtensa/esp32s3/esp32s3-lcd-ev/lvgl. Should I go ahead with the changes and regenerate defconfigs ?

Go ahead!

The `./tools/refresh.sh --silent chip:esp32c3` command is your best friend here ;)

**Comment by devansh-dp** [comment]
> > Hi @tmedicci , thank you for the suggestion. I see the flaw here, if I select a different chip it does not select its correct configuration automatically. Initially I was opting to create another chip module itself for custom configuration but I was worried about some dependencies might crash. Let me try once with the example you have mentioned. I have a question:
> > If we change `ARCH_CHIP_ESP32S3WROOM2` to `ARCH_CHIP_ESP32S3WROOM2N16R8V` in that case we need to regenerate all the defconfig files associated with this configuration. Like in /board/xtensa/esp32s3/esp32s3-lcd-ev/lvgl. Should I go ahead with the changes and regenerate defconfigs ?
> 
> Go ahead!
> 
> The `./tools/refresh.sh --silent chip:esp32s3` command is your best friend here ;)

Hi @tmedicci , I performed some changes:

- changed 'ARCH_CHIP_ESP32S3WROOM2' to 'ARCH_CHIP_ESP32S3WROOM2N16R8V'
- changed 'ARCH_CHIP_ESP32S3WROOM2_32M' to 'ARCH_CHIP_ESP32S3WROOM2N32R8V'
- changed 'ARCH_CHIP_ESP32S3WROOM1' to 'ARCH_CHIP_ESP32S3WROOM1N4'
- changed 'ARCH_CHIP_ESP32S3MINI1' to 'ARCH_CHIP_ESP32S3MINI1N8'
- Added a custom chip module 'ARCH_CHIP_ESP32S3CUSTOM' the way it was suggested.
- Accordingly all the defconfigs are updated to point to correct chip name based on their configuration and '/tools/refresh.sh' worked without any errors.
- I have updated the ESP32S3_PSRAM_8M option with a prompt so user can select if required.
- Also updated the /boards/kconfig file with the new chip names

Let me know if this looks good. :)

**Comment by tmedicci** [comment]
> > > Hi @tmedicci , thank you for the suggestion. I see the flaw here, if I select a different chip it does not select its correct configuration automatically. Initially I was opting to create another chip module itself for custom configuration but I was worried about some dependencies might crash. Let me try once with the example you have mentioned. I have a question:
> > > If we change `ARCH_CHIP_ESP32S3WROOM2` to `ARCH_CHIP_ESP32S3WROOM2N16R8V` in that case we need to regenerate all the defconfig files associated with this configuration. Like in /board/xtensa/esp32s3/esp32s3-lcd-ev/lvgl. Should I go ahead with the changes and regenerate defconfigs ?
> > 
> > 
> > Go ahead!
> > The `./tools/refresh.sh --silent chip:esp32s3` command is your best friend here ;)
> 
> Hi @tmedicci , I performed some changes:
> 
> * changed `ARCH_CHIP_ESP32S3WROOM2` to `ARCH_CHIP_ESP32S3WROOM2N16R8V`
> * changed `ARCH_CHIP_ESP32S3WROOM2_32M` to `ARCH_CHIP_ESP32S3WROOM2N32R8V`
> * changed `ARCH_CHIP_ESP32S3WROOM1` to `ARCH_CHIP_ESP32S3WROOM1N4`
> * changed `ARCH_CHIP_ESP32S3MINI1` to `ARCH_CHIP_ESP32S3MINI1N8`
> * Added a custom chip module `ARCH_CHIP_ESP32S3CUSTOM` the way it was suggested.
> * Accordingly all the defconfigs are updated to point to correct chip name based on their configuration and '/tools/refresh.sh' worked without any errors.
> * I have updated the `ESP32S3_PSRAM_8M` option with a prompt so user can select if required.
> * Also updated the /boards/kconfig file with the new chip names
> 
> Let me know if this looks good. :)

Thanks!

I will trigger our internal CI to make sure everything works as expected... come back soon with the results.

**Comment by acassis** [comment]
@tmedicci since it passed, please merge or remove the Changes requested to let us to merge

**Review by tmedicci — APPROVED** [review]

**Comment by tmedicci** [comment]
> > > Hi @tmedicci , thank you for the suggestion. I see the flaw here, if I select a different chip it does not select its correct configuration automatically. Initially I was opting to create another chip module itself for custom configuration but I was worried about some dependencies might crash. Let me try once with the example you have mentioned. I have a question:
> > > If we change `ARCH_CHIP_ESP32S3WROOM2` to `ARCH_CHIP_ESP32S3WROOM2N16R8V` in that case we need to regenerate all the defconfig files associated with this configuration. Like in /board/xtensa/esp32s3/esp32s3-lcd-ev/lvgl. Should I go ahead with the changes and regenerate defconfigs ?
> > 
> > 
> > Go ahead!
> > The `./tools/refresh.sh --silent chip:esp32s3` command is your best friend here ;)
> 
> Hi @tmedicci , I performed some changes:
> 
> * changed `ARCH_CHIP_ESP32S3WROOM2` to `ARCH_CHIP_ESP32S3WROOM2N16R8V`
> * changed `ARCH_CHIP_ESP32S3WROOM2_32M` to `ARCH_CHIP_ESP32S3WROOM2N32R8V`
> * changed `ARCH_CHIP_ESP32S3WROOM1` to `ARCH_CHIP_ESP32S3WROOM1N4`
> * changed `ARCH_CHIP_ESP32S3MINI1` to `ARCH_CHIP_ESP32S3MINI1N8`
> * Added a custom chip module `ARCH_CHIP_ESP32S3CUSTOM` the way it was suggested.
> * Accordingly all the defconfigs are updated to point to correct chip name based on their configuration and '/tools/refresh.sh' worked without any errors.
> * I have updated the `ESP32S3_PSRAM_8M` option with a prompt so user can select if required.
> * Also updated the /boards/kconfig file with the new chip names
> 
> Let me know if this looks good. :)

Approved. Nice job, thanks!

**Comment by xiaoxiang781216** [comment]
@devansh-dp please drop the first two patch from PR.

**Comment by devansh-dp** [comment]
> @devansh-dp please drop the first two patch from PR.

Sure, First 2 commits are dropped now. 
Also changing the subject line of this PR for better clarity.

**Review by xiaoxiang781216 — APPROVED** [review]

**Pull request merged**
