### PR TITLE
compiler/diagnostic: Replace all #warning to #pragma message

### PR DESCRIPTION
**Pull request by anchao**
## Summary

compiler/diagnostic: Replace all #warning to #pragma message

Since some compilers(MSVC) do not support the syntax of "#warning", use "#pragma message" to enhance portability

D:\archer\code\nuttx\net\can\can_sockif.c(680,1): fatal  error C1021: invalid preprocessor command

Reference:
https://learn.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/fatal-error-c1021?view=msvc-170

Signed-off-by: chao an <anchao@xiaomi.com>

## Impact

N/A

## Testing

cmake + visual studio 2022

### CODE REVIEW

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by anchao** [comment]
Just checked the compilation log of CI, the pragma message cannot be silenced. It seems that need to find other ways to solve this issue

**Comment by patacongo** [comment]
#pragma's are not common, but are specific to a given compiler.  There is no guarantee that a #pragma used by on compiler will be compatible with any other compiler.  The coding standard forbids including and compiler-specific information in any C source file.

**Comment by btashton** [comment]
Looking at most of these... I question if #warning is really appropriate anyway.  The vast majority are calling out broken incomplete code.

**Comment by patacongo** [comment]
I think this change is not a good change.  If you are using a different toolchain with and incompatible C pre-processor, I would suggest that a better solution would be to use the GCC pre-processor with that other toolchain in order to keep compatibility.  But let's please not put #pragmas in the code.  That is a terrible solution.

**Comment by btashton** [comment]
#warning is also not standard. It's a gcc thing some other compilers have chosen to support. I don't think this change is right, but I also don't think the existing usage is appropriate.

**Comment by patacongo** [comment]
> #warning is also not standard. It's a gcc thing some other compilers have chosen to support. I don't think this change is right, but I also don't think the existing usage is appropriate.

Yep.  According to Wikipedia both `#warning` and `#pragma message` are compiler specific and the use of either is deprecated:  https://en.wikipedia.org/wiki/C_preprocessor#Compiler-specific_preprocessor_features

It appears that the only conformant thing to do is either (1) remove all `#warning`s from the code since there is no specified, portable way emit a warning message and continue pre-processing and since the use of warnings is deprecated.  Or (2) perhaps just change all `#warning`s to `#error`s?  `#error` will stop compilation on any warning, but perhaps that is what we want(?)

My suggestion was (3) to settle on GCC's cpp as the pre-processor to be used with any toolchain (since all pre-processors should be capable of generating compile-able code).  It is the most used and most copied pre-processor so not a bad place to settle.

Settling on the Microsoft semantics would be a the worst of all options in my opinion.

**Comment by patacongo** [comment]
> #warning is also not standard. It's a gcc thing some other compilers have chosen to support. I don't think this change is right, but I also don't think the existing usage is appropriate.

`#warning`  has worked with every C pre-processor I have used with NuttX.  That includes at least GCC, IAR, SDCC, and ZiLOG ZDS-III.  And it is a pretty simple matter to use the GCC C pre-processor with any other compiler.  You can (1) either setup a rule to use CPP to convert a .c or .S file to a .i file, then compile the .i file or, or to avoid changing the build, (2) use a work-alike compiler wrapper program to coordinate the mixed tools via system().

**Comment by xiaoxiang781216** [comment]
Since #warning is also a compiler specific, I suggest that:

1. Add a macro in compiler.h to wrap #warning, so we can replace it with a dummy body for Microsoft compiler
2. Remove #warning from common code base(e.g. sched/, fs/, mm/, net/) since Microsoft compiler can only compile sim target

**Comment by patacongo** [comment]
> Since #warning is also a compiler specific, I suggest that:
> 
>     1. Add a macro in compiler.h to wrap #warning, so we can replace it with a dummy body for Microsoft compiler
> 
>     2. Remove #warning from common code base(e.g. sched/, fs/, mm/, net/) since Microsoft compiler can only compile sim target

I thought about suggesting something like that, but was hesitant to do so.  I have had problems in the past with pre-processor macros that expand to other pre-processor macros.  I suspect that this is not handled properly by some pre-processors.  It assumes that in evaluating a macro, the pre-processors expands and re-evaluates the macro recursively  until everything is expanded and all substitutions are made THEN re-values the fully expanded macro one final time to get the final behavior.

So the result of can be difficult to control and is probably not portable.

**Comment by xiaoxiang781216** [comment]
Yes, macro with preprocessor statement may not work as expect.

**Pull request closed without merging**
