### PR TITLE
boards/nrf53: add initial support for Thingy:53 board

### PR DESCRIPTION
**Pull request by raiden00pl**
## Summary
boards/nrf53: add initial support for Thingy:53 board

## Testing
NSH on the app core
NSH on the net core

### CODE REVIEW

**Comment by pkarashchenko** [comment]
> @pkarashchenko this is the board I just got and was talking to you about for building some Bluetooth documentation around. 

Great, thank you!

**Review by xiaoxiang781216 — APPROVED** [review]

**Review by acassis — APPROVED** [review]

**Comment by acassis** [comment]
Do you know if someone at @NordicSemiconductor know about this nice work you are doing? Should be nice to have them helping our project too!

**Comment by raiden00pl** [comment]
Thingy series from Nordic is really cool piece of hardware and seems to be a great candidate for demonstrating the functionality of NuttX. I also plan to port Thingy:91, but that's after nrf91 support will appear upstream (I don't have any deadline for this right now).

@acassis I have no idea and I don't care too much about it. Nordic seems to focus on Zephyr and they are not very interested in others RTOS (insert sad face here).

**Comment by btashton** [comment]
@raiden00pl I'm time limited but I have all this hardware so happy to help as much as I can along the way.

**Comment by raiden00pl** [comment]
@btashton Cool. I have already ported I2C and SPI driver, the rest of the peripherals should be easy to port from NRF52. 

The only problem I see now with the NRF53 is the SoftDevice that takes up a huge amount of the net core FLASH which makes development less enjoyable.

I'm also wondering if it would be possible to integrate NimBLE controller with NuttX. Using the BLE controller from Nordic (which is available only as precompiled binary) is not the best option for open source fans. 
Ideally, NuttX would have its own NRF5x BLE controller implementation, but this task is huge and resource-intensive, so practically impossible to realize without external financing.

**Pull request merged**
