### PR TITLE
fs/mnemofs: Setup and VFS methods

### PR DESCRIPTION
**Pull request by resyfer**
The Setup and VFS methods for mnemofs, a NAND Flash File System.

## Summary
This is Part 1 of the series of PRs to integrate mnemofs into NuttX.

## Impact
- People can use NAND flashes with NuttX.

## Testing
Checkpatch and NAND flash device simulator (for the complete code).

### CODE REVIEW

**Comment by acassis** [comment]
Please add the dual license option to MIT to let other projects to use it too

**Comment by resyfer** [comment]
Hi @acassis, I've added the dual license. Apache 2.0 + BSD-3-Clause.

**Review by acassis — APPROVED** [review]

**Comment by acassis** [comment]
@resyfer CI found some issues in the Kconfig:

```
fs/mnemofs/Kconfig:39: 'endif' in different file than 'if'
fs/mnemofs/Kconfig:10: location of the 'if'
Kconfig:2540: 'endmenu' in different file than 'menu'
fs/mnemofs/Kconfig:10: location of the 'menu'
make: *** [tools/Unix.mk:689: olddefconfig] Error 1
  Enabling CONFIG_ARM_TOOLCHAIN_GNU_EABI
fs/mnemofs/Kconfig:39: 'endif' in different file than 'if'
fs/mnemofs/Kconfig:10: location of the 'if'
Kconfig:2540: 'endmenu' in different file than 'menu'
fs/mnemofs/Kconfig:10: location of the 'menu'
make: *** [tools/Unix.mk:689: olddefconfig] Error 1
  Building NuttX...
make[1]: *** No rule to make target 'context'.
make: *** [tools/Unix.mk:453: libs/libm/.context] Error 2
make: Target 'all' not remade because of errors.
/github/workspace/sources/nuttx/tools/testbuild.sh: line 370: /github/workspace/sources/nuttx/../nuttx/nuttx.manifest: No such file or directory
  Normalize stm32f4discovery/composite
fs/mnemofs/Kconfig:39: 'endif' in different file than 'if'
fs/mnemofs/Kconfig:10: location of the 'if'
Kconfig:2540: 'endmenu' in different file than 'menu'
fs/mnemofs/Kconfig:10: location of the 'menu'
make: *** [tools/Unix.mk:689: olddefconfig] Error 1
fs/mnemofs/Kconfig:39: 'endif' in different file than 'if'
fs/mnemofs/Kconfig:10: location of the 'if'
Kconfig:2540: 'endmenu' in different file than 'menu'
fs/mnemofs/Kconfig:10: location of the 'menu'
make: *** [tools/Unix.mk:712: savedefconfig] Error 1
fs/mnemofs/Kconfig:39: 'endif' in different file than 'if'
fs/mnemofs/Kconfig:10: location of the 'if'
Kconfig:2540: 'endmenu' in different file than 'menu'
fs/mnemofs/Kconfig:10: location of the 'menu'
make: *** [tools/Unix.mk:689: olddefconfig] Error 1
```

**Comment by resyfer** [comment]
Hi @acassis, I think I have fixed the related issue. [Basically you need a newline at the end of Kconfig](http://kanavatar.blogspot.com/2012/03/endmenu-in-different-file-than-menu.html), or it throws this error.

**Comment by resyfer** [comment]
I don't understand why Linux (xtensa) failed?? It doesn't show any error in the output.

**Comment by acassis** [comment]
This PR will fix it: https://github.com/apache/nuttx/pull/12660

**Review by acassis — APPROVED** [review]

**Pull request merged**
