### PR TITLE
Revert "tools: nxstyle if statement check"

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
## Summary

This reverts commit 780366de6269227fced5d8395d192b6d20be1c36.
See the discussion here: https://github.com/apache/nuttx-apps/pull/2501
and more false alarm happen in: https://github.com/apache/nuttx/pull/13109/files

## Impact

avoid false style error for the valid code

## Testing

ci

### CODE REVIEW

**Comment by xiaoxiang781216** [comment]
@LuchianMihai please provide a better check.

**Comment by xiaoxiang781216** [comment]
@acassis could look at this issue?

**Comment by LuchianMihai** [comment]
Hi @xiaoxiang781216,
Sorry for the delay, I'm really busy these days, I'm working on this right now

**Comment by LuchianMihai** [comment]
Hello @xiaoxiang781216,
I've reworked the if statement check
How should we approach my changes?
Will you close this pull request, and after I'll make mine from master with the new change?
Should I open a PR directly and discuss there?

**Comment by xiaoxiang781216** [comment]
please provide your change based on the current master directly. I will close my pr once your change get merged.

**Pull request closed without merging**
