### PR TITLE
Revert "Update esptool version on docs and build system"

### PR DESCRIPTION
**Pull request by jerpelea**
Reverts apache/nuttx#14120

replace by https://github.com/apache/nuttx/pull/14267

### CODE REVIEW

**Comment by jerpelea** [comment]
after revert I will cherry-pick https://github.com/apache/nuttx/pull/14267

**Comment by jerpelea** [comment]
@xiaoxiang781216 please merge

**Review by lupyuen — APPROVED** [review]

**Comment by fdcavalcanti** [comment]
Hey @jerpelea why was this reverted? It's a documentation update.

**Comment by jerpelea** [comment]
it was a merge conflict

**Pull request merged**
