### PR TITLE
{Bp-13658} char driver CAN: add tx_confirm ability in upperCAN driver.

### PR DESCRIPTION
**Pull request by jerpelea**
## Summary
multi backport
https://github.com/apache/nuttx/pull/13647
https://github.com/apache/nuttx/pull/13718
https://github.com/apache/nuttx/pull/13760
https://github.com/apache/nuttx/pull/13762
https://github.com/apache/nuttx/pull/13758

## Impact
RELEASE

## Testing
CI

### CODE REVIEW

**Comment by jerpelea** [comment]
@xiaoxiang781216 there will be several can updates which will fail to compile 
please merge

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by jerpelea** [comment]
https://github.com/apache/nuttx/pull/13718
https://github.com/apache/nuttx/pull/13760
https://github.com/apache/nuttx/pull/13762
https://github.com/apache/nuttx/pull/13758
are needed and will be submitted soon

**Comment by jerpelea** [comment]
needs https://github.com/apache/nuttx-apps/pull/2674

**Review by lupyuen — APPROVED** [review]

**Comment by jerpelea** [comment]
@lupyuen  please merge the PR

**Pull request merged**
