### PR TITLE
drivers/modem/alt1250: Update alt1250 driver

### PR DESCRIPTION
**Pull request by SPRESENSE**
## Summary
Updated alt1250 driver with regarding to the following changes.
- Add LTE hibernation feature
- Split source code per module
- Some refactoring
- Some bug fixes

## Impact
alt1250 driver

## Testing
Tested with spresense

### CODE REVIEW

**Review by jerpelea — APPROVED** [review]
it would be nice to have the changes in separate patches

**Comment by jerpelea** [comment]
please regenerate defconfigs

**Comment by SPRESENSE** [comment]
> please regenerate defconfigs

@jerpelea 
Could you tell me how to regenerate defconfigs?

**Comment by SPRESENSE** [comment]
> > > please regenerate defconfigs
> > 
> > 
> > @jerpelea Could you tell me how to regenerate defconfigs?
> 
> @SPRESENSE make savedefconfig

@jerpelea 
Thank you for your comment.
The boards/arm/cxd56xx/spresense/configs/lte/defconfig was created with make savedefconfig.

**Comment by jerpelea** [comment]
@SPRESENSE 
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   boards/arm/cxd56xx/spresense/configs/lte/defconfig

please push the new config

**Comment by SPRESENSE** [comment]
@jerpelea 
Sorry, defconfig has already been pushed with commit 737c8ef. 
The reason I asked how to create it is because I wanted to make sure the instructions were correct. So please check boards/arm/cxd56xx/spresense/configs/lte/defconfig.

**Comment by jerpelea** [comment]
> @jerpelea Sorry, defconfig has already been pushed with commit [737c8ef](https://github.com/apache/nuttx/commit/737c8ef3913a5cff0a1265bb0ee8a84927794098). The reason I asked how to create it is because I wanted to make sure the instructions were correct. So please check boards/arm/cxd56xx/spresense/configs/lte/defconfig.



> @jerpelea Sorry, defconfig has already been pushed with commit [737c8ef](https://github.com/apache/nuttx/commit/737c8ef3913a5cff0a1265bb0ee8a84927794098). The reason I asked how to create it is because I wanted to make sure the instructions were correct. So please check boards/arm/cxd56xx/spresense/configs/lte/defconfig.

@SPRESENSE I applied the patch locally and it looks like the defconfig changes are not present 
please move the defconfig to a separate patch and forcepush  
Thanks

**Comment by SPRESENSE** [comment]
> @SPRESENSE I applied the patch locally and it looks like the defconfig changes are not present please move the defconfig to a separate patch and forcepush Thanks

@jerpelea 
I have separated the patch for defconfig, please check it.

**Review by jerpelea — APPROVED** [review]

**Pull request merged**
