### PR TITLE
drivers/pty: support pty write to kill signal, like serial driver

### PR DESCRIPTION
**Pull request by Donny9**
## Summary
drivers/pty: support pty write to kill signal, like serial driver
## Impact
support pty write to kill signal, like serial driver
## Testing
adb shell test

### CODE REVIEW

**Comment by Donny9** [comment]
like env issue cause break？
image

**Comment by xiaoxiang781216** [comment]
please reupload the change again.

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by Donny9** [comment]
> @Donny9 please reupload the change again.

Done~

**Review by acassis — CHANGES_REQUESTED** [review]
@Donny9 please include the commit message and explain in more details what this feature brings to NuttX. The break signal already works over serial console (when enabled) to interrupt an application. What is the difference this PR adds to NuttX?

**Comment by Donny9** [comment]
> @Donny9 please include the commit message and explain in more details what this feature brings to NuttX. The break signal already works over serial console (when enabled) to interrupt an application. What is the difference this PR adds to NuttX?

@acassis hello, The interaction between the shell service in adb and adbd occurs through a pseudo-terminal (pty).  The code https://github.com/spiriou/microADB/blob/02c0fd10584a9f7e90f949caf0a983ee45895210/hal/shell_service_uv.c#L330.

so, when a command is launched through adb shell from a PC, users now have the ability to pause or kill the launched,application by inputting specific commands CONFIG_TTY_SIGTSTP_CHAR or CONFIG_TTY_SIGTINT_CHAR,  akin to the capabilities provided by nsh.

**Comment by acassis** [comment]
@Donny9 understood! Thank you! Now it is clear ;-)

**Review by xiaoxiang781216 — APPROVED** [review]

**Pull request merged**
