### PR TITLE
Change the memory of struct filelist to be malloced

### PR DESCRIPTION
**Pull request by guohao15**
*Note: Please adhere to [Contributing Guidelines](https://github.com/apache/nuttx/blob/master/CONTRIBUTING.md).*

## Summary

    The refs in the filelist cannot protect the handles in the prefiles
    The prefiles and its associated group are allocated together, and when
    the group leaves, they are released together.
    During a reboot process, the sync operation may encounter a "used after free"
    issue.

## Impact

    The filelist  will be freed when refence change to zero

## Testing

*Update this section with details on how did you verify the change,
 what Host was used for build (OS, CPU, compiler, ..), what Target was
 used for verification (arch, board:config, ..), etc. Providing build
 and runtime logs from before and after change is highly appreciated.*

### CODE REVIEW

**Comment by guohao15** [comment]
@anchao  help review this patch :)

**Comment by anchao** [comment]
@guohao15 could you please help to verify PR #14444 ? which should resolve the fsync issue you mentioned

**Comment by guohao15** [comment]
> @guohao15 could you please help to verify PR #14444 ? which should resolve the fsync issue you mentioned

@anchao 
this patch will also work, i have tested  a similer patch, but it  has to  recheck the tcb status before get_list and after sync,  
so i think it is better to use the filelist->fl_crefs to maintain the lifecycle of filelist

**Comment by anchao** [comment]
@guohao15 Thanks for your verification. could we make the alloc version to a configurable feature? Individual developers can decide whether to use static or dynamic files,  which would be balanced in terms of safety.

**Pull request closed without merging**
