### PR TITLE
tools/ci: migrate some ci build configurations to CMake

### PR DESCRIPTION
**Pull request by raiden00pl**
## Summary
tools/ci: migrate some ci build configurations to CMake
## Testing
CI

### CODE REVIEW

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by xiaoxiang781216** [comment]
@raiden00pl please rebase your patch to the last mainline, macOS ci has been fixed.

**Comment by raiden00pl** [comment]
@xiaoxiang781216 @anchao any idea why this job can't pass ?https://github.com/apache/nuttx/actions/runs/5596871841/jobs/10234585507?pr=9854

**Comment by raiden00pl** [comment]
It's most likely from:

>   Disabling CONFIG_ARM_TOOLCHAIN_GNU_EABI
> 508
>   Enabling CONFIG_ARM_TOOLCHAIN_CLANG

Probably cmake CI handles this wrong

**Comment by anchao** [comment]
> @xiaoxiang781216 @anchao any idea why this job can't pass ?https://github.com/apache/nuttx/actions/runs/5596871841/jobs/10234585507?pr=9854

Hi @raiden00pl ,
It seems that the cmake needs to restore the previous configuration before refreshing, please try this PR
https://github.com/apache/nuttx/pull/9858

**Comment by raiden00pl** [comment]
@anchao thanks, this problem fixed

**Comment by raiden00pl** [comment]
I had to disable all configurations that use external projects. For some reason `FetchContent_Declare()` doesn't work correctly for the version of CMake 3.16 used by CI. It works without any problem for version 3.26.4 that I have.

**Comment by xiaoxiang781216** [comment]
> I had to disable all configurations that use external projects. For some reason `FetchContent_Declare()` doesn't work correctly for the version of CMake 3.16 used by CI. It works without any problem for version 3.26.4 that I have.

should we upgrade to 3.26.4?

**Comment by raiden00pl** [comment]
@xiaoxiang781216 cmake 3.16 is really old, so if there are no contraindications, it is better to use something newer. 
BTW this PR passes CI now, except `cmake-format not found` error in `Check` job.

**Comment by anchao** [comment]
> @xiaoxiang781216 cmake 3.16 is really old, so if there are no contraindications, it is better to use something newer. BTW this PR passes CI now, except `cmake-format not found` error in `Check` job.

Hi @raiden00pl  I have a quick fix to resolve 'cmake-format' issue, let us waiting for ci finish.
https://github.com/apache/nuttx/pull/9864

**Comment by xiaoxiang781216** [comment]
> @xiaoxiang781216 cmake 3.16 is really old, so if there are no contraindications, it is better to use something newer. BTW this PR passes CI now, except `cmake-format not found` error in `Check` job.

Ok, let's merge this patch first.

**Pull request merged**
