### PR TITLE
fs: Fix mtd/sector512.c:554:19: error: incomplete definition of type 'struct partition_info_s'

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
## Summary

by moving geometry and partition_info_s to include/fs/ioctl.h

## Impact

Fix ci error reported here:
https://github.com/apache/nuttx/actions/runs/11643419979/job/32424162668?pr=14605

## Testing

ci

### CODE REVIEW

**Comment by nuttxpr** [comment]
[**\[Experimental Bot, please feedback here\]**](https://github.com/search?q=repo%3Aapache%2Fnuttx+13552&type=issues)



No, this PR does not fully meet the NuttX requirements as described. While it provides some information, it lacks crucial details.

Here's what's missing:

* **Summary:**  The summary is extremely vague.  It needs to explain *why* moving those structures is necessary.  What problem does this solve? Is it a bug fix? A refactoring?  What was the original issue that led to this change? How does moving the structures address that issue?

* **Impact:** While it links to a CI error, this is insufficient.  It needs to specifically address *all* the impact points:
    * **Is new feature added? Is existing feature changed?** -  This is likely a change to an existing feature (header file organization), so should be clarified.
    * **Impact on user:**  Even if the answer is NO, it should explicitly state NO.
    * **Impact on build:** Even if the CI error is fixed, the description should explain *how* this change fixes the build.  What was the build error and why did moving the structures resolve it?
    * **Impact on hardware:**  Explicitly state NO.
    * **Impact on documentation:**  Does this require documentation updates? If not, explicitly state NO.
    * **Impact on security:**  Explicitly state NO.
    * **Impact on compatibility:**  This is important!  Does moving these structures break backward compatibility with any existing code?  Justify why or why not.
    * **Anything else to consider?** -  Explicitly state N/A if nothing else needs consideration.

* **Testing:**  Simply saying "ci" is not enough.  While CI passing is good, the PR needs to show *specific* test results relevant to the change.
    * **Build Host(s):** Specify the build host details used for testing.
    * **Target(s):** Specify the target architecture and board configuration used for testing.
    * **Testing logs before change:**  Provide actual log output demonstrating the issue before the change. This could include the CI error message or other relevant logs.
    * **Testing logs after change:**  Provide log output showing the successful outcome after the change. This demonstrates that the fix works as intended.


In short, the PR needs to provide more context, explain the reasoning behind the change, and provide concrete evidence of testing and impact analysis.  Just referencing a CI error is not sufficient for a proper review.

**Review by lupyuen — APPROVED** [review]

**Review by cederom — COMMENTED** [review]
Thank you @xiaoxiang781216 :-) Looks like bool definition is missing :-P

**Comment by xiaoxiang781216** [comment]
> Thank you @xiaoxiang781216 :-) Looks like bool definition is missing :-P

Fixed.

**Comment by cederom** [comment]
Thank you @xiaoxiang781216 :-) Lets wait for CI to finish :-)

I can see that we added MSVC CI builder? It fails :-P

**Comment by xiaoxiang781216** [comment]
Fix here: https://github.com/apache/nuttx/pull/14608

**Review by lupyuen — APPROVED** [review]

**Comment by cederom** [comment]
Still some build errors :-( Restarted CI to check msvc fixes..

**Comment by cederom** [comment]
I guess that simple include nuttx.h was not that bad idea :-P Also mscv CI seems fixed :-)  Thank you for the updates @xiaoxiang781216  :-)

**Comment by cederom** [comment]
Argh :\
```
====================================================================================
Configuration/Tool: stm32f777zit6-meadow/projectlab,CONFIG_ARM_TOOLCHAIN_CLANG
2024-11-03 04:15:53
------------------------------------------------------------------------------------
  Cleaning...
  Configuring...
  Disabling CONFIG_ARM_TOOLCHAIN_GNU_EABI
  Enabling CONFIG_ARM_TOOLCHAIN_CLANG
  Building NuttX...
sensors/bmi270_base.c: In function 'bmi270_set_normal_imu':
Error: sensors/bmi270_base.c:1000:3: error: implicit declaration of function 'up_mdelay' [-Werror=implicit-function-declaration]
 1000 |   up_mdelay(30);
      |   ^~~~~~~~~
cc1: all warnings being treated as errors
make[1]: *** [Makefile:107: bmi270_base.o] Error 1
sensors/bmi270.c: In function 'bmi270_close':
Error: sensors/bmi270.c:116:3: error: implicit declaration of function 'up_mdelay' [-Werror=implicit-function-declaration]
  116 |   up_mdelay(30);
      |   ^~~~~~~~~
cc1: all warnings being treated as errors
make[1]: *** [Makefile:107: bmi270.o] Error 1
make[1]: Target 'libdrivers.a' not remade because of errors.
make: *** [tools/LibTargets.mk:107: drivers/libdrivers.a] Error 2
make: Target 'all' not remade because of errors.
/github/workspace/sources/nuttx/tools/testbuild.sh: line 385: /github/workspace/sources/nuttx/../nuttx/nuttx.manifest: No such file or directory
  Normalize stm32f777zit6-meadow/projectlab
====================================================================================
```

**Comment by xiaoxiang781216** [comment]
Done.

**Review by lupyuen — APPROVED** [review]

**Comment by cederom** [comment]
BIG THANK YOU @xiaoxiang781216 and for all related fixes!! :-)

**Pull request merged**
