### PR TITLE
STM32H7 serial TX DMA fix

### PR DESCRIPTION
**Pull request by kk-thrane**
## Summary

Fixes TX DMA for STM32H7

## Testing

Works for me on an STM32H723

### CODE REVIEW

**Comment by davids5** [comment]
How is this checking for the DMA idle?

**Comment by kk-thrane** [comment]
The semaphore is used to indicate when DMA is idle or not. The call to nxsem_trywait() in up_dma_txavailable() perform this check.

Did you notice the reverts? The revert commits reintroduces the call to nxsem_trywait() - not my patch.

**Comment by kk-thrane** [comment]
The half transfer interrupt is not enabled (for TX), only the completion interrupt is enabled.

I had forgot to remove that. I have pushed version where the half transfer interrupt handling is removed (from TX).

**Review by davids5 — COMMENTED** [review]
There are 2 paths, through `up_dma_txavailable` one under interrupt and one from the foreground. The issue that was solved by the critical section was 

 If a TX DMA completion interrups a forground write.
    The TX DMA completion can start a dma_send and it will
    then followed by the forground write's dma_send
    stoping the,then in progress DMA.

    By atomicaly marking the tx dma busy, the forground
    write will not perform the dma_send, and will only
    enqueue the data. At the next TX dma completion any
    data pending in the tx queue will be sent

This case was a random failure and needs to be tested, It was hard to recreate.

**Comment by kk-thrane** [comment]
The current software in master is not working, because the test in up_dma_txavailable() does not correctly determine whether TX DMA is active or not. This could be fixed, but isn't it better to use a semaphore than a critical section? 

I personally also find the code with the semaphore simpler and more intuitive: if TX DMA is running, it is *always* the ISR which initiates the next transfer.

The if-statement in up_dma_txavailable() could be fixed like this:
  if (priv->dev.dmatx.length == 0 && priv->dev.dmatx.nlength == 0 &&
      stm32_dmaresidual(priv->txdma) == 0)
But I think the call to stm32_dmaresidual() is not required?

I have a setup, which easily and immediately detects the errors with TX DMA the driver has and have had.

**Comment by davids5** [comment]
If the only change required is fixing the typo by adding the "== 0" why not do that? I think the CS is a few uS and a nit compared to the semaphore code time and complexity.

**Comment by kk-thrane** [comment]
To my surprise, nuttx implements nxsem_trywait() using a critical section... so yes, using a critical section instead of the semaphore provides better performance.
Hasn't nuttx got a better way to handle this? E.g. disabling only the DMA IRQ would be better.

I believe the call to stm32_dmaresidual() should be removed. I think is redundant and not a reliable method for testing whether DMA is running?

I don't like dma_up_txcallback() calling up_dma_txavailable(). It works, but it is unnecessary. The ISR doesn't need to enter a critical section. I prefer the dma_up_txcallback() implementation in my patch - just leave out the call to nxsem_post(). What do you think?

I will make another version with the above changes and push to this branch later this week when I have had time to verify it. I'm a little preoccupied by something at the moment.

**Comment by davids5** [comment]
@slorquet  Yes https://github.com/apache/nuttx/pull/11990

**Comment by kk-thrane** [comment]
Yes, as @slorquet wrote. Sorry for not making that clear.

**Pull request closed without merging**
