### PR TITLE
qemu: fix CI check error when check qemu net (savedefconfig)

### PR DESCRIPTION
**Pull request by GUIDINGLI**
## Summary

    qemu: fix CI check error when check qemu net (savedefconfig)
    
    CONFIG_SYSTEM_TELNETD_SESSION_STACKSIZE=8192
    
            modified:   boards/arm64/qemu/qemu-armv8a/configs/netnsh/defconfig
            modified:   boards/arm64/qemu/qemu-armv8a/configs/netnsh_hv/defconfig
            modified:   boards/arm64/qemu/qemu-armv8a/configs/netnsh_smp/defconfig
            modified:   boards/arm64/qemu/qemu-armv8a/configs/netnsh_smp_hv/defconfig

## Impact

None

## Testing

CI

### CODE REVIEW

**Review by lupyuen — APPROVED** [review]

**Comment by GUIDINGLI** [comment]
This will also CI error:

user_main: setjmp test
setjmp_test: Initializing jmp_buf
setjmp_test: Try jump
setjmp_test: About to jump, longjmp with ret val: 123
setjmp_test: Jump succeed
setjmp_test: Try jump
setjmp_test: About to jump, longjmp with ret val: 0
setjmp_test: Try jump
dump_assert_info: Current Version: NuttX  10.4.0 11e0262ae8 Oct 14 2024 12:53:49 sim
dump_assert_info: Assertion failed : at file: setjmp.c:46 task: ostest process: ostest 0x7de654
sched_dumpstack: backtrace:
sched_dumpstack: [ 6] [<0xb211b1>] host_backtrace+0x2d/0x41
sched_dumpstack: [ 6] [<0x7a39b2>] up_backtrace+0x10a/0x189
sched_dumpstack: [ 6] [<0x78dc79>] sched_backtrace+0x4d/0x9a
sched_dumpstack: [ 6] [<0x7974e5>] sched_dumpstack+0x5e/0x141
sched_dumpstack: [ 6] [<0x78c679>] dump_running_task+0x2e/0x31
sched_dumpstack: [ 6] [<0x78c83d>] dump_assert_info+0x1c1/0x1dd
sched_dumpstack: [ 6] [<0x78c9df>] _assert+0x146/0x1bd
sched_dumpstack: [ 6] [<0x749df4>] __assert+0x2f/0x34
sched_dumpstack: [ 6] [<0x7df66c>] jump_with_retval+0x7f/0x11b
sched_dumpstack: [ 6] [<0x7df76c>] setjmp_test+0x64/0x82
sched_dumpstack: [ 6] [<0x7dea60>] user_main+0x40c/0x514
sched_dumpstack: [ 6] [<0x74a9ed>] nxtask_startup+0x57/0x5e
sched_dumpstack: [ 6] [<0x740db9>] nxtask_start+0xdf/0xe9
sched_dumpstack: [ 6] [<0x756757>] pre_start+0x2b/0x2e
ostest_main: Exiting with status 256
stdio_test: Standard I/O Check: fprintf to stderr


Fix at:

https://github.com/apache/nuttx-apps/pull/2720

**Comment by GUIDINGLI** [comment]
I will force merge these two PR:
https://github.com/apache/nuttx/pull/14229
https://github.com/apache/nuttx-apps/pull/2720

To see the CI back to normal

**Comment by GUIDINGLI** [comment]
@lupyuen 
You Can see the CI skip of 
image

Why this happens ?

**Comment by lupyuen** [comment]
@GUIDINGLI They will be run when the PR is Merged. We skip the macOS, msys2 and and msvc CI Checks only when Simple PRs are Created or Modified. (To reduce our GitHub Runner Costs)

This PR is considered a Simple PR because it only modifies One Board / Arch: Arm64. More about the Build Rules here: https://github.com/apache/nuttx/issues/13775

**Pull request merged**
