### PR TITLE
drivers/serial: fix race condition in multi-thread write

### PR DESCRIPTION
**Pull request by anchao**
## Summary

drivers/serial: fix race condition in multi-thread write

if multiple threads are doing serial read/write at the same time,
the driver will only wake up one of the thread, which will cause
other threads fail to be woken up in time and cause blocking

Signed-off-by: chao an <anchao@xiaomi.com>

## Impact

N/A

## Testing

sim/nsh

### CODE REVIEW

**Comment by davids5** [comment]
@anchao Did you test this on real HW? Did you test the CDCACM driver, and ensure the lead/lag on connect/disconnect was handled? I.E Data sent in connected state, then disconnected etc

**Comment by anchao** [comment]
> @anchao Did you test this on real HW? Did you test the CDCACM driver, and ensure the lead/lag on connect/disconnect was handled? I.E Data sent in connected state, then disconnected etc

Yes, I verify this change on our real product(Cortex-M55/Cortex-A7(SMP 2 Core))

**Comment by davids5** [comment]
> Yes, I verify this change on our real product(Cortex-M55/Cortex-A7(SMP 2 Core))

Does that use CDCACM?

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by anchao** [comment]
> Does that use CDCACM?

@davids5  emm ... I don't have real hardware for CDCACM yet, could you please help to verify this PR?

**Comment by davids5** [comment]
> > Does that use CDCACM?
> 
> @davids5 emm ... I don't have real hardware for CDCACM yet, could you please help to verify this PR?

Sorry I do not have time this week.

**Comment by anchao** [comment]
> Sorry I do not have time this week.

I have verify this PR on sim/usbdev,  everything works as expected.

**Review by jerpelea — APPROVED** [review]

**Pull request merged**
