### PR TITLE
libc/time: remove lib_strptime

### PR DESCRIPTION
**Pull request by jerpelea**
## Summary
This code is licensed under BSD-4-Clause license which may render the OS unusable for some products.

## Impact
libc/time

## Testing
local build

### CODE REVIEW

**Comment by acassis** [comment]
@jerpelea normally people using NuttX will not endorse/promote NetBSD:
```
 * 4. Neither the name of The NetBSD Foundation nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
```

So maybe instead of removing it you could just put is depending on BSD LICENSE activation.

**Comment by jerpelea** [comment]
@acassis this is a 4 clause license

**Comment by acassis** [comment]
> @acassis this is a 4 clause license and I think that we should look for other alternatives

Yes, but it is only an issue if someone want to endorse or promote the NetBSD name, so it is not a big issue IMHO.

**Comment by jerpelea** [comment]
@acassis 

 3. All advertising materials mentioning features or use of this software
 *    must display the following acknowledgement:
 *        This product includes software developed by the NetBSD
 *        Foundation, Inc. and its contributors.

**Comment by jerpelea** [comment]
Attached is the regular 3 clause license
https://opensource.org/license/bsd-3-clause

As you can see there is a difference between the 2 and we should need to have a special case for this code instead of looking for a proper BSD or Apache implementation (if needed)

**Comment by acassis** [comment]
Gotcha, understood the point!

**Comment by xiaoxiang781216** [comment]
> @acassis
> 
> BSD-2 clause license https://opensource.org/license/bsd-2-clause
> 
> BSD- 3 clause license https://opensource.org/license/bsd-3-clause
> 
> As you can see there is a difference between the OSI licenses and the 4 Clause one
> 
> If we keep the 4 Clause license we will have a special barrier for this code instead of looking for a proper BSD or Apache implementation (if needed).
> 
> Another point, for removing the code, is that all code scanning tools will be triggered by the code ignoring the fact that may not be enabled during the the build or not since they scan all existing code in the git.

but why not guard the code with BSD4 Kconfig? We even have config for GPL code, which is most restricted license.

**Comment by jerpelea** [comment]
@xiaoxiang781216 the BSD 4 clause code will trigger any code scanning tool and the problem is that it is in the NuttX core(libc).
This will potentially make NuttX less attractive for commercial products and will be avoided by companies.

GPL-2 is part of the apps folder which is why it can be guarded by a license ifdef. 

The NuttX folder should not contain GPL or BSD-4 Clause

**Comment by xiaoxiang781216** [comment]
can we port musl version at the same time:
https://git.musl-libc.org/cgit/musl/tree/src/time/strptime.c
I am afraid that this change will break some apps which call strptime.

**Comment by jerpelea** [comment]
@xiaoxiang781216 
please merge my commit and port the MIT one. 

You can ask the musl Author if he agrees to re-license the code to Apache 2.0 for the NuttX project.

**Review by xiaoxiang781216 — APPROVED** [review]

**Pull request merged**
