### PR TITLE
Getline support backspace

### PR DESCRIPTION
**Pull request by zhangwenjian111**
## Summary
getline function support backspace

## Impact
None

## Testing
sim,qemu,arm64

### CODE REVIEW

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by TimJTi** [comment]
@xiaoxiang781216 @zhangwenjian111 Assuming my git bisect attempt was correct, this PR has broken the backspace on my setup (custom board, UART console, MiniCom terminal on via WSL on Windows 11) is no longer working and I can no longer delete characters.

Is there some other setting (or change of a setting) that is related to this?

**Comment by xiaoxiang781216** [comment]
> @xiaoxiang781216 @zhangwenjian111 Assuming my git bisect attempt was correct, this PR has broken the backspace on my setup (custom board, UART console, MiniCom terminal on via WSL on Windows 11) is no longer working and I can no longer delete characters.
> 
> Is there some other setting (or change of a setting) that is related to this?

do you update nsh too? https://github.com/apache/nuttx-apps/pull/2664

**Comment by TimJTi** [comment]
> do you update nsh too? [apache/nuttx-apps#2664](https://github.com/apache/nuttx-apps/pull/2664)
I thought I had - but it seems not. I've had this before so I may need to reclone/refork the repo if this happens again.

HOWEVER - perhaps this PR could have mentioned in the IMPACT section that nsh would be broken without updating to the latest nuttx-apps?

**Comment by xiaoxiang781216** [comment]
update, thanks.

**Pull request merged**
