### PR TITLE
tools/ci: Skip esp32c6 build untils espressif fix the problem

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
## Summary

see the discussion here: https://github.com/apache/nuttx/pull/9016

## Impact

make ci work again

## Testing

ci

### CODE REVIEW

**Review by jerpelea — APPROVED** [review]

**Comment by pkarashchenko** [comment]
But I think CI is already working now after setting the optimisation level to Os, isn't it?

**Comment by pkarashchenko** [comment]
@xiaoxiang781216 let's see if https://github.com/apache/nuttx/pull/9036 helps

**Comment by pkarashchenko** [comment]
Do we need to revert https://github.com/apache/nuttx/pull/9017 with this change?

**Comment by xiaoxiang781216** [comment]
> But I think CI is already working now after setting the optimisation level to Os, isn't it?

No, it stop working again.

> @xiaoxiang781216 let's see if #9036 helps

Ok, but the change need @acassis confirm that removing srodata doesn't have other bad side effect.


> Do we need to revert #9017 with this change?

Yes, could be.

**Comment by pkarashchenko** [comment]
> Ok, but the change need @acassis confirm that removing srodata doesn't have other bad side effect.
But it is not removing, but adding `srodata`.

**Comment by pkarashchenko** [comment]
So let's close this PR?

**Pull request closed without merging**
