### PR TITLE
esp32c3-generic: add simple boot support

### PR DESCRIPTION
**Pull request by almir-okato**
## Summary
- esp32c3-generic: add simple boot support

The Simple Boot feature for Espressif chips is a method of booting that doesn't depend on a 2nd stage bootloader. Its not the intention to replace a 2nd stage bootloader such as MCUboot and ESP-IDF bootloader, but to have a minimal and straight-forward way of booting, and also simplify the building. 

## Impact
- `esp32c3-generic`: This implementation changes the default bootloader configuration from MCUboot to the new Simple Boot method and removes the need for `make bootloader` build step. Also note that some of 2nd stage bootloader features, like OTA and security features, are not available using this method.

## Testing
Internal CI testing.

### CODE REVIEW

**Review by alandeassis — APPROVED** [review]

**Comment by alandeassis** [comment]
@almir-okato is there support to use direct boot on ESP32 as well?

**Comment by almir-okato** [comment]
> @almir-okato is there support to use direct boot on ESP32 as well?

Hi @alandeassis, I suppose that you are talking about that "Direct boot" feature from ESP32-C3, which depends on the chip ROM code, that is not available for ESP32. 
Although the idea of omitting the 2nd stage bootloader is similar, the mentioned "Direct boot" is not equal "Simple boot", they differ in many levels such as image format and how/from where code is executed.

The "Simple boot" referenced in this PR is not implemented for ESP32 yet.

**Review by tmedicci — APPROVED** [review]
@xiaoxiang781216 , Almir works on Espressif too (but on MCUboot team) and I've already reviewed this PR internally. Our internal CI tested it quite a lot and it's ready to be merged from my point of view.

**Review by jerpelea — APPROVED** [review]
please add a commit message

**Review by alandeassis — APPROVED** [review]

**Pull request merged**
