### PR TITLE
sim: fix sim smp boot regression

### PR DESCRIPTION
**Pull request by hujun260**
## Summary
This commit fixes the regression from https://github.com/apache/nuttx/pull/13716

## Impact
sim

## Testing
sim:smp
ostest

### CODE REVIEW

**Comment by nuttxpr** [comment]
[**\[Experimental Bot, please feedback here\]**](https://github.com/search?q=repo%3Aapache%2Fnuttx+13552&type=issues)



**No, the PR does not meet the NuttX requirements.**

**Missing Information:**

* **Summary:** 
    *  Lacks a clear explanation of why the change is necessary. What was the regression introduced in PR #13716? 
    *  Doesn't specify what functional part of the code is being changed.
    *  Omits details on how the change works.
* **Impact:** 
    * While it mentions "sim," it needs more specifics. Which architectures, boards, or drivers within the simulator are affected?
    *  Lacks information on all other impact points (user, build, hardware, documentation, security, compatibility).
* **Testing:** 
    * Provides minimal testing details ("sim:smp", "ostest").  
    *  Does not include any actual testing logs from before or after the change. 

**To meet the requirements, the PR needs to:**

1. **Expand the Summary:** Describe the regression, the code being modified, and the solution's mechanism.
2. **Detail the Impact:** Be specific about the affected simulator components. Address all other impact points, explaining whether they are relevant or not.
3. **Provide Comprehensive Testing Information:** List the build host and target environments used for testing. Include actual testing logs that demonstrate the issue before the fix and the successful outcome after.

**Review by jerpelea — APPROVED** [review]

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by raiden00pl** [comment]
`sim/smp` works better, but something is still wrong. 

Some examples:
1. sometimes NSH prompt is printed 2 times:
```
[raiden00:~/git/RTOS/nuttx/nuttx]$ ./nuttx

NuttShell (NSH) NuttX-10.4.0
nsh> nsh> poweroff
[raiden00:~/git/RTOS/nuttx/nuttx]$ ./nuttx

NuttShell (NSH) NuttX-10.4.0
nsh> nsh> poweroff
[raiden00:~/git/RTOS/nuttx/nuttx]$ ./nuttx

NuttShell (NSH) NuttX-10.4.0
nsh> poweroff
[raiden00:~/git/RTOS/nuttx/nuttx]$ ./nuttx

NuttShell (NSH) NuttX-10.4.0
nsh> poweroff

```

2. there is something wrong with console output, you can test this by executing the `help` command several times
```
NuttShell (NSH) NuttX-10.4.0
nsh> help
help usage:  help [-v] [<cmd>]
  help [-v] [<cmd>]

    .           cp          exit        ls          ps          true        
    [           cmp         expr        mkdir       pwd         truncate    
    [           cmp         expr        mkdir       pwd         truncate    
    ?           dirname     false       mkrd        rm          uname       
    alias       dd          fdinfo      mount       rmdir       umount      
    unalias     df          free        mv          set         unset       
    basename    dmesg       help        pidof       sleep       uptime      
    break       echo        hexdump     poweroff    source      usleep      
    break       echo        hexdump     poweroff    source      usleep      
    cat         env         kill        quit        test        xd          
    cd          exec        pkill       printf      time        

Builtin Apps:
    getprime    nsh         sh          taskset     
    getprime    nsh         sh          taskset     
    hello       ostest      smp         
nsh> help
help usage:  help [-v] [<cmd>]

    .           cp          exit        ls          ps          true        
    [           cmp         expr        mkdir       pwd         truncate    
    ?           dirname     false       mkrd        rm          uname       
    ?           dirname     false       mkrd        rm          uname       
    alias       dd          fdinfo      mount       rmdir       umount      
    unalias     df          free        mv          set         unset       
    basename    dmesg       help        pidof       sleep       uptime      
    basename    dmesg       help        pidof       sleep       uptime      
    break       echo        hexdump     poweroff    source      usleep      
    cat         env         kill        quit        test       cat         env         kill        quit        test        xd          
     xd          
    cd          exec        pkill       printf      time        

Builtin Apps:
    getprime    nsh         sh          taskset     
    hello       ostest      smp         
    hello       ostest      smp         
nsh> help
help usage:  help [-v] [<cmd>]

    .           cp          exit        ls          ps          true        
    [           cmp         expr        mkdir       pwd         truncate    
    ?           dirname     false       mkrd        rm          uname       
    ?           dirname     false       mkrd        rm          uname       
    alias       dd          fdinfo      mount       rmdir       umount      
    unalias     df          free        mv          set         unset       
    basename    dmesg       help        pidof       sleep       uptime      
    break       echo        hexdump     poweroff    source      usleep      
    cat         env         kill        quit        test        xd          
    cd          exec        pkill       printf      time        
    cd          exec        pkill       printf      time        

Builtin Apps:
    getprime    nsh         sh          taskset     
    hello       ostest      smp         
nsh> help
help usage:  help [-v] [<cmd>]
  help [-v] [<cmd>]

    .           cp          exit        ls          ps          true        
    .           cp          exit        ls          ps          true        
    [           cmp         expr        mkdir       pwd         truncate    
    ?           dirname     false       mkrd        rm          uname       
    alias       dd          fdinfo      mount       rmdir       umount      
    unalias     df          free        mv          set         unset       
    basename    dmesg       help        pidof       sleep       uptime      
    break       echo        hexdump     poweroff    source      usleep      
    break       echo        hexdump     poweroff    source      usleep      
    cat         env         kill        quit        test        xd          
    cd          exec        pkill       printf      time        

Builtin Apps:
    getprime    nsh         sh          taskset     
    hello       ostest      smp         
nsh> help
help usage:  help [-v] [<cmd>]


    .           cp          exit        ls          ps          true        
    [           cmp       [           cmp         expr        mkdir       pwd         truncate    
      expr        mkdir       pwd         truncate    
    ?           dirname     false       mkrd        rm          uname       
    alias       dd          fdinfo      mount       rmdir       umount      
    unalias     df          free        mv          set         unset       
    basename    dmesg       help        pidof       sleep       uptime      
    break       echo        hexdump     poweroff    source      usleep      
    break       echo        hexdump     poweroff    source      usleep      
    cat         env         kill        quit        test        xd          
    cd          exec        pkill       printf      time        

Builtin Apps:
    getprime    nsh         sh          taskset     
    hello       ostest      smp         
    hello       ostest      smp         
nsh> 
```

**Comment by hujun260** [comment]
> `sim/smp` works better, but something is still wrong.
> 
> Some examples:
> 
> 1. sometimes NSH prompt is printed 2 times:
> 
> ```
> [raiden00:~/git/RTOS/nuttx/nuttx]$ ./nuttx
> 
> NuttShell (NSH) NuttX-10.4.0
> nsh> nsh> poweroff
> [raiden00:~/git/RTOS/nuttx/nuttx]$ ./nuttx
> 
> NuttShell (NSH) NuttX-10.4.0
> nsh> nsh> poweroff
> [raiden00:~/git/RTOS/nuttx/nuttx]$ ./nuttx
> 
> NuttShell (NSH) NuttX-10.4.0
> nsh> poweroff
> [raiden00:~/git/RTOS/nuttx/nuttx]$ ./nuttx
> 
> NuttShell (NSH) NuttX-10.4.0
> nsh> poweroff
> ```
> 
> 2. there is something wrong with console output, you can test this by executing the `help` command several times
> 
> ```
> NuttShell (NSH) NuttX-10.4.0
> nsh> help
> help usage:  help [-v] [<cmd>]
>   help [-v] [<cmd>]
> 
>     .           cp          exit        ls          ps          true        
>     [           cmp         expr        mkdir       pwd         truncate    
>     [           cmp         expr        mkdir       pwd         truncate    
>     ?           dirname     false       mkrd        rm          uname       
>     alias       dd          fdinfo      mount       rmdir       umount      
>     unalias     df          free        mv          set         unset       
>     basename    dmesg       help        pidof       sleep       uptime      
>     break       echo        hexdump     poweroff    source      usleep      
>     break       echo        hexdump     poweroff    source      usleep      
>     cat         env         kill        quit        test        xd          
>     cd          exec        pkill       printf      time        
> 
> Builtin Apps:
>     getprime    nsh         sh          taskset     
>     getprime    nsh         sh          taskset     
>     hello       ostest      smp         
> nsh> help
> help usage:  help [-v] [<cmd>]
> 
>     .           cp          exit        ls          ps          true        
>     [           cmp         expr        mkdir       pwd         truncate    
>     ?           dirname     false       mkrd        rm          uname       
>     ?           dirname     false       mkrd        rm          uname       
>     alias       dd          fdinfo      mount       rmdir       umount      
>     unalias     df          free        mv          set         unset       
>     basename    dmesg       help        pidof       sleep       uptime      
>     basename    dmesg       help        pidof       sleep       uptime      
>     break       echo        hexdump     poweroff    source      usleep      
>     cat         env         kill        quit        test       cat         env         kill        quit        test        xd          
>      xd          
>     cd          exec        pkill       printf      time        
> 
> Builtin Apps:
>     getprime    nsh         sh          taskset     
>     hello       ostest      smp         
>     hello       ostest      smp         
> nsh> help
> help usage:  help [-v] [<cmd>]
> 
>     .           cp          exit        ls          ps          true        
>     [           cmp         expr        mkdir       pwd         truncate    
>     ?           dirname     false       mkrd        rm          uname       
>     ?           dirname     false       mkrd        rm          uname       
>     alias       dd          fdinfo      mount       rmdir       umount      
>     unalias     df          free        mv          set         unset       
>     basename    dmesg       help        pidof       sleep       uptime      
>     break       echo        hexdump     poweroff    source      usleep      
>     cat         env         kill        quit        test        xd          
>     cd          exec        pkill       printf      time        
>     cd          exec        pkill       printf      time        
> 
> Builtin Apps:
>     getprime    nsh         sh          taskset     
>     hello       ostest      smp         
> nsh> help
> help usage:  help [-v] [<cmd>]
>   help [-v] [<cmd>]
> 
>     .           cp          exit        ls          ps          true        
>     .           cp          exit        ls          ps          true        
>     [           cmp         expr        mkdir       pwd         truncate    
>     ?           dirname     false       mkrd        rm          uname       
>     alias       dd          fdinfo      mount       rmdir       umount      
>     unalias     df          free        mv          set         unset       
>     basename    dmesg       help        pidof       sleep       uptime      
>     break       echo        hexdump     poweroff    source      usleep      
>     break       echo        hexdump     poweroff    source      usleep      
>     cat         env         kill        quit        test        xd          
>     cd          exec        pkill       printf      time        
> 
> Builtin Apps:
>     getprime    nsh         sh          taskset     
>     hello       ostest      smp         
> nsh> help
> help usage:  help [-v] [<cmd>]
> 
> 
>     .           cp          exit        ls          ps          true        
>     [           cmp       [           cmp         expr        mkdir       pwd         truncate    
>       expr        mkdir       pwd         truncate    
>     ?           dirname     false       mkrd        rm          uname       
>     alias       dd          fdinfo      mount       rmdir       umount      
>     unalias     df          free        mv          set         unset       
>     basename    dmesg       help        pidof       sleep       uptime      
>     break       echo        hexdump     poweroff    source      usleep      
>     break       echo        hexdump     poweroff    source      usleep      
>     cat         env         kill        quit        test        xd          
>     cd          exec        pkill       printf      time        
> 
> Builtin Apps:
>     getprime    nsh         sh          taskset     
>     hello       ostest      smp         
>     hello       ostest      smp         
> nsh> 
> ```

this 2 issue  introduced by https://github.com/apache/nuttx/pull/4413
@GUIDINGLI

**Comment by xiaoxiang781216** [comment]
let's fix the rest problem with the new patch.

**Pull request merged**
