### PR TITLE
drivers/rpmsg: Using safe list iterating in rpmsg_device_created() to fix list access after delete error

### PR DESCRIPTION
**Pull request by JianyuWang0623**
## Summary
1. Using safe list iterating in rpmsg_device_created()
2. Fix a typo error of rpmsg_device_destory()

- Log
```
  [ap] kasan_report: kasan detected a read access error, address at 0x40b7ae78,size is 8, return address: 0x402a3c50
  [ap] kasan_show_memory: Shadow bytes around the buggy address:
  [ap] kasan_show_memory:   0x40b7ae20: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  [ap] kasan_show_memory:   0x40b7ae30: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  [ap] kasan_show_memory:   0x40b7ae40: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  [ap] kasan_show_memory:   0x40b7ae50: 20 af b7 40 00 00 00 00 c0 17 2a 40 00 00 00 00
  [ap] kasan_show_memory:   0x40b7ae60: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  [ap] kasan_show_memory:   0x40b7ae70: 00 00 00 00 00 00 00 00[b0 f7 b3 40 00 00 00 00]
  [ap] kasan_show_memory:   0x40b7ae80: c8 48 b8 40 00 00 00 00 00 00 00 00 00 00 00 00
  [ap] kasan_show_memory:   0x40b7ae90: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  [ap] kasan_show_memory:   0x40b7aea0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  [ap] kasan_show_memory:   0x40b7aeb0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00

  $ addr2line -fe nuttx/nuttx 0x402a3c50
  rpmsg_device_created
  /workspace/nuttx/drivers/rpmsg/rpmsg.c:395 (discriminator 2)

  # line 395 is local version, corresponds to metal_list_for_each() in rpmsg_device_created() of apache:nuttx version.

```
## Impact
- drivers/rpmsg

## Testing
1. Local test
```
  /* Export */
  rpmsgdev_export("SERVER", "/dev/DEVNAME");

  /* Register */
  rpmsgdev_register("CLIENT", "/dev/DEVNAME", "/dev/server-DEVNAME", 0);
```
2. Github CI

### CODE REVIEW

**Comment by JianyuWang0623** [comment]
6352c1ef06d52ae387866a7293fb35a1d48c86cb - As commit message say, reported by @terry0012

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by anchao** [comment]
Merge these two commits into one

**Review by anchao — CHANGES_REQUESTED** [review]
I don't understand why the callback will delete the node. You already hold a mutex lock outside the list. Is there any code that bypasses the lock protection to delete the node?

**Comment by JianyuWang0623** [comment]
> I don't understand why the callback will delete the node. You already hold a mutex lock outside the list. Is there any code that bypasses the lock protection to delete the node?

As "test" of PR message, `rpmsgdev_export()` => `rpmsgdev_server_created()` => `rpmsg_unregister_callback()`, please see: https://github.com/apache/nuttx/blob/master/drivers/misc/rpmsgdev_server.c#L519

**Comment by JianyuWang0623** [comment]
> Merge these two commits into one

Perhaps these can also be considered two independent things, not necessarily related.

**Comment by anchao** [comment]
> > Merge these two commits into one
> 
> 
> 
> Perhaps these can also be considered two independent things, not necessarily related.

ok， I checked the code on my phone and mistakenly thought that the changes were made to the same line. could you update the commit and replace the list below with the safety version? It seems that there is also an issue with deleting nodes

https://github.com/apache/nuttx/blob/master/drivers/rpmsg/rpmsg.c#L450C3-L450C41

**Comment by JianyuWang0623** [comment]
> > > Merge these two commits into one
> > 
> > 
> > Perhaps these can also be considered two independent things, not necessarily related.
> 
> ok， I checked the code on my phone and mistakenly thought that the changes were made to the same line. could you update the commit and replace the list below with the safety version? It seems that there is also an issue with deleting nodes
> 
> https://github.com/apache/nuttx/blob/master/drivers/rpmsg/rpmsg.c#L450C3-L450C41

OK, I will also try to build the scene for comparison and verification, which may take some time. If it goes well, I will update to the current patch, or create a new submission after sufficient verification.

**Review by anchao — APPROVED** [review]

**Pull request merged**
