### PR TITLE
arch/xmc4: Fix CCU registers

### PR DESCRIPTION
**Pull request by nicolas71640**
## Summary
Fix registers definition for CCU (Capture/Compare Unit) on XMC4

## Impact
Original register definition ( https://github.com/apache/nuttx/pull/11600) missed the fact that there were multiple CCU modules AND multiple slices in each of this modules. This PR fixes that by adding related registers

## Testing
Tested that on XMC4800 relax

@trns1997 @leducp  @Rdk-T

### CODE REVIEW

**Comment by acassis** [comment]
Hi @nicolas71640 nice contribution! We need more people using XMC4 and contributing code to it!

**Comment by acassis** [comment]
@nicolas71640 please fix the commit name to something like:
"arch/xmc4: Fix CCU registers"

Please fix the comment issues:

/* CCU40 CC40 Slice Register */ <<--- space after Register

**Review by xiaoxiang781216 — APPROVED** [review]

**Review by pkarashchenko — APPROVED** [review]

**Review by Rdk-T — APPROVED** [review]

**Review by leducp — APPROVED** [review]

**Review by jerpelea — COMMENTED** [review]
please add a commit message describing the change

**Review by jerpelea — APPROVED** [review]
please add a commit message

**Comment by acassis** [comment]
Since many people approved and the commit title explains what it does...

**Pull request merged**
