### PR TITLE
libc/exit: Purge calls to userspace API exit() from kernel

### PR DESCRIPTION
**Pull request by pussuw**
## Summary
Remove calls to the userspace API exit() from the kernel. The problem with doing such calls is that the exit functions are called with kernel mode privileges which is a big security no-no.

## Impact
Remove illegal usage of a user API from kernel

## Testing
CI and icicle:knsh, ostest with icicle:nsh / pnsh

### CODE REVIEW

**Comment by pussuw** [comment]
This is a placeholder! I will abuse CI to see which platforms cause issues, and fix them along the way.

**Comment by pussuw** [comment]
Ok, that should do it. If any regressions arise please let me know and I will address them.

At least ostest ran successfully.

**Review by xiaoxiang781216 — APPROVED** [review]

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by tmedicci** [comment]
Hi!

This caused a regression while building `./tools/configure.sh esp32s3-devkit:knsh`: 

```
xtensa-esp32s3-elf-ld: /home/tiago/Documents/work/espressif/projects/nuttx/nuttxspace_beta/nuttx/staging/libkc.a(lib_abort.o):(.literal.unlikely.abort+0x0): undefined reference to `exit'
xtensa-esp32s3-elf-ld: /home/tiago/Documents/work/espressif/projects/nuttx/nuttxspace_beta/nuttx/staging/libkc.a(lib_abort.o): in function `abort':
/home/tiago/Documents/work/espressif/projects/nuttx/nuttxspace_beta/nuttx/libs/libc/stdlib/lib_abort.c:69: undefined reference to `exit'
```
`abort` calls `exit`. Could please check the best approach to handle this?

Thanks!

**Comment by xiaoxiang781216** [comment]
It's strange why this patch pass the ci.

**Comment by pussuw** [comment]
> Hi!
> 
> This caused a regression while building `./tools/configure.sh esp32s3-devkit:knsh`:
> 
> ```
> xtensa-esp32s3-elf-ld: /home/tiago/Documents/work/espressif/projects/nuttx/nuttxspace_beta/nuttx/staging/libkc.a(lib_abort.o):(.literal.unlikely.abort+0x0): undefined reference to `exit'
> xtensa-esp32s3-elf-ld: /home/tiago/Documents/work/espressif/projects/nuttx/nuttxspace_beta/nuttx/staging/libkc.a(lib_abort.o): in function `abort':
> /home/tiago/Documents/work/espressif/projects/nuttx/nuttxspace_beta/nuttx/libs/libc/stdlib/lib_abort.c:69: undefined reference to `exit'
> ```
> 
> `abort` calls `exit`. Could please check the best approach to handle this?
> 
> Thanks!

Hi, thanks for bringing this up.

My suggestion is to convert the call to `abort()` into `_exit(EXIT_FAILURE);`

It is strange indeed that CI did not notice this. I literally did a test patch first to see which modules would fail to compile.

**Pull request merged**
