### PR TITLE
Add i.MX8MP platform (Cortex-M7)

### PR DESCRIPTION
**Pull request by Siviuze**
## Summary
Support for i.MX8MP platform. Note that the i.MX8Mx family is different than the i.MX8Qx.

### CODE REVIEW

**Comment by Siviuze** [comment]
Question: I have a few styles errors due to long lien found, especially in mx8mp_ccm.c and mx8mp_pinmux.h files.
Do you have any recommendations to handle theses so that the definitions stays readable?

**Comment by xiaoxiang781216** [comment]
@Siviuze  please fix the warning reported by check:
https://github.com/apache/nuttx/actions/runs/5952422308/job/16148351709?pr=10378
and rebase to the last master to the break which should be fixed by https://github.com/apache/nuttx/pull/10370 and https://github.com/apache/nuttx-apps/pull/1990.

**Comment by Siviuze** [comment]
> @Siviuze please fix the warning reported by check: https://github.com/apache/nuttx/actions/runs/5952422308/job/16148351709?pr=10378 and rebase to the last master to the break which should be fixed by #10370 and [apache/nuttx-apps#1990](https://github.com/apache/nuttx-apps/pull/1990).

Theses are the warnings about too long line that I don't know how to proceed to keep a code readable :)

**Comment by hartmannathan** [comment]
> Theses are the warnings about too long line that I don't know how to proceed to keep a code readable :)

`nxstyle` (the program that checks for too-long lines and other code style rules) looks at the length of the `/*************` separators in the file and uses that to decide the longest allowed line. Note, though, that while it requires lines of **_code_** to be shorter than the row of asterisks, it allows some leeway for lines of `#define`s: these can be longer than the asterisks as long as the definition starts before the end of the asterisks. This exception is included exactly for the purpose of keeping defines readable!

An example might make it more clear. See:

https://github.com/apache/nuttx/blob/master/arch/arm/src/tiva/hardware/tm4c/tm4c_memorymap.h

Notice how the lines of defines are longer than the asterisks. However, this is accepted by `nxstyle` because the definition begins before the asterisks end.

In your file, the definitions that `nxstyle` complains about begin after the asterisks.

A workaround is to add more asterisks. You can use `tools/nxstyle` in the NuttX repo to test your file. That way, you don't have to keep force-pushing and waiting for the lengthy checks.

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by Siviuze** [comment]
Thanks for the explanations @hartmannathan !

I have updated the code :)

**Review by xiaoxiang781216 — APPROVED** [review]

**Pull request merged**
