### PR TITLE
drivers: return sequential characters for /dev/zero device

### PR DESCRIPTION
**Pull request by Gary-Hobson**
## Summary
It will return all characters between ' '(0x20)-'~'(0x7e).

### CODE REVIEW

**Comment by patacongo** [comment]
/dev/zero is not specified by POSIX AFAIK but is common to most Unix implementations.  It is, for example, described in https://en.wikipedia.org/wiki//dev/zero 

> "/dev/zero is a [special file](https://en.wikipedia.org/wiki/Special_file) in Unix-like operating systems that provides as many null (ASCII NUL, 0x00) as are read from it."

I believe that behavior must not change.  /dev/zero should never return anything but zero, regardless of configuration settings.  I don't believe that this change should be merged as it (conditionally) breaks Unix conventions.

**Comment by Gary-Hobson** [comment]
> /dev/zero is not specified by POSIX AFAIK but is common to most Unix implementations. It is, for example, described in https://en.wikipedia.org/wiki//dev/zero
> 
> > "/dev/zero is a [special file](https://en.wikipedia.org/wiki/Special_file) in Unix-like operating systems that provides as many null (ASCII NUL, 0x00) as are read from it."
> 
> I believe that behavior must not change. /dev/zero should never return anything but zero, regardless of configuration settings. I don't believe that this change should be merged as it (conditionally) breaks Unix conventions.
> 
> Why not create a new device, say /dev/ascii, that supports the behavior that you want instead of pirating /dev/zero?

Done

**Comment by xiaoxiang781216** [comment]
@patacongo could you review again?

**Comment by davids5** [comment]
@Gary-Hobson Please change the title of the PR

**Pull request merged**
