### PR TITLE
arm: Add support for CSK6011A SOC and CSK6011A-NANO board

### PR DESCRIPTION
**Pull request by fengshutietou**
## Summary
Added initial support for the CSK6011A chip to the NuttX RTOS. This includes:

- Basic initialization and configuration for the CSK6011A and CSK6011A-NANO.
- Integration with the existing NuttX build system and configuration files.
- Relevant testing and verification based on the CSK6011A-NANO.

This contribution allows developers to use the CSK6011A chip within the NuttX environment, expanding the range of supported hardware and ensuring basic functionality.

## Testing
Tested with CSK6011A-NANO board

### CODE REVIEW

**Comment by acassis** [comment]
Hi @fengshutietou nice contribution! Kudos!!!

Please fix the coding style issues, please follow the https://nuttx.apache.org/docs/latest/contributing/making-changes.html#git-workflow-with-an-upstream-repository and run checkpatch.sh to find the issues.

**Comment by fengshutietou** [comment]
邮件已收到，谢谢！

**Comment by acassis** [comment]
> 邮件已收到，谢谢！

English, please

**Comment by fengshutietou** [comment]
Could you  help retry the CI? I’ve already fixed the previous issues. Thanks

**Comment by fengshutietou** [comment]
done!

**Review by acassis — APPROVED** [review]

**Pull request merged**
