### PR TITLE
Doc: Migrate ARMv7-M run time stack checking doc

### PR DESCRIPTION
**Pull request by lvanasse**
Migrate the ARMv7-M run time stack checking documentation page from the Confluence wiki to the official documentation.

## Summary

Simply migrate the [https://cwiki.apache.org/confluence/display/NUTTX/ARMv7-M+Run+Time+Stack+Checking](https://cwiki.apache.org/confluence/display/NUTTX/ARMv7-M+Run+Time+Stack+Checking) page

## Impact

None, it only updates the documentation

## Testing

I've tested the documentation generation by writing it with the autobuild feature

### CODE REVIEW

**Comment by lvanasse** [comment]
I'm not sure how to update the #11127 issue to mark the page as migrated. But @raiden00pl let me know which way you'd prefer it is update :). 

Cheers

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by xiaoxiang781216** [comment]
ditto

**Comment by raiden00pl** [comment]
@lvanasse I think you need committer privileges to be able to update an issue that isn't yours. 
Just ping me when you change something related to this issue and I'll update tasks list.

**Review by raiden00pl — CHANGES_REQUESTED** [review]
please use headings style like it's recommended in doc:

https://nuttx.apache.org/docs/latest/contributing/documentation.html#headings

```
=================
Top Level Heading
=================

Subsection
==========

Subsubsection
-------------

```

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by xiaoxiang781216** [comment]
@lvanasse please drop merge patch from pr.

**Comment by lvanasse** [comment]
> @lvanasse please drop merge patch from pr.

Sorry, I think it's fixed now.

**Comment by xiaoxiang781216** [comment]
need rebase to the master to fix the conflict

**Comment by lvanasse** [comment]
> need rebase to the master to fix the conflict

Very sorry, I think this fixes the conflicts. There's probably going to be another of those rebase happening on the other documentation PR. So I'll do it again once this one is merge :).

Thank you!

**Review by hartmannathan — APPROVED** [review]
Thank you!

**Comment by lvanasse** [comment]
Just rebase @xiaoxiang781216, should be good now :)

**Pull request merged**
