### PR TITLE
Reapply "sched/spinlock: remove nesting spinlock support"

### PR DESCRIPTION
**Pull request by hujun260**
## Summary
since https://github.com/apache/nuttx/pull/14200 fix the dead lock.
we reapply https://github.com/apache/nuttx/pull/14190

## Impact
none

## Testing
Build Host(s): Linux x86
Target(s): sim/smp

After that, there will be no warnings for compilation
make distclean -j20; ./tools/configure.sh -l sim:smp;make -j20
  Copy files
  Select CONFIG_HOST_LINUX=y
  Refreshing...
CP: arch/dummy/Kconfig to /home/hujun5/downloads1/vela_sim/nuttx/arch/dummy/dummy_kconfig
CP: boards/dummy/Kconfig to /home/hujun5/downloads1/vela_sim/nuttx/boards/dummy/dummy_kconfig
LN: platform/board to /home/hujun5/downloads1/vela_sim/apps/platform/dummy
LN: include/arch to arch/sim/include
LN: include/arch/board to /home/hujun5/downloads1/vela_sim/nuttx/boards/sim/sim/sim/include
LN: drivers/platform to /home/hujun5/downloads1/vela_sim/nuttx/drivers/dummy
LN: include/arch/chip to /home/hujun5/downloads1/vela_sim/nuttx/arch/sim/include/sim
LN: arch/sim/src/chip to /home/hujun5/downloads1/vela_sim/nuttx/arch/sim/src/sim
LN: arch/sim/src/board to /home/hujun5/downloads1/vela_sim/nuttx/boards/sim/sim/sim/src
mkkconfig in /home/hujun5/downloads1/vela_sim/apps/examples/mcuboot
mkkconfig in /home/hujun5/downloads1/vela_sim/apps/examples
mkkconfig in /home/hujun5/downloads1/vela_sim/apps/crypto
mkkconfig in /home/hujun5/downloads1/vela_sim/apps/audioutils
mkkconfig in /home/hujun5/downloads1/vela_sim/apps/logging
mkkconfig in /home/hujun5/downloads1/vela_sim/apps/system
mkkconfig in /home/hujun5/downloads1/vela_sim/apps/fsutils
mkkconfig in /home/hujun5/downloads1/vela_sim/apps/benchmarks
mkkconfig in /home/hujun5/downloads1/vela_sim/apps/database
mkkconfig in /home/hujun5/downloads1/vela_sim/apps/interpreters/luamodules
mkkconfig in /home/hujun5/downloads1/vela_sim/apps/interpreters
mkkconfig in /home/hujun5/downloads1/vela_sim/apps/boot
mkkconfig in /home/hujun5/downloads1/vela_sim/apps/testing
mkkconfig in /home/hujun5/downloads1/vela_sim/apps/mlearning
mkkconfig in /home/hujun5/downloads1/vela_sim/apps/graphics
mkkconfig in /home/hujun5/downloads1/vela_sim/apps/netutils
mkkconfig in /home/hujun5/downloads1/vela_sim/apps/sdr
mkkconfig in /home/hujun5/downloads1/vela_sim/apps/canutils
mkkconfig in /home/hujun5/downloads1/vela_sim/apps/lte
mkkconfig in /home/hujun5/downloads1/vela_sim/apps/inertial
mkkconfig in /home/hujun5/downloads1/vela_sim/apps/math
mkkconfig in /home/hujun5/downloads1/vela_sim/apps/wireless/ieee802154
mkkconfig in /home/hujun5/downloads1/vela_sim/apps/wireless/bluetooth
mkkconfig in /home/hujun5/downloads1/vela_sim/apps/wireless
mkkconfig in /home/hujun5/downloads1/vela_sim/apps/videoutils
mkkconfig in /home/hujun5/downloads1/vela_sim/apps/games
mkkconfig in /home/hujun5/downloads1/vela_sim/apps/industry
mkkconfig in /home/hujun5/downloads1/vela_sim/apps
Loaded configuration '.config'
Configuration saved to '.config'
Create version.h
LN: platform/board to /home/hujun5/downloads1/vela_sim/apps/platform/dummy
Register: hello
Register: nsh
Register: sh
Register: taskset
Register: ostest
Register: getprime
Register: smp
CP:  /home/hujun5/downloads1/vela_sim/nuttx/include/nuttx/config.h
CP:  /home/hujun5/downloads1/vela_sim/nuttx/include/nuttx/fs/hostfs.h
LD:  nuttx

### CODE REVIEW

**Comment by nuttxpr** [comment]
[**\[Experimental Bot, please feedback here\]**](https://github.com/search?q=repo%3Aapache%2Fnuttx+13552&type=issues)



The PR summary is missing some key details:

* **Why**: It mentions re-applying a previous PR due to a deadlock fix, but doesn't clearly explain what the original PR aimed to achieve. 
* **What**: It lacks specifics about the functional code changes being made.
* **How**:  No explanation on how the re-applied changes work.

**Impact** section is too brief. While stating "none" might be accurate, it's better to explicitly confirm no impact on:

* User experience
* Build process (despite showing build commands, it's not a confirmation)
* Hardware compatibility
* Documentation needs
* Security implications
* Backward/forward compatibility

**Testing** section has issues:

* Only mentions build hosts and target; needs more details about the testing environment (OS versions, compiler versions).
* It claims "no warnings for compilation" but doesn't prove it.  The provided logs are build logs, not compilation logs.
* No "before change" logs are present, making it impossible to assess the impact of the changes.

**Verdict**: **This PR does not meet the NuttX requirements.** It lacks crucial information in the summary and impact sections, and the testing section doesn't provide sufficient evidence of verification.

**Comment by lupyuen** [comment]
Wonder why this `telnetd` build is failing? It doesn't seem to be caused by the PR.
https://github.com/apache/nuttx/actions/runs/11313625049/job/31462630855
```text
Configuration/Tool: zkit-arm-1769/nxhello,CONFIG_ARM_TOOLCHAIN_GNU_EABI
2024-10-13 11:11:50
telnetd.c: In function 'telnetd_main':
Error: telnetd.c:57:5: error: 'CONFIG_SYSTEM_TELNETD_SESSION_STACKSIZE' undeclared (first use in this function); did you mean 'CONFIG_SYSTEM_TELNETD_SESSION_PRIORITY'?
   57 |     CONFIG_SYSTEM_TELNETD_SESSION_STACKSIZE,
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |     CONFIG_SYSTEM_TELNETD_SESSION_PRIORITY
```

**Comment by xiaoxiang781216** [comment]
@lupyuen fix by https://github.com/apache/nuttx-apps/pull/2716

**Comment by masayuki2009** [comment]
> since https://github.com/apache/nuttx/pull/14200 fix the dead lock.

@anchao @hujun260 @xiaoxiang781216 

I tried this PR with https://github.com/apache/nuttx/pull/14200, the nsh deadlock issue that I reported in https://github.com/apache/nuttx/pull/14079#issuecomment-2408714889 was resolved.

However, if I run nxplayer repeatedly with spresense:rndis_smp, deadlock happens.
I think we would find other deadlocks if we test more complicated use cases.

As I commented in https://github.com/apache/nuttx/pull/14079#issuecomment-2408714889, I think it's too early to remove nesting spinlock support. So again, I suggest we revert this PR.

**Comment by anchao** [comment]
> > since #14200 fix the dead lock.
> 
> @anchao @hujun260 @xiaoxiang781216
> 
> I tried this PR with #14200, the nsh deadlock issue that I reported in [#14079 (comment)](https://github.com/apache/nuttx/pull/14079#issuecomment-2408714889) was resolved.
> 
> However, if I run nxplayer repeatedly with spresense:rndis_smp, deadlock happens. I think we would find other deadlocks if we test more complicated use cases.
> 
> As I commented in [#14079 (comment)](https://github.com/apache/nuttx/pull/14079#issuecomment-2408714889), I think it's too early to remove nesting spinlock support. So again, I suggest we revert this PR.

@masayuki2009 
OK, please review this PR whether works for you, thanks

**Pull request merged**
