### PR TITLE
qemu-armv8a/netnsh: Set iob buffer size to 1514 to improve performance 

### PR DESCRIPTION
**Pull request by anchao**
## Summary

qemu-armv8a/netnsh: Set iob buffer size to 1514 to improve performance

Signed-off-by: chao an <anchao@xiaomi.com>

## Impact

Link issue:
https://github.com/apache/nuttx/issues/7802#issuecomment-1341856827

## Testing

qemu-armv8a/netnsh iperf test

### CODE REVIEW

**Comment by masayuki2009** [comment]
@anchao 
The defconfigs improve `iperf -c` but `iperf -s` does not work.

```
+ /home/ishikawa/opensource/QEMU/qemu-7.1/build/qemu-system-aarch64 -cpu cortex-a53 -smp 4 -nographic -machine virt,virtualization=on,gic-version=3 -chardev stdio,id=con,mux=on -serial chardev:con -global virtio-mmio.force-legacy=false -netdev user,id=u1,hostfwd=tcp:127.0.0.1:10023-10.0.2.15:23,hostfwd=tcp:127.0.0.1:15001-10.0.2.15:5001 -device virtio-net-device,netdev=u1,bus=virtio-mmio-bus.0 -mon chardev=con,mode=readline -kernel ./nuttx
telnetd [4:100]

NuttShell (NSH) NuttX-10.4.0
nsh> uname -a
NuttX  10.4.0 ae37c9a061 Dec  9 2022 08:52:47 arm64 qemu-armv8a
nsh> ps
  PID GROUP PRI POLICY   TYPE    NPX STATE    EVENT     SIGMASK   STACK   USED  FILLED COMMAND
    0     0   0 FIFO     Kthread N-- Ready              00000000 008144 000992  12.1%  Idle Task
    1     1 192 RR       Kthread --- Waiting  Semaphore 00000000 008096 000960  11.8%  hpwork 0x402d3428
    2     2 100 RR       Kthread --- Waiting  Semaphore 00000000 008096 000960  11.8%  lpwork 0x402d3458
    3     3 100 RR       Task    --- Running            00000000 008112 003024  37.2%  nsh_main
    4     4 100 RR       Task    --- Waiting  Semaphore 00000010 008112 001616  19.9%  telnetd
nsh> iperf -c 43.31.77.50
       IP: 10.0.2.15

 mode=tcp-client sip=10.0.2.15:5001,dip=43.31.77.50:5001, interval=3, time=30

           Interval         Transfer         Bandwidth

   0.00-   3.01 sec   78479360 Bytes  208.58 Mbits/sec
   3.01-   6.02 sec  153731072 Bytes  200.00 Mbits/sec
   6.02-   9.03 sec  233570304 Bytes  212.20 Mbits/sec
   9.03-  12.04 sec  314228736 Bytes  214.37 Mbits/sec
  12.04-  15.05 sec  390135808 Bytes  201.75 Mbits/sec
  15.05-  18.06 sec  470974464 Bytes  214.85 Mbits/sec
  18.06-  21.07 sec  550240256 Bytes  210.67 Mbits/sec
  21.07-  24.08 sec  626622464 Bytes  203.01 Mbits/sec
  24.08-  27.09 sec  703201280 Bytes  203.53 Mbits/sec
  27.09-  30.10 sec  783155200 Bytes  212.50 Mbits/sec
   0.00-  30.10 sec  783155200 Bytes  208.15 Mbits/sec
iperf exit
nsh> iperf -s
       IP: 10.0.2.15

 mode=tcp-server sip=10.0.2.15:5001,dip=0.0.0.0:5001, interval=3, time=0
accept: 10.0.2.2,59832

           Interval         Transfer         Bandwidth

   0.00-   3.01 sec      27740 Bytes    0.06 Mbits/sec
   3.01-   6.02 sec      27740 Bytes    0.00 Mbits/sec
   6.02-   9.03 sec      27740 Bytes    0.00 Mbits/sec
tcp server recv error, error code: 11, reason: Unknown error
iperf exit
nsh>
```

**Comment by anchao** [comment]
> The defconfigs improve iperf -c but iperf -s does not work.

@masayuki2009 san,
Do you have sanity testing for virtio drvier? It seems virtio driver is not stable, why not use openamp to implement it?

**Comment by masayuki2009** [comment]
>Do you have sanity testing for virtio drvier? It seems virtio driver is not stable, why not use openamp to implement it?

Oh, really?
I tested the driver with `iperf -c`, `iperf -s`, `telnetd` and `renew`.
They were stable when my PR https://github.com/apache/nuttx/pull/7673 was merged.

**Comment by anchao** [comment]
> > Do you have sanity testing for virtio drvier? It seems virtio driver is not stable, why not use openamp to implement it?
> 
> @anchao Oh, really? I tested the driver with `iperf -c`, `iperf -s`, `telnetd` and `renew`. They were stable and the performance was good when my PR #7673 was merged.

Yes, I understand your position, I will investigate this issue further

**Comment by anchao** [comment]
> > > Do you have sanity testing for virtio drvier? It seems virtio driver is not stable, why not use openamp to implement it?
> > 
> > 
> > @anchao Oh, really? I tested the driver with `iperf -c`, `iperf -s`, `telnetd` and `renew`. They were stable and the performance was good when my PR #7673 was merged.

There is a issue with the the virtio driver before https://github.com/apache/nuttx/pull/7616 merged, if the UDP protocol is used and bandwidth is set to 100M, the virtio driver will can not receive any interrupts, and  virtio (available/used) index will not continue to increase,

Host iperf client, set bandwidth to 100M
```
$ iperf -c 127.0.0.1 -i 1 -p 15001 -u -b 100M
------------------------------------------------------------
Client connecting to 127.0.0.1, UDP port 15001
Sending 1470 byte datagrams, IPG target: 112.15 us (kalman adjust)
UDP buffer size:  208 KByte (default)
------------------------------------------------------------
[  3] local 127.0.0.1 port 47139 connected with 127.0.0.1 port 15001
[ ID] Interval       Transfer     Bandwidth
[  3]  0.0- 1.0 sec  12.5 MBytes   105 Mbits/sec
[  3]  1.0- 2.0 sec  12.5 MBytes   105 Mbits/sec
[  3]  2.0- 3.0 sec  12.5 MBytes   105 Mbits/sec
```

nuttx (checkout before https://github.com/apache/nuttx/pull/7616 merged, and setup udp forward port hostfwd=udp:127.0.0.1:15001-10.0.2.15:5001)
```
incubator-nuttx$ qemu-system-aarch64 -cpu cortex-a53 -smp 4 -nographic -machine virt,virtualization=on,gic-version=3 -chardev stdio,id=con,mux=on -serial chardev:con -global virtio-mmio.force-legacy=false -netdev user,id=u1,hostfwd=tcp:127.0.0.1:10023-10.0.2.15:23,hostfwd=tcp:127.0.0.1:15001-10.0.2.15:5001,hostfwd=tcp:127.0.0.1:15002-10.0.2.15:5002,hostfwd=udp:127.0.0.1:15001-10.0.2.15:5001 -device virtio-net-device,netdev=u1,bus=virtio-mmio-bus.0 -mon chardev=con,mode=readline -kernel ./nuttx
telnetd [4:100]

NuttShell (NSH) NuttX-10.4.0
nsh> iperf -s -u -i 1
       IP: 10.0.2.15

 mode=udp-server sip=10.0.2.15:5001,dip=0.0.0.0:5001, interval=1, time=0
want recv=16384

           Interval         Transfer         Bandwidth

   0.00-   1.01 sec       5880 Bytes    0.00 Mbits/sec
   1.01-   2.02 sec       5880 Bytes    0.00 Mbits/sec
   2.02-   3.03 sec       5880 Bytes    0.00 Mbits/sec
   3.03-   4.04 sec       5880 Bytes    0.00 Mbits/sec
   4.04-   5.05 sec       5880 Bytes    0.00 Mbits/sec
   5.05-   6.06 sec       5880 Bytes    0.00 Mbits/sec
   6.06-   7.07 sec       5880 Bytes    0.00 Mbits/sec
```


After PR https://github.com/apache/nuttx/pull/7616 is merged, the schedule timing will changed, this issue will easier to reproduce on TCP protocol, also that the rx queue cannot receive any data from host, I think the most fundamental issue is that why virtio driver will hang up on the UDP protocol if bandwidth is set to 100M.
@masayuki2009 san, Do you have any suggestions? since I am not familiar with the virtio driver yet.

**Comment by masayuki2009** [comment]
@anchao 
Sorry, I only tested the iperf in TCP mode.
I will try the iperf in UDP mode tomorrow.

**Comment by anchao** [comment]
> @anchao Sorry, I only tested the iperf in TCP mode. I will try the iperf in UDP mode tomorrow.

@masayuki2009 san, please try the latest update, I changed the update strategy for RX index, which can fix the UDP issue, and also I did the related test of iperf UDP/TCP, it seems that everything works as expected

**Comment by xiaoxiang781216** [comment]
@anchao please rebase to the last master, ci break has been fixed.

**Comment by masayuki2009** [comment]
>@masayuki2009 san, please try the latest update, I changed the update strategy for RX index, which can fix the UDP issue, and also I did the related test of iperf UDP/TCP, it seems that everything works as expected

@anchao 

`qemu-armv8a:netnsh` seems OK but `qemu-armv8a:netnsh_smp` has a problem.

```
+ /home/ishikawa/opensource/QEMU/qemu-7.1/build/qemu-system-aarch64 -cpu cortex-a53 -smp 4 -nographic -machine virt,virtualization=on,gic-version=3 -chardev stdio,id=con,mux=on -serial chardev:con -global virtio-mmio.force-legacy=false -netdev user,id=u1,hostfwd=tcp:127.0.0.1:10023-10.0.2.15:23,hostfwd=tcp:127.0.0.1:15001-10.0.2.15:5001 -device virtio-net-device,netdev=u1,bus=virtio-mmio-bus.0 -mon chardev=con,mode=readline -kernel ./nuttx
telnetd [7:100]

NuttShell (NSH) NuttX-10.4.0
nsh> uname -a
NuttX  10.4.0 a13c876080 Dec 12 2022 09:02:59 arm64 qemu-armv8a
nsh> ps
  PID GROUP CPU PRI POLICY   TYPE    NPX STATE    EVENT     SIGMASK   STACK   USED  FILLED COMMAND
    0     0   0   0 FIFO     Kthread N-- Assigned           00000000 008144 001040  12.7%  CPU0 IDLE
    1     1   1   0 FIFO     Kthread N-- Running            00000000 008144 000320   3.9%  CPU1 IDLE
    2     2   2   0 FIFO     Kthread N-- Running            00000000 008144 000320   3.9%  CPU2 IDLE
    3     3   3   0 FIFO     Kthread N-- Running            00000000 008144 000080   0.9%  CPU3 IDLE
    4     4 --- 192 RR       Kthread --- Waiting  Semaphore 00000000 008096 000496   6.1%  hpwork 0x402d55d0
    5     5 --- 100 RR       Kthread --- Waiting  Semaphore 00000000 008096 000528   6.5%  lpwork 0x402d5600
    6     6   0 100 RR       Task    --- Running            00000000 008112 002480  30.5%  nsh_main
    7     7 --- 100 RR       Task    --- Waiting  Semaphore 00000010 008112 001216  14.9%  telnetd
nsh> iperf -s -i 1 -t 5
       IP: 10.0.2.15

 mode=tcp-server sip=10.0.2.15:5001,dip=0.0.0.0:5001, interval=1, time=5
accept: 10.0.2.2,53800

           Interval         Transfer         Bandwidth

   0.00-   1.01 sec      36500 Bytes     inf Mbits/sec
   1.01-   2.02 sec      59860 Bytes     inf Mbits/sec
   2.02-   3.03 sec      59860 Bytes     nan Mbits/sec
   3.03-   4.04 sec      59860 Bytes     nan Mbits/sec
   4.04-   5.05 sec     109729 Bytes     inf Mbits/sec
   0.00-   5.05 sec     109729 Bytes    0.17 Mbits/sec
iperf exit
```

**Comment by anchao** [comment]
> `qemu-armv8a:netnsh` seems OK but `qemu-armv8a:netnsh_smp` has a problem.

This is not caused by the commit of #7616. This issue existed before #7616 was merged. I think we can create a separate issue to track it, Could we merge this PR if there are no other issues with qemu-armv8a/netnsh?

**Comment by masayuki2009** [comment]
>This is not caused by the commit of https://github.com/apache/nuttx/pull/7616. This issue existed before https://github.com/apache/nuttx/pull/7616 was merged. 

@anchao 
Hmm, I do not think so. 
With the latest upstream, `iperf -s` in TCP mode achieves ~120Mbps.

```
+ /home/ishikawa/opensource/QEMU/qemu-7.1/build/qemu-system-aarch64 -cpu cortex-a53 -smp 4 -nographic -machine virt,virtualization=on,gic-version=3 -chardev stdio,id=con,mux=on -serial chardev:con -global virtio-mmio.force-legacy=false -netdev user,id=u1,hostfwd=tcp:127.0.0.1:10023-10.0.2.15:23,hostfwd=tcp:127.0.0.1:15001-10.0.2.15:5001 -device virtio-net-device,netdev=u1,bus=virtio-mmio-bus.0 -mon chardev=con,mode=readline -kernel ./nuttx
telnetd [7:100]

NuttShell (NSH) NuttX-10.4.0
nsh> ps
  PID GROUP CPU PRI POLICY   TYPE    NPX STATE    EVENT     SIGMASK   STACK   USED  FILLED COMMAND
    0     0   0   0 FIFO     Kthread N-- Assigned           00000000 008144 001088  13.3%  CPU0 IDLE
    1     1   1   0 FIFO     Kthread N-- Running            00000000 008144 000320   3.9%  CPU1 IDLE
    2     2   2   0 FIFO     Kthread N-- Running            00000000 008144 000320   3.9%  CPU2 IDLE
    3     3   3   0 FIFO     Kthread N-- Running            00000000 008144 000080   0.9%  CPU3 IDLE
    4     4 --- 192 RR       Kthread --- Waiting  Semaphore 00000000 008096 000496   6.1%  hpwork 0x402d55d0
    5     5 --- 100 RR       Kthread --- Waiting  Semaphore 00000000 008096 000528   6.5%  lpwork 0x402d5600
    6     6   0 100 RR       Task    --- Running            00000000 008112 002288  28.2%  nsh_main
    7     7 --- 100 RR       Task    --- Waiting  Semaphore 00000010 008112 001216  14.9%  telnetd
nsh> uname -a
NuttX  10.4.0 4a84555d1c Dec 12 2022 12:55:55 arm64 qemu-armv8a
nsh> iperf -s
       IP: 10.0.2.15

 mode=tcp-server sip=10.0.2.15:5001,dip=0.0.0.0:5001, interval=3, time=0
accept: 10.0.2.2,53868

           Interval         Transfer         Bandwidth

   0.00-   3.01 sec   26281460 Bytes     inf Mbits/sec
   3.01-   6.02 sec   72277300 Bytes     inf Mbits/sec
   6.02-   9.03 sec  117957780 Bytes     inf Mbits/sec
closed by the peer: 10.0.2.2,59578
iperf exit
nsh>

On Ubuntu:

$ iperf -c localhost -p 15001 -i 1 -t 10
------------------------------------------------------------
Client connecting to localhost, TCP port 15001
TCP window size: 3.26 MByte (default)
------------------------------------------------------------
[  3] local 127.0.0.1 port 59578 connected with 127.0.0.1 port 15001
[ ID] Interval       Transfer     Bandwidth
[  3]  0.0- 1.0 sec  3.34 MBytes  28.0 Mbits/sec
[  3]  1.0- 2.0 sec  14.8 MBytes   124 Mbits/sec
[  3]  2.0- 3.0 sec  15.0 MBytes   126 Mbits/sec
[  3]  3.0- 4.0 sec  14.4 MBytes   121 Mbits/sec
[  3]  4.0- 5.0 sec  14.2 MBytes   120 Mbits/sec
[  3]  5.0- 6.0 sec  14.9 MBytes   125 Mbits/sec
[  3]  6.0- 7.0 sec  14.8 MBytes   124 Mbits/sec
[  3]  7.0- 8.0 sec  13.6 MBytes   114 Mbits/sec
[  3]  8.0- 9.0 sec  15.0 MBytes   126 Mbits/sec
[  3]  9.0-10.0 sec  14.9 MBytes   125 Mbits/sec
[  3]  0.0-10.1 sec   135 MBytes   112 Mbits/sec
```

However, with this PR, `iperf -s` in TCP mode is much slower.

```

+ /home/ishikawa/opensource/QEMU/qemu-7.1/build/qemu-system-aarch64 -cpu cortex-a53 -smp 4 -nographic -machine virt,virtualization=on,gic-version=3 -chardev stdio,id=con,mux=on -serial chardev:con -global virtio-mmio.force-legacy=false -netdev user,id=u1,hostfwd=tcp:127.0.0.1:10023-10.0.2.15:23,hostfwd=tcp:127.0.0.1:15001-10.0.2.15:5001 -device virtio-net-device,netdev=u1,bus=virtio-mmio-bus.0 -mon chardev=con,mode=readline -kernel ./nuttx
telnetd [7:100]

NuttShell (NSH) NuttX-10.4.0
nsh> uname -a
NuttX  10.4.0 a13c876080 Dec 12 2022 12:57:33 arm64 qemu-armv8a
nsh> ps
  PID GROUP CPU PRI POLICY   TYPE    NPX STATE    EVENT     SIGMASK   STACK   USED  FILLED COMMAND
    0     0   0   0 FIFO     Kthread N-- Assigned           00000000 008144 001040  12.7%  CPU0 IDLE
    1     1   1   0 FIFO     Kthread N-- Running            00000000 008144 000320   3.9%  CPU1 IDLE
    2     2   2   0 FIFO     Kthread N-- Running            00000000 008144 000320   3.9%  CPU2 IDLE
    3     3   3   0 FIFO     Kthread N-- Running            00000000 008144 000080   0.9%  CPU3 IDLE
    4     4 --- 192 RR       Kthread --- Waiting  Semaphore 00000000 008096 000496   6.1%  hpwork 0x402d55d0
    5     5 --- 100 RR       Kthread --- Waiting  Semaphore 00000000 008096 000528   6.5%  lpwork 0x402d5600
    6     6   0 100 RR       Task    --- Running            00000000 008112 002240  27.6%  nsh_main
    7     7 --- 100 RR       Task    --- Waiting  Semaphore 00000010 008112 001216  14.9%  telnetd
nsh> iperf -s
       IP: 10.0.2.15

 mode=tcp-server sip=10.0.2.15:5001,dip=0.0.0.0:5001, interval=3, time=0
accept: 10.0.2.2,42298

           Interval         Transfer         Bandwidth

   0.00-   3.01 sec     110424 Bytes    0.29 Mbits/sec
   3.01-   6.02 sec     215274 Bytes    0.27 Mbits/sec
   6.02-   9.03 sec     320124 Bytes    0.27 Mbits/sec
   9.03-  12.04 sec     424974 Bytes    0.27 Mbits/sec
  12.04-  15.05 sec     529824 Bytes    0.27 Mbits/sec
  15.05-  18.06 sec     634674 Bytes    0.27 Mbits/sec
  18.06-  21.07 sec     739524 Bytes    0.27 Mbits/sec
  21.07-  24.08 sec     844374 Bytes    0.27 Mbits/sec
  24.08-  27.09 sec     949224 Bytes    0.27 Mbits/sec
  27.09-  30.10 sec    1054074 Bytes    0.27 Mbits/sec
  30.10-  33.11 sec    1179737 Bytes    0.33 Mbits/sec
  33.11-  36.12 sec    1368553 Bytes    0.50 Mbits/sec
  36.12-  39.13 sec    1471220 Bytes    0.27 Mbits/sec

On Ubuntu:

$ iperf -c localhost -p 15001 -i 1 -t 10
------------------------------------------------------------
Client connecting to localhost, TCP port 15001
TCP window size: 3.26 MByte (default)
------------------------------------------------------------
[  3] local 127.0.0.1 port 42298 connected with 127.0.0.1 port 15001
[ ID] Interval       Transfer     Bandwidth
[  3]  0.0- 1.0 sec  3.34 MBytes  28.0 Mbits/sec
[  3]  1.0- 2.0 sec  0.00 Bytes  0.00 bits/sec
[  3]  2.0- 3.0 sec  4.71 MBytes  39.6 Mbits/sec
[  3]  3.0- 4.0 sec   512 KBytes  4.19 Mbits/sec
[  3]  4.0- 5.0 sec  0.00 Bytes  0.00 bits/sec
[  3]  5.0- 6.0 sec  0.00 Bytes  0.00 bits/sec
[  3]  6.0- 7.0 sec  0.00 Bytes  0.00 bits/sec
[  3]  7.0- 8.0 sec  0.00 Bytes  0.00 bits/sec
[  3]  8.0- 9.0 sec  0.00 Bytes  0.00 bits/sec
[  3]  9.0-10.0 sec  0.00 Bytes  0.00 bits/sec
[  3]  0.0-10.2 sec  8.56 MBytes  7.05 Mbits/sec
```

**Comment by anchao** [comment]
> > This is not caused by the commit of #7616. This issue existed before #7616 was merged.
> 
> @anchao Hmm, I do not think so. With the latest upstream, `iperf -s` in TCP mode achieves ~120Mbps.

What you shared are two different issues, one is tcp service and the other is client, please can retry latest PR, it solves qemu-armv8a: netnsh_smp tcp traffic drops

**Comment by masayuki2009** [comment]
>What you shared are two different issues, one is tcp service and the other is client, please can retry latest PR, it solves qemu-armv8a: netnsh_smp tcp traffic drops

Yes. The first ieeue (e.g. `iperf -s` with  `qemu-armv8a: netnsh_smp`) was newly found during testing this PR.
Now the latest commits fixes both issues.

**Comment by masayuki2009** [comment]
Though there are some issues with 'Build / macOS (macos)', I think the issues do not relate to this PR.
So let me merge this PR.

**Pull request merged**
