### PR TITLE
sim_uart: fix printf error when use irq mode

### PR DESCRIPTION
**Pull request by GUIDINGLI**
## Summary

sim_uart: fix printf error when use irq mode

## Impact

sim printf

## Testing

VELA

### CODE REVIEW

**Review by acassis — APPROVED** [review]

**Review by xiaoxiang781216 — APPROVED** [review]

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by fjpanag** [comment]
@GUIDINGLI @xiaoxiang781216 This PR breaks sim (and has stopped all our testing from working).

After this commit, sim output is not flushed when a task is exited.  
Thus the last output before task exit is lost, and our CI cannot parse the test results.

For example, when running mmtest, this is the normal output before this change:
```
...

(31)Releasing memory at 0x7f93e1633f00 (size=24 bytes)
     mallinfo:
       Total space allocated from system = 66059728
       Number of non-inuse chunks        = 2
       Largest non-inuse chunk           = 65557792
       Total allocated space             = 432688
       Total non-inuse space             = 65627040
TEST COMPLETE
```

after this change:
```
...

(26)Releasing memory at 0x7f716cc34500 (size=25 bytes)
     mallinfo:
       Total space a
```

Can you please have a look?

**Comment by GUIDINGLI** [comment]
@fjpanag 

Which defconfig do you use ?

I got the following output when use `sim:nsh`:

```
(31)Releasing memory at 0x7ffff3e9e3a0 (size=24 bytes)
     mallinfo:
       Total space allocated from system = 67108192
       Number of non-inuse chunks        = 4
       Largest non-inuse chunk           = 65247392
       Total allocated space             = 1860608
       Total non-inuse space             = 65247584
TEST COMPLETE
```

**Comment by fjpanag** [comment]
@GUIDINGLI Please try to enable `CONFIG_TESTING_MM_POWEROFF`.

**Comment by GUIDINGLI** [comment]
@fjpanag 

https://github.com/apache/nuttx/pull/8408
Please have a try, thanks.

**Pull request merged**
