### PR TITLE
boards/stm32f411-minimum: add support for /dev/gpio*

### PR DESCRIPTION
**Pull request by mlyszczek**
## Summary
This patch allows user to simply select which GPIOs he wants to use and access them via /dev/gpio_a0 or similar device with standard gpio driver.

By default gpio names match pin names printed on the board. So when enabling A3 pin, it will show as /dev/gpio_a3 in runtime. This name can be changed in kconfig.

User can also select pin function (input, output, interrupt) as well as standard pin settings like, pull up/down, output type pushpull/open drain etc.

All pins that are exposed via boards goldpins are listed in Kconfig. Extra pins that are supported by chiip but are not exposed for easy usage are not listed.

To have this nice Kconfig configuration and for things to be easily debugable/understandable it requires code to have big Kconfig and header file with all possible definitions

Because of file sizes I decided to split gpio related kconfig and header into separate files. Otherwise it would really make original files hard to read and find anything.

## Impact
stm32f411-minimum boards

## Testing
Tested read, write and interrupt on stm32f411-minimum board via example GPIO program.

### CODE REVIEW

**Comment by mlyszczek** [comment]
For reference - it looks like it

```
┌── enable gpio subsystem ──────────────────────────────────────────────────────────┐
│                                                                                   │
│                             pull (pull down)  --->                                │
│                             speed (2MHz)  --->                                    │
│                     [ ]   enable pin A10                                          │
│                     [ ]   enable pin A11                                          │
│                     [ ]   enable pin A12                                          │
│                     [ ]   enable pin A15                                          │
│                     [ ]   enable pin B0                                           │
│                     [ ]   enable pin B1                                           │
│                     [ ]   enable pin B2                                           │
│                     [ ]   enable pin B3                                           │
│                     [ ]   enable pin B4                                           │
│                     [ ]   enable pin B5                                           │
│                     [ ]   enable pin B6                                           │
│                     [ ]   enable pin B7                                           │
│                     [ ]   enable pin B8                                           │
│                     [ ]   enable pin B9                                           │
│                     [ ]   enable pin B10                                          │
│                     [*]   enable pin B12                                          │
│                         (gpio_teapot) Pin name                                    │
│                             Pin type (output)  --->                               │
│                             output type (push pull)  --->                         │
│                             default state (set)  --->                             │
│                             pull (pull down)  --->                                │
│                             speed (2MHz)  --->                                    │
│                     [*]   enable pin B13                                          │
│                         (gpio_pump) Pin name                                      │
│                             Pin type (output)  --->                               │
│                             output type (push pull)  --->                         │
│                             default state (set)  --->                             │
│                             pull (pull down)  --->                                │
│                             speed (2MHz)  --->                                    │
│                     [*]   enable pin B14                                          │
│                         (gpio_motor_l) Pin name                                   │
│                             Pin type (output)  --->                               │
│                             output type (push pull)  --->                         │
│                                                                                   │
│                                                                                   │
└F1Help─F2SymInfo─F3Help 2─F4ShowAll─F5Back─F6Save─F7Load─F8SymSearch─F9Exit────────┘
```

**Comment by acassis** [comment]
@mlyszczek I suggest you to use pin PAx, PBx, PCx, etc, because if someone see /dev/gpio_a0 could be induced to think it is an analog, because this is the naming used for example in Arduino.

**Comment by mlyszczek** [comment]
Hmm... you think? I named them exactly as they are printed on the PCB.

**Comment by acassis** [comment]
> Hmm... you think? I named them exactly as they are printed on the PCB.

Hmm, ok! In the datasheet they are referenced as PA*, PB*, PC*, etc

**Comment by mlyszczek** [comment]
Yes, in stm32 datasheet they refer to pins as PA, PB etc.
but board refers to them as A, B... I'm pretty sure it's
to save space on PCB, as they would not fit PA, PB...
Here is an image of that board.

https://stm32-base.org/assets/img/boards/STM32F411CEU6_WeAct_Black_Pill_V2.0-2.jpg

And since these files are board specific - and not chip
specific, I think a0, a1... are better than pa0, pa1, etc.

That was my reasoning for naming scheme.

**Comment by acassis** [comment]
Please rebase to fix the CI issue

**Comment by mlyszczek** [comment]
let's try another rebase, and hope it works :)

**Comment by acassis** [comment]
@mlyszczek the error seems to be in your Kconfig:

Kconfig Configuration Error: boards/arm/stm32/stm32f411-minimum/Kconfig:83:
  warning: style: quotes recommended around
  'boards/arm/stm32/stm32f411-minimum/Kconfig.gpio' in 'source
  boards/arm/stm32/stm32f411-minimum/Kconfig.gpio'

**Comment by mlyszczek** [comment]
Yay, finally a success. Sorry it took so long.

**Review by xiaoxiang781216 — APPROVED** [review]

**Review by jerpelea — APPROVED** [review]

**Review by acassis — APPROVED** [review]

**Pull request merged**
