### PR TITLE
sched: Remove pidhash_s and move ticks to tcb_s 

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
## Summary
simplify the code logic and reduce memory a little bit

## Impact
Internal interface change

### CODE REVIEW

**Comment by xiaoxiang781216** [comment]
@gustavonihei could you merge it if no more issue, thanks.

**Comment by masayuki2009** [comment]
@xiaoxiang781216 

I noticed that the ostest crashed with esp32-devkitc:smp, maix-bit:smp and sim:smp.

**Comment by masayuki2009** [comment]
@xiaoxiang781216 

>I noticed that the ostest crashed with esp32-devkitc:smp (QEMU), maix-bit:smp (QEMU), and sim:smp.

The ostest with spresense:smp and sabre-quad:smp work but the above configurations do not work.
I think we should revert this PR until the root cause of the issue is resolved.

What do you think?

**Comment by xiaoxiang781216** [comment]
Ok, I found the problem, @masayuki2009 could you try https://github.com/apache/incubator-nuttx/pull/4676?

**Pull request merged**
