### PR TITLE
fix regression caused by remove sync pause

### PR DESCRIPTION
**Pull request by hujun260**
## Summary
If we need to handle a tcb that is running on another CPU, we need to process it through the smpcall method.

This commit fixes the regression from https://github.com/apache/nuttx/pull/13863
## Impact
fix regression

## Testing
ci ostest

### CODE REVIEW

**Comment by nuttxpr** [comment]
[**\[Experimental Bot, please feedback here\]**](https://github.com/search?q=repo%3Aapache%2Fnuttx+13552&type=issues)



Yes, this PR appears to meet the basic NuttX requirements, but is missing some crucial details.  While it provides a summary of the change and identifies it as a bug fix, it lacks important information for proper review.

Here's what's missing and needs to be added:

* **Summary:**  While the summary explains the *why*, it's missing the *what* and *how*.  Which functional part of the code is changed?  Specifically, what code was modified to fix the regression?  What was the original bug, and how does this change address it?
* **Impact:**  While it says it fixes a regression, it needs more detail. Does this fix impact any users directly? Were there noticeable symptoms of the regression?  Are there any specific architectures, boards, or drivers affected? Does this change require any documentation updates?
* **Testing:** "ci ostest" is insufficient. Provide *actual* log output before and after the change, demonstrating the fix.  What specific tests in `ostest` were run? Also, specify the build host and target details (OS, architecture, compiler version, etc.).  Just stating "ci" doesn't provide enough information for reviewers to reproduce your testing.

Without this additional information, it's difficult to thoroughly review the PR and assess its correctness and impact.  Providing these details will significantly improve the review process and help ensure the quality of the contribution.

**Review by xiaoxiang781216 — APPROVED** [review]

**Review by acassis — APPROVED** [review]

**Comment by tmedicci** [comment]
Hi @hujun260, it seems that it has been fixed for the test that was breaking... I'll let it testing in a long-term test. Thanks!

**Comment by tmedicci** [comment]
Hi @hujun260, our internal CI showed that `ostest` is failing for `esp32s3-devkit:smp` defconfig:

I can reproduce it locally too. It isn't a 100% fail rate, so you may run it and it passes, but it's more common to fail than pass. In order to do a fair comparison, I tried the commit just before and it executed `ostest` more than 10 times without any failure.

The ostest stuck here:
```
user_main: pthread_rwlock test
pthread_rwlock: Initializing rwlock
pthread_exit_thread 42: Exiting
```

Our internal CI enables the following configs:
```
diff --git a/boards/xtensa/esp32s3/esp32s3-devkit/configs/smp/defconfig b/boards/xtensa/esp32s3/esp32s3-devkit/configs/smp/defconfig
index a72faf9b2d..bf6fbad093 100644
--- a/boards/xtensa/esp32s3/esp32s3-devkit/configs/smp/defconfig
+++ b/boards/xtensa/esp32s3/esp32s3-devkit/configs/smp/defconfig
@@ -21,8 +21,12 @@ CONFIG_ARCH_STACKDUMP=y
 CONFIG_ARCH_XTENSA=y
 CONFIG_BOARD_LOOPSPERMSEC=16717
 CONFIG_BUILTIN=y
+CONFIG_DEBUG_ASSERTIONS=y
+CONFIG_DEBUG_ASSERTIONS_EXPRESSION=y
+CONFIG_DEBUG_FEATURES=y
 CONFIG_DEBUG_FULLOPT=y
 CONFIG_DEBUG_SYMBOLS=y
+CONFIG_ESP32S3_MERGE_BINS=y
 CONFIG_ESP32S3_UART0=y
 CONFIG_FS_PROCFS=y
 CONFIG_HAVE_CXX=y
 ```
(As the test isn't failing all the time, I couldn't evaluate if enabling these configs has some interference in the result of the test).

Do you have any idea about it?

**Comment by hujun260** [comment]
> Hi @hujun260, our internal CI showed that `ostest` is failing for `esp32s3-devkit:smp` defconfig:
> 
> I can reproduce it locally too. It isn't a 100% fail rate, so you may run it and it passes, but it's more common to fail than pass. In order to do a fair comparison, I tried the commit just before and it executed `ostest` more than 10 times without any failure.
> 
> The ostest stuck here:
> 
> ```
> user_main: pthread_rwlock test
> pthread_rwlock: Initializing rwlock
> pthread_exit_thread 42: Exiting
> ```
> 
> Our internal CI enables the following configs:
> 
> ```
> diff --git a/boards/xtensa/esp32s3/esp32s3-devkit/configs/smp/defconfig b/boards/xtensa/esp32s3/esp32s3-devkit/configs/smp/defconfig
> index a72faf9b2d..bf6fbad093 100644
> --- a/boards/xtensa/esp32s3/esp32s3-devkit/configs/smp/defconfig
> +++ b/boards/xtensa/esp32s3/esp32s3-devkit/configs/smp/defconfig
> @@ -21,8 +21,12 @@ CONFIG_ARCH_STACKDUMP=y
>  CONFIG_ARCH_XTENSA=y
>  CONFIG_BOARD_LOOPSPERMSEC=16717
>  CONFIG_BUILTIN=y
> +CONFIG_DEBUG_ASSERTIONS=y
> +CONFIG_DEBUG_ASSERTIONS_EXPRESSION=y
> +CONFIG_DEBUG_FEATURES=y
>  CONFIG_DEBUG_FULLOPT=y
>  CONFIG_DEBUG_SYMBOLS=y
> +CONFIG_ESP32S3_MERGE_BINS=y
>  CONFIG_ESP32S3_UART0=y
>  CONFIG_FS_PROCFS=y
>  CONFIG_HAVE_CXX=y
> ```
> 
> (As the test isn't failing all the time, I couldn't evaluate if enabling these configs has some interference in the result of the test).
> 
> Do you have any idea about it?

Based on your test results, https://github.com/apache/nuttx/pull/14611 may potentially cause the ostest to hang？

**Comment by tmedicci** [comment]
> > Hi @hujun260, our internal CI showed that `ostest` is failing for `esp32s3-devkit:smp` defconfig:
> > I can reproduce it locally too. It isn't a 100% fail rate, so you may run it and it passes, but it's more common to fail than pass. In order to do a fair comparison, I tried the commit just before and it executed `ostest` more than 10 times without any failure.
> > The ostest stuck here:
> > ```
> > user_main: pthread_rwlock test
> > pthread_rwlock: Initializing rwlock
> > pthread_exit_thread 42: Exiting
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Our internal CI enables the following configs:
> > ```
> > diff --git a/boards/xtensa/esp32s3/esp32s3-devkit/configs/smp/defconfig b/boards/xtensa/esp32s3/esp32s3-devkit/configs/smp/defconfig
> > index a72faf9b2d..bf6fbad093 100644
> > --- a/boards/xtensa/esp32s3/esp32s3-devkit/configs/smp/defconfig
> > +++ b/boards/xtensa/esp32s3/esp32s3-devkit/configs/smp/defconfig
> > @@ -21,8 +21,12 @@ CONFIG_ARCH_STACKDUMP=y
> >  CONFIG_ARCH_XTENSA=y
> >  CONFIG_BOARD_LOOPSPERMSEC=16717
> >  CONFIG_BUILTIN=y
> > +CONFIG_DEBUG_ASSERTIONS=y
> > +CONFIG_DEBUG_ASSERTIONS_EXPRESSION=y
> > +CONFIG_DEBUG_FEATURES=y
> >  CONFIG_DEBUG_FULLOPT=y
> >  CONFIG_DEBUG_SYMBOLS=y
> > +CONFIG_ESP32S3_MERGE_BINS=y
> >  CONFIG_ESP32S3_UART0=y
> >  CONFIG_FS_PROCFS=y
> >  CONFIG_HAVE_CXX=y
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > (As the test isn't failing all the time, I couldn't evaluate if enabling these configs has some interference in the result of the test).
> > Do you have any idea about it?
> 
> Based on your test results, #14611 may potentially cause the ostest to hang？

Yes, exactly. If I checkout to the commit just before it, it never hangs...

**Comment by hujun260** [comment]
> Yes, exactly. If I checkout to the commit just before it, it never hangs...

@tmedicci 
https://github.com/apache/nuttx-apps/pull/2822

https://github.com/apache/nuttx/pull/14656
These two PRs have just been merged and should be able to resolve the hanging issue. Please pull the latest code and help me verify it.

**Comment by tmedicci** [comment]
> > Yes, exactly. If I checkout to the commit just before it, it never hangs...
> 
> @tmedicci [apache/nuttx-apps#2822](https://github.com/apache/nuttx-apps/pull/2822)
> 
> #14656 These two PRs have just been merged and should be able to resolve the hanging issue. Please pull the latest code and help me verify it.

Hi @hujun260 ,

Still hanging at the same point...

**Comment by hujun260** [comment]
> > > Yes, exactly. If I checkout to the commit just before it, it never hangs...
> > 
> > 
> > @tmedicci [apache/nuttx-apps#2822](https://github.com/apache/nuttx-apps/pull/2822)
> > #14656 These two PRs have just been merged and should be able to resolve the hanging issue. Please pull the latest code and help me verify it.
> 
> Hi @hujun260 ,
> 
> Still hanging at the same point...

https://github.com/apache/nuttx-apps/pull/2834 please  try this patch

**Pull request merged**
