### PR TITLE
arch/arm64: add have fork config

### PR DESCRIPTION
**Pull request by lipengfei28**
1.ARCH_ARM64 select ARCH_HAVE_FORK

*Update this section with information on why change is necessary,
 what it exactly does and how, if new feature shows up, provide
 references (dependencies, similar problems and solutions), etc.*

## Impact

*Update this section, where applicable, on how change affects users,
 build process, hardware, documentation, security, compatibility, etc.*

## Testing

*Update this section with details on how did you verify the change,
 what Host was used for build (OS, CPU, compiler, ..), what Target was
 used for verification (arch, board:config, ..), etc. Providing build
 and runtime logs from before and after change is highly appreciated.*

### CODE REVIEW

**Comment by pussuw** [comment]
I'm pretty sure ostest will crash with arm64 kernel mode.

**Comment by xiaoxiang781216** [comment]
> I'm pretty sure ostest will crash with arm64 kernel mode.

Yes, the current implementation of fork/vfork is only for flat/protected build, the kernel mode need be reimplemented like Linux, which is a huge task I think that.

**Comment by pussuw** [comment]
> > I'm pretty sure ostest will crash with arm64 kernel mode.
> 
> Yes, the current implementation of fork/vfork is only for flat/protected build, the kernel mode need be reimplemented like Linux, which is a huge task I think that.

I mean arm64 vfork() will cause ostest crash in kernel mode, making the test unusable in arm64.
I did the fix for risc-v, it could be backported to this platform too ?

**Comment by xiaoxiang781216** [comment]
> > > I'm pretty sure ostest will crash with arm64 kernel mode.
> > 
> > 
> > Yes, the current implementation of fork/vfork is only for flat/protected build, the kernel mode need be reimplemented like Linux, which is a huge task I think that.
> 
> I mean arm64 vfork() will cause ostest crash in kernel mode, making the test unusable in arm64. I did the fix for risc-v, it could be backported to this platform too ?

how about change to:
```
	select ARCH_HAVE_FORK if !BUILD_KERNEL
```
before we port your riscv patch to arm64.

**Comment by pussuw** [comment]
> > > > I'm pretty sure ostest will crash with arm64 kernel mode.
> > > 
> > > 
> > > Yes, the current implementation of fork/vfork is only for flat/protected build, the kernel mode need be reimplemented like Linux, which is a huge task I think that.
> > 
> > 
> > I mean arm64 vfork() will cause ostest crash in kernel mode, making the test unusable in arm64. I did the fix for risc-v, it could be backported to this platform too ?
> 
> how about change to:
> 
> ```
> 	select ARCH_HAVE_FORK if !BUILD_KERNEL
> ```
> 
> before we port your riscv patch to arm64.

Sounds good to me

**Review by pussuw — APPROVED** [review]

**Comment by lupyuen** [comment]
Sorry I have to cancel the CI Check, there's a problem with CI Test:
- https://github.com/apache/nuttx/pull/14667#issuecomment-2461197521

**Review by xiaoxiang781216 — APPROVED** [review]

**Pull request merged**
