### PR TITLE
Update config for nuttx-apps#1558

### PR DESCRIPTION
**Pull request by PetervdPerk-NXP**
## Summary
Rename LIBCANARDV0 to LIBDRONECAN

## Impact
See apache/nuttx-apps#1558

## Testing
Compilation

### CODE REVIEW

**Comment by acassis** [comment]
Guys, why CI is not finding the toolchain:
```
/usr/bin/bash: arm-nuttx-eabi-gcc: command not found
```

**Comment by pkarashchenko** [comment]
> Guys, why CI is not finding the toolchain:
> 
> ```
> /usr/bin/bash: arm-nuttx-eabi-gcc: command not found
> ```

I think because it is not installed on the CI :)

**Comment by pkarashchenko** [comment]
Personally I've never used NuttX native toolchain, but I'm interested to try it out. @acassis do you have a link to instructions on how to use it?

**Comment by acassis** [comment]
> Personally I've never used NuttX native toolchain, but I'm interested to try it out. @acassis do you have a link to instructions on how to use it?

No, I'm also interested to master it. Maybe we can learn it and wrote a small documentation to guide others. I think it was mostly done by Brennan and Xiang.

**Review by pkarashchenko — APPROVED** [review]

**Review by lucasssvaz — APPROVED** [review]

**Comment by btashton** [comment]
@PetervdPerk-NXP some configs need to be normalized after this change for CI to pass

**Pull request merged**
