### PR TITLE
arch:xtensa:toolchain: add -Wno-atmoic-alignment flags

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
## Summary

to avoid the compiler warning

## Impact

xtensa

## Testing

Pass CI

### CODE REVIEW

**Review by pkarashchenko — APPROVED** [review]

**Comment by gustavonihei** [comment]
@xiaoxiang781216 Could you please share the motivation for disabling this warning? In which scenario does it manifest?

From this Clang patchset, this warning seems useful:
https://reviews.llvm.org/D45319

**Comment by xiaoxiang781216** [comment]
> @xiaoxiang781216 Could you please share the motivation for disabling this warning? In which scenario does it manifest?

@gustavonihei here is the warning generated by Candance's clang:
```
[2023-01-19T07:31:49.594Z] media_proxy.c:498:9: error: large atomic operation may incur significant performance penalty [-Werror,-Watomic-alignment]
[2023-01-19T07:31:49.594Z]     if (atomic_load(&priv->refs) == 1 && priv->socket) {
[2023-01-19T07:31:49.594Z]         ^
```

Here is the related struct definition:
```
typedef struct MediaProxyPriv {
    void                  *proxy;
    char                  *cpu;
    uint64_t              handle;
    atomic_int            refs;
    int                   socket;
    void                  *cookie;
    media_event_callback  event;
} MediaProxyPriv;
```
The warning looks wrong since refs should be naturally alignment.

> 
> From this Clang patchset, this warning seems useful: https://reviews.llvm.org/D45319
> 
> > If an atomic variable is misaligned Clang will emit accesses to it as a libcall. These calls are likely to be slow and involve locks; they are almost certainly not what the developer intended.

**Comment by gustavonihei** [comment]
I honestly feel that adding this flag to this broad scope is too overkill, even because the occurrence is not even in upstream code. And this is a kind of warning that shouldn't be overlooked.

Considering the motivation of bypassing a possible false positive from Clang, I would suggest to reduce the scope of this flag to the minimum possible.

**Comment by pkarashchenko** [comment]
@xiaoxiang781216 could you please point me to some good article describing atomic variables and accessing it? I need to educate myself as I was not expecting `atomic_load` to be used with `atomic_int`, but was expecting simple `priv->refs == 1` if `refs` is `atomic_int`.

**Comment by xiaoxiang781216** [comment]
Here https://en.cppreference.com/w/c/atomic/atomic_load

**Comment by pkarashchenko** [comment]
Seems to be the same as https://github.com/RIOT-OS/RIOT/issues/12048

**Comment by pkarashchenko** [comment]
Maybe that disabling can be done selectively only for Clang?

**Comment by xiaoxiang781216** [comment]
Ok, I move them to xcc section, @pkarashchenko

**Review by pkarashchenko — APPROVED** [review]

**Pull request merged**
