### PR TITLE
fs/littlefs: Add to get the full path

### PR DESCRIPTION
**Pull request by crafcat7**
## Summary
Add FIOC_FILEPATH to LFS ioctl
## Impact
LFS ioctl adds FIOC_FILEPATH for file paths
## Testing
local test PASS

### CODE REVIEW

**Comment by xiaoxiang781216** [comment]
@crafcat7 let's put littlefs patch in the same patch to avoid the ci break.

**Comment by crafcat7** [comment]
> @crafcat7 let's put littlefs patch in the same patch to avoid the ci break.

Okay, I'll sort out the relevant changes and add them in

**Comment by crafcat7** [comment]
> Missing lfs_file_path

Please try to compile it again with the latest changes, I submitted an implementation of lfs_file_path for littlefs.

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by jturnsek** [comment]
> > Missing lfs_file_path
> 
> Please try to compile it again with the latest changes, I submitted an implementation of lfs_file_path for littlefs.

It works now. Thanks.

**Comment by yamt** [comment]
@crafcat7 have you submitted the littlefs patch to the upstream? i don't think it's a good idea to maintain it in nuttx.

**Comment by crafcat7** [comment]
> @crafcat7 have you submitted the littlefs patch to the upstream? i don't think it's a good idea to maintain it in nuttx.

I sorted out the new interfaces for obtaining paths and submitted them here.
https://github.com/littlefs-project/littlefs/pull/975

**Comment by yamt** [comment]
is this functionality mainly for https://github.com/apache/nuttx/pull/11724 ?

**Comment by crafcat7** [comment]
> is this functionality mainly for #11724 ?

The current implementation of filelock still relies on getting the path to the file to determine the target. So if we want to use filelock on a file on littlefs, we need a way to get the path to the target file.
In addition to this, there are implementations such as “fdinfo” that should also rely on getting the path to the file.

**Pull request merged**
