### PR TITLE
net: Remove IFF_DOWN flag to compatible with Linux/*BSD

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
## Summary

turn off interface by checking IFF_UP flag isn't set: https://github.com/apache/nuttx/issues/1838

## Impact

improve the compatibility

## Testing

internal

### CODE REVIEW

**Comment by nuttxpr** [comment]
[**\[Experimental Bot, please feedback here\]**](https://github.com/search?q=repo%3Aapache%2Fnuttx+13552&type=issues)



This PR appears **incomplete** based on the provided description. 

**Here's why and what's missing:**

* **Insufficient Detail:** The summary and impact sections lack specifics. 
    * **Summary:**  While it links a related issue, the PR needs to clearly explain *what* functional part of the code is changed to achieve turning off the interface when IFF_UP isn't set.  
    * **Impact:** Simply stating "improve the compatibility" is too vague.  The PR needs to detail:
        *  *Which* compatibility issues are addressed?
        *  Is this backward compatible?  
        *  Are there any potential side effects for existing users?

* **Missing Testing Information:** "Internal" testing is not sufficient for a proper review.  The PR must include:
    *  **Specific build host details:** OS, CPU architecture, compiler version used.
    *  **Specific target details:**  Architecture (simulated or real hardware), board name, and the configuration used. 
    *  **Relevant log snippets:**  Don't just paste entire logs.  Include *specific* portions that demonstrate the issue before the change and the successful outcome after the change.

**To improve this PR:**

1. **Expand the Summary:** Provide a technical explanation of *how* the change works.
2. **Detail the Impact:** Be specific about the compatibility improvements, potential user impact, and any other notable effects.
3. **Provide Complete Testing Information:**  Follow the template's guidelines to include all necessary build/target details and focused log snippets.

A well-documented PR makes it easier for reviewers to understand, verify, and ultimately merge your contribution.

**Review by cederom — APPROVED** [review]
Thank you @xiaoxiang781216 :-)

**Comment by fdcavalcanti** [comment]
@jerpelea would be possible to backport this commit on 12.7?
The related  commit on `nuttx-apps` was [backported](https://github.com/apache/nuttx-apps/pull/2661), but it seems this has not. This causes issues on our internal CI wifi tests.

Just tested the release with this commit cherry-picked and it solves the problem.

@xiaoxiang781216 any problem on that?

**Comment by jerpelea** [comment]
@fdcavalcanti please test https://github.com/apache/nuttx/pull/14319

**Pull request merged**
