### PR TITLE
add Systick irq_attach_thread

### PR DESCRIPTION
**Pull request by yangguangcai01**
## Summary
add config ARMV7M_SYSTICK_IRQ_THREAD，we can use irq_thread attach systick interrupt.
## Impact
armv7m systick.
## Testing
chip:cortexM7

### CODE REVIEW

**Comment by nuttxpr** [comment]
[**\[Experimental Bot, please feedback here\]**](https://github.com/search?q=repo%3Aapache%2Fnuttx+13552&type=issues)



**Concise Review of PR against NuttX Requirements:**

The PR appears **incomplete** based on the provided information.

**Strengths:**

*  Clear summary of the change's purpose (using systick interrupt with `irq_thread`).
*  Identifies the specific architecture impacted (ARMv7M).
*  Mentions testing on Cortex-M7.

**Weaknesses / Missing Information:**

* **Impact Section:**  Lacks detail. 
    *  Is this a new feature or a change to an existing one?
    *  How will this impact users? Will existing code need modification?
    *  Are there build system changes? Documentation updates? 
    *  Consider all the bullet points in the requirements.
* **Testing:** 
    * **Insufficient Detail:** "chip:cortexM7" is not enough. Specify the board and configuration used.
    * **No Logs:**  Provide "before" and "after" logs to demonstrate the change's effect. 

**Recommendation:**

Expand the "Impact" section with specific details for each point. Provide complete testing information, including board/config and relevant log snippets. This will significantly improve the PR's clarity and reviewability.

**Review by anchao — CHANGES_REQUESTED** [review]
squash commits into one

**Review by xiaoxiang781216 — APPROVED** [review]

**Review by anchao — APPROVED** [review]

**Comment by raiden00pl** [comment]
@yangguangcai01 hi, could you explain how this should work? now when you enable this feature it just crash on the first entry to `irq_default_handler()` because `info->handler` is NULL.

**Comment by yangguangcai01** [comment]
> @yangguangcai01 hi, could you explain how this should work? now when you enable this feature it just crash on the first entry to `irq_default_handler()` because `info->handler` is NULL.

Just enable the configuration CONFIG_ARMV7M_SYSTICK_IRQ_THREAD

**Comment by raiden00pl** [comment]
@yangguangcai01  it crash on the first entry to `irq_default_handler()`. You probably missed some changes to `irq_attach_thread.c`, `info->handler == NULL` is not handled properly.

**Comment by yangguangcai01** [comment]
> @yangguangcai01 it crash on the first entry to `irq_default_handler()`. You probably missed some changes to `irq_attach_thread.c`, `info->handler == NULL` is not handled properly.

yes, the parameter of the irq_attach_thread function is not allowed to be empty now，this the fix patch.
https://github.com/apache/nuttx/pull/14195

**Comment by yangguangcai01** [comment]
> @yangguangcai01 it crash on the first entry to `irq_default_handler()`. You probably missed some changes to `irq_attach_thread.c`, `info->handler == NULL` is not handled properly.

yes, the parameter of the irq_attach_thread function is not allowed to be empty now, this fix patchhttps://github.com/apache/nuttx/pull/14196

**Comment by xiaoxiang781216** [comment]
@hujun260 should we fix irq thread/work?

**Pull request merged**
