### PR TITLE
sim/config: enable luamodule

### PR DESCRIPTION
**Pull request by XuNeo**
## Summary
`sim:lua` configuration update:

Enable existing luamodules: csjon, lfs, lsyslog and luv.

## Impact
No.

## Testing
Locally tested.

### CODE REVIEW

**Comment by acassis** [comment]
@XuNeo the CI is failing because some issues on lua-cjson.c

I was looking you personal repository, should be nice to have lugl (Lua + LVGL) support on NuttX ;-)

**Comment by XuNeo** [comment]
> @XuNeo the CI is failing because some issues on lua-cjson.c
I have fixed them in apps repo.

> I was looking you personal repository, should be nice to have lugl (Lua + LVGL) support on NuttX ;-)
That's the goal. `lugl` is still under development with lots of API changes. I'll upload to nuttx once it's ready.

**Comment by xiaoxiang781216** [comment]
> > @XuNeo the CI is failing because some issues on lua-cjson.c
> 
> I have fixed them in apps repo.
> 
> > I was looking you personal repository, should be nice to have lugl (Lua + LVGL) support on NuttX ;-)
> 
> That's the goal. `lugl` is still under development with lots of API changes. I'll upload to nuttx once it's ready.

@XuNeo it's better to add lugl to https://github.com/lvgl/lvgl once it's ready, since:

1. It doesn't depend on NuttX, can be reused in the broader environment
2. lvgl community can improve the binding continually

**Comment by xiaoxiang781216** [comment]
@btashton @gustavonihei Documentation and macOS CI always fail from yesterday, do you have any idea?

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by kisvegabor** [comment]
Thanks for tagging me. 

> That's the goal. lugl is still under development with lots of API changes. I'll upload to nuttx once it's ready.

Amazing news! I also think LVGL might be a better place for the binding. If you agree feel free to a open an issue in our repo.

**Comment by xiaoxiang781216** [comment]
@XuNeo please open an issue in lvgl repo to track your great work.

**Pull request merged**
