### PR TITLE
boards: add nimble defconfig to esp32c3-generic

### PR DESCRIPTION
**Pull request by Laczen**
*Note: Please adhere to [Contributing Guidelines](https://github.com/apache/nuttx/blob/master/CONTRIBUTING.md).*

## Summary

Provide nimble configuration for esp32c3.

## Testing

Verified on wsl2: ubuntu 22.04

### CODE REVIEW

**Comment by nuttxpr** [comment]
[**\[Experimental Bot, please feedback here\]**](https://github.com/search?q=repo%3Aapache%2Fnuttx+13552&type=issues)



No, this PR does not fully meet the NuttX requirements. While it provides a summary of the change, it lacks crucial information.  Here's a breakdown of what's missing:

* **Summary:** While it states *what* is being done (providing nimble config), it doesn't explain *why* (is it a new feature, bug fix, etc.), *how it works* (details of the nimble configuration), or reference related issues.
* **Impact:** This section is completely empty.  It needs to address all the listed points (impact on user, build, hardware, documentation, security, compatibility).  Even if the answer is "NO" for some, it should be explicitly stated.
* **Testing:** While the host OS is mentioned, compiler information is missing.  Crucially, the target information is incomplete. While `esp32c3` is mentioned, the specific board and configuration are not.  And most importantly, there are no "before" and "after" testing logs.  These logs are essential to demonstrate the change's effect and that it works as intended.


To make this PR compliant, you need to add the missing information in each section.  For example:

**Example of a more complete Summary:**

> This change adds nimble configuration for the esp32c3 to enable Bluetooth Low Energy (BLE) functionality.  It adds a new Kconfig file for nimble under the esp32c3 architecture and updates the board configuration to enable it.  This addresses [NuttX Issue #XXX](link-to-issue) which requested BLE support for esp32c3.

**Example of a more complete Impact:**

> * Is new feature added? YES (Adds BLE support via nimble)
> * Impact on user (will user need to adapt to change)? YES (Users will need to enable nimble in their configuration and may need to install additional tools for BLE development)
> * Impact on build (will build process change)? YES (Nimble will be included in the build if enabled)
> * Impact on hardware (will arch(s) / board(s) / driver(s) change)? YES (Affects esp32c3 architecture and boards using it)
> * Impact on documentation (is update required / provided)? YES (Documentation will need to be updated to describe how to configure and use nimble on esp32c3)
> * Impact on security (any sort of implications)? NO
> * Impact on compatibility (backward/forward/interoperability)? NO
> * Anything else to consider? None

**Example of more complete Testing:**

> I confirm that changes are verified on local setup and works as intended:
> * Build Host(s): OS (Ubuntu 22.04 on WSL2), CPU(x86_64), compiler(GCC 11.3.0)
> * Target(s): arch(esp32c3), board:esp32c3-devkit:default

> Testing logs before change:
> ```
>  (Log output showing the lack of BLE functionality, e.g., attempting a BLE scan and failing)
> ```

> Testing logs after change:
> ```
> (Log output showing successful BLE operation, e.g., successful scan results)
> ```


By filling in the missing information like this, your PR will better meet the requirements and be easier for reviewers to assess.

**Review by acassis — APPROVED** [review]

**Comment by acassis** [comment]
@Laczen please take a look at this issue:

```
Error: /github/workspace/sources/apps/wireless/bluetooth/nimble/mynewt-nimble/nimble/host/src/ble_gap.c:6979:1: error: 'ble_gap_event_listener_call' defined but not used [-Werror=unused-function]
 6979 | ble_gap_event_listener_call(struct ble_gap_event *event)
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
```

**Comment by Laczen** [comment]
> @Laczen please take a look at this issue:
> 
> ```
> Error: /github/workspace/sources/apps/wireless/bluetooth/nimble/mynewt-nimble/nimble/host/src/ble_gap.c:6979:1: error: 'ble_gap_event_listener_call' defined but not used [-Werror=unused-function]
>  6979 | ble_gap_event_listener_call(struct ble_gap_event *event)
>       | ^~~~~~~~~~~~~~~~~~~~~~~~~~~
> cc1: all warnings being treated as errors
> ```

This is a bit annoying, the correction of this error (if at all possible) is done in a different repo (nuttx-apps).

**Comment by raiden00pl** [comment]
@Laczen I see that you don't configure any BLE role for nimble. Probably this is why this warning happens, and probably this is why you need `ifup bnep0`. You should add  `CONFIG_NIMBLE_ROLE_PERIPHERAL=y` to configuration.

**Review by anchao — APPROVED** [review]

**Comment by Laczen** [comment]
@acassis, it seems the PR is still failing CI. How can I see the error, I've tried looking at the build failure output, but the failure is unclear for me.

**Comment by acassis** [comment]
@Laczen the issue seems related to other board config:
```
	boards/risc-v/qemu-rv/rv-virt/configs/citest/logs/
```

You can try to update your upstream, rebase your branch against it and send a git push -f

@lupyuen please take a look

**Comment by lupyuen** [comment]
@Laczen The error is caused by something else:
https://github.com/apache/nuttx/actions/runs/12329209626/job/34414942581?pr=15187#step:7:320
```text
Configuration/Tool: rv-virt/citest
test_open_posix/test_openposix_.py::test_ltp_interfaces_pthread_barrierattr_init_2_1 FAILED [ 17%]
```
Which we're still fixing (sorry I'm a bit overloaded sigh):
- https://github.com/apache/nuttx/issues/15170

FYI If we're not sure if our PR is causing the CI Build to fail, we might check nuttx-dashboard.org. This shows that rv-virt/citest is indeed broken, so it's not because of our PR :-)

Screenshot 2024-12-16 at 11 53 08 AM

**Review by lupyuen — APPROVED** [review]

**Comment by Laczen** [comment]
@acassis should I rebase?

**Comment by lupyuen** [comment]
@Laczen There's a problem with CITest, I'm patching it here:
- https://github.com/apache/nuttx/pull/15327

**Comment by Laczen** [comment]
> @Laczen There's a problem with CITest, I'm patching it here:
> 
> * [risc-v/rv-virt: Remove SCANFTEST from rv-virt:citest #15327](https://github.com/apache/nuttx/pull/15327)

Ok, if I need to rebase just let me know.

**Comment by lupyuen** [comment]
Sorry @Laczen could you rebase with master? It should fix the `SCANFTEST` error. Thanks :-)
https://github.com/apache/nuttx/actions/runs/12329209626/job/34848165076?pr=15187#step:7:1267

**Pull request merged**
