### PR TITLE
assert: Replace CONFIG_BOARD_ASSERT_RESET_VALUE with BOARDIOC_SOFTRESETCAUSE_ASSERT

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
## Summary

unify the reset cause value

## Impact

Minor

## Testing

CI

### CODE REVIEW

**Review by davids5 — CHANGES_REQUESTED** [review]
Changing this API is not OK. It breaks systems that pass the value CONFIG_BOARD_ASSERT_RESET_VALUE to mean s something. 0 reboot, 1 boot to ROM... etc

Once before this was changed: the default was moved from 0 to 1. That broke all code using the value.

**Comment by xiaoxiang781216** [comment]
> Changing this API is not OK. It breaks systems that pass the value CONFIG_BOARD_ASSERT_RESET_VALUE to mean s something. 0 reboot, 1 boot to ROM... etc
> 

> Once before this was changed: the default was moved from 0 to 1. That broke all code using the value.

But, the default value is 1 not 0:
https://github.com/apache/nuttx/pull/8940/files#diff-60cc096e3a9b22a769602cbbc3b0f5e7731e72db7b0338da04fcf665ed753b64L4064

**Review by davids5 — CHANGES_REQUESTED** [review]
> > Changing this API is not OK. It breaks systems that pass the value CONFIG_BOARD_ASSERT_RESET_VALUE to mean s something. 0 reboot, 1 boot to ROM... etc
> 
> > Once before this was changed: the default was moved from 0 to 1. That broke all code using the value.
> 
> But, the default value is 1 not 0: https://github.com/apache/nuttx/pull/8940/files#diff-60cc096e3a9b22a769602cbbc3b0f5e7731e72db7b0338da04fcf665ed753b64L4064

Yes that change: setting the default from 0 to 1 broke all the systems that have compressed defconfigs with the default.
So all the defconfigs had to now set  CONFIG_BOARD_ASSERT_RESET_VALUE to 0.

Once you change `board_reset(CONFIG_BOARD_ASSERT_RESET_VALUE)` to `board_reset(BOARDIOC_SOFTRESETCAUSE_ASSERT)`
systems that had CONFIG_BOARD_ASSERT_RESET_VALUE to 0, will not get value of BOARDIOC_SOFTRESETCAUSE_ASSERT
and this breaks the ability for the board to select the value of CONFIG_BOARD_ASSERT_RESET_VALUE and breaks existing bootloaders.

**Comment by xiaoxiang781216** [comment]
Ok, I fix the problem with a different method, @davids5 please review this patch: https://github.com/apache/nuttx/pull/8956.

**Pull request closed without merging**
