### PR TITLE
assert: change the do-while of assert to a conditional expression

### PR DESCRIPTION
**Pull request by Gary-Hobson**
## Summary
assert: change the do-while of assert to a conditional expression

According to the standard definition, assert should return a void expression
https://pubs.opengroup.org/onlinepubs/007904875/basedefs/assert.h.html

This patch involves two changes:

If you define the NDEBUG macro, assert does not use any parameters and directly returns a void expression.
assert should return a void expression and cannot use do-while statements.
If the following code , a compilation error will occur.

## Testing
sim

### CODE REVIEW

**Review by xiaoxiang781216 — APPROVED** [review]

**Review by acassis — APPROVED** [review]

**Comment by masayuki2009** [comment]
I encountered a build error with qemu-armv8a:netnsh_smp_hv

```
CC:  common/arm64_arch_timer.c
aarch64-none-elf-gcc -c -D_LDBL_EQ_DBL -fno-common -Wall -Wstrict-prototypes -Wshadow -Wundef -Werror -Wno-attributes -Wno-unknown-pragmas -Wno-psabi -Os -fno-strict-aliasing -fomit-frame-pointer -ffunction-sections -fdata-sections -g -march=armv8-a -mcpu=cortex-a53 -isystem /mnt/m2ssd/opensource/RTOS/nuttx/nuttx/include -D__NuttX__ -DNDEBUG -D__KERNEL__  -pipe -I /mnt/m2ssd/opensource/RTOS/nuttx/nuttx/arch/arm64/src/chip -I /mnt/m2ssd/opensource/RTOS/nuttx/nuttx/arch/arm64/src/common -I /mnt/m2ssd/opensource/RTOS/nuttx/nuttx/sched    common/arm64_arch_timer.c -o  arm64_arch_timer.o
common/arm64_arch_timer.c: In function 'arm64_tick_cancel':
common/arm64_arch_timer.c:209:37: error: unused variable 'priv' [-Werror=unused-variable]
  209 |   struct arm64_oneshot_lowerhalf_s *priv =
      |                                     ^~~~
cc1: all warnings being treated as errors
```

**Comment by masayuki2009** [comment]
rv-virt:nsh

```
riscv-none-elf-gcc -c -fno-common -Wall -Wstrict-prototypes -Wshadow -Wundef -Wno-attributes -Wno-unknown-pragmas -Wno-psabi -Os -fno-strict-aliasing -fomit-frame-pointer -ffunction-sections -fdata-sections -g -march=rv32imafdc_zicsr_zifencei -mabi=ilp32d -isystem /mnt/m2ssd/opensource/gh_masayuki2009/apache-nuttx-tmp/nuttx/include -D__NuttX__ -DNDEBUG  -pipe -I /mnt/m2ssd/opensource/gh_masayuki2009/apache-nuttx-tmp/nuttx/libs/libc    machine/risc-v/arch_elf.c -o  bin/arch_elf.o
machine/risc-v/arch_elf.c: In function 'up_relocateadd':
machine/risc-v/arch_elf.c:481:20: warning: variable 'insn' set but not used [-Wunused-but-set-variable]
  481 |           uint32_t insn;
      |                    ^~~~
```

**Comment by masayuki2009** [comment]
I think we should revert this PR and fix all warnings before merging this PR.

**Comment by xiaoxiang781216** [comment]
@acassis the ci doesn't pass yet:(.

**Comment by Gary-Hobson** [comment]
@masayuki2009 I submitted a repair patch, which involves two repositories
https://github.com/apache/nuttx-apps/pull/2302
https://github.com/apache/nuttx/pull/11742

**Pull request merged**
