### PR TITLE
elf:fix a ci error

### PR DESCRIPTION
**Pull request by gneworld**
## Summary

Configuration/Tool: teensy-2.0/nsh
In file included from
/github/workspace/sources/nuttx/include/nuttx/coredump.h:35:0,
                 from
/github/workspace/sources/nuttx/sched/misc/coredump.h:28,
                 from ./init/nx_bringup.c:54:
/github/workspace/sources/nuttx/include/nuttx/elf.h:31:22: fatal error: arch/elf.h: No such file or directory

## Impact
non arm arch

## Testing
ci build

### CODE REVIEW

**Review by lupyuen — APPROVED** [review]

**Review by xiaoxiang781216 — APPROVED** [review]

**Review by GUIDINGLI — APPROVED** [review]

**Comment by lupyuen** [comment]
Sorry the build failed in arm_backtrace_unwind.c
```text
Configuration/Tool: nrf52840-dk/ieee802154_mac,CONFIG_ARM_TOOLCHAIN_GNU_EABI
2024-10-15 07:14:03
common/arm_backtrace_unwind.c: In function 'search_index':
##[debug]Dropping file value '/home/runner/work/nuttx/nuttx/common/arm_backtrace_unwind.c'. Path does not exist
Error: common/arm_backtrace_unwind.c:144:23: error: invalid use of undefined type 'struct __EIT_entry'
  144 |   while (start < stop - 1)
```
https://github.com/apache/nuttx/actions/runs/11339989899/job/31537744993?pr=14290

**Comment by GUIDINGLI** [comment]
> Sorry the build failed in arm_backtrace_unwind.c
> 
> ```
> Configuration/Tool: nrf52840-dk/ieee802154_mac,CONFIG_ARM_TOOLCHAIN_GNU_EABI
> 2024-10-15 07:14:03
> common/arm_backtrace_unwind.c: In function 'search_index':
> ##[debug]Dropping file value '/home/runner/work/nuttx/nuttx/common/arm_backtrace_unwind.c'. Path does not exist
> Error: common/arm_backtrace_unwind.c:144:23: error: invalid use of undefined type 'struct __EIT_entry'
>   144 |   while (start < stop - 1)
> ```
> 
> https://github.com/apache/nuttx/actions/runs/11339989899/job/31537744993?pr=14290

Haven't meet error in lcoal:
./tools/configure.sh nrf52840-dk/ieee802154_mac
make

**Comment by GUIDINGLI** [comment]
Got it, use this PR:
https://github.com/apache/nuttx/pull/14290

**Review by lupyuen — APPROVED** [review]

**Review by GUIDINGLI — APPROVED** [review]
Seems Good

**Comment by GUIDINGLI** [comment]
CI back to normal

**Pull request merged**
