### PR TITLE
mm/kasan: Delete the lock when adding regions

### PR DESCRIPTION
**Pull request by 0528Mike**
## Summary
mm/kasan: Delete the lock when adding regions

### CODE REVIEW

**Comment by 0528Mike** [comment]
It is useless because there is almost no possibility of adding regions at the same time.

**Comment by acassis** [comment]
> It is useless because there is almost no possibility of adding regions at the same time.

Right, please include this information and more details in the commit log message. This way "people of the future" will understand why you did it.

**Comment by acassis** [comment]
When you said: "almost no possibility of adding regions at the same time", this "almost" means that there still some remote possibility, how it could happen?

**Comment by anchao** [comment]
Some special board-level implementations will call `mm_addregion()` after co-cpus (`nx_smp_start()`) is started.
e.g:
`nx_smp_start()`->`nx_bringup()`->`board_late_initialize()`->`mm_addregion()`

**Comment by 0528Mike** [comment]
> Some special board-level implementations will call `mm_addregion()` after co-cpus (`nx_smp_start()`) is started. e.g: `nx_smp_start()`->`nx_bringup()`->`board_late_initialize()`->`mm_addregion()`

Okay, this is still possible. That cannot be deleted

**Pull request closed without merging**
