### PR TITLE
armv7-a/gicv2: move IRQ to group1 and group0 as the FIQ

### PR DESCRIPTION
**Pull request by GUIDINGLI**
## Summary

armv7-a/gicv2: move IRQ to group1 and group0 as the FIQ

Purpose: make the the os crash when busyloop with interrupt disable

Follow the arm gicv2 spec, if we want to use the IRQ and FIQ simultaneously when not using the processor Security Externsions. We should:
1. IRQ to Group 1 and FIQ to Group 0;
2. Set CICC_CTLR.FIQEn to 1;

Then in NuttX:
1. implement the arm_decodefiq and directly crash in it;
2. provide interface to change the IRQ to FIQ, e.g. change the watchdog IRQ to FIQ, so the watchdog can trigger even with the interrupt disabled (up_irq_save() called);

## Impact

armv7 a/r armv8a

## Testing

bes board

### CODE REVIEW

**Comment by masayuki2009** [comment]
@GUIDINGLI 
I tried this PR with sabre-6quad:nsh (qemu) but it does not boot.

```
$ /home/ishikawa/opensource/QEMU/qemu-8.2.0/build/qemu-system-arm -semihosting -M sabrelite -m 1024 -smp 4 -kernel nuttx -nographic
```

**Comment by GUIDINGLI** [comment]
Thanks very much, I am working on it

**Comment by GUIDINGLI** [comment]
@masayuki2009 
Updated,
Test with sabre-6quad:nsh (qemu)

**Comment by GUIDINGLI** [comment]
@masayuki2009 
CI pass, please help to review

**Comment by masayuki2009** [comment]
@GUIDINGLI 
I confirmed the latest PR fixes the issue.

**Pull request merged**
