### PR TITLE
cmake(bugfix):Synchronize the compilation differences between CMake and Makefile in nuttx repo

### PR DESCRIPTION
**Pull request by xuxin930**
## Summary
sync CMake missing sources

There are differences between the current CMake base and Makefile. 
This patch synchronizes the differences between modules 
so that the CMake compilation content should be consistent with the Makefile.

## Impact
[arm ach, fs, sched, mm , libc, drivers]

## Testing
all CI build

### CODE REVIEW

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by nuttxpr** [comment]
[**\[Experimental Bot, please feedback here\]**](https://github.com/search?q=repo%3Aapache%2Fnuttx+13552&type=issues)



**Yes, but with minor improvements:**

**Meets Requirements:**

* **Summary:**  Clearly states the "why" (CMake/Makefile discrepancy), "what" (synchronizing modules), and "how" (patch for consistency).
* **Impact:**  Lists affected areas, which is helpful.
* **Testing:**  States "all CI builds" pass, indicating thoroughness.

**Suggested Improvements:**

* **Impact:** 
    * Be more specific. Instead of just listing areas, briefly describe the impact *within* each.  E.g., "**fs:** Adds missing source files for X feature." 
    *  Address ALL impact points. Even if it's "NO", explicitly state it for clarity (especially security, compatibility, etc.).
* **Testing:**
    * While "all CI builds" is good, a *few* specific examples of before/after log snippets would add strong evidence. Choose ones demonstrating the problem being solved.

**Overall:** Good start!  Adding the specifics mentioned above will make this PR review much smoother.

**Comment by xuxin930** [comment]
image
hi @simbit18 It seems that there is a bash command line limitation issue under msys2
Could you help take a look?

**Comment by simbit18** [comment]
Hi @xuxin930 Sure now I try.

**Comment by simbit18** [comment]
I tried this PR locally 

Cmake 
The problem does not occur when building NuttX only with Cmake.


```
[100%] Linking C static library libapps.a
[100%] Built target apps
[100%] Building C object apps/system/nsh/CMakeFiles/apps_nsh.dir/nsh_main.c.obj
[100%] Linking C static library libapps_nsh.a
[100%] Built target apps_nsh
[100%] Building C object apps/system/nsh/CMakeFiles/apps_sh.dir/sh_main.c.obj
[100%] Linking C static library libapps_sh.a
[100%] Built target apps_sh
[100%] Building C object apps/examples/hello/CMakeFiles/apps_hello.dir/hello_main.c.obj
[100%] Linking C static library libapps_hello.a
[100%] Built target apps_hello
[100%] Building C object CMakeFiles/nuttx.dir/empty.c.obj
[100%] Linking C executable nuttx
[100%] Built target nuttx
[100%] Generating nuttx.hex
[100%] Built target nuttx-hex
[100%] Generating nuttx.bin
[100%] Built target nuttx-bin
```

Cmake+Ninja 
The problem occurs when building NuttX with Cmake+Ninja. 

```
/bin/sh: line 1: /home/bit/nuttxnew/tools/gcc-arm-none-eabi/bin/arm-none-eabi-ar: Argument list too long
[813/1026] Building C object mm/CMakeFiles/mm.dir/umm_heap/umm_malloc_size.c.obj
ninja: build stopped: subcommand failed.
```

It is certainly related to the fact that Windows has a limit of 8192 characters for command line arguments.

This does not seem an easy error to solve!!! 

Should we disable CMAKE + Ninja for Msys2 while waiting for a solution?

**Review by anchao — APPROVED** [review]

**Comment by xuxin930** [comment]
> 
> Should we disable CMAKE + Ninja for Msys2 while waiting for a solution?

@simbit18 nice catch!
We split the ar step here, but it seems that it only works for the default generator, not the ninja generator. 
I agree that disable the ninja generator  in the msys2 environment.

https://github.com/apache/nuttx/blob/0647b4999058ba8886c7c7c201ad0c539d54360e/arch/arm/src/cmake/gcc.cmake#L80-L92

**Comment by simbit18** [comment]
@xuxin930  I will be away for a few days so if you decide to disable Cmake + Ninja for Msys2 just remove -N

on build.yml for Nuttx 
https://github.com/apache/nuttx/blob/6ea3dcace44bece9b7a5f91f6080fdbd3030d9f9/.github/workflows/build.yml#L327

and Apps
https://github.com/apache/nuttx-apps/blob/faea166566d1620d5ca4f6b5ea0419b148b042f4/.github/workflows/build.yml#L322

**Comment by xuxin930** [comment]
> 
> and Apps https://github.com/apache/nuttx-apps/blob/faea166566d1620d5ca4f6b5ea0419b148b042f4/.github/workflows/build.yml#L322

@simbit18  sure, thanks for your suggestion.

**Review by xiaoxiang781216 — APPROVED** [review]

**Pull request merged**
