### PR TITLE
PCI Refactoring

### PR DESCRIPTION
**Pull request by btashton**
## Summary
This is a set of changes on top of the PCI branch that take care of some high level refactoring from pcie/pci as well as creating more driver primitives.  This is not based on the jailhouse code so we also avoid having to have that licensed attached to code that likely will continue to grow and change over time.

TODO:
- [x] Make the drive a pci driver instead of PCIe -- We can add PCIe specific functions on top of it.
- [x] Remove Jailhouse dependency
- [ ] Implement removed msi/msix primatives

### CODE REVIEW

**Comment by btashton** [comment]
@sonicyang Here is a draft PR with my changes against the PCI branch.

**Comment by sonicyang** [comment]
I think we can remove the QEMU_MAX_BDF config for now, because we are scanning according to PCI spec.

**Comment by btashton** [comment]
Here is the comments on the Linux mailing list about scanning with Jailhouse 
```

From: Jan Kiszka <jan.kiszka@siemens.com>

Per PCIe r4.0, sec 7.5.1.1.9, multi-function devices are required to
have a function 0.  Therefore, Linux scans for devices at function 0
(devfn 0/8/16/...) and only scans for other functions if function 0
has its Multi-Function Device bit set or ARI or SR-IOV indicate
there are more functions.

The Jailhouse hypervisor may pass individual functions of a
multi-function device to a guest without passing function 0, which
means a Linux guest won't find them.

Change Linux PCI probing so it scans all function numbers when
running as a guest over Jailhouse.

This is technically prohibited by the spec, so it is possible that
PCI devices without the Multi-Function Device bit set may have
unexpected behavior in response to this probe.
```

**Comment by sonicyang** [comment]
Interesting, because I was passing a whole card to the cell.
I will double check my experiment.

**Comment by btashton** [comment]
If you run your test again with the previous brute force search can you send me the bdf that were found. That will answer the question about the hierarchy.  I made progress on the jailhouse setup in QEMU last night, but I'm still learning.

**Comment by btashton** [comment]
@sonicyang I found one issue in the bus scanning code that might have caused it to miss function 0 if the device was multifunction.  Maybe this is why your device did not show up?

I have added a bunch more logic in to support dumping the PCI dev and reading out configuration parameters.  The QEMU pci-testdev is also much more supported now, including both MMIO and PIO BARs with tests run against it.  Still need to do some cleanup and then add in the MSI MSI-X logic.

Here is the dump from my setup
```
qemu-system-x86_64  -cpu host,+pcid,+x2apic,+tsc-deadline,+xsave,+rdrand --enable-kvm -smp 1 -m 2G -cdrom boot.iso --nographic -s -no-reboot -device pci-testdev,membar=0x100000000 -device e1000e
```
Console:
```
qemu_pci_init: Initializing PCI Bus
pci_dev_dump: [00:00.0] 8086:1237
pci_dev_dump: 	type 00 Prog IF 00 Class 06 Subclass 00
pci_dev_dump: [00:01.0] 8086:7000
pci_dev_dump: 	type 80 Prog IF 00 Class 06 Subclass 01
pci_dev_dump: [00:01.1] 8086:7010
pci_dev_dump: 	type 00 Prog IF 80 Class 01 Subclass 01
pci_dev_dump: 	BAR [4] PIO range 0xc160-0xc16f (0x10)
pci_dev_dump: [00:01.3] 8086:7113
pci_dev_dump: 	type 00 Prog IF 00 Class 06 Subclass 80
pci_dev_dump: [00:02.0] 1234:1111
pci_dev_dump: 	type 00 Prog IF 00 Class 03 Subclass 00
pci_dev_dump: 	BAR [0] MEM 32b range 0xfd000000-0xfdffffff (0x1000000)
pci_dev_dump: 	BAR [2] MEM 32b range 0xfebf4000-0xfebf4fff (0x1000)
pci_dev_dump: [00:03.0] 8086:100e
pci_dev_dump: 	type 00 Prog IF 00 Class 02 Subclass 00
pci_dev_dump: 	BAR [0] MEM 32b range 0xfeb80000-0xfeb9ffff (0x20000)
pci_dev_dump: 	BAR [1] PIO range 0xc100-0xc13f (0x40)
pci_dev_dump: [00:04.0] 1b36:0005
pci_dev_dump: 	type 00 Prog IF 00 Class 00 Subclass ff
pci_dev_dump: 	BAR [0] MEM 32b range 0xfebf5000-0xfebf5fff (0x1000)
pci_dev_dump: 	BAR [1] PIO range 0xc000-0xc0ff (0x100)
pci_dev_dump: 	BAR [2] MEM 64b range 0x100000000-0x1ffffffff (0x100000000)
pci_probe_device: Found: Qemu PCI test device
pci_probe_device: [00:04.0] Probing
qemu_pci_test_probe: Enabled bus mastering
qemu_pci_test_probe: Enabled i/o port and memory resources
qemu_pci_test_bar: WRITING Test# 0 0xfebf5000
qemu_pci_test_bar: Running test: mmio-no-eventfd
qemu_pci_test_bar: COUNT: 0000
qemu_pci_test_bar: Width: 1
qemu_pci_test_bar: Data: 00fa
qemu_pci_test_bar: Offset: 0800
qemu_pci_test_bar: Issuing WRITE to 0xfebf5800 fa 1
qemu_pci_test_bar: Issuing WRITE to 0xfebf5800 fa 1
qemu_pci_test_bar: Issuing WRITE to 0xfebf5800 fa 1
qemu_pci_test_bar: Issuing WRITE to 0xfebf5800 fa 1
qemu_pci_test_bar: Issuing WRITE to 0xfebf5800 fa 1
qemu_pci_test_bar: Issuing WRITE to 0xfebf5800 fa 1
qemu_pci_test_bar: Issuing WRITE to 0xfebf5800 fa 1
qemu_pci_test_bar: Issuing WRITE to 0xfebf5800 fa 1
qemu_pci_test_bar: COUNT: 0008
qemu_pci_test_probe: Test Completed BAR [0] TEST [0]
qemu_pci_test_bar: WRITING Test# 1 0xfebf5000
qemu_pci_test_bar: Running test: mmio-wildcard-eventfd
qemu_pci_test_bar: COUNT: 0000
qemu_pci_test_bar: Width: 1
qemu_pci_test_bar: Data: 00ce
qemu_pci_test_bar: Offset: 0801
qemu_pci_test_bar: Issuing WRITE to 0xfebf5801 ce 1
qemu_pci_test_bar: Issuing WRITE to 0xfebf5801 ce 1
qemu_pci_test_bar: Issuing WRITE to 0xfebf5801 ce 1
qemu_pci_test_bar: Issuing WRITE to 0xfebf5801 ce 1
qemu_pci_test_bar: Issuing WRITE to 0xfebf5801 ce 1
qemu_pci_test_bar: Issuing WRITE to 0xfebf5801 ce 1
qemu_pci_test_bar: Issuing WRITE to 0xfebf5801 ce 1
qemu_pci_test_bar: Issuing WRITE to 0xfebf5801 ce 1
qemu_pci_test_bar: COUNT: 0000
qemu_pci_test_probe: Test Completed BAR [0] TEST [1]
qemu_pci_test_bar: WRITING Test# 2 0xfebf5000
qemu_pci_test_bar: Running test: mmio-datamatch-eventfd
qemu_pci_test_bar: COUNT: 0000
qemu_pci_test_bar: Width: 1
qemu_pci_test_bar: Data: 00fa
qemu_pci_test_bar: Offset: 0802
qemu_pci_test_bar: Issuing WRITE to 0xfebf5802 fa 1
qemu_pci_test_bar: Issuing WRITE to 0xfebf5802 fa 1
qemu_pci_test_bar: Issuing WRITE to 0xfebf5802 fa 1
qemu_pci_test_bar: Issuing WRITE to 0xfebf5802 fa 1
qemu_pci_test_bar: Issuing WRITE to 0xfebf5802 fa 1
qemu_pci_test_bar: Issuing WRITE to 0xfebf5802 fa 1
qemu_pci_test_bar: Issuing WRITE to 0xfebf5802 fa 1
qemu_pci_test_bar: Issuing WRITE to 0xfebf5802 fa 1
qemu_pci_test_bar: COUNT: 0008
qemu_pci_test_probe: Test Completed BAR [0] TEST [2]
qemu_pci_test_bar: WRITING Test# 3 0xfebf5000
qemu_pci_test_bar: Running test: 
qemu_pci_test_bar: COUNT: 0000
qemu_pci_test_bar: Width: 0
qemu_pci_test_bar: WRITING Test# 0 0xc000
qemu_pci_test_bar: Running test: portio-no-eventfd
qemu_pci_test_bar: COUNT: 0000
qemu_pci_test_bar: Width: 1
qemu_pci_test_bar: Data: 00fa
qemu_pci_test_bar: Offset: 0083
qemu_pci_test_bar: Issuing WRITE to 0xc083 fa 1
qemu_pci_test_bar: Issuing WRITE to 0xc083 fa 1
qemu_pci_test_bar: Issuing WRITE to 0xc083 fa 1
qemu_pci_test_bar: Issuing WRITE to 0xc083 fa 1
qemu_pci_test_bar: Issuing WRITE to 0xc083 fa 1
qemu_pci_test_bar: Issuing WRITE to 0xc083 fa 1
qemu_pci_test_bar: Issuing WRITE to 0xc083 fa 1
qemu_pci_test_bar: Issuing WRITE to 0xc083 fa 1
qemu_pci_test_bar: COUNT: 0008
qemu_pci_test_probe: Test Completed BAR [1] TEST [0]
qemu_pci_test_bar: WRITING Test# 1 0xc000
qemu_pci_test_bar: Running test: portio-wildcard-eventfd
qemu_pci_test_bar: COUNT: 0000
qemu_pci_test_bar: Width: 1
qemu_pci_test_bar: Data: 00ce
qemu_pci_test_bar: Offset: 0084
qemu_pci_test_bar: Issuing WRITE to 0xc084 ce 1
qemu_pci_test_bar: Issuing WRITE to 0xc084 ce 1
qemu_pci_test_bar: Issuing WRITE to 0xc084 ce 1
qemu_pci_test_bar: Issuing WRITE to 0xc084 ce 1
qemu_pci_test_bar: Issuing WRITE to 0xc084 ce 1
qemu_pci_test_bar: Issuing WRITE to 0xc084 ce 1
qemu_pci_test_bar: Issuing WRITE to 0xc084 ce 1
qemu_pci_test_bar: Issuing WRITE to 0xc084 ce 1
qemu_pci_test_bar: COUNT: 0000
qemu_pci_test_probe: Test Completed BAR [1] TEST [1]
qemu_pci_test_bar: WRITING Test# 2 0xc000
qemu_pci_test_bar: Running test: portio-datamatch-eventfd
qemu_pci_test_bar: COUNT: 0000
qemu_pci_test_bar: Width: 1
qemu_pci_test_bar: Data: 00fa
qemu_pci_test_bar: Offset: 0085
qemu_pci_test_bar: Issuing WRITE to 0xc085 fa 1
qemu_pci_test_bar: Issuing WRITE to 0xc085 fa 1
qemu_pci_test_bar: Issuing WRITE to 0xc085 fa 1
qemu_pci_test_bar: Issuing WRITE to 0xc085 fa 1
qemu_pci_test_bar: Issuing WRITE to 0xc085 fa 1
qemu_pci_test_bar: Issuing WRITE to 0xc085 fa 1
qemu_pci_test_bar: Issuing WRITE to 0xc085 fa 1
qemu_pci_test_bar: Issuing WRITE to 0xc085 fa 1
qemu_pci_test_bar: COUNT: 0000
qemu_pci_test_probe: Test Completed BAR [1] TEST [2]
qemu_pci_test_bar: WRITING Test# 3 0xc000
qemu_pci_test_bar: Running test: 
qemu_pci_test_bar: COUNT: 0000
qemu_pci_test_bar: Width: 0
qemu_pci_test_bar: WRITING Test# 0 0x100000000
qemu_pci_test_bar: Running test: 
qemu_pci_test_bar: COUNT: 17adaf12
pci_dev_dump: [00:05.0] 8086:10d3
pci_dev_dump: 	type 00 Prog IF 00 Class 02 Subclass 00
pci_dev_dump: 	CAP 01
pci_dev_dump: 	CAP 05
pci_dev_dump: 	CAP 10
pci_dev_dump: 	CAP 11
pci_dev_dump: 	BAR [0] MEM 32b range 0xfeba0000-0xfebbffff (0x20000)
pci_dev_dump: 	BAR [1] MEM 32b range 0xfebc0000-0xfebdffff (0x20000)
pci_dev_dump: 	BAR [2] PIO range 0xc140-0xc15f (0x20)
pci_dev_dump: 	BAR [3] MEM 32b range 0xfebf0000-0xfebf3fff (0x4000)
x86_rng_initialize: Initializing RNG
```

**Comment by btashton** [comment]
I also rebased this and the pci branch against the newest changes since there were some conflicts.

**Comment by btashton** [comment]
Added initial support for the "edu" test device which will allow for testing interrupts both INTx and MSI, as well as DMA transfers. I'll try to get that in tomorrow.

https://github.com/qemu/qemu/blob/master/docs/specs/edu.txt

Right now I don't really like how we are handling mapping the BARs.  It would be nice if we had an OS resource manager, something like in freebsd where addressed spaces IRQs can be requested and returned.   In Linux we also get `/proc/ioports` `/proc/iomem` and `/proc/interrupts` where these can be visualized.

https://www.freebsd.org/doc/en_US.ISO8859-1/books/arch-handbook/pci-bus.html

**Comment by sonicyang** [comment]
@btashton I am also not so satisfied.

I also refactored the code in my own repository when porting jailhouse drivers.

I wrote a dummy allocator and let OS do the allocation and manage the bar memory and other type of resources.
You might want to check it out.

I have tried to use the built-in gran allocator, but it is only up to 32 pages. :/

This is currently a board level implementation, but as you said, making an OS level implementation might be a better option, perhaps?

https://github.com/sonicyang/incubator-nuttx 
 (The GPL branch. Yes there are GPL code, so I am not considering doing any PRs.)

**Comment by xiaoxiang781216** [comment]
> @btashton I am also not so satisfied.
> 
> I also refactored the code in my own repository when porting jailhouse drivers.
> 
> I wrote a dummy allocator and let OS do the allocation and manage the bar memory and other type of resources.
> You might want to check it out.
> 
> I have tried to use the built-in gran allocator, but it is only up to 32 pages. :/
> 

I think it's easy to extend gran allocator for more than 32 pages.

> This is currently a board level implementation, but as you said, making an OS level implementation might be a better option, perhaps?
> 
> https://github.com/sonicyang/incubator-nuttx
> (The GPL branch. Yes there are GPL code, so I am not considering doing any PRs.)

**Comment by sonicyang** [comment]
@xiaoxiang781216 
Yeah, my allocator replicated the bitmap management of gran allocator, in a very inefficient way.

**Comment by patacongo** [comment]
> > I have tried to use the built-in gran allocator, but it is only up to 32 pages. :/
> 
> I think it's easy to extend gran allocator for more than 32 pages.

That is not true.  The granule allocator is not limited in the number of pages in any way.  It does not use a single 32-bit word, it uses an array of 32-bit words in the granule allocation table.  I have used it with many hundreds of granules.  The size of `struct gran_s` is determined dynamically  You are probably being misled by the `uint32_t gram[1] `field is in `struct gran_s`.  That is the minimum size, one 32-bit.  The actually allocated size is:

    #define SIZEOF_GRAN_S(n) \
      (sizeof(struct gran_s) + sizeof(uint32_t) * (SIZEOF_GAT(n) - 1))

In mm/mm_gran/mm_granit:

    138   ngranules    = alignedsize >> log2gran;
    139
    140   /* Allocate the information structure with a granule table of the
    141    * correct size.
    142    */
    143
    144   priv = (FAR struct gran_s *)kmm_zalloc(SIZEOF_GRAN_S(ngranules));
    145   if (priv)
    146     {
    150       priv->ngranules = ngranules;

**Comment by xiaoxiang781216** [comment]
Yes, gran allocator can manage the block much larger than 32, but each allocation can't extend 32:
```
/****************************************************************************
 * Name: gran_alloc
 *
 * Description:
 *   Allocate memory from the granule heap.
 *
 *   NOTE: The current implementation also restricts the maximum allocation
 *   size to 32 granules.  That restriction could be eliminated with some
 *   additional coding effort.
 *
 * Input Parameters:
 *   handle - The handle previously returned by gran_initialize
 *   size   - The size of the memory region to allocate.
 *
 * Returned Value:
 *   On success, a non-NULL pointer to the allocated memory is returned;
 *   NULL is returned on failure.
 *
 ****************************************************************************/

FAR void *gran_alloc(GRAN_HANDLE handle, size_t size)
{
  FAR struct gran_s *priv = (FAR struct gran_s *)handle;
  unsigned int ngranules;
  size_t       tmpmask;
  uintptr_t    alloc;
  uint32_t     curr;
  uint32_t     next;
  uint32_t     mask;
  int          granidx;
  int          gatidx;
  int          bitidx;
  int          shift;
  int          ret;

  DEBUGASSERT(priv != NULL && size <= 32 * (1 << priv->log2gran));
```

**Comment by patacongo** [comment]
> Yes, gran allocator can manage the block much larger than 32, but each allocation can't extend 32:

That is a limitation in the implementation of gran_alloc() not in the underlying data structures.  That implementation could be enhanced.

**Comment by sonicyang** [comment]
@patacongo 
Yeah you are right. I think my words are at accurate enough.
I don't know this is an intended limitation or pending of implementation type.
If it's the later, I can try to extend it and do a PR.

**Comment by sonicyang** [comment]
One of the concern is that, for example, I am using a PCI-e serial card as the console.
To have it initialized, I might need the allocator ready in the very early stage of the booting process.
Of course I can do static allocation by Kconfig, but I really don't like that semantics either.

**Comment by patacongo** [comment]
> I don't know whether this is an intended limitation or pending of implementation type.
> If it's the later, I can try to extend it and do a PR.

No, it is not necessary to restrict the number of granules to 32.  That just made the design easier.  In the header to the gran_alloc function it says (line 45):  "NOTE: The current implementation also restricts the maximum allocation  size to 32 granules.  That restriction could be eliminated with some additional coding effort."

I would appreciate that extension if you have a change to do it.

The primary use for the gran allocator is in the KERNEL build mode:  It is used to manage the physical page table.  In that case, the page size is 4Kb; a limit of 32 contiguous granules limits the amount of contiguous memory to 128Kb.

That is not a serious problem for the KERNEL build, however, since most pages are allocated one at a time and do not have to be physically contiguous; they are mapped to virtually contiguous memory using the MMU.

However, that 128Kb limit has an effect the maximum size of DMA buffers.  DMA buffers must be physically contiguous so that limits the size of allocated DMA buffers to 128Kb which is probably not a problem either.

**Comment by patacongo** [comment]
The simplest extension would be to change the uint32_t to a uint64_t.  However, I would prefer they we do NOT make the change that way; there are some low-end MCUs that do not support uint16_t.  A better, more portable solution would involve an array of uint32_t's and some support functions to manage arrays of uint32_t's vs. a single uint32_t value.

**Comment by patacongo** [comment]
> One of the concern is that, for example, I am using a PCI-e serial card as the console.
> To have it initialized, I might need the allocator ready in the very early stage of the booting process.
> Of course I can do static allocation by Kconfig, but I really don't like that semantics either.

You have to have the semaphore functionality initialized prior to using gran allocator.  That happens after nx_start() is called, but before up_initialize() is called.  I think you could do this at the beginning of the up_initialize function before any hardware drivers have been initialized.

**Comment by patacongo** [comment]
> You have to have the semaphore functionality initialized prior to using gran allocator.

Thinking more... even though the semaphore facility is not initialized, I think that you could certainly call gran_init() (but possibly not gran_alloc()) very early in initialization, perhaps even in __start().  gran_init(0 does call nxsem_init(), but that should not be a problem.

If you intend to use gran_alloc() from interrupt handlers, then it will call enter/leave_critical_section().  In the SMP case, I don't think that would work that early in initialization.  I am not sure.

In the non-interrupt case, it would use sem_wait() and sem_post().   Those should be innocuous while we are running single threaded because there is no competition for the seamphore.  However, I think they will also call enter/leave_critical_section which could, again, be a problem in SMP mode.

I think we could extend gran_init() to accept a list of reserved (pre-allocated) granules.  gran_init() would just call gram_mark_allocated() for each reserved memory region in the list.  If NULL were an allowed option for this list argument, then this would be backward compatible with existing use of gran_init().

**Comment by patacongo** [comment]
>  A better, more portable solution would involve an array of uint32_t's and some support functions to manage arrays of uint32_t's vs. a single uint32_t value.

No.. that is not a good idea.  You really need only two masks:  The one at the beginning of the run of bits and one at the end.  Any between those are implicitly 0xffffffff.  This kind of thing is done a lot in the graphics/ code.   For example in /graphics/nxglib/fb/nxglib_fillrectangle.c you can see how the leadmask and the tailmask are use to maske an array of bits into the framebuffer.  That is very fast and very efficient.  The same kind of like could be use to find a run of nbits in the GAT too.

**Comment by btashton** [comment]
I think there might be a little misunderstanding of what I was originally talking about. I was talking about OS resource management rather than memory allocation.

A slightly dated resource on what I am talking about. 
https://www.oreilly.com/library/view/linux-device-drivers/0596000081/ch02s05.html

**Comment by sonicyang** [comment]
Let me try to capture the idea again.
1. It is not only about management of memory, but any kind of resource.
2. It provides a way to avoid drivers obtaining conflicting resources and understand which driver gets hold on a region of physical resources.
3. For example, with it, driver might not be able to map the same resource twice. (Which any of the current implementation can)

**Comment by btashton** [comment]
Since PCI is really the only interface that we support that has these requirements maybe it is fine to just leave it as is. It is nice being able to see the memory mappings via `/proc/iomem`.  Also supporting any kind of hot-swaping seems unlikely to be a requirement so I dont think we would be doing any kind of re-mapping.

**Comment by btashton** [comment]
Interrupt and DMA tests are implemented and pass for the QEMU "edu" device. MSI is the last functional test to get working.
```
qemu_edu_probe: Enabled bus mastering
qemu_edu_probe: Enabled memory resources
qemu_edu_probe: Device Initialized
qemu_edu_test_poll: Identification: 0x010000edu
qemu_edu_test_poll: Live Check: Wrote: 0xdeadbeef Read: 0x21524110 Error Bits 0x00000000
qemu_edu_test_poll: TEST PASS
qemu_edu_test_poll: Waiting to compute factorial...
qemu_edu_test_poll: Computed factorial of 10 as 3628800
qemu_edu_test_poll: TEST PASS
qemu_edu_probe: Attaching IRQ 42 to 0x10091f2b8
qemu_edu_test_intx: Identification: 0x010000edu
qemu_edu_test_intx: Triggering interrupt with value 0xdeadbeef
qemu_edu_interrupt: Received value: 0xdeadbeef
qemu_edu_test_intx: TEST PASS
qemu_edu_test_intx: Computing factorial of 5
qemu_edu_interrupt: Computed factorial: 120
qemu_edu_test_intx: TEST PASS
qemu_edu_interrupt: Received value: 0x00000005
qemu_edu_test_intx: TEST PASS
qemu_edu_test_dma: Identification: 0x010000edu
qemu_edu_test_dma: Test block checksum 0xb4908b8a
EDU: clamping DMA 0x0000000101170ed0 to 0x0000000001170ed0!
qemu_edu_interrupt: DMA transfer complete
qemu_edu_test_dma: DMA transfer to device complete.
EDU: clamping DMA 0x0000000101170ed0 to 0x0000000001170ed0!
qemu_edu_interrupt: DMA transfer complete
qemu_edu_test_dma: DMA transfer from device complete.
qemu_edu_test_dma: Received block checksum 0xb4908b8a
qemu_edu_test_dma: TEST PASS
```

**Comment by btashton** [comment]
There is an additional issue that we will likely need to resolve.  Right now one one handler can be attached to a given IRQ.  In reality multiple devices are frequently attached to the same interrupt line.

In Linux they handle this by instead of having single function defined in the IRQ struct, there is a linked list of handlers that is traversed.
https://www.oreilly.com/library/view/understanding-the-linux/0596005652/ch04s06.html#understandlk-CHP-4-TABLE-6

For now I am going to move forward with the requirement of a single device per IRQ, but this will likely have to be addressed at some point.

**Comment by xiaoxiang781216** [comment]
> There is an additional issue that we will likely need to resolve. Right now one one handler can be attached to a given IRQ. In reality multiple devices are frequently attached to the same interrupt line.
> 
> In Linux they handle this by instead of having single function defined in the IRQ struct, there is a linked list of handlers that is traversed.
> https://www.oreilly.com/library/view/understanding-the-linux/0596005652/ch04s06.html#understandlk-CHP-4-TABLE-6
> 
> For now I am going to move forward with the requirement of a single device per IRQ, but this will likely have to be addressed at some point.

The interrupt chain already support long time ago:
```
commit d38be46655846948d3c7f6bb149fb757bf0498ea
Author: zhuguangqing <zhuguangqing@pinecone.net>
Date:   Fri Aug 24 15:10:23 2018 -0600

    sched/irq:  Add support interrupt chains in NuttX.  IRQ chain is very useful in these cases:  (1) Multiple hardware connect to the same request line(e.g. PCI), (2) Need multiple driver to support one hardware block (like Linux MFD)
```

**Comment by btashton** [comment]
Thanks! I guess I did not see this when I looked over it the first time.   It looks like the `irq_foreach` function which is used by `/proc/irqs` is not aware of this.  Might be worth expanding it to be able to see the real handlers with there args and not just the dispatcher.

**Comment by xiaoxiang781216** [comment]
Yes, it's good to support the dump irq chain in proc/irqs

**Comment by xiaoxiang781216** [comment]
should we close this patch? @raiden00pl .

**Comment by patacongo** [comment]
Would we also remove the PCI branch? https://github.com/apache/nuttx/tree/pci

**Comment by raiden00pl** [comment]
> should we close this patch? @raiden00pl .

Yes, the changes from here are squashed and included in https://github.com/apache/nuttx/pull/11583
I'll deal with `Implement removed msi/msix primatives` task later.

> Would we also remove the PCI branch? https://github.com/apache/nuttx/tree/pci

We can remove this branch. 

> A lot of this work was done by @btashton

@btashton work is squashed here https://github.com/apache/nuttx/pull/11583/commits/d14e86e23691999c369ed758deffa8067abd9370 and https://github.com/apache/nuttx/pull/11583/commits/f89da2076b190ef0c1f63ee85ae673894962bfaf
@sonicyang work is squashed here https://github.com/apache/nuttx/pull/11583/commits/954abf3b7ee780380e850aeec4d01610b868517a

There were a lot of conflicts to resolve, so preserving the full history of the committees seems like waste of time.

**Comment by xiaoxiang781216** [comment]
OK, let's close it.

**Pull request closed without merging**
