### PR TITLE
{BP-12553} sched/tcb: fix 12320 regression

### PR DESCRIPTION
**Pull request by jerpelea**
## Summary
This patch attempts to fix regressions reported for pull# 12320.

## Impact
RELEASE

## Testing
NONE

### CODE REVIEW

**Review by xiaoxiang781216 — APPROVED** [review]

**Review by anchao — APPROVED** [review]

**Comment by jerpelea** [comment]
@xiaoxiang781216 
FAILED: nuttx 
: && /tools/ccache/bin/cc  -T nuttx.ld CMakeFiles/nuttx.dir/arch/sim/src/sim/posix/sim_hostirq.c.o CMakeFiles/nuttx.dir/arch/sim/src/sim/posix/sim_hostmemory.c.o CMakeFiles/nuttx.dir/arch/sim/src/sim/posix/sim_hostmisc.c.o CMakeFiles/nuttx.dir/arch/sim/src/sim/posix/sim_hosttime.c.o CMakeFiles/nuttx.dir/arch/sim/src/sim/posix/sim_hostuart.c.o CMakeFiles/nuttx.dir/arch/sim/src/sim/posix/sim_tapdev.c.o CMakeFiles/nuttx.dir/arch/sim/src/sim/posix/sim_rawgadget.c.o CMakeFiles/nuttx.dir/arch/sim/src/sim/posix/sim_hostfs.c.o CMakeFiles/nuttx.dir/empty.c.o -o nuttx  nuttx.rel  -lpthread  -lrt  -lm && :
/usr/bin/ld: nuttx.rel: in function `uv_key_create':
/github/workspace/sources/apps/system/libuv/libuv/src/unix/thread.c:846: undefined reference to `NXpthread_key_create'
/usr/bin/ld: nuttx.rel: in function `uv_key_get':
/github/workspace/sources/apps/system/libuv/libuv/src/unix/thread.c:857: undefined reference to `NXpthread_getspecific'
/usr/bin/ld: nuttx.rel: in function `uv_key_set':
/github/workspace/sources/apps/system/libuv/libuv/src/unix/thread.c:862: undefined reference to `NXpthread_setspecific'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

**Comment by xiaoxiang781216** [comment]
> @xiaoxiang781216 FAILED: nuttx : && /tools/ccache/bin/cc -T nuttx.ld CMakeFiles/nuttx.dir/arch/sim/src/sim/posix/sim_hostirq.c.o CMakeFiles/nuttx.dir/arch/sim/src/sim/posix/sim_hostmemory.c.o CMakeFiles/nuttx.dir/arch/sim/src/sim/posix/sim_hostmisc.c.o CMakeFiles/nuttx.dir/arch/sim/src/sim/posix/sim_hosttime.c.o CMakeFiles/nuttx.dir/arch/sim/src/sim/posix/sim_hostuart.c.o CMakeFiles/nuttx.dir/arch/sim/src/sim/posix/sim_tapdev.c.o CMakeFiles/nuttx.dir/arch/sim/src/sim/posix/sim_rawgadget.c.o CMakeFiles/nuttx.dir/arch/sim/src/sim/posix/sim_hostfs.c.o CMakeFiles/nuttx.dir/empty.c.o -o nuttx nuttx.rel -lpthread -lrt -lm && : /usr/bin/ld: nuttx.rel: in function `uv_key_create': /github/workspace/sources/apps/system/libuv/libuv/src/unix/thread.c:846: undefined reference to `NXpthread_key_create' /usr/bin/ld: nuttx.rel: in function `uv_key_get': /github/workspace/sources/apps/system/libuv/libuv/src/unix/thread.c:857: undefined reference to `NXpthread_getspecific' /usr/bin/ld: nuttx.rel: in function `uv_key_set': /github/workspace/sources/apps/system/libuv/libuv/src/unix/thread.c:862: undefined reference to `NXpthread_setspecific' collect2: error: ld returned 1 exit status ninja: build stopped: subcommand failed.

@jerpelea do you cherry-pick https://github.com/apache/nuttx/pull/12592 to 12.6?

**Comment by jerpelea** [comment]
see https://github.com/apache/nuttx/pull/12731

**Comment by jerpelea** [comment]
@xiaoxiang781216 
 /usr/bin/ld: nuttx.rel: in function `uv_key_create':
/github/workspace/sources/apps/system/libuv/libuv/src/unix/thread.c:846: undefined reference to `NXpthread_key_create'
/usr/bin/ld: nuttx.rel: in function `uv_key_get':
/github/workspace/sources/apps/system/libuv/libuv/src/unix/thread.c:857: undefined reference to `NXpthread_getspecific'
/usr/bin/ld: nuttx.rel: in function `uv_key_set':
/github/workspace/sources/apps/system/libuv/libuv/src/unix/thread.c:862: undefined reference to `NXpthread_setspecific'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

**Comment by xiaoxiang781216** [comment]
do you rebase this patch @jerpelea ?

**Review by acassis — APPROVED** [review]

**Comment by jerpelea** [comment]
@acassis @xiaoxiang781216 please merge

**Pull request merged**
