### PR TITLE
fix new warning reported by gcc 13

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
## Summary

- stm32f4discovery/cxxtest: Fix gcc13.2 compiler error
- lpc43xx/usb: Fix gcc13.2 compiler error 
- arch/arm: Disable -Warray-bound for dm320 and lpc31xx 
- modem/alt1250: Fix 'inst' may be used uninitialized
- am335x_lcdc: Fix error: array subscript 0 is outside array bounds 
- arm/sama5: Fix error: array subscript 0 is outside array bounds

## Impact

fix new warning reported by gcc 13

## Testing

ci

### CODE REVIEW

**Comment by raiden00pl** [comment]
@xiaoxiang781216 looks like more things are broken

**Comment by xiaoxiang781216** [comment]
> @xiaoxiang781216 looks like more things are broken

yes, look like the compiler isn't smart enough to handle the complex case correctly.

**Comment by xiaoxiang781216** [comment]
@raiden00pl the good news is that the new compiler warning finds many real problems.

**Comment by raiden00pl** [comment]
@xiaoxiang781216 that's interesting how many new bugs were found :) 
Could you update the PR title as it now contains more commits ?

**Review by anchao — APPROVED** [review]

**Pull request merged**
