### PR TITLE
Revert "tools: Fix CONFIG_BASE_DEFCONFIG generation"

### PR DESCRIPTION
**Pull request by pkarashchenko**
Reverts apache/nuttx#9572 to fix regression described in https://github.com/apache/nuttx/issues/9670

### CODE REVIEW

**Comment by acassis** [comment]
@pkarashchenko maybe instead of reverting it, we could find a solution that works on Linux, BSDs, MacOS and Windows. Without this commit everytime we modify something on menuconfig and save it a new "-dirty" will be added to the name.
So it end up "board:profilename-dirty-dirty-dirty..."

**Comment by pkarashchenko** [comment]
@acassis yes, the goal is to have a universal solution, but I'm blocked on working with master from MAC because of this issue, so I created a revert. I'm fine to wait a few days if someone can provide a universal solution, but I think the correct strategy is:
1. Revert to working state
2. Provide universal solution

**Comment by acassis** [comment]
Ok, agree!

**Comment by lucasssvaz** [comment]
Fixed in #9754

**Pull request merged**
