### PR TITLE
Fix #13873

### LINKED ISSUE #13873: [BUG] Regression when building with C++ toolchain enabled - broken locale
### Description / Steps to reproduce the issue

Since PR #13755, compilation is broken with arm-gcc at least (but probably all version) because public locale were moved to a .c file (which have no sense since it is a public API used by the GCC libstdc++ and llvm libxx).

### On which OS does this issue occur?

[OS: Linux]

### What is the version of your OS?

Debian testing

### NuttX Version

master

### Issue Architecture

[Arch: all]

### Issue Area

[Area: OS Components]

### Verification

- [X] I have verified before submitting the report.

### PR DESCRIPTION
**Pull request by leducp**
## Summary
https://github.com/apache/nuttx/pull/13755 break C++ build with GCC libstdc++. This PR re-enable the macro while takin care of MSVC build.

## Impact
Fix #13873 - build on G++ while keeping MSVC happy.

## Testing
Only with GCC, I do not have tools to test on MSVC.

### CODE REVIEW

**Comment by leducp** [comment]
ping @xuxin930 Can you test this PR with your MSVC setup to ensure no regression on your side?

**Comment by xiaoxiang781216** [comment]
> > @leducp could you switch one defconfig to link toolchain's libcxx?
> 
> Yes I am planning to do so, but it will not be sufficient: we need a user app that use a few tools from the standard C++ library to catch theses kind of errors.

it's enough to enable apps/testing/cxxtest/

> I can add something but I do not know how to tell the CI to use it. Any clue?

it simple to add/modify one defconfig under boards/, ci will build your defconfig automatically.

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by leducp** [comment]
> > > @leducp could you switch one defconfig to link toolchain's libcxx?
> > 
> > 
> > Yes I am planning to do so, but it will not be sufficient: we need a user app that use a few tools from the standard C++ library to catch theses kind of errors.
> 
> it's enough to enable apps/testing/cxxtest/
> 
> > I can add something but I do not know how to tell the CI to use it. Any clue?
> 
> it simple to add/modify one defconfig under boards/, ci will build your defconfig automatically.

I enabled the cxxtest app and the C++ toolchain with all options (RTTI, exceptions, etc) on the xmc4800-relax. Let me know if this is OK

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by xiaoxiang781216** [comment]
looks fine.

**Review by jerpelea — COMMENTED** [review]
commit merged without proper title or commit message!

**Pull request merged**
