### PR TITLE
Add defconfigs for testing the RTP Tools on Simulator and ESP32-LyraT board and relevant documentation about it

### PR DESCRIPTION
**Pull request by tmedicci**
## Summary

Add `defconfig`s for testing the RTP Tools on Simulator and ESP32-LyraT board. Also, add relevant documentation about it.

## Impact

Add usage examples of https://github.com/apache/nuttx-apps/pull/1651

## Testing

`sim:rtptools` and `esp32-lyrat:rtptools` using the instructions documented in this PR's documentation.

### CODE REVIEW

**Review by xiaoxiang781216 — APPROVED** [review]

**Review by jerpelea — APPROVED** [review]

**Comment by jerpelea** [comment]
@tmedicci please add commit message explaining the change

**Comment by tmedicci** [comment]
> @tmedicci please add commit message explaining the change

Hi @jerpelea , I didn't get what message should be updated. I updated the PR title (sorry, I forgot it). Besides it, do you think any commit needs to be improved?

**Comment by tmedicci** [comment]
I converted it to Draft to treat the failing CI.

**Comment by jerpelea** [comment]
> > @tmedicci please add commit message explaining the change
> 
> Hi @jerpelea , I didn't get what message should be updated. I updated the PR title (sorry, I forgot it). Besides it, do you think any commit needs to be improved?

usually each commit has a message describing the change / things it fixes or enhancements. (including logs where applicable)
The PR message is not displayed when someone uses git log to see the patches.

**Comment by tmedicci** [comment]
> > > @tmedicci please add commit message explaining the change
> > 
> > 
> > Hi @jerpelea , I didn't get what message should be updated. I updated the PR title (sorry, I forgot it). Besides it, do you think any commit needs to be improved?
> 
> usually each commit has a message describing the change / things it fixes or enhancements. (including logs where applicable) The PR message is not displayed when someone uses git log to see the patches.

Usually, I use the following pattern for commits: on 1st line, a general description, 2nd line (empty), 3rd (and others) a message describing the commit in detail.

However, in this PR (and others), the 1st line describes the commits sufficiently, I think:
```
2023-05-01 21:10 -0300 Tiago Medicci Serrano         o [feature/add_rtptools] documentation: add references to RTP Tools' defconfigs
2023-03-08 22:15 -0300 Tiago Medicci Serrano         o boards/esp32-lyrat/configs: add defconfig for RTP Tools
2023-02-24 12:04 -0300 Tiago Medicci Serrano         o boards/sim/configs: add defconfig for RTP Tools
```

I couldn't think of any additional information that would fit the "detail" section of the message. I think it'd be just verbosity and repetition. Do you have any thoughts about it?

**Comment by jerpelea** [comment]
I agree that those commit make it quite hard for a message but I think that you can express what are "RTP Tools" good for and why you add the defconfig for them

**Comment by tmedicci** [comment]
> I agree that those commit make it quite hard for a message
> 
> just an idea: you can express what are "RTP Tools" good for and why you add the defconfig for them

It's done ;)

Let's check if CI is fixed...

**Pull request merged**
