### PR TITLE
arch/arm64: rename register names to align with arm32

### PR DESCRIPTION
**Pull request by lipengfei28**
## Summary
1.arch/arm64: rename register names to align with arm32

### CODE REVIEW

**Comment by nuttxpr** [comment]
[**\[Experimental Bot, please feedback here\]**](https://github.com/search?q=repo%3Aapache%2Fnuttx+13552&type=issues)



This PR summary is insufficient. Here's a breakdown of what's missing and how to improve it:

**Summary Issues:**

* **Missing "Why":**  The summary states WHAT is being changed ("rename register names..."), but not WHY.  Is this for consistency? To fix a bug? To support a new feature?
* **Missing Scope:** What "functional part" is affected? Is it just assembly code? Specific drivers? This helps reviewers understand the potential impact area.
* **Missing "How":**  "Align with arm32" is vague. Provide specifics:
    * Are registers being renamed *to* the arm32 names, or is it a different scheme?
    * Are there naming conventions being followed?

**Impact Issues:**

* **Incomplete Sections:** Most sections are empty. You MUST address each point:
    * **New/Changed Features:**  Even if the answer is "NO", state it explicitly.
    * **User Impact:**  Will users see any difference? Likely not if it's internal register naming, but clarify this.
    * **Build Impact:** Will build systems or configurations need changes?
    * **Hardware Impact:**  Will this affect any existing ARM64 targets?
    * **Documentation:** If register names appear in docs, those need updating.
    * **Security/Compatibility:** While unlikely to be impacted here, you must still analyze and state "NO" if applicable.

**Testing Issues:**

* **Missing Details:**
    * **Build Host:** Be specific about your OS, compiler version (e.g., GCC 12.2).
    * **Targets:**  List ALL tested configurations:
        * If using simulators, which ones? QEMU versions matter.
        * For real hardware, provide the board name AND the NuttX configuration used (e.g., `board-name:nsh`).
* **Missing Logs:** Placeholder comments aren't helpful.  Provide ACTUAL logs showing the relevant behavior before and after the change.

**How to Improve:**

1. **Expand the Summary:**  Provide the missing WHY, SCOPE, and HOW details.
2. **Complete the Impact Assessment:**  Address EACH point, even if it's to say "NO impact". Be thorough.
3. **Provide Real Testing Data:** Include build logs, console output, or anything demonstrating the change's effect (or lack thereof).

**Example (Not Complete, but Illustrative):**

```markdown
## Summary

This change renames ARM64 registers within the assembly code of the `arch/arm64/src/xyz` module to align with the naming conventions used by the ARM32 architecture. This is done for improved code readability and maintainability, as developers familiar with ARM32 will find the ARM64 code more intuitive.

The renaming follows the ARM Architectural Reference Manual for ARMv8-A, ensuring consistency with official documentation.

## Impact

* Is new feature added? NO
* Is existing feature changed? NO
* ... (Address ALL impact points)

## Testing

I confirm that changes are verified on the following setup:

* Build Host: Ubuntu 22.04, GCC 12.1
* Targets:
    * QEMU (version X.Y.Z):  `qemu-system-aarch64 -M ...`
    * Raspberry Pi 4 (board config: `rpi-4:nsh`)

Testing logs before change:

```
(Actual log output showing relevant register names)
```

Testing logs after change:
```
(Actual log output showing the renamed registers)
```
```

**Comment by masayuki2009** [comment]
@lipengfei28 @xiaoxiang781216 
I noticed that qemu-armv8a:netnsh_smp causes the following error after merging this PR.

```
/home/ishikawa/opensource/QEMU/qemu-9.0.0/build/qemu-system-aarch64 -cpu cortex-a53 -smp 4 -nographic -M virt,virtualization=on,gic-version=3 -kernel ./nuttx
- Ready to Boot Primary CPU
- Boot from EL2
- Boot from EL1
- Boot to C runtime for OS Initialize
- Ready to Boot Second CPU
- Boot from EL2
- Boot from EL1
- Boot to C runtime for OS Initialize
[CPU1] ERROR: Failed to mount procfs at /proc: -12
[CPU1] dump_assert_info: Current Version: NuttX  12.0.0 f68d594420 Oct 11 2024 11:43:04 arm64
[CPU1] dump_assert_info: Assertion failed : at file: nsh_consolemain.c:67 task(CPU1): nsh_main process: nsh_main 0x40294748
[CPU1] up_dump_register: stack = 0x403d3550
[CPU1] up_dump_register: x0:   0x403d3550          x1:   0x2
[CPU1] up_dump_register: x2:   0x0                 x3:   0x403e7870
[CPU1] up_dump_register: x4:   0x403d3000          x5:   0x1
[CPU1] up_dump_register: x6:   0x0                 x7:   0x1
[CPU1] up_dump_register: x8:   0x403e3418          x9:   0x0
[CPU1] up_dump_register: x10:  0x101010101010101   x11:  0x20
[CPU1] up_dump_register: x12:  0x101010101010101   x13:  0x0
[CPU1] up_dump_register: x14:  0x0                 x15:  0x28
[CPU1] up_dump_register: x16:  0x0                 x17:  0x1
[CPU1] up_dump_register: x18:  0x0                 x19:  0x0
[CPU1] up_dump_register: x20:  0x403d3210          x21:  0x403e7870
[CPU1] up_dump_register: x22:  0x403d2000          x23:  0x0
[CPU1] up_dump_register: x24:  0x403bbbcb          x25:  0x340
[CPU1] up_dump_register: x26:  0x0                 x27:  0x6
[CPU1] up_dump_register: x28:  0x43                x29:  0x403ebd20
[CPU1] up_dump_register: x30:  0x402887c8        
[CPU1] up_dump_register: 
[CPU1] up_dump_register: STATUS Registers:
[CPU1] up_dump_register: SPSR:      0x5               
[CPU1] up_dump_register: ELR:       0x4028c94c        
[CPU1] up_dump_register: SP_EL0:    0x0               
[CPU1] up_dump_register: SP_ELX:    0x403ebd10        
[CPU1] up_dump_register: EXE_DEPTH: 0x0               

```

**Comment by lipengfei28** [comment]
> @lipengfei28 @xiaoxiang781216 I noticed that qemu-armv8a:netnsh_smp causes the following error after merging this PR.
> 
> ```
> /home/ishikawa/opensource/QEMU/qemu-9.0.0/build/qemu-system-aarch64 -cpu cortex-a53 -smp 4 -nographic -M virt,virtualization=on,gic-version=3 -kernel ./nuttx
> - Ready to Boot Primary CPU
> - Boot from EL2
> - Boot from EL1
> - Boot to C runtime for OS Initialize
> - Ready to Boot Second CPU
> - Boot from EL2
> - Boot from EL1
> - Boot to C runtime for OS Initialize
> [CPU1] ERROR: Failed to mount procfs at /proc: -12
> [CPU1] dump_assert_info: Current Version: NuttX  12.0.0 f68d594420 Oct 11 2024 11:43:04 arm64
> [CPU1] dump_assert_info: Assertion failed : at file: nsh_consolemain.c:67 task(CPU1): nsh_main process: nsh_main 0x40294748
> [CPU1] up_dump_register: stack = 0x403d3550
> [CPU1] up_dump_register: x0:   0x403d3550          x1:   0x2
> [CPU1] up_dump_register: x2:   0x0                 x3:   0x403e7870
> [CPU1] up_dump_register: x4:   0x403d3000          x5:   0x1
> [CPU1] up_dump_register: x6:   0x0                 x7:   0x1
> [CPU1] up_dump_register: x8:   0x403e3418          x9:   0x0
> [CPU1] up_dump_register: x10:  0x101010101010101   x11:  0x20
> [CPU1] up_dump_register: x12:  0x101010101010101   x13:  0x0
> [CPU1] up_dump_register: x14:  0x0                 x15:  0x28
> [CPU1] up_dump_register: x16:  0x0                 x17:  0x1
> [CPU1] up_dump_register: x18:  0x0                 x19:  0x0
> [CPU1] up_dump_register: x20:  0x403d3210          x21:  0x403e7870
> [CPU1] up_dump_register: x22:  0x403d2000          x23:  0x0
> [CPU1] up_dump_register: x24:  0x403bbbcb          x25:  0x340
> [CPU1] up_dump_register: x26:  0x0                 x27:  0x6
> [CPU1] up_dump_register: x28:  0x43                x29:  0x403ebd20
> [CPU1] up_dump_register: x30:  0x402887c8        
> [CPU1] up_dump_register: 
> [CPU1] up_dump_register: STATUS Registers:
> [CPU1] up_dump_register: SPSR:      0x5               
> [CPU1] up_dump_register: ELR:       0x4028c94c        
> [CPU1] up_dump_register: SP_EL0:    0x0               
> [CPU1] up_dump_register: SP_ELX:    0x403ebd10        
> [CPU1] up_dump_register: EXE_DEPTH: 0x0               
> ```

Maybe it’s not caused by this PR
image
image
image

**Comment by masayuki2009** [comment]
> I noticed that qemu-armv8a:netnsh_smp causes the following error after merging this PR.

@lipengfei28 
Please try qemu-armv8a:nsh_smp instead.

**Comment by lipengfei28** [comment]
> > I noticed that qemu-armv8a:netnsh_smp causes the following error after merging this PR.
> 
> @lipengfei28 Please try qemu-armv8a:nsh_smp instead.

Sorry，I will fix the bug

**Comment by lipengfei28** [comment]
> > I noticed that qemu-armv8a:netnsh_smp causes the following error after merging this PR.
> 
> @lipengfei28 Please try qemu-armv8a:nsh_smp instead.

https://github.com/apache/nuttx/pull/14074
This PR fix the bug

**Pull request merged**
