### PR TITLE
risc-v/mpfs: enable DEFAULT_SMALL for insufficient envm capacity

### PR DESCRIPTION
**Pull request by gneworld**
## Summary
to fix ci error about https://github.com/apache/nuttx/pull/14070
image

## Impact
risc-v/mpfs

### CODE REVIEW

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by gneworld** [comment]
@eenurkka Kindly take a look at this modification

**Review by eenurkka — APPROVED** [review]
LGTM!

**Comment by xiaoxiang781216** [comment]
@gneworld please fix:
```
====================================================================================
Configuration/Tool: icicle/rpmsg-sbi
2024-10-13 12:50:39
------------------------------------------------------------------------------------
  Cleaning...
  Configuring...
  Building NuttX...
riscv-none-elf-ld: warning: /github/workspace/sources/nuttx/nuttx has a LOAD segment with RWX permissions
  Normalize icicle/rpmsg-sbi
62,106d61
< CONFIG_NSH_DISABLE_BASENAME=y
< CONFIG_NSH_DISABLE_CAT=y
< CONFIG_NSH_DISABLE_CD=y
< CONFIG_NSH_DISABLE_CMP=y
< CONFIG_NSH_DISABLE_CP=y
< CONFIG_NSH_DISABLE_DD=y
< CONFIG_NSH_DISABLE_DF=y
< CONFIG_NSH_DISABLE_DIRNAME=y
< CONFIG_NSH_DISABLE_DMESG=y
< CONFIG_NSH_DISABLE_ECHO=y
< CONFIG_NSH_DISABLE_ENV=y
< CONFIG_NSH_DISABLE_EXEC=y
< CONFIG_NSH_DISABLE_EXIT=y
< CONFIG_NSH_DISABLE_EXPORT=y
< CONFIG_NSH_DISABLE_FREE=y
< CONFIG_NSH_DISABLE_GET=y
< CONFIG_NSH_DISABLE_HEXDUMP=y
< CONFIG_NSH_DISABLE_IFCONFIG=y
< CONFIG_NSH_DISABLE_IFUPDOWN=y
< CONFIG_NSH_DISABLE_KILL=y
< CONFIG_NSH_DISABLE_LOSETUP=y
< CONFIG_NSH_DISABLE_MKDIR=y
< CONFIG_NSH_DISABLE_MKFATFS=y
< CONFIG_NSH_DISABLE_MKRD=y
< CONFIG_NSH_DISABLE_MOUNT=y
< CONFIG_NSH_DISABLE_MV=y
< CONFIG_NSH_DISABLE_PRINTF=y
< CONFIG_NSH_DISABLE_PS=y
< CONFIG_NSH_DISABLE_PUT=y
< CONFIG_NSH_DISABLE_PWD=y
< CONFIG_NSH_DISABLE_RM=y
< CONFIG_NSH_DISABLE_RMDIR=y
< CONFIG_NSH_DISABLE_SET=y
< CONFIG_NSH_DISABLE_SLEEP=y
< CONFIG_NSH_DISABLE_SOURCE=y
< CONFIG_NSH_DISABLE_TEST=y
< CONFIG_NSH_DISABLE_TIME=y
< CONFIG_NSH_DISABLE_TRUNCATE=y
< CONFIG_NSH_DISABLE_UMOUNT=y
< CONFIG_NSH_DISABLE_UNAME=y
< CONFIG_NSH_DISABLE_UNSET=y
< CONFIG_NSH_DISABLE_UPTIME=y
< CONFIG_NSH_DISABLE_USLEEP=y
< CONFIG_NSH_DISABLE_WGET=y
< CONFIG_NSH_DISABLE_XD=y
109d63
< CONFIG_PREALLOC_TIMERS=4
Saving the new configuration file
HEAD detached at pull/14201/merge
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   boards/risc-v/mpfs/icicle/configs/rpmsg-sbi/defconfig
```

**Review by pkarashchenko — APPROVED** [review]

**Comment by gneworld** [comment]
> @gneworld please fix:
> 
> ```
> ====================================================================================
> Configuration/Tool: icicle/rpmsg-sbi
> 2024-10-13 12:50:39
> ------------------------------------------------------------------------------------
>   Cleaning...
>   Configuring...
>   Building NuttX...
> riscv-none-elf-ld: warning: /github/workspace/sources/nuttx/nuttx has a LOAD segment with RWX permissions
>   Normalize icicle/rpmsg-sbi
> 62,106d61
> < CONFIG_NSH_DISABLE_BASENAME=y
> < CONFIG_NSH_DISABLE_CAT=y
> < CONFIG_NSH_DISABLE_CD=y
> < CONFIG_NSH_DISABLE_CMP=y
> < CONFIG_NSH_DISABLE_CP=y
> < CONFIG_NSH_DISABLE_DD=y
> < CONFIG_NSH_DISABLE_DF=y
> < CONFIG_NSH_DISABLE_DIRNAME=y
> < CONFIG_NSH_DISABLE_DMESG=y
> < CONFIG_NSH_DISABLE_ECHO=y
> < CONFIG_NSH_DISABLE_ENV=y
> < CONFIG_NSH_DISABLE_EXEC=y
> < CONFIG_NSH_DISABLE_EXIT=y
> < CONFIG_NSH_DISABLE_EXPORT=y
> < CONFIG_NSH_DISABLE_FREE=y
> < CONFIG_NSH_DISABLE_GET=y
> < CONFIG_NSH_DISABLE_HEXDUMP=y
> < CONFIG_NSH_DISABLE_IFCONFIG=y
> < CONFIG_NSH_DISABLE_IFUPDOWN=y
> < CONFIG_NSH_DISABLE_KILL=y
> < CONFIG_NSH_DISABLE_LOSETUP=y
> < CONFIG_NSH_DISABLE_MKDIR=y
> < CONFIG_NSH_DISABLE_MKFATFS=y
> < CONFIG_NSH_DISABLE_MKRD=y
> < CONFIG_NSH_DISABLE_MOUNT=y
> < CONFIG_NSH_DISABLE_MV=y
> < CONFIG_NSH_DISABLE_PRINTF=y
> < CONFIG_NSH_DISABLE_PS=y
> < CONFIG_NSH_DISABLE_PUT=y
> < CONFIG_NSH_DISABLE_PWD=y
> < CONFIG_NSH_DISABLE_RM=y
> < CONFIG_NSH_DISABLE_RMDIR=y
> < CONFIG_NSH_DISABLE_SET=y
> < CONFIG_NSH_DISABLE_SLEEP=y
> < CONFIG_NSH_DISABLE_SOURCE=y
> < CONFIG_NSH_DISABLE_TEST=y
> < CONFIG_NSH_DISABLE_TIME=y
> < CONFIG_NSH_DISABLE_TRUNCATE=y
> < CONFIG_NSH_DISABLE_UMOUNT=y
> < CONFIG_NSH_DISABLE_UNAME=y
> < CONFIG_NSH_DISABLE_UNSET=y
> < CONFIG_NSH_DISABLE_UPTIME=y
> < CONFIG_NSH_DISABLE_USLEEP=y
> < CONFIG_NSH_DISABLE_WGET=y
> < CONFIG_NSH_DISABLE_XD=y
> 109d63
> < CONFIG_PREALLOC_TIMERS=4
> Saving the new configuration file
> HEAD detached at pull/14201/merge
> Changes not staged for commit:
>   (use "git add <file>..." to update what will be committed)
>   (use "git restore <file>..." to discard changes in working directory)
> 	modified:   boards/risc-v/mpfs/icicle/configs/rpmsg-sbi/defconfig
> ```

@xiaoxiang781216 done

**Review by pkarashchenko — APPROVED** [review]

**Pull request merged**
