### PR TITLE
Nucleo-H563ZI with NSH configuration

### PR DESCRIPTION
**Pull request by stbenn**
Created stm32h5 directory to add support for the H5 chip, and used a Nucleo-H563ZI dev board during development. The goal was to get a working nutshell through the STLink connector on the board.

Code contained in PR was written in collaboration with @kywwilson11. 

*Note: Please adhere to [Contributing Guidelines](https://github.com/apache/nuttx/blob/master/CONTRIBUTING.md).*

## Summary

There has not been support for STM32H5 chips, so this should provide a starting point for further development. Being able to get to a nutshell on a dev board seems like a good first step. 

## Testing

Testing was done by building the configuration, programming the board and seeing the characters printed during start, followed by `nsh>` working. 

OS: `Ubuntu 24.04` (Running in WSL2 on Windows 11)
Compiler: `arm-none-eabi-gcc (15:13.2.rel1-2) 13.2.1 20231009`
Target:
- Arch: STM32H5
- Chip: STM32H563ZIT6U
- Board: Nucleo-H563ZI
- Config: `nucleo-h563zi:nsh` config (added by this PR)

### CODE REVIEW

**Comment by stbenn** [comment]
If this PR needs to be broken up into smaller components, please advise on what components would make the most sense as the first step in the process.

**Comment by acassis** [comment]
@stbenn there is not fixed rule. You can create an initial commit that add the new arch with the headers files, then the peripherals and later on the board support

**Comment by stbenn** [comment]
@acassis Would you suggest closing this PR to do that then? The main reason this PR was so large is because we wanted to get the H5 to a point you could actually do something with it (nutshell).

**Comment by acassis** [comment]
> @acassis Would you suggest closing this PR to do that then? The main reason this PR was so large is because we wanted to get the H5 to a point you could actually do something with it (nutshell).

It is up to you, it is possible to create new commit and use git push forced to update your PR

**Comment by cederom** [comment]
Thank you @stbenn !! Great work, and most welcome! However, as @acassis mentioned it is better to include this kind of change in small parts, so we can test integration step by step and pinpoint / fix possible problems that arise during build on various platforms and configurations :-)

**Comment by cederom** [comment]
On the other hand if all builds and works fine splitting that big change is a lot of additional work and may result in additional problems :-P

**Pull request closed without merging**
