### PR TITLE
fix some bug of strtold

### PR DESCRIPTION
**Pull request by flyingfish89**
## Summary
  with the test of sim:lua ,I have fixed some bug of error output
  1.input: "  " and error output string is "NULL"
  2.input: "1.2e+", error output string is "NULL"
  3.input: "."      error output string is "NULL"
## Testing
```
  char *a = "    n";
  char *b;
  float number = strtof(a,&b);
  syslog(LOG_INFO,"string is %s\n number is %f and string is %s\n",a,number,b);

  a = " 10  nsh";
  number = strtof(a,&b);
 syslog(LOG_INFO,"string is %s\nnumber is %f and string is %s\n",a,number,b);
  a = "2nsh";
  number = strtof(a,&b);
 syslog(LOG_INFO,"string is %s\nnumber is %f and string is %s\n",a,number,b);
  a = " 3e0 nsh";
  number = strtof(a,&b);
 syslog(LOG_INFO,"string is %s\nnumber is %f and string is %s\n",a,number,b);
  a = "1.0e+nsh";
  number = strtof(a,&b);
 syslog(LOG_INFO,"string is %s\nnumber is %f and string is %s\n",a,number,b);
  a = "2 nsh";
  number = strtof(a,&b);
 syslog(LOG_INFO,"string is %s\nnumber is %f and string is %s\n",a,number,b);
  a = "2nsh";
  number = strtof(a,&b);
 syslog(LOG_INFO,"string is %s\nnumber is %f and string is %s\n",a,number,b);
  a = "-2 nsh";
  number = strtof(a,&b);
 syslog(LOG_INFO,"astring is %s\nnumber is %f and string is %s\n",a,number,b);
  a = " -0xa nsh";
  number = strtof(a,&b);
  syslog(LOG_INFO,"astring is %s\n number is %f and string is %s\n",a,number,b);
  a = "+0.01 nsh";
  number = strtof(a,&b);
 syslog(LOG_INFO,"astring is %s\nnumber is %f and string is %s\n",a,number,b);
  a = "+.01 nsh";
  number = strtof(a,&b);
 syslog(LOG_INFO,"astring is %s\nnumber is %f and string is %s\n",a,number,b);
  a = ".01 nsh";
  number = strtof(a,&b);
 syslog(LOG_INFO,"astring is %s\nnumber is %f and string is %s\n",a,number,b); 
 a = "-1. nsh";
  number = strtof(a,&b);
 syslog(LOG_INFO,"astring is %s\nnumber is %f and string is %s\n",a,number,b);
  a = "+1. nsh";
  number = strtof(a,&b);
 syslog(LOG_INFO,"astring is %s\nnumber is %f and string is %s\n",a,number,b);
  a = "+ 0.01 nsh";
  number = strtof(a,&b);
 syslog(LOG_INFO,"astring is %s\nnumber is %f and string is %s\n",a,number,b); 
 a = "+.e1 nsh";
  number = strtof(a,&b);
 syslog(LOG_INFO,"string is %s\nnumber is %f and string is %s\n",a,number,b);
  a = "1e nsh";
  number = strtof(a,&b);
 syslog(LOG_INFO,"string is %s\nnumber is %f and string is %s\n",a,number,b);  a = "1.0e+ nsh";
  number = strtof(a,&b);
 syslog(LOG_INFO,"string is %s\nnumber is %f and string is %s\n",a,number,b);  a = ". nsh";
  number = strtof(a,&b);
 syslog(LOG_INFO,"string is %s\nnumber is %f and string is %s\n",a,number,b);  a = "nan";
  number = strtof(a,&b);
 syslog(LOG_INFO,"string is %s\nnumber is %f and string is %s\n",a,number,b);  a = "-012 nsh";
  number = strtof(a,&b);
 syslog(LOG_INFO,"string is %s\nnumber is %f and string is %s\n",a,number,b);  a = "-1.2e2 nsh";
  number = strtof(a,&b);
 syslog(LOG_INFO,"string is %s\nnumber is %f and string is %s\n",a,number,b);  a = "e1 nsh";
  number = strtof(a,&b);
 syslog(LOG_INFO,"string is %s\nnumber is %f and string is %s\n",a,number,b);  a = "0xffffffffffff nsh";
  number = strtof(a,&b);
 syslog(LOG_INFO,"string is %s\nnumber is %f and string is %s\n",a,number,b);  a = "x";
  number = strtof(a,&b);
 syslog(LOG_INFO,"string is %s\nnumber is %f and string is %s\n",a,number,b);  a = "0xffffffffffff nsh";
  number = strtof(a,&b);
 syslog(LOG_INFO,"string is %s\nnumber is %f and string is %s\n",a,number,b);  a = "0x3. nsh";
  number = strtof(a,&b);
 syslog(LOG_INFO,"string is %s\nnumber is %f and string is %s\n",a,number,b);  a = "0x0. nsh";
  number = strtof(a,&b);
 syslog(LOG_INFO,"string is %s\nnumber is %f and string is %s\n",a,number,b);  a = "-0xfFfa nsh";
  number = strtof(a,&b);
 syslog(LOG_INFO,"string is %s\nnumber is %f and string is %s\n",a,number,b);  a = "0xffffFFFF nsh";
  number = strtof(a,&b);
 syslog(LOG_INFO,"string is %s\nnumber is %f and string is %s\n",a,number,b);  a = "0x.0p-3";
  number = strtof(a,&b);
 syslog(LOG_INFO,"string is %s\nnumber is %f and string is %s\n",a,number,b);  a = "0ffffFFFF nsh";
  number = strtof(a,&b);
 syslog(LOG_INFO,"string is %s\nnumber is %f and string is %s\n",a,number,b);  a = "+0x2 nsh";
  number = strtof(a,&b);
 syslog(LOG_INFO,"string is %s\nnumber is %f and string is %s\n",a,number,b);  a = "-0xaA nsh";
  number = strtof(a,&b);
 syslog(LOG_INFO,"string is %s\nnumber is %f and string is %s\n",a,number,b);  a = "-0xffFFFfff nsh";
  number = strtof(a,&b);
 syslog(LOG_INFO,"string is %s\nnumber is %f and string is %s\n",a,number,b);  a = "0E+1 nsh";
  number = strtof(a,&b);
 syslog(LOG_INFO,"string is %s\nnumber is %f and string is %s\n",a,number,b);  a = "0E+1 nsh";
  number = strtof(a,&b);
 syslog(LOG_INFO,"string is %s\nnumber is %f and string is %s\n",a,number,b);  a = "0xe-1 nsh";
  number = strtof(a,&b);
 syslog(LOG_INFO,"string is %s\nnumber is %f and string is %s\n",a,number,b);  a = "  0x2.5 nsh";
  number = strtof(a,&b);
 syslog(LOG_INFO,"string is %s\nnumber is %f and string is %s\n",a,number,b);  a = "  -0x2.5 nsh";
  number = strtof(a,&b);
 syslog(LOG_INFO,"string is %s\nnumber is %f and string is %s\n",a,number,b);  a = "0x0.51p nsh";
  number = strtof(a,&b);
 syslog(LOG_INFO,"string is %s\nnumber is %f and string is %s\n",a,number,b);  a = "0x.00000001 nsh";
  number = strtof(a,&b);
 syslog(LOG_INFO,"string is %s\nnumber is %f and string is %s\n",a,number,b);  a = "0xA.a nsh";
  number = strtof(a,&b);
 syslog(LOG_INFO,"string is %s\nnumber is %f and string is %s\n",a,number,b);  a = "0xa.aP4 nsh";
  number = strtof(a,&b);
 syslog(LOG_INFO,"string is %s\nnumber is %f and string is %s\n",a,number,b);  a = "0x4P-2 nsh";
  number = strtof(a,&b);
 syslog(LOG_INFO,"string is %s\nnumber is %f and string is %s\n",a,number,b);  a = "0x1.1 nsh";
  number = strtof(a,&b);
 syslog(LOG_INFO,"string is %s\nnumber is %f and string is %s\n",a,number,b);  a = "1. nsh";
  number = strtof(a,&b);
 syslog(LOG_INFO,"string is %s\nnumber is %f and string is %s\n",a,number,b);  a = ".1 nsh";
  number = strtof(a,&b);
 syslog(LOG_INFO,"string is %s\nnumber is %f and string is %s\n",a,number,b);  a = "0.001e+3 nsh";
  number = strtof(a,&b);
 syslog(LOG_INFO,"string is %s\nnumber is %f and string is %s\n",a,number,b);  a = "1111111111111110 nsh";
  number = strtof(a,&b);
 syslog(LOG_INFO,"string is %s\nnumber is %f and string is %s\n",a,number,b);  a = "1111111111111111 nsh";
  number = strtof(a,&b);
 syslog(LOG_INFO,"string is %s\nnumber is %f and string is %s\n",a,number,b);  a = "+1.23E18 nsh";
  number = strtof(a,&b);
 syslog(LOG_INFO,"string is %s\nnumber is %f and string is %s\n",a,number,b);  a = " 1.3e-2  nsh";
  number = strtof(a,&b);
 syslog(LOG_INFO,"string is %s\nnumber is %f and string is %s\n",a,number,b);  a = " -1.00000000000001 nsh";
  number = strtof(a,&b);
 syslog(LOG_INFO,"string is %s\nnumber is %f and string is %s\n",a,number,b);  a = "10 nsh";
  number = strtof(a,&b);
 syslog(LOG_INFO,"string is %s\nnumber is %f and string is %s\n",a,number,b);  a = "20 nsh";
  number = strtof(a,&b);
 syslog(LOG_INFO,"string is %s\nnumber is %f and string is %s\n",a,number,b);  
```

### CODE REVIEW

**Review by xiaoxiang781216 — APPROVED** [review]

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by fjpanag** [comment]
@flyingfish89 Thank you for this.

Just to provide some feedback, after this patch, all tests pass, apart from specifically the following:

```Lua
assert(tonumber'+ 0.01' == nil and tonumber'+.e1' == nil and
       tonumber'1e' == nil     and tonumber'1.0e+' == nil and
       tonumber'.' == nil)
```

I think this is the only one left.

**Comment by flyingfish89** [comment]
> @flyingfish89 Thank you for this.
> 
> Just to provide some feedback, after this patch, all tests pass, apart from specifically the following:
> 
> ```lua
> assert(tonumber'+ 0.01' == nil and tonumber'+.e1' == nil and
>        tonumber'1e' == nil     and tonumber'1.0e+' == nil and
>        tonumber'.' == nil)
> ```
> 
> I think this is the only one left.

yes,i have tried these,and i have found if  " '1.0e+' == nil " is wrong ,because it will return 1.0 and "+"

**Comment by flyingfish89** [comment]
Oh, this "e" should be returned, coule you change the strtold.c like this and try again
屏幕截图 2023-02-11 230336

**Comment by fjpanag** [comment]
Well... After applying this change, a get a previous test failing:

```Lua
assert(0e12 == 0 and .0 == 0 and 0. == 0 and .2e2 == 20 and 2.E-1 == 0.2)
```

with:
```
math.lua:5: malformed number near '2.E-1'
```

**Comment by flyingfish89** [comment]
ok,how about this
屏幕截图 2023-02-11 233815

**Comment by fjpanag** [comment]
Unfortunatelly not...

```Lua
assert(string.format("%+08d", 2^31 - 1) == "+2147483647")
```

fails with:

```
strings.lua:154: malformed number near '2'
```

**Comment by flyingfish89** [comment]
i'm sorry.i have tried this and i couldn't found any question,could you please show me about it!

**Comment by flyingfish89** [comment]
also,i have trid this
屏幕截图 2023-02-12 002830

**Comment by fjpanag** [comment]
Maybe I did a typo? Can you please post as code, instead of a screenshot?

**Comment by flyingfish89** [comment]
yes
屏幕截图 2023-02-12 003347
and this is the return
屏幕截图 2023-02-12 003452

**Comment by flyingfish89** [comment]
> 

em...,this mistake have no connection with what I just modified

**Comment by flyingfish89** [comment]
if ((c | 32) == 'e' && (isdigit(*f) || ((*f == '+' || *f == '-') && (isdigit(*(f + 1))))))
    {
      num_decimal = scanexp(&f, 1) + num_decimal;
      if (num_decimal <= llong_min / 100)
        {
          ifexist(endptr, f);
          return zero;
        }
    }

how about this!

**Comment by flyingfish89** [comment]
if ((c | 32) == 'e' && (isdigit(*f) || ((*f == '+' || *f == '-') && (isdigit(*(f + 1))))))
    {
      num_decimal = scanexp(&f, 1) + num_decimal;
      if (num_decimal <= llong_min / 100)
        {
          ifexist(endptr, f);
          return zero;
        }
    }

how about this

**Comment by flyingfish89** [comment]
if ((c | 32) == 'e' && (isdigit(*f) || ((*f == '+' || *f == '-') && (isdigit(*(f + 1))))))
    {
      num_decimal = scanexp(&f, 1) + num_decimal;
      if (num_decimal <= llong_min / 100)
        {
          ifexist(endptr, f);
          return zero;
        }
    }

how about this

**Comment by flyingfish89** [comment]
if ((c | 32) == 'e' && (isdigit(*f) || ((*f == '+' || *f == '-') && (isdigit(*(f + 1))))))

ok!how about this.

**Comment by flyingfish89** [comment]
`if ((c | 32) == 'e' && (isdigit(*f) || ((*f == '+' || *f == '-') && (isdigit(*(f + 1))))))
    {
      num_decimal = scanexp(&f, 1) + num_decimal;
      if (num_decimal <= llong_min / 100)
        {
          ifexist(endptr, f);
          return zero;
        }
    }`
how about this

**Comment by flyingfish89** [comment]
`if ((c | 32) == 'e' && (isdigit(*f) || ((*f == '+' || *f == '-') && (isdigit(*(f + 1))))))
`
how about this

**Comment by fjpanag** [comment]
@flyingfish89 Yes! That did the trick!  
All tests now pass.

Can you please provide a PR for this?

**Comment by flyingfish89** [comment]
ok.

**Pull request merged**
