### PR TITLE
Request for SIM/QEMU automation script

### PR DESCRIPTION
**Pull request by GUIDINGLI**
## Summary

Hi all,

Here open a new PR just for :
Requesting SIM/QEMU automation script

Especially the compile cmd, run cmd.

Recently we push lots of PR to the community, but some of them have regression, like:
https://github.com/apache/nuttx/pull/13651

So can someone/anyone share your automation script to us.
Then we can integrate it to CI, and catch the regression.

## Impact

None

## Testing

None

@masayuki2009
@fdcavalcanti 
@lupyuen

### CODE REVIEW

**Comment by lupyuen** [comment]
@GUIDINGLI That's a great idea! I run these scripts daily at GitHub Actions:
- [qemu-riscv-nsh.yml](https://github.com/lupyuen/nuttx-riscv64/blob/main/.github/workflows/qemu-riscv-nsh.yml): Daily Build and Test NuttX for QEMU RISC-V 32-bit (Flat Build)
- [qemu-riscv-knsh.yml](https://github.com/lupyuen/nuttx-riscv64/blob/main/.github/workflows/qemu-riscv-knsh.yml): Daily Build and Test NuttX for QEMU RISC-V 32-bit (Kernel Build)

GitHub Actions won't run OSTest correctly for 64-bit QEMU. I run these scripts on my computer instead:
- [test-nsh64.sh](https://github.com/lupyuen/nuttx-riscv64/blob/main/task/test-nsh64.sh): Automated Testing of Apache NuttX RTOS for QEMU RISC-V 64-bit Flat Build
- [test-knsh64.sh](https://github.com/lupyuen/nuttx-riscv64/blob/main/task/test-knsh64.sh): Automated Testing of Apache NuttX RTOS for QEMU RISC-V 64-bit Kernel Build

I'm not sure why GitHub Actions is failing for 64-bit QEMU. Here's what I discovered:
- ["NuttX QEMU RISC-V fails on GitHub Actions"](https://lupyuen.github.io/articles/rust6#appendix-nuttx-qemu-risc-v-fails-on-github-actions)

**Comment by lupyuen** [comment]
Here's another option: We can run the Milk-V Duo S Emulator in GitHub Actions: https://lupyuen.github.io/articles/sg2000b

This morning we caught a Serial Driver problem during the Daily Auto-Test:
https://github.com/lupyuen/nuttx-sg2000/actions/runs/11265744154/job/31329258960
```text
spawn ./temu nuttx.cfg
TinyEMU Emulator for Sophgo SG2000 SoC
ABC
```

Normally it runs like this:
https://github.com/lupyuen/nuttx-sg2000/actions/runs/11246511514/job/31268441936
```text
spawn ./temu nuttx.cfg
TinyEMU Emulator for Sophgo SG2000 SoC
ABC
NuttShell (NSH) NuttX-12.7.0-RC0
nsh> uname -a
NuttX 12.7.0-RC0 6ce7b70a3a Oct  9 2024 00:15:20 risc-v milkv_duos
```

**Comment by GUIDINGLI** [comment]
https://github.com/apache/nuttx/pull/14033

**Comment by GUIDINGLI** [comment]
> Here's another option: We can run the Milk-V Duo S Emulator in GitHub Actions: https://lupyuen.github.io/articles/sg2000b
> 
> This morning we caught a Serial Driver problem during the Daily Auto-Test: https://github.com/lupyuen/nuttx-sg2000/actions/runs/11265744154/job/31329258960
> 
> ```
> spawn ./temu nuttx.cfg
> TinyEMU Emulator for Sophgo SG2000 SoC
> A�BC
> ```
> 
> Normally it runs like this: https://github.com/lupyuen/nuttx-sg2000/actions/runs/11246511514/job/31268441936
> 
> ```
> spawn ./temu nuttx.cfg
> TinyEMU Emulator for Sophgo SG2000 SoC
> A�BC
> NuttShell (NSH) NuttX-12.7.0-RC0
> nsh> uname -a
> NuttX 12.7.0-RC0 6ce7b70a3a Oct  9 2024 00:15:20 risc-v milkv_duos
> ```

Fix on :
https://github.com/apache/nuttx/pull/14033

**Comment by lupyuen** [comment]
This might be helpful: This script will **Auto-Test the Past 20 Commits** on NuttX QEMU knsh64: https://github.com/lupyuen/nuttx-riscv64/blob/main/special-qemu-riscv-knsh64.sh#L42-L56

**Comment by GUIDINGLI** [comment]
> This might be helpful when something breaks: This script will **Auto-Test the Past 50 Commits** on NuttX QEMU knsh64: https://github.com/lupyuen/nuttx-riscv64/blob/main/special-qemu-riscv-knsh64.sh#L42-L56

Great, hope you can integrate them to our CI earlier.
I am not good at the CI, so may not be able to help you, Sorry.

**Review by lupyuen — APPROVED** [review]

**Pull request closed without merging**
