### PR TITLE
boards/raspberrypi-pico: Remove early return for error cases in initialization functions.

### PR DESCRIPTION
**Pull request by hcd-bdltd**
## Summary

Ensure proper error handling by adding return statements for error cases in various initialization functions.

## Impact

RaspberryPico targets.

## Testing

Internal CI testing

### CODE REVIEW

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by acassis** [comment]
@hcd-bdltd by default we don't add return inside these error messages (see stm32 boards), because if something not related is failing the bring up will not continue and users will waste a lot of time trying to figure out what is happening.

It seems like the obvious option is just fix the previous error, but in real life it is not ideal, it is better to report the error message and try to move on, expect for cases where you need previous resource.

**Comment by hcd-bdltd** [comment]
> @hcd-bdltd by default we don't add return inside these error messages (see stm32 boards), because if something not related is failing the bring up will not continue and users will waste a lot of time trying to figure out what is happening.
> 
> It seems like the obvious option is just fix the previous error, but in real life it is not ideal, it is better to report the error message and try to move on, expect for cases where you need previous resource.

Understood, what are the guidelines about which errors should be returned early and which should not?

**Comment by acassis** [comment]
> > @hcd-bdltd by default we don't add return inside these error messages (see stm32 boards), because if something not related is failing the bring up will not continue and users will waste a lot of time trying to figure out what is happening.
> > It seems like the obvious option is just fix the previous error, but in real life it is not ideal, it is better to report the error message and try to move on, expect for cases where you need previous resource.
> 
> Understood, what are the guidelines about which errors should be returned early and which should not?

I think we don't have a written guideline for it, but if you try to initialize a device that is requirement for the next initialization, like mounting a SDCard filesystem that requires the sdcard device, then you need to return in the sdcard initialization.

In those case a good sugestion is put these kind of initialization as latest in the bringup function.

**Comment by hcd-bdltd** [comment]
@acassis Sorry but I'm having trouble identifying which error should be returned and which should not.

The `nrf52_bringup.c` and `cxd56_bringup.c` do not return any error early.

But the `stm32_bringup` sometimes return, sometimes not.

Should the default be not to return early, then? Should I delete all early returns?

**Comment by acassis** [comment]
> @acassis Sorry but I'm having trouble identifying which error should be returned and which should not.
> 
> The `nrf52_bringup.c` and `cxd56_bringup.c` do not return any error early.
> 
> But the `stm32_bringup` sometimes return, sometimes not.
> 
> Should the default be not to return early, then? Should I delete all early returns?

Yes, it is better remove all return than returning early. Where do you suggest we add this information as a guide for new developers? Maybe after C Coding Style: https://nuttx.apache.org/docs/latest/contributing/index.html ?

**Review by acassis — CHANGES_REQUESTED** [review]
Hudson, lets move it to draft until you update it

**Comment by hcd-bdltd** [comment]
> Yes, it is better remove all return than returning early. Where do you suggest we add this information as a guide for new developers? Maybe after C Coding Style: https://nuttx.apache.org/docs/latest/contributing/index.html ?

It seems a very specific guideline to add into the general contribution documentation. Maybe the best approach is to open a ticket to ensure the bring_up logic is consistent across boards?

And then make the required changes, so if a new developer needs to have a look again, it can check against the others boards.

I would be more than happy to help with this task if necessary.

**Comment by acassis** [comment]
> > Yes, it is better remove all return than returning early. Where do you suggest we add this information as a guide for new developers? Maybe after C Coding Style: https://nuttx.apache.org/docs/latest/contributing/index.html ?
> 
> It seems a very specific guideline to add into the general contribution documentation. Maybe the best approach is to open a ticket to ensure the bring_up logic is consistent across boards?
> 
> And then make the required changes, so if a new developer needs to have a look again, it can check against the others boards.
> 
> I would be more than happy to help with this task if necessary.

Agree!

Maybe another option is our CI could verify if it is the bring-up function and in that case it checks for those returns to warn the developers

**Review by acassis — APPROVED** [review]

**Review by xiaoxiang781216 — APPROVED** [review]

**Pull request merged**
