### PR TITLE
change gd32f470z board code

### PR DESCRIPTION
**Pull request by GD32-MCU**

### CODE REVIEW

**Comment by acassis** [comment]
Hi @GD32-MCU nice work! Please include a proper commit log message saying the improvements your patch is adding to mainline code.

**Comment by acassis** [comment]
@GD32-MCU also please include documentation about your board and a picture. It seems empty: https://nuttx.apache.org/docs/latest/platforms/arm/gd32f4/index.html

**Comment by GD32-MCU** [comment]
> Hi @GD32-MCU nice work! Please include a proper commit log message saying the improvements your patch is adding to mainline code.

Thanks for the advice. How should I include a new proper commit log message now. Should  I close and re-commit this pull request?

**Comment by GD32-MCU** [comment]
> @GD32-MCU also please include documentation about your board and a picture. It seems empty: https://nuttx.apache.org/docs/latest/platforms/arm/gd32f4/index.html

And I,m not clear how to include documentation about the board and a picture on .html, could you please give me some advice?
Thanks

**Comment by acassis** [comment]
> > Hi @GD32-MCU nice work! Please include a proper commit log message saying the improvements your patch is adding to mainline code.
> 
> Thanks for the advice. How should I include a new proper commit log message now. Should I close and re-commit this pull request?

It is explained in our documentation here:

https://nuttx.apache.org/docs/latest/contributing/making-changes.html#how-to-include-the-suggestions-on-your-pull-request

**Comment by acassis** [comment]
> > @GD32-MCU also please include documentation about your board and a picture. It seems empty: https://nuttx.apache.org/docs/latest/platforms/arm/gd32f4/index.html
> 
> And I,m not clear how to include documentation about the board and a picture on .html, could you please give me some advice? Thanks

Please look the existing examples in our Documentation:
i.e.: Documentation/platforms/xtensa/esp32/boards/esp32-devkitc/index.rst

**Comment by GD32-MCU** [comment]
> > > Hi @GD32-MCU nice work! Please include a proper commit log message saying the improvements your patch is adding to mainline code.
> > 
> > 
> > Thanks for the advice. How should I include a new proper commit log message now. Should I close and re-commit this pull request?
> 
> It is explained in our documentation here:
> 
> https://nuttx.apache.org/docs/latest/contributing/making-changes.html#how-to-include-the-suggestions-on-your-pull-request

Thanks

**Review by xiaoxiang781216 — APPROVED** [review]

**Pull request merged**
