### PR TITLE
syslog: enable LF to CRLF config as default

### PR DESCRIPTION
**Pull request by yangsong8-ai**
## Summary

enable LF to CRLF config as default

## Impact

log output

## Testing

selftest

### CODE REVIEW

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by xiaoxiang781216** [comment]
@FelipeMdeO @raiden00pl could you try this patch?

**Review by raiden00pl — APPROVED** [review]

**Comment by raiden00pl** [comment]
@jerpelea please backport to 12.7

**Comment by jerpelea** [comment]
@raiden00pl thanks

**Comment by jerpelea** [comment]
backport https://github.com/apache/nuttx/pull/14430

**Review by cederom — COMMENTED** [review]
Thank you @yangsong8-ai !! :-)

**Pull request merged**
