### PR TITLE
arm/stm32h7/stm32h745i-disco: Add STM32H745I-DISCO Per Core Support

### PR DESCRIPTION
**Pull request by nonpawite**
## Summary

- Created new defconfig `nsh_cm4` and `nsh_cm7`.
- Editted `flash.ld`: Add shmem, condotion for flash size
- Added `flash_c4.ld`
- Editted Make and CMake file to compile according to core
- Added UART7 pin by default for CM4 serial output
- Changed `GPIO_LED_BLUE` to `GPIO_LED_ORANGE` in userled to fix error

## Impact

STM32H745I-DISCO now have 1 instance and 2 instance nuttx support

## Testing

Tested both cm4 and cm7 on stm32h745i-disco board

### CODE REVIEW

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by xiaoxiang781216** [comment]
@nonpawite please boards/arm/stm32h7/stm32h745i-disco/src/CMakeLists.txt with cmake-format to fix ci error.

**Review by raiden00pl — APPROVED** [review]

**Review by jerpelea — APPROVED** [review]
please update the title to 
arm/stm32h7/stm32h745i-disco: Add STM32H745I-DISCO Per Core Support 

and add a commit message

**Comment by xiaoxiang781216** [comment]
@nonpawite please squash your patch into one.

**Review by xiaoxiang781216 — APPROVED** [review]

**Review by acassis — APPROVED** [review]

**Comment by nonpawite** [comment]
@acassis Okay! I will do that.

**Comment by nonpawite** [comment]
@acassis I might push a Documentation a little bit late, since I'm working on my thesis right now.

**Comment by adriendesp** [comment]
Hey, 
I have a STM32H745i eval board and I would like to use both core at the same time. CM4 would continuously read/write SPI from external sensor, at high speed. CM7 would perform application, using values read from CM4.

So far, I have succeeded to build and flash a "Hello World" example on USART3 with Cortex M7 core. And I already used nuttx on other single-core architecture.

Could you, please,  guide me a bit in the process of configuring, building and using both core at the same time ? Where should I start ?

**Comment by nonpawite** [comment]
Hi @adriendesp, please join our Discord community via this [link](https://discord.gg/rQXQVggn)!

**Pull request merged**
