### PR TITLE
arch/arm: Change the default value to ARCH_TRUSTZONE_NONSECURE

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
## Summary

since nuttx normally run inside the non secure execution environment

## Impact

trustzone

## Testing

ci

### CODE REVIEW

**Comment by raiden00pl** [comment]
this breaks most of the nrf91 and nrf53 (only cpu_app has TZ) configurations. Only nrf9160-dk/modem_ns works in NS env now.

**Comment by xiaoxiang781216** [comment]
> this breaks most of the nrf91 and nrf53 (only cpu_app has TZ) configurations. Only nrf9160-dk/modem_ns works in NS env now.

 It's strange that NRF works in the security mode for normal operation?

**Comment by raiden00pl** [comment]
Secure environment is the default execution environment after boot. Most of nrf91/nrf53 configs don't use bootlaoder so there is no jump to non secure environment. At the moment, we aren't able to create with NuttX a combined image with secure + non secure image (as Zephyr does for example), so it's easier to have configs as secure image - then we don't need to flash 2 images.

I thing this change make sense, but please update Nordic configurations.

**Comment by xiaoxiang781216** [comment]
Ok, I will update soon.

**Comment by xiaoxiang781216** [comment]
> Secure environment is the default execution environment after boot. Most of nrf91/nrf53 configs don't use bootlaoder so there is no jump to non secure environment. At the moment, we aren't able to create with NuttX a combined image with secure + non secure image (as Zephyr does for example), so it's easier to have configs as secure image - then we don't need to flash 2 images.
> 
> I think this change make sense, but please update Nordic configurations.

@raiden00pl all nrf91 are updated, please review again.

**Comment by raiden00pl** [comment]
@xiaoxiang781216 Still missing nrf53 which is also CM33 (both cores). The changes for nrf91 look good

**Comment by xiaoxiang781216** [comment]
> @xiaoxiang781216 Still missing nrf53 which is also CM33 (both cores). The changes for nrf91 look good

But, nrf53 doesn't select ARCH_HAVE_TRUSTZONE, so it's impossible to add CONFIG_ARCH_TRUSTZONE_SECURE=y.

**Comment by raiden00pl** [comment]
Right, I see I forgot `ARCH_HAVE_TRUSTZONE` for nrf53. I'll fix it later

**Pull request merged**
