### PR TITLE
boot: fix potential bl jump to app failed issue

### PR DESCRIPTION
**Pull request by gneworld**
Summary
After changing sp, following functions calling will result in unpredictable behavior in case of jumping.

Impact
boot of imxrt1064, nrf52, nrf53, nrf91,samv7

Testing

### CODE REVIEW

**Comment by acassis** [comment]
@gneworld did you test it on samv7 board and on other boards that will be impacted by this change?

**Comment by acassis** [comment]
> After changing sp, following functions calling will result in unpredictable behavior in case of jumping

BTW, why did you remove the Summary template?

**Comment by pkarashchenko** [comment]
The change seems to be correct, however nrf91 seems to be impacted most

**Review by pkarashchenko — APPROVED** [review]

**Review by raiden00pl — CHANGES_REQUESTED** [review]
This change is not correct for nrf91. You can't ignore `tz_nonsecure_call` attribute when switching from secure to non-secure environment is required (`CONFIG_NRF91_NONSECURE_BOOT=y`).
Non-secure call must be done with `__gnu_cmse_nonsecure_call`. Here is correct assembler:
```
  ns_reset();
    8d8e:       6864            ldr     r4, [r4, #4]
    8d90:       0864            lsrs    r4, r4, #1
    8d92:       0064            lsls    r4, r4, #1
    8d94:       4620            mov     r0, r4
    8d96:       4621            mov     r1, r4
    8d98:       4622            mov     r2, r4
    8d9a:       4623            mov     r3, r4
    8d9c:       f000 f858       bl      8e50 <__gnu_cmse_nonsecure_call>
```

With your change it is:

```
  __asm__ __volatile__("\tmsr msp_ns, %0\n"
    8d8e:       e9d5 3200       ldrd    r3, r2, [r5]
    8d92:       f383 8888       msr     MSP_NS, r3
    8d96:       f3bf 8f6f       isb     sy
    8d9a:       4697            mov     pc, r2

```

**Comment by gneworld** [comment]
> This change is not correct for nrf91. You can't ignore `tz_nonsecure_call` attribute when switching from secure to non-secure environment is required (`CONFIG_NRF91_NONSECURE_BOOT=y`). Non-secure call must be done with `__gnu_cmse_nonsecure_call`. Here is correct assembler:
> 
> ```
>   ns_reset();
>     8d8e:       6864            ldr     r4, [r4, #4]
>     8d90:       0864            lsrs    r4, r4, #1
>     8d92:       0064            lsls    r4, r4, #1
>     8d94:       4620            mov     r0, r4
>     8d96:       4621            mov     r1, r4
>     8d98:       4622            mov     r2, r4
>     8d9a:       4623            mov     r3, r4
>     8d9c:       f000 f858       bl      8e50 <__gnu_cmse_nonsecure_call>
> ```
> 
> With your change it is:
> 
> ```
>   __asm__ __volatile__("\tmsr msp_ns, %0\n"
>     8d8e:       e9d5 3200       ldrd    r3, r2, [r5]
>     8d92:       f383 8888       msr     MSP_NS, r3
>     8d96:       f3bf 8f6f       isb     sy
>     8d9a:       4697            mov     pc, r2
> ```

I have dropped the modification  int case of  CONFIG_NRF91_NONSECURE_BOOT  for nrf91, thanks a lot

**Review by raiden00pl — APPROVED** [review]

**Review by jerpelea — APPROVED** [review]

**Comment by pkarashchenko** [comment]
Just out of my curiosity, how does assembly look before the change? Is the fault reproduced only with -O0?

**Review by pkarashchenko — APPROVED** [review]

**Comment by gneworld** [comment]
> Just out of my curiosity, how does assembly look before the change? Is the fault reproduced only with -O0?

@pkarashchenko 
image

This patch just eliminates the potential risk of boot failure at  certain or specific conditions

**Pull request merged**
