### PR TITLE
drivers/pinctl: add pinctrl framework

### PR DESCRIPTION
**Pull request by Donny9**
## Summary
driver/pinctl: add pinctrl framework
## Impact
support pinctl driver framework
## Testing
Vela

### CODE REVIEW

**Review by lupyuen — APPROVED** [review]

**Review by acassis — CHANGES_REQUESTED** [review]
Hi @Donny9 please include https://nuttx.apache.org/docs/latest/components/drivers/index.html

**Comment by Donny9** [comment]
> Hi @Donny9 please include https://nuttx.apache.org/docs/latest/components/drivers/index.html

Done~

**Review by acassis — APPROVED** [review]

**Comment by acassis** [comment]
@Donny9 please include the index in the device driver documentation toc list:

```
 Warning, treated as error:
/home/runner/work/nuttx/nuttx/Documentation/components/drivers/special/pinctrl.rst:document isn't included in any toctree
make: *** [Makefile:47: html] Error 2
Error: Process completed with exit code 2.
```

**Comment by Donny9** [comment]
> @Donny9 please include the index in the device driver documentation toc list:
> 
> ```
>  Warning, treated as error:
> /home/runner/work/nuttx/nuttx/Documentation/components/drivers/special/pinctrl.rst:document isn't included in any toctree
> make: *** [Makefile:47: html] Error 2
> Error: Process completed with exit code 2.
> ```

Done~

**Review by xiaoxiang781216 — APPROVED** [review]

**Pull request merged**
