### PR TITLE
esp32s2: add simple boot support

### PR DESCRIPTION
**Pull request by almir-okato**
## Summary
The Simple Boot feature for Espressif chips is a method of booting that doesn't depend on a 2nd stage bootloader. It is intended to provide a minimal and straight-forward way of booting, and also simplify the building.

This PR also removes the Legacy Boot compatibility configuration for ESP32-S2 and removes deprecated code. 
It also makes this bootloader configuration as default for ESP32-S2 targets and removes the need for running 'make bootloader' command for it.

## Impact
ESP32-S2 targets and bootloader.

## Testing
Internal CI testing

### CODE REVIEW

**Comment by almir-okato** [comment]
@tmedicci @eren-terzioglu @fdcavalcanti @xiaoxiang781216 PTAL

**Review by xiaoxiang781216 — APPROVED** [review]

**Review by acassis — APPROVED** [review]

**Comment by acassis** [comment]
@almir-okato is it possible to have this support for ESP32 was well or only ESP32-Sx ?

**Comment by almir-okato** [comment]
> I'm fixing the last errors pointed by the CI.

CI fixed.

**Review by tmedicci — APPROVED** [review]

**Comment by almir-okato** [comment]
> @almir-okato is it possible to have this support for ESP32 was well or only ESP32-Sx ?

I'm working on that.
It is already implemented for Espressif RISC-V chips also.

**Pull request merged**
