### PR TITLE
sched/env: add tg_envc in task_group_s to avoid some loops in code

### PR DESCRIPTION
**Pull request by CV-Bowen**
## Summary
this commit optimize the env api speed by avoiding some loops (while/for) in code

## Impact
should be none

## Testing
sim:ostest pass

### CODE REVIEW

**Review by acassis — APPROVED** [review]

**Comment by acassis** [comment]
Hi @CV-Bowen did you make some profiling tests? How much it improves the execution time?

**Comment by pkarashchenko** [comment]
I think some time in the past we have count of variables, but moved away from it. @xiaoxiang781216 most probably can provide more details.

**Comment by xiaoxiang781216** [comment]
> I think some time in the past we have count of variables, but moved away from it. @xiaoxiang781216 most probably can provide more details. Anyway I will review.

Yes, but the layout is change:

1. The old way save all env in one big char array like this "env1=value1\0env2=value2"
2. The new way save all env in array of char array like this {"env1=value1", "env2=value2", NULL}

Layout 2 is required implicitly by environ: https://pubs.opengroup.org/onlinepubs/7908799/xsh/environ.html

**Review by xiaoxiang781216 — APPROVED** [review]

**Review by pkarashchenko — APPROVED** [review]
LGTM!

**Pull request merged**
