### PR TITLE
ci:use Reginald action check build system change

### PR DESCRIPTION
**Pull request by xuxin930**
## Summary

leave a warning for PR when Makefile or *.defs changed

### CODE REVIEW

**Review by xiaoxiang781216 — APPROVED** [review]

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by xiaoxiang781216** [comment]
> image I got the above error, but the action was indeed obtained from the market.
> refer: https://github.com/marketplace/actions/reginald-a-pull-request-review-bot

@btashton do you know how to enable the third-party action?

**Comment by btashton** [comment]
They are blocked outside of the approved ones listed in the error message.  You can try opening an Apache Infra ticket, but I expect it will not be approved.

**Comment by xuxin930** [comment]
@xiaoxiang781216 @btashton thank u all, I will try other actions, or implement it myself

**Comment by acassis** [comment]
@xuxin930 what you want to do with this PR? Close or implement other actions?

**Comment by xuxin930** [comment]
> @xuxin930 what you want to do with this PR? Close or implement other actions?

close this first, I'll find another way.

**Pull request closed without merging**
