### PR TITLE
esp32: Port the bootloader patch

### PR DESCRIPTION
**Pull request by yamt**
## Summary
currently esp32 protected mode requires a patched bootloader. it's a bit cumbersome to build the bootloader for that purpose.

this commit attempts to remove the need of the patched bootloader by applying the changes by ourselves using esp hal.

## Testing
esp32-devkitc:knsh (with https://github.com/apache/nuttx/pull/13309)

### CODE REVIEW

**Comment by tmedicci** [comment]
This patch wouldn't work by itself, right? I meant: it would not remove the need of the IDF bootloader, right?

I'm not against getting rid of the IDF/legacy bootloader (in fact, I support that), but I thing the changes necessary to run the `knsh` with simpleboot must be in this same PR.

**Review by tmedicci — CHANGES_REQUESTED** [review]
This patch wouldn't work by itself, right? I meant: it would not remove the need of the IDF bootloader, right?

I'm not against getting rid of the IDF/legacy bootloader (in fact, I support that), but I thing the changes necessary to run the knsh with simpleboot must be in this same PR.

**Comment by yamt** [comment]
> This patch wouldn't work by itself, right? I meant: it would not remove the need of the IDF bootloader, right?
> 
> I'm not against getting rid of the IDF/legacy bootloader (in fact, I support that), but I thing the changes necessary to run the knsh with simpleboot must be in this same PR.

why?

this patch is to make it work with unpatched bootlooder. it works as far as i tested.

it isn't about simpleboot.

**Comment by tmedicci** [comment]
> > This patch wouldn't work by itself, right? I meant: it would not remove the need of the IDF bootloader, right?
> > I'm not against getting rid of the IDF/legacy bootloader (in fact, I support that), but I thing the changes necessary to run the knsh with simpleboot must be in this same PR.
> 
> why?
> 
> this patch is to make it work with unpatched bootlooder. it works as far as i tested.
> 
> it isn't about simpleboot.

Hi @yamt , 

This commit does not remove the need for the "patched" bootloader (a.k.a IDF bootloader). See: the legacy bootloader (IDF bootloader) is selected by [`CONFIG_ESP32_APP_FORMAT_LEGACY`](https://github.com/apache/incubator-nuttx/blob/91dfd20eafd6cfef338692d20a0159ff25f77b3d/arch/xtensa/src/esp32/Kconfig#L2674), which is selected by default if `CONFIG_BUILD_PROTECTED` is enabled (the case for `esp32-devkitc:knsh`).

Also, as I commented in https://github.com/apache/nuttx/issues/13308#issuecomment-2339015822, the HW testing of  the `knsh` is failing (device panics). I tried applying this patch and the result is the same.

I support/encourage getting rid of the `CONFIG_ESP32_APP_FORMAT_LEGACY` and use the simpleboot for `CONFIG_BUILD_PROTECTED`, but this requires reworking the associated linker scripts and testing. This commit does not do that by itself.

**Comment by yamt** [comment]
> > > This patch wouldn't work by itself, right? I meant: it would not remove the need of the IDF bootloader, right?
> > > I'm not against getting rid of the IDF/legacy bootloader (in fact, I support that), but I thing the changes necessary to run the knsh with simpleboot must be in this same PR.
> > 
> > 
> > why?
> > this patch is to make it work with unpatched bootlooder. it works as far as i tested.
> > it isn't about simpleboot.
> 
> Hi @yamt ,
> 
> This commit does not remove the need for the "patched" bootloader (a.k.a IDF bootloader). See: the legacy bootloader (IDF bootloader) is selected by [`CONFIG_ESP32_APP_FORMAT_LEGACY`](https://github.com/apache/incubator-nuttx/blob/91dfd20eafd6cfef338692d20a0159ff25f77b3d/arch/xtensa/src/esp32/Kconfig#L2674), which is selected by default if `CONFIG_BUILD_PROTECTED` is enabled (the case for `esp32-devkitc:knsh`).
> 
> Also, as I commented in [#13308 (comment)](https://github.com/apache/nuttx/issues/13308#issuecomment-2339015822), the HW testing of the `knsh` is failing (device panics). I tried applying this patch and the result is the same.
> 
> I support/encourage getting rid of the `CONFIG_ESP32_APP_FORMAT_LEGACY` and use the simpleboot for `CONFIG_BUILD_PROTECTED`, but this requires reworking the associated linker scripts and testing. This commit does not do that by itself.

i don't understand why you insist to associate this PR to simpleboot.
this PR is NOT about simpleboot.

without this PR, we need a patched version of esp-idf bootloader.
with this PR, we can use the plain esp-idf bootloader.

although i'm not sure what exactly you mean by "the HW testing", i tested this on a real board.

**Comment by yamt** [comment]
> > > > > This patch wouldn't work by itself, right? I meant: it would not remove the need of the IDF bootloader, right?
> > > > > I'm not against getting rid of the IDF/legacy bootloader (in fact, I support that), but I thing the changes necessary to run the knsh with simpleboot must be in this same PR.
> > > > 
> > > > 
> > > > why?
> > > > this patch is to make it work with unpatched bootlooder. it works as far as i tested.
> > > > it isn't about simpleboot.
> > > 
> > > 
> > > Hi @yamt ,
> > > This commit does not remove the need for the "patched" bootloader (a.k.a IDF bootloader). See: the legacy bootloader (IDF bootloader) is selected by [`CONFIG_ESP32_APP_FORMAT_LEGACY`](https://github.com/apache/incubator-nuttx/blob/91dfd20eafd6cfef338692d20a0159ff25f77b3d/arch/xtensa/src/esp32/Kconfig#L2674), which is selected by default if `CONFIG_BUILD_PROTECTED` is enabled (the case for `esp32-devkitc:knsh`).
> > > Also, as I commented in [#13308 (comment)](https://github.com/apache/nuttx/issues/13308#issuecomment-2339015822), the HW testing of the `knsh` is failing (device panics). I tried applying this patch and the result is the same.
> > > I support/encourage getting rid of the `CONFIG_ESP32_APP_FORMAT_LEGACY` and use the simpleboot for `CONFIG_BUILD_PROTECTED`, but this requires reworking the associated linker scripts and testing. This commit does not do that by itself.
> > 
> > 
> > i don't understand why you insist to associate this PR to simpleboot. this PR is NOT about simpleboot.
> > without this PR, we need a patched version of esp-idf bootloader. with this PR, we can use the plain esp-idf bootloader.
> > although i'm not sure what exactly you mean by "the HW testing", i tested this on a real board.
> 
> Right, we are probably doing the tests differently: I was unable to build the bootloader and make it work with this patch, please describe how you did it using it. What do you mean by ` we can use the plain esp-idf bootloader.`?

* i built the bootloader (and partition table) in esp-idf directly. (it was a bit ago and i don't remember the exact build proceduce.)
* because i haven't built the bootloader using nuttx's "make bootloader", the bootloader i'm using does not have this patch. https://github.com/apache/nuttx/blob/master/arch/xtensa/src/esp32/bootloader/0001-esp32-Connect-Xtensa-Instruction-RAM1-to-Cache.patch
* i used "make flash ESPTOOL_BINDIR=./esp/bin ESPTOOL_PORT=/dev/tty.SLAB_USBtoUART" to build and flash nuttx, whele ./esp/bin contains the bootloader and partition table mentioned above.

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by yamt** [comment]
> Thanks for reporting! It's important to make this patch to work within NuttX too. Officially, `make bootloader` is required to build the legacy bootloader and, by doing that, it would apply the patch you mentioned in the 2nd argument.
> 
> After some debugging, I figured out that this PR is able to make it work with some modifications in `Bootloader.mk` and in the defconfig. I also suggest some minor fixes too. Can you please apply the following patch:

i understand the Bootloader.mk change.
but is the defconfig change related to this PR?

**Comment by yamt** [comment]
> > Thanks for reporting! It's important to make this patch to work within NuttX too. Officially, `make bootloader` is required to build the legacy bootloader and, by doing that, it would apply the patch you mentioned in the 2nd argument.
> > After some debugging, I figured out that this PR is able to make it work with some modifications in `Bootloader.mk` and in the defconfig. I also suggest some minor fixes too. Can you please apply the following patch:
> 
> i understand the Bootloader.mk change. but is the defconfig change related to this PR?

i applied the bootloader.mk patch.

i guess the defconfig one warrants another PR.

**Review by tmedicci — APPROVED** [review]

**Pull request merged**
