### PR TITLE
arm: Make ARMv5 boards work again

### PR DESCRIPTION
**Pull request by ldube**
## Summary
Fix some bugs found while trying run modern NuttX on an old board.

## Testing
NuttX builds and runs on my board but most of the board support is not in the repo.

### CODE REVIEW

**Comment by ldube** [comment]
@acassis Please check if this fixes #8966.

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by xiaoxiang781216** [comment]
@ldube thanks to fix this long-time regression.

**Comment by acassis** [comment]
@ldube I just tested it on LPC2378 following these steps: https://acassis.wordpress.com/2023/04/01/testing-nuttx-again-on-olimex-lpc2378-stk-board/ and same issue, board does start

**Comment by acassis** [comment]
What board did you use?

**Comment by ldube** [comment]
https://en.wikipedia.org/wiki/NSLU2

**Comment by ldube** [comment]
I think arm_decodeirq needs to be updated. The return value is important. If nothing changes, you return the argument instead of NULL. I do not call irq_dispatch directly. That is done by arm_doirq.
Here is my arm_decodeirq:

uint32_t *arm_decodeirq(uint32_t *regs)
{
#ifdef CONFIG_SUPPRESS_INTERRUPTS
  err("ERROR: Unexpected IRQ\n");
  PANIC();
#else

  unsigned int irq_enc = ic_getreg32(INTR_IRQ_ENC_ST_OFFSET) >> 2;
  if (irq_enc != 0)
    {
      unsigned int irq = irq_enc - 1;
      /* Verify that the resulting IRQ number is valid */
      if (irq < NR_IRQS)
        {
          /* Deliver the IRQ */
          regs = arm_doirq(irq, regs);
        }
    }
#endif
  return regs;
}

**Comment by acassis** [comment]
Hi @ldube thank you very much!
That NSLU2 device is really nice. If you can, please submit the board support to mainline. I'll buy one from eBay.

**Pull request merged**
