### PR TITLE
sim/rpserver_virtio: Fix the defconfig

### PR DESCRIPTION
**Pull request by lupyuen**
## Summary

The defconfig for `sim:rpserver_virtio` needs to be updated due to
- https://github.com/apache/nuttx/pull/15336

This PR updates the defconfig for `sim:rpserver_virtio`:
```bash
tools/refresh.sh --silent sim:rpserver_virtio
```

## Impact

This PR fixes the defconfig check for `sim:rpserver_virtio` in CI Job sim-03.

### Before The PR

`sim:rpserver_virtio` fails the defconfig check in CI Job sim-03:
https://github.com/NuttX/nuttx/actions/runs/12548591697/job/34988156883#step:7:380
```text
Configuration/Tool: sim/rpserver_virtio
  Normalize sim/rpserver_virtio
< CONFIG_BLK_RPMSG_SERVER=y
< CONFIG_CLK_RPMSG=y
< CONFIG_DEV_RPMSG_SERVER=y
< CONFIG_EXAMPLES_RPMSGSOCKET=y
< CONFIG_FS_RPMSGFS_SERVER=y
< CONFIG_IOEXPANDER_RPMSG=y
< CONFIG_NET_RPMSG=y
< CONFIG_NET_RPMSG_DRV=y
< CONFIG_NET_USRSOCK_RPMSG_SERVER=y
< CONFIG_OPENAMP_DEBUG=y
< CONFIG_REGULATOR_RPMSG=y
< CONFIG_RPMSGMTD_SERVER=y
< CONFIG_RPMSG_PING=y
< CONFIG_RPMSG_UART=y
< CONFIG_RPMSG_VIRTIO=y
< CONFIG_RTC_RPMSG=y
< CONFIG_RTC_RPMSG_SERVER=y
< CONFIG_SENSORS_RPMSG=y
< CONFIG_SIM_RPMSG_MASTER=y
< CONFIG_SYSLOG_RPMSG_SERVER=y
< CONFIG_UINPUT_RPMSG=y
```

### After The PR

`sim:rpserver_virtio` completes the defconfig check successfully for sim-03:
https://gist.github.com/lupyuen/7911775fdba6400d3ee2fa4242e31f85
```bash
sudo docker run \
  -it \
  ghcr.io/apache/nuttx/apache-nuttx-ci-linux:latest \
  /bin/bash
cd
git clone https://github.com/lupyuen2/wip-nuttx nuttx --branch rpserver_virtio
git clone https://github.com/apache/nuttx-apps apps
pushd nuttx ; echo NuttX Source: https://github.com/apache/nuttx/tree/$(git rev-parse HEAD) ; popd
pushd apps  ; echo NuttX Apps: https://github.com/apache/nuttx-apps/tree/$(git rev-parse HEAD) ; popd
cd nuttx/tools/ci
./cibuild.sh -c -A -N -R testlist/sim-03.dat 

Configuration/Tool: sim/rpserver_virtio
  Normalize sim/rpserver_virtio
```

CI Job sim-03 still fails due to `sim:rpproxy_virtio`, it will be fixed later:
- https://github.com/apache/nuttx/pull/15336#issuecomment-2566073980

### CODE REVIEW

**Comment by nuttxpr** [comment]
[**\[Experimental Bot, please feedback here\]**](https://github.com/search?q=repo%3Aapache%2Fnuttx+13552&type=issues)



This PR description mostly meets the NuttX requirements, but could be slightly improved.

**Strengths:**

* **Clear Summary:**  Explains the "why" (broken defconfig), "what" (updating defconfig), and "how" (using `refresh.sh`).  The link to the related PR is helpful.
* **Specific Impact:** Clearly identifies the impact on CI and the specific job affected.
* **Detailed Testing:** Provides links and log snippets to demonstrate the before/after behavior. The Gist for "after" is especially useful.  The explanation of the remaining `sim:rpproxy_virtio` failure is also important context.

**Areas for Improvement:**

* **Summary: Functional Area:**  While it mentions defconfig, it could be more specific about the functional area of the code. E.g., "Build System (defconfig for sim:rpserver_virtio)".
* **Impact:  Be Explicit with NOs:** Instead of just mentioning the one impact, explicitly state "NO" for all other impacts (build process, hardware, documentation, security, compatibility). This makes it easier for reviewers to quickly assess the scope of the change.
* **Testing: Local Setup:** While you provide CI logs, the "Build Host(s)" and "Target(s)" sections aren't filled out.  Even if testing is primarily done in CI, mention the local environment where the `refresh.sh` script was run.  Something like: "Build Host: Linux, x86_64, GCC (Docker image ghcr.io/apache/nuttx/apache-nuttx-ci-linux:latest)". Target is "sim".
* **Testing Logs:  Conciseness:** The "after" log is very short, which is good.  The "before" log could be trimmed down to the essential parts showing the failure.  The important part is the diff showing the missing config options.

**Suggested Revision (incorporating the above improvements):**

## Summary

This PR fixes the build system by updating the defconfig for `sim:rpserver_virtio`, which was broken by changes introduced in https://github.com/apache/nuttx/pull/15336.  This update is performed using the `refresh.sh` script.

## Impact

* Is new feature added? NO
* Is existing feature changed? NO
* Impact on user (will user need to adapt to change)? NO
* Impact on build (will build process change)? NO
* Impact on hardware (will arch(s) / board(s) / driver(s) change)? NO
* Impact on documentation (is update required / provided)? NO
* Impact on security (any sort of implications)? NO
* Impact on compatibility (backward/forward/interoperability)? NO
* Anything else to consider? This PR fixes the defconfig check for `sim:rpserver_virtio` in CI Job sim-03. CI Job sim-03 still fails due to `sim:rpproxy_virtio`, which will be addressed in a separate PR.

## Testing

I confirm that changes are verified and works as intended:
* Build Host(s): Linux, x86_64, GCC (Docker image ghcr.io/apache/nuttx/apache-nuttx-ci-linux:latest)
* Target(s): sim

Testing logs before change (showing missing config options):

```
< CONFIG_BLK_RPMSG_SERVER=y
< CONFIG_CLK_RPMSG=y
...  (other missing options)
```

Testing logs after change (showing successful normalization):
```bash
Configuration/Tool: sim/rpserver_virtio
  Normalize sim/rpserver_virtio
```


By making these small adjustments, the PR becomes even clearer and easier for reviewers to process.  It explicitly addresses all the required points in a concise and organized way.

**Review by acassis — APPROVED** [review]

**Comment by acassis** [comment]
@lupyuen I think you need to normalize other sim board configs as well, please look the error message!

**Comment by lupyuen** [comment]
@acassis I think you meant `sim:rpproxy_virtio`? We need to fix the build here:
- https://github.com/apache/nuttx/pull/15336#issuecomment-2566073980

**Comment by CV-Bowen** [comment]
@lupyuen @acassis Hi, I create a PR (https://github.com/apache/nuttx/pull/15395) to fix the rpmsg_virtio compile error after we rename the rpmsg_virtio.c to rpmsg_virtio_lite.c (https://github.com/apache/nuttx/pull/15336)
CC @xiaoxiang781216

**Comment by lupyuen** [comment]
sim-03 build is OK now, no need for this PR. Thanks everyone, have an awesome new year :-)
https://github.com/NuttX/nuttx/actions/runs/12559257073/job/35014757100

**Pull request closed without merging**
