### PR TITLE
Update v4l2m2m interface & create videoio.h

### PR DESCRIPTION
**Pull request by shizhenghui**
## Update v4l2m2m interface & create videoio.h

1. Copy part of linux videodev2.h which is used in v4l2m2m
2. Move userspace interface from nuttx/video/video.h to include/sys/videoio.h

## Impact

N/A

## Testing

CI

### CODE REVIEW

**Comment by acassis** [comment]
@shizhenghui what is the purpose of this command:
```
ffmpeg -vcodec h264_v4l2m2m -i /stream/333.mp4 -pix_fmt rgb32 -f fbdev /dev/fb0
```

I assume it is only used on Linux side, since we don't have ffmpeg ported.

Please include more information and documentation about how to use video support on NuttX

**Comment by xiaoxiang781216** [comment]
> @shizhenghui what is the purpose of this command:
> 
> ```
> ffmpeg -vcodec h264_v4l2m2m -i /stream/333.mp4 -pix_fmt rgb32 -f fbdev /dev/fb0
> ```
> 
> I assume it is only used on Linux side, since we don't have ffmpeg ported.
> 

Xiaomi made a porting two years ago.

> Please include more information and documentation about how to use video support on NuttX

this is the first step, m2m driver and documentation will provide in the next step.

**Comment by shizhenghui** [comment]
> @shizhenghui what is the purpose of this command:
> 
> ```
> ffmpeg -vcodec h264_v4l2m2m -i /stream/333.mp4 -pix_fmt rgb32 -f fbdev /dev/fb0
> ```
> 
> I assume it is only used on Linux side, since we don't have ffmpeg ported.
> 
> Please include more information and documentation about how to use video support on NuttX

**Comment by acassis** [comment]
@xiaoxiang781216 is it possible to submit the ffmpeg port to mainline or we need to wait for h264_v4l2m2m support first?

**Comment by xiaoxiang781216** [comment]
> @xiaoxiang781216 is it possible to submit the ffmpeg port to mainline or we need to wait for h264_v4l2m2m support first?

it will open source publicly within 6 months.

**Pull request closed without merging**
