### PR TITLE
rv-virt/configs: avoid build errors with cmake or stock gcc 10.2

### PR DESCRIPTION
**Pull request by yf13**
## Summary

Revised rv-virt/nsh and rv-virt/nsh64 defconfigs for  following changes:

- disable NSH_SYMTAB to avoid build errors with cmake system.
- enable LIBM to avoid build errors with stock `gcc-riscv64-unknown-elf` toolchain and makefile system.
- use HELLO=y for easy use within qemu console.

## Impact

rv-virt/nsh and rv-virt/nsh64 

## Testing

checked `rv-virt/nsh` and `rv-virt/nsh64` on Linux

### CODE REVIEW

**Comment by pkarashchenko** [comment]
I'm not sure about the libm change. I think by "stock" you mean the Ubuntu package of some version? I'm really not sure that we should be tight to the particular version of a toolchain.

**Comment by yf13** [comment]
@pkarashchenko 

Yes I mean the `gcc-riscv64-unknown-elf` toolchain on Ubuntu  Jammy, which is easy to install via `apt`. actually I checked both that toolchain and the xpack toolchain 13.2, they both working fine with makefile system during my check. So this PR is not to tight to that particular version, it actually enables more toolchains lacking libm.

**Comment by yf13** [comment]
@pkarashchenko 

Yes I mean the `gcc-riscv64-unknown-elf` toolchain on Ubuntu  Jammy, which is easy to install via `apt`. actually I checked both Ubuntu toolchain and the xpack toolchain 13.2, they both are fine when using makefile system during my check. 

So this PR is not to tight to a particular toolchain, it is just to enable more.

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by anchao** [comment]
Maybe you can migrate the ci of rv-virt/nsh(64) to cmake? 
https://github.com/apache/nuttx/blob/master/tools/ci/testlist/risc-v.dat

**Comment by yf13** [comment]
@anchao I am unfamiliar with the CI stuffs, but I will try to make `rv-virt/nsh(64)` work with CMake+gcc-10.2 later.

BTW, do you know why my local run of "tools/refresh.sh --silent" failed to catch errors related to "NSH_SYMTAB_ARRAYNAME"? is the "tools/refresh.sh" in CI different from the one on "master"?

**Comment by anchao** [comment]
> BTW, do you know why my local run of "tools/refresh.sh --silent" failed to catch errors related to "NSH_SYMTAB_ARRAYNAME"? is the "tools/refresh.sh" in CI different from the one on "master"?


No difference AFAIK. CI also uses this script. You could try to run the issued board configuration separately.
`./tools/refresh.sh --silent rv-virt/nsh`

**Review by anchao — APPROVED** [review]

**Comment by yf13** [comment]
@anchao I am unfamiliar with the CI stuffs, but I will try to make `rv-virt/nsh(64)` work with CMake later.

BTW, do you know why my local run of "tools/refresh.sh --silent" missed errors related to "NSH_SYMTAB_ARRAYNAME"? is the tool in CI different?

**Review by jerpelea — APPROVED** [review]

**Comment by masayuki2009** [comment]
@yf13 

>use HELLO=y for easy use within qemu console.

It seems that `rv-virt:nsh64` is not modified to use CONFIG_EXAMPLES_HELLO=y

>checked rv-virt/nsh and rv-virt/nsh64 on Linux

Did you test the hello app with rv-virt:nsh64?
Actually, it crashed with qemu-8.2.0

And, in my understanding, this PR is a tentative solution to avoid the cmake error.
I think once the error is fixed, this PR should be reverted.

**Pull request merged**
