### PR TITLE
Revert "Exec: Support run exec in current task"

### PR DESCRIPTION
**Pull request by masayuki2009**
Reverts apache/nuttx#10380 since the PR has an issue with CONFIG_DEBUG_ASSERTIONS=y

### CODE REVIEW

**Review by pkarashchenko — APPROVED** [review]

**Comment by acassis** [comment]
@masayuki2009 maybe instead of Revert it, they could send a fast fix. @xiaoxiang781216 what do you think?

**Comment by masayuki2009** [comment]
>@masayuki2009 maybe instead of Revert it, they could send a fast fix.

Hmm, my automatic tests have been failing for over 23 hours due to the issue.

**Comment by pkarashchenko** [comment]
Let's merge and give more time to evaluate the solution

**Comment by xiaoxiang781216** [comment]
> > @masayuki2009 maybe instead of Revert it, they could send a fast fix.
> 
> Hmm, my automatic tests have been failing for over 23 hours due to the issue.

Could you integrate your automatic test into ci workflow? It will help to catch the error before merging in the future.

**Pull request merged**
