### PR TITLE
Usb: add sim usb device and host driver

### PR DESCRIPTION
**Pull request by zyfeier**
## Summary

SIM USBDEV
===========================

Use Linux Raw Gadget and Dummy UDC to set up virtual USB device;

Raw Gadget setup
------------

Get Raw Gadget:
Get Raw Gadget code at https://github.com/xairy/raw-gadget.

Make Raw Gadget:
Run make in the raw_gadget and dummy_hcd directory. If raw_gadget build fail, you need to check which register interface meets your kenel version, usb_gadget_probe_driver or usb_gadget_register_driver.

Install Raw Gadget:
Run ./insmod.sh in the raw_gadget and dummy_hcd directory.

Configuration
-------------

sim:usbdev contains two different sets of composite devices.

     conn0: adb & rndis
     conn1: cdcacm & cdcecm

You can use the sim:usbdev configuration;

    ./tools/configure.sh sim:usbdev

How to run
----------

Run nuttx with root mode, then you can use it as the following:

For example run ADB:

    $ conn 0
    $ adbd &

Host PC enter the adb command:

    $ adb devices
    List of devices attached
    * daemon not running; starting now at tcp:5037
    * daemon started successfully
    0101        device

SIM USBHOST
===========================

Simulate USB Host using libusb,  it's possible to connect simulated USB devices and real USB devices based on the configured VID and PID.  At this stage, only one USB device can be connected.

Libusb1.0 setup
------------

    $ sudo apt-get -y install libusb-1.0-0-dev
    $ sudo apt-get -y install libusb-1.0-0-dev:i386

Configuration
-------------

sim:usbhost support cdcacm.

You can use the sim:usbdev configuration:

    ./tools/configure.sh sim:usbhost

How to run
----------

Run sim usbhost with root mode, run sim usbdev or plug-in cdcacm usb device.
Then you can use /dev/ttyACM to transfer data.

## Impact

NA

## Testing

sim:usbdev sim:usbhost test adb, rndis, cdcacm, cdcecm.

### CODE REVIEW

**Comment by xiaoxiang781216** [comment]
@zyfeier create a separate PR to install libusb package:
https://github.com/apache/nuttx/blob/master/tools/ci/docker/linux/Dockerfile#L251

**Comment by acassis** [comment]
@zyfeier are you planing to add some driver examples implementing a USB device? It should be a good idea

**Comment by xiaoxiang781216** [comment]
let's add some instruction in sim README.txt about the new usbdev/usbhost config:
https://github.com/apache/nuttx/blob/master/boards/sim/sim/sim/README.txt#L563

**Comment by acassis** [comment]
> let's add some instruction in sim README.txt about the new usbdev/usbhost config: https://github.com/apache/nuttx/blob/master/boards/sim/sim/sim/README.txt#L563

Please don't! Use the Documentation, we need to phase out these README.txt file since we didn't find a way to automatically get content of README.txt to feed the Documentation.

**Comment by zyfeier** [comment]
> @zyfeier are you planing to add some driver examples implementing a USB device? It should be a good idea

@acassis This is a good idea, and I'll add some examples after this PR submitted.

**Comment by btashton** [comment]
I noticed that we are running out of space again on the docker image build/push so I don't think the image got updated :(. I think I know how to free up some more space on the worker that I can try this evening.  Otherwise I can manually push the updated image for the short term.

**Comment by xiaoxiang781216** [comment]
> I noticed that we are running out of space again on the docker image build/push so I don't think the image got updated :(. I think I know how to free up some more space on the worker that I can try this evening. Otherwise I can manually push the updated image for the short term.

Thanks @btashton , let's wait your try if the result isn't good please update the image manuaully to unblock this PR.

**Comment by xiaoxiang781216** [comment]
@btashton do you have progress, thanks?

**Comment by btashton** [comment]
> @btashton do you have progress, thanks?

Sorry for the delay. Let's see if this works, it looks like it frees up about 13GB.

https://github.com/apache/nuttx/pull/8680

**Comment by xiaoxiang781216** [comment]
> > @btashton do you have progress, thanks?
> 
> Sorry for the delay. Let's see if this works, it looks like it frees up about 13GB.
> 
> #8680

Thanks! @btashton

**Review by acassis — APPROVED** [review]

**Pull request merged**
