### PR TITLE
build.yml[bugfix]:disable CMake Ninja for Msys2

### PR DESCRIPTION
**Pull request by xuxin930**
## Summary

CI in the msys2 environment, the CMake ninja generator will have a problem with parameters being too long

## Impact

Msys2

## Testing

Ci build

### CODE REVIEW

**Review by xiaoxiang781216 — APPROVED** [review]

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by anchao** [comment]
Why not fix this issue directly? Ninja will be much faster than Makefile backend(CMake)

**Comment by simbit18** [comment]
Hi, before we disable -N on Msys2, let's try to solve the error.

I cannot help you now, I will be able to look for a solution on Thursday of next week.

I don't know if this way can help

**CMake variable CMAKE_NINJA_FORCE_RESPONSE_FILE to ON.**

https://cosylab.com/technology/a-compact-and-fast-build-system-fit-for-a-ninja/

**Comment by xuxin930** [comment]
> > **CMake variable CMAKE_NINJA_FORCE_RESPONSE_FILE to ON.**
> 
> thanks @simbit18
> 
> I tried to create an Msys2 environment and set CMAKE_NINJA_FORCE_RESPONSE_FILE
> 
> The result is that the rsp file seems to be generated and the length of the compilation command is indeed shortened. But it seems that the compiler cannot recognize it. Is this because we are using mingw compilation?
> 

I may be right. In Ubuntu, gnu_gcc can correctly identify the rsp file, but mingw_gcc fails to do so. :-(

**Comment by xiaoxiang781216** [comment]
@simbit18 @anchao before you can provide a method to support ninja on msys2, it's better to disable ninja to unblock Windows Native CI. Patch breaks Windows Native build frequently, so it's important to enable the check as soon as possible.

**Review by anchao — APPROVED** [review]

**Pull request merged**
