### PR TITLE
arch: fixed error in the calculation of nwords caused an out of bounds

### PR DESCRIPTION
**Pull request by zyfeier**
## Summary

 Fixed an error in the calculation of nwords caused an out of bounds.

## Impact

stack

## Testing

ostest pass

### CODE REVIEW

**Comment by pkarashchenko** [comment]
@masayuki2009 can this cause an issue that needs your workaround for stm32discovery?

**Comment by masayuki2009** [comment]
>@masayuki2009 can this cause an issue that needs your workaround for stm32discovery?

@pkarashchenko 
Let me check this PR tomorrow but I think this PR just fixes stack coloring and would not fix the issue on stm32f4discovery because the feature was disabled when I encountered the hardfault on the board.

**Comment by masayuki2009** [comment]
>Let me check this PR tomorrow but I think this PR just fixes stack coloring and would not fix the issue on stm32f4discovery because the feature was disabled when I encountered the hardfault on the board.

I confirmed that this PR does not fix the hardfault issue on stm32f4discovery.
However, this PR would fix the stack coloring issue.

**Review by masayuki2009 — APPROVED** [review]

**Comment by xiaoxiang781216** [comment]
@masayuki2009 could you merge it?

**Review by xiaoxiang781216 — APPROVED** [review]

**Pull request merged**
