### PR TITLE
{Bp-13842} net: Remove IFF_DOWN flag to compatible with Linux/*BSD

### PR DESCRIPTION
**Pull request by jerpelea**
## Summary
turn off interface by checking IFF_UP flag isn't set: https://github.com/apache/nuttx/issues/1838

## Impact
RELEASE

## Testing
CI

### CODE REVIEW

**Comment by jerpelea** [comment]
backport from https://github.com/apache/nuttx/pull/13842

**Comment by jerpelea** [comment]
@lupyuen CI is broken

**Comment by lupyuen** [comment]
@jerpelea Just fixed, please rebase: https://github.com/apache/nuttx/pull/14290

**Comment by jerpelea** [comment]
we are

> @jerpelea Just fixed, please rebase: #14290

the patch is unrelated 
Run echo "::add-matcher::nuttx/.github/nxstyle.json"
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.12/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
Error: Process completed with exit code 1.

**Comment by fdcavalcanti** [comment]
> @acassis @cederom Same error here sigh. Wish I learnt some Python.

Problem is newer Python/pip versions do not allow you to install packages system wide. You must install them inside a virtual environment. I suggest a new issue is opened regarding this, as it only affects linting of Python files.

**Comment by lupyuen** [comment]
@fdcavalcanti Problem is that we are urgently rolling out a new NuttX Release right now. So we need to fix this now ... Or roll back to the earlier version before the fixes?

**Comment by fdcavalcanti** [comment]
> @fdcavalcanti Problem is that we are urgently rolling out a new NuttX Release right now. So we need to fix this now ... Or roll back to the earlier version before the fixes?

Let me try and fix this real quick.

**Comment by lupyuen** [comment]
@jerpelea Sorry I have a terrible, drastic suggestion:
(1) Could we freeze all merging to `master` for a few days
(2) Ask all stakeholders to test `master` on their respective boards
(3) Merge to `master` only the urgent fixes that we need
(4) Release `master` as the New NuttX Release
(5) Because we are seeing too many merges over the past weekend, it might cause more problems. Thank you so much 🙏

**Comment by jerpelea** [comment]
> @jerpelea Sorry I have a terrible, drastic suggestion: (1) Could we freeze all merging to `master` for a few days (2) Ask all stakeholders to test `master` on their respective boards (3) Merge to `master` only the urgent fixes that we need (4) Release `master` as the New NuttX Release (5) Because we are seeing too many merges over the past weekend, it might cause more problems. Thank you so much 🙏

I this that is really not a good idea but if this is the community wish we can go down this rabbit hole

CI Issues
The CI is common for both release branch and master (now broken by a patch merged in the past 20 h)

Release branch facts
1.the release branch compiles fine locally / we need some patches to unblock the release
2.the master patch has more problems than our release branch 

I will let the community decide

**Comment by GUIDINGLI** [comment]
> @jerpelea Sorry I have a terrible, drastic suggestion: (1) Could we freeze all merging to `master` for a few days (`nuttx` and `nuttx-apps`) (2) Ask all stakeholders to test `master` on their respective boards (3) Merge to `master` only the urgent fixes that we need (4) Release `master` as the New NuttX Release (5) Because we are seeing too many merges over the past weekend, it might cause more problems. Thank you so much 🙏

You can lock the master, but not Today, suggest lock from next week.
Because lots of patches are merging to master currently, we plan finish this job at this week.

**Comment by GUIDINGLI** [comment]
After this upload to the community is completed, we plan to upload once a month in the future to ensure that there won't be so many patches uploaded at the same time.

**Comment by lupyuen** [comment]
Yep we should probably sync the NuttX Release Schedule with the Xiaomi Release Schedule. Lesson Learnt: Please try not to release NuttX during the Golden Week Holidays :-)

**Review by xiaoxiang781216 — APPROVED** [review]

**Pull request merged**
