### PR TITLE
Cordic api modify

### PR DESCRIPTION
**Pull request by behappy1234**
Sorry for I wrong closed the PR, and I can not reopen it. 
image

https://github.com/apache/nuttx/pull/10282

@raiden00pl @xiaoxiang781216

### CODE REVIEW

**Comment by raiden00pl** [comment]
Response from the old PR https://github.com/apache/nuttx/pull/10282#issuecomment-1685518888
> Yes, the numerical type for q1.15 is as a default here. I do this, because if I open for MATH_FFT, then math.c is compiled, so cordic.h is included and CONFIG_MATH_CORDIC_USE_Q31 is needed for cordic_num_t to be configed even in this case I don't need to care about cordic. So, CONFIG_MATH_CORDIC_USE_Q31 is "redundant" here, or a default cordic_num_t definition is need. And I remove it as a default one.

If you don't need cordic, then why just not guard all cordic logic with `#ifdef CONFIG_MATH_CORDIC` ? The same applies to the FFT.

**Comment by behappy1234** [comment]
> Response from the old PR [#10282 (comment)](https://github.com/apache/nuttx/pull/10282#issuecomment-1685518888)
> 
> > Yes, the numerical type for q1.15 is as a default here. I do this, because if I open for MATH_FFT, then math.c is compiled, so cordic.h is included and CONFIG_MATH_CORDIC_USE_Q31 is needed for cordic_num_t to be configed even in this case I don't need to care about cordic. So, CONFIG_MATH_CORDIC_USE_Q31 is "redundant" here, or a default cordic_num_t definition is need. And I remove it as a default one.
> 
> If you don't need cordic, then why just not guard all cordic logic with `#ifdef CONFIG_MATH_CORDIC` ? The same applies to the FFT.

understood

**Comment by behappy1234** [comment]
squash the two commits into one.

**Review by jerpelea — APPROVED** [review]
please add commit message

**Comment by behappy1234** [comment]
> please add commit message

Sorry for miss understanding, I have submmit two commits, and the first one is discarded. No more commit message needed.

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by xiaoxiang781216** [comment]
@raiden00pl could you review again?

**Review by raiden00pl — APPROVED** [review]
LGTM. Thanks !

**Pull request merged**
