### PR TITLE
Support defconfig merge

### PR DESCRIPTION
**Pull request by Gary-Hobson**
## Summary
I've added two scripts that can reference the config snippets in different ways

1. process_config allows the use of #include statements in defcnfig, which can reference other config files
2. merge_config supports merging multiple config files into one
    ./tools/merge_config.py -o defconfig .config1 .config2

### CODE REVIEW

**Comment by anchao** [comment]
1. How to split and update statements of defconfig separately?
2. Merge feature depends on kconfig right? Why are there two scripts one is shell and the other is python? I think using python for both has better platform compatibility.

**Comment by Gary-Hobson** [comment]
> 1. How to split and update statements of defconfig separately?
We cannot split into multiple fragments from already merged files

> 2. Merge feature depends on [kconfiglib](https://github.com/ulfalizer/Kconfiglib) right? Why are there two scripts one is shell and the other is python? I think using python for both has better platform compatibility.

merge_config.py:
It has the same function as merge_config in Linux, except that we use python to implement it.、

process_config.sh:
It is actually a simplified preprocessor that only supports include statements.

Because the gcc preprocessor cannot recognize comments starting with #, we use a shell script to implement this function.
My first version was implemented using python, but in order to avoid relying on python during compilation I changed it to a shell script

**Comment by anchao** [comment]
> We cannot split into multiple fragments from already merged files

without split feature, the developer will not be able to correctly tell which configuration needs to be placed in the appropriate place

> Because the gcc preprocessor cannot recognize comments starting with #, we use a shell script to implement this function. My first version was implemented using python, but in order to avoid relying on python during compilation I changed it to a shell script

Please also upload the python version, which can be implement this feature on native windows

**Comment by xiaoxiang781216** [comment]
let's provide python version later, because:

1. All mainline defconfig doesn't use merge functionality yet
2. it seldom to build nuttx on Windows without shell environment

**Comment by acassis** [comment]
I agree it is better not depending on python and the implementation should work for both kconfig-frontends and kconfiglib!

@Gary-Hobson please include some usage instructions at Documentation/ to avoid it becoming a hidden feature

**Comment by Gary-Hobson** [comment]
> I agree it is better not depending on python and the implementation should work for both kconfig-frontends and kconfiglib!
> 
> @Gary-Hobson please include some usage instructions at Documentation/ to avoid it becoming a hidden feature

Done

**Review by xiaoxiang781216 — APPROVED** [review]

**Review by xiaoxiang781216 — APPROVED** [review]

**Pull request merged**
