### PR TITLE
Optimize iic and spi parts and add iic slave drivers

### PR DESCRIPTION
**Pull request by Zhangshoukui**
## Summary
Optimize iic and spi parts and add iic slave drivers
## Impact
iic and spi driver
## Testing

iic and spi driver

### CODE REVIEW

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by acassis** [comment]
@Zhangshoukui nice work!! Kudos!!!

Could you please include a Documentation to I2C Slave at https://nuttx.apache.org/docs/latest/components/drivers/special/index.html at I2C Drivers. The existing documentation is "non-existent", since you are working on it, please help us to improve it.

**Comment by Zhangshoukui** [comment]
> @Zhangshoukui nice work!! Kudos!!!
> 
> Could you please include a Documentation to I2C Slave at https://nuttx.apache.org/docs/latest/components/drivers/special/index.html at I2C Drivers. The existing documentation is "non-existent", since you are working on it, please help us to improve it.

**Comment by Zhangshoukui** [comment]
I updated the submission to add documentation

**Comment by Zhangshoukui** [comment]
@acassis I updated the submission to add documentation

**Review by xiaoxiang781216 — APPROVED** [review]

**Review by xiaoxiang781216 — APPROVED** [review]

**Review by acassis — APPROVED** [review]

**Pull request merged**
