### PR TITLE
Unify the code of libelf and modlib, and delete the implementation of libelf

### PR DESCRIPTION
**Pull request by anjiahao1**
## Summary

Move the special usage of libelf to modlib, enhance and fix bugs in modlib, and then remove the libelf implementation. This will allow us to better reuse the code for dynamic loading

## Impact
Dynamic loading/kernal mode
## Testing
run `rv-virt:knsh` and pass ostest

### CODE REVIEW

**Comment by anjiahao1** [comment]
depends on [app 2696](https://github.com/apache/nuttx-apps/pull/2696)

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by masayuki2009** [comment]
@anjiahao1 

I noticed that getprime crashes with rv-virt:knsh after merging this PR.

```
/home/ishikawa/opensource/QEMU/qemu-9.0.0/build/qemu-system-riscv32 -semihosting -nographic -cpu rv32 -M virt,aclint=on -kernel nuttx

OpenSBI v1.4
   ____                    _____ ____ _____
  / __ \                  / ____|  _ \_   _|
 | |  | |_ __   ___ _ __ | (___ | |_) || |
 | |  | | '_ \ / _ \ '_ \ \___ \|  _ < | |
 | |__| | |_) |  __/ | | |____) | |_) || |_
  \____/| .__/ \___|_| |_|_____/|____/_____|
        | |
        |_|

Platform Name             : riscv-virtio,qemu
Platform Features         : medeleg
Platform HART Count       : 1
Platform IPI Device       : aclint-mswi
Platform Timer Device     : aclint-mtimer @ 10000000Hz
Platform Console Device   : semihosting
Platform HSM Device       : ---
Platform PMU Device       : ---
Platform Reboot Device    : syscon-reboot
Platform Shutdown Device  : syscon-poweroff
Platform Suspend Device   : ---
Platform CPPC Device      : ---
Firmware Base             : 0x80000000
Firmware Size             : 319 KB
Firmware RW Offset        : 0x40000
Firmware RW Size          : 63 KB
Firmware Heap Offset      : 0x47000
Firmware Heap Size        : 35 KB (total), 2 KB (reserved), 9 KB (used), 24 KB (free)
Firmware Scratch Size     : 4096 B (total), 184 B (used), 3912 B (free)
Runtime SBI Version       : 2.0

Domain0 Name              : root
Domain0 Boot HART         : 0
Domain0 HARTs             : 0*
Domain0 Region00          : 0x00100000-0x00100fff M: (I,R,W) S/U: (R,W)
Domain0 Region01          : 0x02000000-0x0200ffff M: (I,R,W) S/U: ()
Domain0 Region02          : 0x80040000-0x8004ffff M: (R,W) S/U: ()
Domain0 Region03          : 0x80000000-0x8003ffff M: (R,X) S/U: ()
Domain0 Region04          : 0x0c400000-0x0c5fffff M: (I,R,W) S/U: (R,W)
Domain0 Region05          : 0x0c000000-0x0c3fffff M: (I,R,W) S/U: (R,W)
Domain0 Region06          : 0x00000000-0xffffffff M: () S/U: (R,W,X)
Domain0 Next Address      : 0x80200000
Domain0 Next Arg1         : 0x87e00000
Domain0 Next Mode         : S-mode
Domain0 SysReset          : yes
Domain0 SysSuspend        : yes

Boot HART ID              : 0
Boot HART Domain          : root
Boot HART Priv Version    : v1.12
Boot HART Base ISA        : rv32imafdch
Boot HART ISA Extensions  : sstc,zicntr,zihpm,zicboz,zicbom
Boot HART PMP Count       : 16
Boot HART PMP Granularity : 2 bits
Boot HART PMP Address Bits: 32
Boot HART MHPM Info       : 16 (0x0007fff8)
Boot HART MIDELEG         : 0x00001666
Boot HART MEDELEG         : 0x00f0b509
ABC
NuttShell (NSH) NuttX-12.0.0
nsh> uname -a
NuttX 12.0.0 b503b323ce Oct 12 2024 15:55:50 risc-v rv-virt
nsh> ps
  PID GROUP PRI POLICY   TYPE    NPX STATE    EVENT     SIGMASK           STACK COMMAND
    0     0   0 FIFO     Kthread   - Ready              0000000000000000 0003056 Idle_Task
    1     0 100 RR       Kthread   - Waiting  Semaphore 0000000000000000 0001984 lpwork 0x80600010 0x80600034
    2     2 100 RR       Task      - Running            0000000000000000 0003024 /system/bin/init
nsh> free
      total       used       free    maxused    maxfree  nused  nfree name
    4164028      17236    4146792     716368    3448016    343      5 Kmem
    4194304     606208    3588096    3588096 Page
nsh> hello
Hello, World!!
nsh> getprime
[1846835937280000.001000] dump_assert_info: Current Version: NuttX  12.0.0 b503b323ce Oct 12 2024 15:55:48 risc-v
[1846835937280000.001000] dump_assert_info: Assertion failed : at file: misc/lib_envpath.c:167 task: /system/bin/init process: /system/bin/init 0xc000001a
[1846835937280000.001000] up_dump_register: EPC: 802129ae
[1846835937280000.001000] up_dump_register: A0: 80606780 A1: 000000a7 A2: 00000000 A3: 00000000
[1846835937280000.001000] up_dump_register: A4: 00000002 A5: 00000000 A6: ffffffff A7: 00000001
[1846835937280000.001000] up_dump_register: T0: 00000000 T1: ffff0000 T2: 00000000 T3: 00000000
[1846835937280000.001000] up_dump_register: T4: 00030001 T5: c0802a54 T6: 00000000
[1846835937280000.001000] up_dump_register: S0: 80606000 S1: 00000000 S2: 00000000 S3: 00042022
[1846835937280000.001000] up_dump_register: S4: 80607000 S5: 00000006 S6: 80607000 S7: 8021ad94
[1846835937280000.001000] up_dump_register: S8: 000000a7 S9: 80608808 S10: c000e000 S11: 00000000
[1846835937280000.001000] up_dump_register: SP: 80609254 FP: 80606000 TP: 80608808 RA: 802129ae

```

**Comment by nuttxpr** [comment]
Sorry @anjiahao1 I'm also having problems with knsh64: https://gist.github.com/lupyuen/5bfa7af7e2927e7fd1ba7b65e8c405e5
```text
$ git reset --hard 56aa628eeca4d96d80eba21a90656f17f771a451
HEAD is now at 56aa628eec binfmt_loadmodule.c:fix build break
...
$ qemu-system-riscv64 -semihosting -M virt,aclint=on -cpu rv64 -kernel nuttx -nographic
QEMU emulator version 9.0.2
OpenSBI v1.4
ABC
dump_assert_info: Current Version: NuttX  12.7.0-RC0 56aa628eec Oct 13 2024 13:07:08 risc-v
dump_assert_info: Assertion failed : at file: init/nx_bringup.c:381 task: Idle_Task process: Kernel 0x80200fda
```
The previous commit works OK: https://gist.github.com/lupyuen/c6a32aab4ba186c53ffc4c1150541a8b

Any idea why this is failing? Thanks!

**Comment by lupyuen** [comment]
Sorry @anjiahao1 I'm also having problems with knsh64: https://gist.github.com/lupyuen/5bfa7af7e2927e7fd1ba7b65e8c405e5
```text
$ git reset --hard 56aa628eeca4d96d80eba21a90656f17f771a451
HEAD is now at 56aa628eec binfmt_loadmodule.c:fix build break
...
$ qemu-system-riscv64 -semihosting -M virt,aclint=on -cpu rv64 -kernel nuttx -nographic
QEMU emulator version 9.0.2
OpenSBI v1.4
ABC
dump_assert_info: Current Version: NuttX  12.7.0-RC0 56aa628eec Oct 13 2024 13:07:08 risc-v
dump_assert_info: Assertion failed : at file: init/nx_bringup.c:381 task: Idle_Task process: Kernel 0x80200fda
```
The previous commit works OK: https://gist.github.com/lupyuen/c6a32aab4ba186c53ffc4c1150541a8b

Any idea why this is failing? Thanks!

**Comment by xiaoxiang781216** [comment]
@anjiahao1 please take a look.

**Comment by anjiahao1** [comment]
Ok, I will fix this problem today.

**Comment by anjiahao1** [comment]
https://github.com/apache/nuttx/pull/14205 @lupyuen @masayuki2009  hello, this pr fix it

**Comment by tmedicci** [comment]
Hi @anjiahao1 , we are facing problems on ESP32-S3 caused by this PR too I created an issue https://github.com/apache/nuttx/issues/14487 Could you please take a look?

**Comment by tmedicci** [comment]
> Hi @anjiahao1 , we are facing problems on ESP32-S3 caused by this PR too I created an issue #14487 Could you please take a look?

Hi @anjiahao1 , did you see this too?

**Comment by anjiahao1** [comment]
> > Hi @anjiahao1 , we are facing problems on ESP32-S3 caused by this PR too I created an issue #14487 Could you please take a look?
> 
> Hi @anjiahao1 , did you see this too?

Sorry, I have some things to deal with during the week. I will fix this problem on Friday.

**Pull request merged**
