### PR TITLE
NuttX graduated the Incubator; update repository links

### PR DESCRIPTION
**Pull request by hartmannathan**
## Summary

NuttX has graduated the Incubator and the repositories will be renamed to remove the `incubator-` prefix.

This PR updates all links, documentation, etc., to the new names.

Note: Please DO NOT MERGE until Infra has renamed the repositories.

See the Infra Jira ticket: https://issues.apache.org/jira/browse/INFRA-23935

## Impact

Affects GitHub workflows.

## Testing

N/A

### CODE REVIEW

**Comment by lucasssvaz** [comment]
Isn't it better to leave the PR as a draft until they renamed the repos ? Just to avoid any headaches by an accidental merge :)

**Comment by hartmannathan** [comment]
> Isn't it better to leave the PR as a draft until they renamed the repos ? Just to avoid any headaches by an accidental merge :)

Good idea. I'll do that now.

**Comment by acassis** [comment]
@hartmannathan I think now it can me merged

**Comment by hartmannathan** [comment]
> @hartmannathan I think now it can me merged

@acassis Yay! I will mark it ready for review.

Please check carefully: this patch affects the GitHub workflows!!

Hopefully the tests will pass now that the repos were actually renamed.

See also:
https://github.com/apache/incubator-nuttx-apps/pull/1437
https://github.com/apache/incubator-nuttx-website/pull/80

**Comment by hartmannathan** [comment]
@btashton The checks are failing even though the repositories have been renamed. Do you know what else needs to be updated to make the checks pass again?

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by hartmannathan** [comment]
@xiaoxiang781216 The checks appear to be broken and I am not sure what is missing. Does this usually happen when modifying the workflow scripts?

**Comment by btashton** [comment]
There are a couple details that we may need to fix. I'm not sure the container reference will magically work without pushing a new one (possibly it will). The checks are failing here because they could not clone from the new location which is strange, I will trigger them again.

**Comment by btashton** [comment]
Looks like we just need to sort the build image out. I'll do that this morning.

**Comment by btashton** [comment]
@hartmannathan I will need to do some more work to get this done.  We can either leave the container alone in this PR for now (just reference the images) which will let this pass, or we can wait for me to make the changes required to associate a new container with this repository.

**Comment by hartmannathan** [comment]
> @hartmannathan I will need to do some more work to get this done. We can either leave the container alone in this PR for now (just reference the images) which will let this pass, or we can wait for me to make the changes required to associate a new container with this repository.

@btashton I appreciate the help. I don't know where to find the container, let alone where to begin! I think it's better to wait for the required changes. This way, we will know that everything will work properly and we won't leave loose ends.

**Comment by btashton** [comment]
@hartmannathan I think we should be good now (no changes to this PR required) long as the test pass. I have restarted CI for both this PR and the on in nuttx-apps.  They are now able to pull the new image.  This build container is not associated with the repo right now (just Apache and me), but we can fix that in a follow on PR if it does not get fixed by the push action when the CI runs on trunk with this change.

**Comment by hartmannathan** [comment]
@btashton Thanks for all your help on this!

**Pull request merged**
