### PR TITLE
enable sigpause test for open posix

### PR DESCRIPTION
**Pull request by fxysunshine**
## Summary
enable sigpause test,  https://github.com/apache/nuttx/pull/11916 break several case and revert it.

## Impact
none

## Testing
open posix ci

### CODE REVIEW

**Comment by xiaoxiang781216** [comment]
@anchao could you take look? https://github.com/apache/nuttx/pull/11916 break several LTP signal test cases.

**Comment by xiaoxiang781216** [comment]
@fxysunshine test_ltp_interfaces_pthread_rwlock_timedrdlock_3_1 fail?

**Comment by anchao** [comment]
> @anchao could you take look? #11916 break several LTP signal test cases.

I will take a look today

**Comment by anchao** [comment]
@xiaoxiang781216 @fxysunshine  please review PR: https://github.com/apache/nuttx/pull/11997

**Comment by fxysunshine** [comment]
workaround, do not NEED.

**Pull request closed without merging**
