### PR TITLE
ISSUE_TEMPLATE: fix missing labels

### PR DESCRIPTION
**Pull request by simbit18**
## Summary

Not all labels are added because there is no match with the label name.

issue_labeler.yml
os: Linux -> os: linux

001_bug_report.yml
Type: bug -> Type: Bug
Corrected label in links

002_feature_request.yml
Type: enhancement -> Type: Enhancement
Corrected label in links

003_help.yml
Type: question -> Community: Question
Corrected label in links

## Impact
Impact on user: No changes to user-facing functionality
Impact on build: Build process remains the same

## Testing
CI
https://github.com/simbit18/nuttx-testing-templates/issues

### CODE REVIEW

**Comment by nuttxpr** [comment]
[**\[Experimental Bot, please feedback here\]**](https://github.com/search?q=repo%3Aapache%2Fnuttx+13552&type=issues)



This PR makes minor changes to the issue templates to correct typos and capitalization inconsistencies in labels. 

**Does it meet the requirements?** 

Mostly. Here's a breakdown:

* **Summary:** ✅ Provides a clear reason for the change and what was modified.
* **Impact:** 
    * ✅  Accurately identifies no user-facing changes.
    * ✅  Correctly states no build process changes.
    * ➖ Could explicitly state "NO" for all other impact categories for completeness.
* **Testing:**
    * ⚠️  Relies solely on CI testing. While CI is important, providing _some_ local testing details, even if minimal, would strengthen the PR. Ideally, include examples of commands used to validate the template changes.

**Recommendations:**

1. **Explicitly state "NO" for all other impact categories.**  This leaves no room for ambiguity.
2. **Add brief local testing details.**  Even simple commands showing template usage demonstrate thoroughness. 
3. **Consider adding a screenshot of the updated template in the PR description.** This makes it easier for reviewers to visualize the changes without having to check out the code.

**Review by raiden00pl — APPROVED** [review]

**Comment by simbit18** [comment]
@raiden00pl missing label  **Type: Question** can you add ?

https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/managing-labels#creating-a-label

**Comment by raiden00pl** [comment]
what about this: https://github.com/apache/nuttx/labels/Community%3A%20Question ?

**Comment by simbit18** [comment]
for 003_help.yml

https://github.com/apache/nuttx/blob/35c278b716f7ffb3347395b8dc9bb31cc304093f/.github/ISSUE_TEMPLATE/003_help.yml?plain=1#L16

**Comment by raiden00pl** [comment]
can we change this to `Community: Question` ?

**Comment by simbit18** [comment]
@raiden00pl  Ok

**Pull request merged**
