### PR TITLE
arm/qemuv7a: Modify link script

### PR DESCRIPTION
**Pull request by W-M-R**
## Summary
1. Modify to map to the specified memory, CONFIG_FLASH_START and CONFIG_RAM_START
2. Add explanation README.TXT
## Impact
All configurations under qemev7a have been specified with CONFIG_FLASH_START CONFIG_FLASH_SIZE, CONFIG_RAM-START, and CONFIG_RAM_SIZE
## Testing
No

### CODE REVIEW

**Comment by nuttxpr** [comment]
[**\[Experimental Bot, please feedback here\]**](https://github.com/search?q=repo%3Aapache%2Fnuttx+13552&type=issues)



**No, this PR does not meet the NuttX requirements.**

**Missing Information:**

* **Summary:**
    * Lacks a clear explanation of *why* the change is necessary. Is it a bug fix, performance improvement, or new feature?
    * Doesn't specify what functional part of the code is being changed.  Mention specific files or modules.
    * How does the mapping to `CONFIG_FLASH_START` and `CONFIG_RAM_START` actually work? What code is modified?
    * Are there related NuttX issues?
* **Impact:**
    *  While it states all configurations are impacted, it's unclear what the user-facing consequences are. Will applications behave differently? Are there potential compatibility issues?
    *  Will the build process change for any boards?  Provide specifics if yes.
* **Testing:**
    * **Unacceptable:**  "No" is not sufficient.  You **must** provide testing evidence.
    * List the specific host operating systems, compilers, target architectures, and boards used for testing.
    * Include relevant log snippets demonstrating the problem before the change and the correct behavior after the change.

**Recommendations:**

1. **Expand the Summary:** Clearly articulate the problem or need this PR addresses. Provide more context on the code being modified and the mechanics of the change.
2. **Detail Impact:** Go beyond stating configurations are affected. Explain the consequences for users, build processes, and potential compatibility concerns.
3. **Provide Thorough Testing Information:**  Testing is crucial! List all host and target environments, and include log snippets showing before/after behavior. 

Without these improvements, it's difficult for maintainers to assess the PR's validity and safety.

**Comment by GUIDINGLI** [comment]
Hold for fix the knsh error

**Review by xiaoxiang781216 — APPROVED** [review]

**Review by acassis — CHANGES_REQUESTED** [review]
Please don't include README.txt into boards/. All README.txt were moved and converted to ReStructuredText into Documentation/ long time ago!

**Comment by W-M-R** [comment]
Related changes have been merged into other patches

**Pull request closed without merging**
