### PR TITLE
boards/arm/stm32/stm32f429i-disco add CAN driver support

### PR DESCRIPTION
**Pull request by GC-20-20**
## Summary
add CAN driver support
## Testing
on fire development board

### CODE REVIEW

**Review by acassis — COMMENTED** [review]
Please fix these issues:

Error: /home/runner/work/nuttx/nuttx/nuttx/boards/arm/stm32/stm32f429i-disco/include/board.h:209:0: error: Missing space after opening C comment
Error: /home/runner/work/nuttx/nuttx/nuttx/boards/arm/stm32/stm32f429i-disco/include/board.h:209:6: error: Missing space before closing C comment
Error: Process completed with exit code 1.

**Comment by acassis** [comment]
@GC-20-20 please squash your commits, as explained in our documentation: https://nuttx.apache.org/docs/latest/contributing/making-changes.html#how-to-include-the-suggestions-on-your-pull-request

**Review by acassis — APPROVED** [review]

**Comment by acassis** [comment]
@GC-20-20 I already approved it, but please squash the commits

**Comment by GC-20-20** [comment]
> @GC-20-20 I already approved it, but please squash the commits

ok

**Comment by acassis** [comment]
Thank you!

**Pull request merged**
