### PR TITLE
arch/armv7-r: add armv7-r smp support

### PR DESCRIPTION
**Pull request by zyfeier**
## Summary

This PR add armv7-r smp support.

## Impact

ARMV7-R SMP

## Testing

Verify in vdk ARM R8 SMP environment.

### CODE REVIEW

**Comment by masayuki2009** [comment]
@zyfeier 
Can we try this PR with QEMU instead of VDK?

**Comment by zyfeier** [comment]
> @zyfeier Can we try this PR with QEMU instead of VDK?

Hi, i see the existing boards do not have support for armv7-r qemu. I will try to add one.

**Comment by btashton** [comment]
@zyfeier and @xiaoxiang781216 are you planning to add a board for this? Right now we don't have any build coverage for this code path so hard to prevent even the most basic regression

**Comment by zyfeier** [comment]
> @zyfeier and @xiaoxiang781216 are you planning to add a board for this? Right now we don't have any build coverage for this code path so hard to prevent even the most basic regression

Yes, I have plans to add a board for armv7r, and I expect to provide it in early next month.

**Comment by xiaoxiang781216** [comment]
Thanks, @zyfeier , let's merge this patch first.

**Review by xiaoxiang781216 — APPROVED** [review]

**Pull request merged**
