### PR TITLE
esp32s3-devkit: add a config for qemu

### PR DESCRIPTION
**Pull request by yamt**
## Summary
based on esp32s3-devkit:toywasm, tailored for the espressif fork
of qemu. [1]

* disabled a few things for which emulation doesn't seem available:

  * wifi
  * spiram
  * ESP32S3_SYSTEM_BBPLL_RECALIB

* enabled DEBUG_SYMBOLS for my convenience (thus _debug suffix)

* enabled hostfs for my convenience

[1] https://github.com/espressif/qemu

## Testing

tested with:
qemu-xtensa-softmmu-esp_develop_9.0.0_20240606-x86_64-apple-darwin.tar.xz

### CODE REVIEW

**Comment by yamt** [comment]
@tmedicci can ESP32S3_SYSTEM_BBPLL_RECALIB still be necessary for the boot loader version used for simple boot?

**Review by xiaoxiang781216 — APPROVED** [review]

**Review by acassis — APPROVED** [review]

**Comment by xiaoxiang781216** [comment]
@yamt @acassis this patch combines with https://github.com/apache/nuttx/pull/12639 hit break:
```
< CONFIG_NET_ICMP=y
Saving the new configuration file
HEAD detached at pull/12[659](https://github.com/apache/nuttx/actions/runs/9867921047/job/27249088187?pr=12659#step:7:660)/merge
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   boards/xtensa/esp32s3/esp32s3-devkit/configs/qemu_debug/defconfig
```
please provide a patch fix it to unblock ci.

**Comment by tmedicci** [comment]
> @tmedicci can ESP32S3_SYSTEM_BBPLL_RECALIB still be necessary for the boot loader version used for simple boot?

Do you anything about it, @almir-okato ?

**Comment by yamt** [comment]
> @yamt @acassis this patch combines with #12639 hit break:
> 
> ```
> < CONFIG_NET_ICMP=y
> Saving the new configuration file
> HEAD detached at pull/12[659](https://github.com/apache/nuttx/actions/runs/9867921047/job/27249088187?pr=12659#step:7:660)/merge
> Changes not staged for commit:
>   (use "git add <file>..." to update what will be committed)
>   (use "git restore <file>..." to discard changes in working directory)
> 	modified:   boards/xtensa/esp32s3/esp32s3-devkit/configs/qemu_debug/defconfig
> ```
> 
> please provide a patch fix it to unblock ci.

https://github.com/apache/nuttx/pull/12660

**Pull request merged**
