### PR TITLE
Minor improvement for mmc

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
## Summary

- drivers/mmcsd: Rename mmcsd_read_csd to mmcsd_read_extcsd 
- drivers/mmcsd: mmcsd_sdinitialize should save csd register into priv->csd

## Impact

code refactor only

## Testing

ci

### CODE REVIEW

**Comment by davids5** [comment]
> Rename mmcsd_read_csd to mmcsd_read_extcsd
Why?

**Comment by xiaoxiang781216** [comment]
> > Rename mmcsd_read_csd to mmcsd_read_extcsd
> 
> Why?

since CSD and EXTCSD is different register, the origin code uses the wrong name:
image

**Review by davids5 — APPROVED** [review]
@xiaoxiang781216 - Thank you for the explanation.  I would be much appreciated if your PR's answer the "Why" in the Title block.

**Comment by xiaoxiang781216** [comment]
> @xiaoxiang781216 - Thank you for the explanation. I would be much appreciated if your PR's answer the "Why" in the Title block.

commit message contain this info:
```
commit 6085b0be1b70c7fe8b19ecbe330b9675d2893bbe
Author: Xiang Xiao <xiaoxiang@xiaomi.com>
Date:   Tue Oct 17 23:32:52 2023 +0800

    drivers/mmcsd: Rename mmcsd_read_csd to mmcsd_read_extcsd
    
    since it really read extcsd register not csd register
    
    Signed-off-by: Xiang Xiao <xiaoxiang@xiaomi.com>
```

**Comment by xiaoxiang781216** [comment]
Change to draft to wait the internal patch which support multiple emmc partition?

**Pull request closed without merging**
