### PR TITLE
i.mxrt d-cache write-back mode with networking

### PR DESCRIPTION
**Pull request by masayuki2009**
## Summary

- This PR consists of the following 3 commits
  - commit1: arch: imxrt: Fix CONFIG_IMXRT_ENET_ENHANCEDBD
    - I noticed that CONFIG_IMXRT_ENET_ENHANCEDBD is not correctly
      used though it is defined in Kconfig.
    - This commit fixes this issue.
  - commit2: arch: imxrt: Enable IMXRT_ENET_ENHANCEDBD if !ARMV7M_DCACHE_WRITETHROUGH
    - I noticed that there are two kinds of descriptors for imxrt_enet.c
    - The first one is the legacy descriptor and its size is 8bytes.
    - The second one is the enhanced descriptor and its size is 32bytes.
    - In both cases, we can not use a descriptor chain like stm32.
    - Considering cache line alignment, the second one is perfect because
      one descriptor fits the Cortex-M7 cache line which would fix networking
      stability issues in d-cache write-back mode.
  - commit3: boards: imxrt1060-evk: Add netnsh_dcache_wb configuration
    - This commit adds netnsh_dcache_wb configuration which enables
      d-cache write-back mode with networking.

## Impact

- imxrt ethernet in d-cache write-back mode

## Testing

- Tested with iperf, telnet and ping on imxrt1060-evk board
- iperf -s 94Mbps, iperf -c 93Mbps

### CODE REVIEW

**Comment by masayuki2009** [comment]
@davids5 
I've just fixed i.mxrt d-cache write-back issues with networking.
Could you please review this PR?

**Review by xiaoxiang781216 — APPROVED** [review]

**Review by jerpelea — APPROVED** [review]

**Review by pkarashchenko — APPROVED** [review]

**Comment by masayuki2009** [comment]
Hmm, I think the following error does not relate to this PR.

```
====================================================================================
Configuration/Tool: stm32f4discovery/testlibcxx,CONFIG_ARM_TOOLCHAIN_GNU_EABI
------------------------------------------------------------------------------------
  Cleaning...
  Configuring...
  Disabling CONFIG_ARM_TOOLCHAIN_GNU_EABI
  Enabling CONFIG_ARM_TOOLCHAIN_GNU_EABI
  Building NuttX...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

100 1836k  100 1836k    0     0  8916k      0 --:--:-- --:--:-- --:--:-- 8916k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

100  539k  100  539k    0     0  2983k      0 --:--:-- --:--:-- --:--:-- 2983k
In file included from /github/workspace/sources/nuttx/include/libcxx/filesystem:241,
                 from libcxx/src/filesystem/operations.cpp:9:
In member function 'std::__1::_EnableIf<std::__1::__is_cpp17_forward_iterator<_InputIter>::value> std::__1::basic_string<_CharT, _Traits, _Allocator>::__init(_ForwardIterator, _ForwardIterator) [with _ForwardIterator = const char*; _CharT = char; _Traits = std::__1::char_traits<char>; _Allocator = std::__1::allocator<char>]',
    inlined from 'std::__1::basic_string<_CharT, _Traits, _Allocator>::basic_string(_InputIterator, _InputIterator, const allocator_type&) [with _InputIterator = const char*; <template-parameter-2-2> = void; _CharT = char; _Traits = std::__1::char_traits<char>; _Allocator = std::__1::allocator<char>]' at /github/workspace/sources/nuttx/include/libcxx/string:2195:11,
    inlined from 'std::__1::basic_string<_CharT, _Traits, _Allocator>& std::__1::basic_string<_CharT, _Traits, _Allocator>::__append_forward_unsafe(_ForwardIterator, _ForwardIterator) [with _ForwardIterator = const char*; _CharT = char; _Traits = std::__1::char_traits<char>; _Allocator = std::__1::allocator<char>]' at /github/workspace/sources/nuttx/include/libcxx/string:2676:32,
    inlined from 'std::__1::basic_string<_CharT, _Traits, _Allocator>& std::__1::basic_string<_CharT, _Traits, _Allocator>::__append_forward_unsafe(_ForwardIterator, _ForwardIterator) [with _ForwardIterator = const char*; _CharT = char; _Traits = std::__1::char_traits<char>; _Allocator = std::__1::allocator<char>]' at /github/workspace/sources/nuttx/include/libcxx/string:2662:1:
Error: /github/workspace/sources/nuttx/include/libcxx/string:2156:35: error: '__temp' may be used uninitialized [-Werror=maybe-uninitialized]
 2156 |         this->__throw_length_error();
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~^~
```

**Comment by masayuki2009** [comment]
>Hmm, I think the following error does not relate to this PR.

Let me rebase to the latest master.

**Comment by masayuki2009** [comment]
>Let me rebase to the latest master.

Hmm, the build error still happens.

**Review by xiaoxiang781216 — APPROVED** [review]

**Review by davids5 — APPROVED** [review]

**Comment by xiaoxiang781216** [comment]
Let's ignore the ci broken which is fixed by https://github.com/apache/nuttx/pull/8611 and merge this simple change.

**Pull request merged**
