### PR TITLE
free up runner disk space before build docker image

### PR DESCRIPTION
**Pull request by trns1997**
## Summary

Should hopefully fix the following error: https://github.com/apache/nuttx/actions/runs/7116873366

### CODE REVIEW

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by btashton** [comment]
This should not have been merged. Only certain github actions are allowed by org policy.

I would recommend extending what I already did here which should have done most of what this action was doing
https://github.com/apache/nuttx/pull/8680

FYI @raiden00pl

**Comment by xiaoxiang781216** [comment]
the script is copied into nuttx repo by https://github.com/apache/nuttx/pull/11354, so it doesn't a problem now.

**Comment by trns1997** [comment]
@btashton sorry I hadn't noticed what you had already done. We now have 2 sections in the docker actions doing the same thing. I think it would be a good idea to either remove my modification and extend to what @btashton had done or keep the new action and remove @btashton modification. I'm open to both let me know what you guys think.

**Comment by btashton** [comment]
I'm not attached to mine :). So whatever we think is best.

**Comment by xiaoxiang781216** [comment]
Let's continue to improve https://github.com/jlumbroso/free-disk-space?

**Pull request merged**
