### PR TITLE
sim: fix nuttx consumes much CPU time

### PR DESCRIPTION
**Pull request by GUIDINGLI**
## Summary

sim: fix nuttx consumes much CPU time

And also:
Fix hang on configure sim:smp when (CONFIG_SMP_NCPUS=1), which report by https://github.com/apache/nuttx/pull/8469

## Impact

SIM

## Testing

sim:smp both CONFIG_SMP_NCPUS = 1 & CONFIG_SMP_NCPUS = 4

### CODE REVIEW

**Comment by masayuki2009** [comment]
@GUIDINGLI 
I tried this PR with sim:smp (CONFIG_SMP_NCPUS=1) on ubuntu 18.04 x86_64.
However, the deadlock still happens.

```
--- a/boards/sim/sim/sim/configs/smp/defconfig
+++ b/boards/sim/sim/sim/configs/smp/defconfig
@@ -27,6 +27,7 @@ CONFIG_READLINE_CMD_HISTORY=y
 CONFIG_SCHED_HAVE_PARENT=y
 CONFIG_SIM_WALLTIME_SIGNAL=y
 CONFIG_SMP=y
+CONFIG_SMP_NCPUS=1
 CONFIG_STACK_COLORATION=y
 CONFIG_SYSTEM_NSH=y
 CONFIG_SYSTEM_SYSTEM=y
```

**Comment by GUIDINGLI** [comment]
@masayuki2009 

Thanks for the reply.

I have tried the CONFIG_SMP_NCPUS=1.

```
ligd@Opt:~/platform/mainline/nuttx$ 
ligd@Opt:~/platform/mainline/nuttx$ uname -a
Linux Opt 5.15.0-58-generic #64~20.04.1-Ubuntu SMP Fri Jan 6 16:42:31 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
ligd@Opt:~/platform/mainline/nuttx$ 
ligd@Opt:~/platform/mainline/nuttx$ 
ligd@Opt:~/platform/mainline/nuttx$ vim .config
ligd@Opt:~/platform/mainline/nuttx$ 
ligd@Opt:~/platform/mainline/nuttx$ 
ligd@Opt:~/platform/mainline/nuttx$ cat .config |grep NCPUS
CONFIG_SMP_NCPUS=1
ligd@Opt:~/platform/mainline/nuttx$ 
ligd@Opt:~/platform/mainline/nuttx$ ./nuttx 

NuttShell (NSH) NuttX-10.4.0
nsh> ps
  PID GROUP CPU PRI POLICY   TYPE    NPX STATE    EVENT     SIGMASK   STACK   USED  FILLED COMMAND
    0     0   0   0 FIFO     Kthread N-- Assigned           00000000 066512 004760   7.1%  CPU0 IDLE
    1     1 --- 255 FIFO     Kthread --- Waiting  Signal    00000000 067504 004728   7.0%  loop_task
    2     2   0 100 FIFO     Task    --- Running            00000000 067504 007000  10.3%  nsh_main
nsh> 
```


I will find a 18.04 Ubuntu to try this.

**Comment by masayuki2009** [comment]
@GUIDINGLI 
By the way, I noticed that the nuttx consumes much CPU time compared to nuttx-12.0.0-RC1.

**Comment by GUIDINGLI** [comment]
@masayuki2009 

Could you have try again ?
And I also fix the consumes much CPU time issue.

Thanks.

**Comment by masayuki2009** [comment]
@GUIDINGLI 

```
====================================================================================
Configuration/Tool: sim/nxwm
------------------------------------------------------------------------------------
  Cleaning...
  Configuring...
  Building NuttX...
src/cnxtimer.cxx: In member function 'void NXWidgets::CNxTimer::start()':
Error: src/cnxtimer.cxx:145:34: error: division by zero [-Werror=div-by-zero]
  145 |       uint32_t ticks = m_timeout / MSEC_PER_TICK;
      |                                  ^
cc1plus: all warnings being treated as errors
make[3]: *** [/github/workspace/sources/apps/Application.mk:161: cnxtimer.cxx.github.workspace.sources.apps.graphics.nxwidgets.o] Error 1
make[3]: Target 'all' not remade because of errors.
make[2]: *** [Makefile:52: /github/workspace/sources/apps/graphics/nxwidgets_all] Error 2
make[2]: Target '/github/workspace/sources/apps/libapps.a' not remade because of errors.
make[1]: *** [Makefile:46: all] Error 2
make: *** [tools/LibTargets.mk:216: /github/workspace/sources/apps/libapps.a] Error 2
make: Target 'all' not remade because of errors.
```

**Comment by masayuki2009** [comment]
@GUIDINGLI 
>And I also fix the consumes much CPU time issue.

sim:smp (CONFIG_SMP_NCPUS=4) still has a high CPU load.

```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
12930 ishikawa  20   0   74700   2232   1668 S 159.8  0.0   1:48.85 nuttx
```

Also, sim:smp (CONFIG_SMP_NCPUS=1) still does not work.

**Comment by GUIDINGLI** [comment]
@masayuki2009 

I have installed a 18.04 Ubuntu to docker.
And run the SMP & NCPUS=1.

But haven't meet your questions, have you `distclean` the project before `make` ?

```
root@ProDesk-680:~/mainline/nuttx# ./nuttx 
NuttShell (NSH) NuttX-12.0.0
nsh> 
nsh> 
nsh> ps
  PID GROUP CPU PRI POLICY   TYPE    NPX STATE    EVENT     SIGMASK   STACK   USED  FILLED COMMAND
    0     0   0   0 FIFO     Kthread N-- Assigned           00000000 066512 004760   7.1%  CPU0 IDLE
    1     1 --- 255 FIFO     Kthread --- Waiting  Signal    00000000 067504 005320   7.8%  loop_task
    2     2 --- 224 FIFO     Kthread --- Waiting  Semaphore 00000000 067488 005256   7.7%  hpwork 0x55951725fe60
    3     3   0 100 FIFO     Task    --- Running            00000000 067504 007464  11.0%  nsh_main
nsh> poweroff
root@ProDesk-680:~/mainline/nuttx# 
root@ProDesk-680:~/mainline/nuttx# cat /etc/issue
Ubuntu 18.04.6 LTS \n \l

root@ProDesk-680:~/mainline/nuttx# 
root@ProDesk-680:~/mainline/nuttx# cat .config |grep NCPUS
CONFIG_SMP_NCPUS=1
root@ProDesk-680:~/mainline/nuttx# 
```

**Comment by masayuki2009** [comment]
@GUIDINGLI 

>But haven't meet your questions, have you distclean the project before make ?

Oh, really? So do you mean that you can not see a high CPU load with this PR?
Yes, I cleaned up local repositories by `git clean -fdx` before configuring the nuttx.

**Comment by GUIDINGLI** [comment]
Sorry for not clearly.

I haven't met:
sim:smp (CONFIG_SMP_NCPUS=1) still does not work.

A high CPU load:
Yes, that is a question, I will find a fix method.

**Comment by masayuki2009** [comment]
@GUIDINGLI 
Could you update the PR title and summary based on the latest commits?

**Comment by GUIDINGLI** [comment]
Could you update the PR title and summary based on the latest commits?

Yes, updated.

I have do some test just now, and haven't inform you timely.

So, can you help to review the newest patch ?

**Comment by masayuki2009** [comment]
@GUIDINGLI 
I confirmed that `sim:smp (CONFIG_SMP_NCPUS=1) ` now works.
Also, confirmed that the CPU load is low.

**Comment by GUIDINGLI** [comment]
@masayuki2009 

Thanks a lot.

**Pull request merged**
