### PR TITLE
Fix error: unknown warning option '-Wno-unqualified-std-cast-call'

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
## Summary

report here: https://github.com/apache/nuttx-apps/actions/runs/6248425557/job/16963139872?pr=2077

## Testing

ci

### CODE REVIEW

**Comment by xiaoxiang781216** [comment]
@pkarashchenko do you know why clang report this follow error some time?
```
====================================================================================
Configuration/Tool: sim/libcxxtest
------------------------------------------------------------------------------------
  Cleaning...
  Configuring...
  Building NuttX...
error: unknown warning option '-Wno-unqualified-std-cast-call'; did you mean '-Wno-qualified-void-return-type'? [-Werror,-Wunknown-warning-option]
make[1]: *** [directory_iterator.o] Error 1
make[1]: Target `libxx.a' not remade because of errors.
make: *** [libs/libxx/libxx.a] Error 2
make: Target `all' not remade because of errors.
/Users/runner/work/nuttx/nuttx/sources/nuttx/tools/testbuild.sh: line 370: /Users/runner/work/nuttx/nuttx/sources/nuttx/../nuttx/nuttx.manifest: No such file or directory
```

**Comment by mu578** [comment]
yeah that's a clang flag ; however if using clang: the default should be always `-Werror=unqualified-std-cast-call` ; no cruft++ hackery allowed by any means: pedantic or die.

**Comment by pkarashchenko** [comment]
@xiaoxiang781216 I think that new version of CXX should use `std::move` and not `move` to get rid of this error. I hope that would be fixed in new versions of `libc++`, so currently we either need to patch the lib or keep what I did (obviously was too lazy to patch the lib).

**Comment by xiaoxiang781216** [comment]
> @xiaoxiang781216 I think that new version of CXX should use `std::move` and not `move` to get rid of this error. I hope that would be fixed in new versions of `libc++`, so currently we either need to patch the lib or keep what I did (obviously was too lazy to patch the lib).

Ok, I will finish the libcxx upgrade(https://github.com/apache/nuttx/pull/8244) tomorrow.

**Pull request closed without merging**
