### PR TITLE
add defconfig for ltp openposix testsuite

### PR DESCRIPTION
**Pull request by extinguish**
## Summary
nuttx/board/sim/posix_test: add defconfig for ltp openposix testsuite
1. the defconfig is based on nuttx/boards/sim/sim/configs/nsh/defconfig
2. make the option enabled by default that needed by open posix

### CODE REVIEW

**Comment by extinguish** [comment]
this patch need to wait another fix, so this patch cannot pass CI for now.

**Comment by extinguish** [comment]
there are some ltp testcases that has build warning, which cannot pass CI.
the https://github.com/apache/nuttx-apps/pull/2020 fix these build warning, after https://github.com/apache/nuttx-apps/pull/2020 is merged, then we can trying to merge this patch

**Comment by extinguish** [comment]
there is a build error with "CONFIG_LIBC_PASSWD_FILE=y", and need to wait the https://github.com/apache/nuttx/pull/10473 is merged

**Comment by xiaoxiang781216** [comment]
@extinguish please add the rule to remove ltp.zip from apps/testing/ltp/Makefile:
```
Untracked files:
  (use "git add <file>..." to include in what will be committed)
	testing/ltp/ltp.zip
```

**Comment by extinguish** [comment]
there is a CI warning, need to wait this warning finished in: https://github.com/apache/nuttx-apps/pull/2043 merge request.

**Review by xiaoxiang781216 — APPROVED** [review]

**Pull request merged**
