### PR TITLE
Fix virtio-mmio-net

### PR DESCRIPTION
**Pull request by masayuki2009**
## Summary

- This commit consists of the following 2 commits
  - commit1: dirivers: virtio: Fix virtnet_virtnet_txpoll() in virtio-mmio-net.c
  - commit2: boards: Enable NFS to test virtio-mmio-net

## Impact

- None

## Testing

- Tested with qemu-7.1

### CODE REVIEW

**Comment by masayuki2009** [comment]
Hmm, I think the following error does not relate to this PR.

```
====================================================================================
Configuration/Tool: fvp-armv8r/nsh_smp
------------------------------------------------------------------------------------
  Cleaning...
  Configuring...
  Building NuttX...
  Normalize fvp-armv8r/nsh_smp
make: *** [tools/Unix.mk:686: savedefconfig] Error 1
HEAD detached at pull/9457/merge
Untracked files:
  (use "git add <file>..." to include in what will be committed)
	defconfig.tmp

nothing added to commit but untracked files present (use "git add" to track)
```

**Comment by masayuki2009** [comment]
Let me rebase this PR to the latest master.

**Comment by masayuki2009** [comment]
>make: *** [tools/Unix.mk:686: savedefconfig] Error 1

I've just created https://github.com/apache/nuttx/pull/9458

**Comment by masayuki2009** [comment]
>I've just created https://github.com/apache/nuttx/pull/9458

I've just rebased this PR to the latest master.

**Review by jerpelea — APPROVED** [review]

**Pull request merged**
