### PR TITLE
sensors/bmi270: fix accel and gyro data position

### PR DESCRIPTION
**Pull request by raiden00pl**
## Summary

- sensors/bmi270: fix accel and gyro data position
accel registers are DATA_8 to DATA_13
gyro registers are DATA_14 to DATA_19

## Testing
CI

### CODE REVIEW

**Review by hartmannathan — APPROVED** [review]
LGTM - verified against [datasheet](https://www.bosch-sensortec.com/media/boschsensortec/downloads/datasheets/bst-bmi270-ds000.pdf) (page 73-74)

**Review by xiaoxiang781216 — APPROVED** [review]

**Review by acassis — APPROVED** [review]

**Comment by acassis** [comment]
@raiden00pl how did you spot this issue? Are you testing this device?

I just noticed that the sensor_fusion example is only for MPU6050, it should be IMU agnostic. Maybe using the new sensor orb it could be possible

**Comment by raiden00pl** [comment]
@acassis I'm porting the sensors present on Thingy boards to the new sensor framework. Data returned by bmi270 after conversion to g-force didn't make sense and it turned out that regs were in the wrong order.

I don't see any obstacles to using the new sensor framework with sensor_fusion.

**Comment by acassis** [comment]
> @acassis I'm porting the sensors present on Thingy boards to the new sensor framework. Data returned by bmi270 after conversion to g-force didn't make sense and it turned out that regs were in the wrong order.
> 
> I don't see any obstacles to using the new sensor framework with sensor_fusion.

Thank you @raiden00pl

**Pull request merged**
