### PR TITLE
Add  ESP32-2432S028 board

### PR DESCRIPTION
**Pull request by halyssonJr**
## Summary
Add new board ES32-2432S028 board (Reference : https://www.openhasp.com/0.7.0/hardware/sunton/esp32-2432s028/)
## Impact
New feature
## Testing
Pass CI

### CODE REVIEW

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by xiaoxiang781216** [comment]
@halyssonJr please rebase your patch, ci broken is fixed by https://github.com/apache/nuttx/pull/10975.

**Review by jerpelea — APPROVED** [review]
please add a commit message

**Review by acassis — COMMENTED** [review]
Please add the Board documentation, to include information about the board (and a picture of the board) to appear at: https://nuttx.apache.org/docs/12.2.1/platforms/xtensa/esp32/index.html#supported-boards

**Comment by xiaoxiang781216** [comment]
@halyssonJr run `./tools/checkpatch.sh -g HEAD~...HEAD` to fix the ci error:
```
  Normalize esp32-2432S028/nsh
8d7
< # CONFIG_ARCH_LEDS is not set
Saving the new configuration file
HEAD detached at pull/10976/merge
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   boards/xtensa/esp32/esp32-2432S028/configs/nsh/defconfig
```

**Comment by xiaoxiang781216** [comment]
@halyssonJr sorry, I suggest the wrong command, please try: `./tools/refresh.sh --silent esp32-2432S028/nsh`.

**Comment by halyssonJr** [comment]
@xiaoxiang781216 , This board uses the driver ILI9341, if you check the implementation on ESP32 (`nuttx/boards/xtensa/esp32/common/src/esp32_ili9341.c`), you see we don't have a config or function to turn on the backlight using GPIO.  Because of this, I need to add(`esp32_gpiowrite(DISPLAY_BCKL, true)`)  to turn on the backlight and run the LVGL example. Do you have any suggestions I can do that?

**Comment by xiaoxiang781216** [comment]
> @xiaoxiang781216 , This board uses the driver ILI9341, if you check the implementation on ESP32 (`nuttx/boards/xtensa/esp32/common/src/esp32_ili9341.c`), you see we don't have a config or function to turn on the backlight using GPIO. Because of this, I need to add(`esp32_gpiowrite(DISPLAY_BCKL, true)`) to turn on the backlight and run the LVGL example. Do you have any suggestions I can do that? Maybe create a new CONFIG?

Yes, new CONFIG is one of method. @acassis do you have better suggestion?

**Pull request merged**
