### PR TITLE
boards/rv-virt: cmake for pnsh and nsbi

### PR DESCRIPTION
**Pull request by yf13**
## Summary

This adds cmake scripts for NuttSBI and PROTECTED builds.
PROTECTED check should be done with pull/12022.

## Impact

N/A

## Testing

- local checks with rv-virt target and `nsbi`, `nsbi64`, `pnsh`, `pnsh64` etc.
- CI checks

### CODE REVIEW

**Comment by yf13** [comment]
Linux(sim-01) got Timeout during LTP, retrigger once

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by yf13** [comment]
@xiaoxiang781216, seems that `Linux(sim-01)` LTP got `Result : Timeout` again as per [this log](https://github.com/apache/nuttx/actions/runs/10313100935/job/28549377334). Please teach if you have any suggestions about it.

**Comment by yf13** [comment]
@xiaoxiang781216, seems that `Linux(sim-01)` LTP got `Result : Timeout` again as per [this log](https://github.com/apache/nuttx/actions/runs/10313100935/job/28549377334). Please teach if you have any suggestions about it.

**Review by jerpelea — APPROVED** [review]

**Comment by xiaoxiang781216** [comment]
let's merge this pr to fix arm-13 ci break.

**Pull request merged**
