### PR TITLE
Modify the existing process of LocalSocket to support LocalSocket functionality

### PR DESCRIPTION
**Pull request by wangchen61698**
## Summary

Modify the existing process of LocalSocket to support LocalSocket functionality

## Impact

localsocket

## Testing
Refers to The Linux Programming Interface(https://www.man7.org/tlpi/index.html) chapter 57(sockets:UNIX DOMAIN) and their demo （us_xfr_sv.c & us_xfr_cl.c & ud_ucase_sv.c & ud_ucase_cl.c）
resouce code:
[localsocket_tcp.zip](https://github.com/apache/nuttx/files/14427551/localsocket_tcp.zip)
[localsocket_udp.zip](https://github.com/apache/nuttx/files/14427552/localsocket_udp.zip)
test result:
TCP localsocket:
e2877ae2-a6cd-4fe0-9900-aaf546d04d76
UDP localsocket:
e6ba6f10-6117-4f7f-b9b4-9b993e4d5685

### CODE REVIEW

**Comment by acassis** [comment]
@wangchen61698 there are many modifications in many files and you didn't include any comment about Testing. Did you test it? How did you test it? Please include more information here, include commit message and if possible instructions to let other people to test it too.

**Comment by wangchen61698** [comment]
> @wangchen61698 there are many modifications in many files and you didn't include any comment about Testing. Did you test it? How did you test it? Please include more information here, include commit message and if possible instructions to let other people to test it too.

The testing information has been supplemented

**Comment by wangchen61698** [comment]
> The testing information has been supplemented

**Comment by wangchen61698** [comment]
> @wangchen61698 there are many modifications in many files and you didn't include any comment about Testing. Did you test it? How did you test it? Please include more information here, include commit message and if possible instructions to let other people to test it too.

The testing information has been supplemented

**Pull request closed without merging**
