### PR TITLE
x86-64: Support symbol table and kasan global variables cross-border detection

### PR DESCRIPTION
**Pull request by W-M-R**
## Summary

1. Add kasan compilation options
2. Modify the link process to support symbol tables and kasan global variables cross-border detection

## Impact

*Update this section, where applicable, on how change affects users,
 build process, hardware, documentation, security, compatibility, etc.*

## Testing

*Update this section with details on how did you verify the change,
 what Host was used for build (OS, CPU, compiler, ..), what Target was
 used for verification (arch, board:config, ..), etc. Providing build
 and runtime logs from before and after change is highly appreciated.*

### CODE REVIEW

**Comment by nuttxpr** [comment]
[**\[Experimental Bot, please feedback here\]**](https://github.com/search?q=repo%3Aapache%2Fnuttx+13552&type=issues)



This PR does **not** fully meet the NuttX requirements as presented. While it provides a summary of the changes, it lacks crucial details in the Impact and Testing sections.

Here's a breakdown:

**Summary:** While it mentions the *what*, it lacks the *why* and *how*.  It needs to explain the rationale behind adding KASAN support and the specific modifications made to the link process.  For example, *why* is KASAN support being added? Is it to address a specific memory issue or for general robustness?  *How* does modifying the link process enable cross-border detection? What specific changes were made?  A related issue number would also be helpful if one exists.

**Impact:**  This section is entirely incomplete.  All points need to be addressed.  KASAN will almost certainly have an impact on build size and potentially performance.  It might also affect compatibility with existing code. These potential impacts need to be documented. Does enabling KASAN require any specific configuration options?  Will users need to adapt their code?  Does it introduce any security considerations? These questions must be answered.

**Testing:** This section is also incomplete.  It needs to specify the host operating system, CPU architecture, compiler version, and target architecture and board configuration used for testing.  Critically, it needs to include *actual* testing logs from before and after the change, demonstrating the effectiveness of the KASAN implementation.  Simply stating that changes were verified is insufficient.  Concrete evidence is required.

**In short, the PR needs to be significantly more detailed to meet the NuttX requirements.**  It needs to provide a comprehensive explanation of the changes, their impact, and thorough testing results.

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by W-M-R** [comment]
Why does my patch cause issues with other architectures 🧐， It shouldn't be

**Comment by xiaoxiang781216** [comment]
> Why does my patch cause issues with other architectures 🧐， It shouldn't be

it's a known issue, @lupyuen is looking at.

**Comment by lupyuen** [comment]
Thanks @W-M-R: We just discovered a new bug in the Build Rules!

- This PR is labelled ["Arch: x86"](https://github.com/apache/nuttx/pull/14885#event-15375133985). Which is a [Simple PR](https://lupyuen.github.io/articles/ci3#limit-to-simple-prs).

- Expected Behaviour is to run the CI Build for One Single Target Group: `other`(x86). The CI Build for `other` should complete within 1 hour.

- Actual Behaviour: It runs the CI Build for [All Target Groups](https://github.com/apache/nuttx/actions/runs/11949743934/attempts/1)! (Arm, RISC-V, Xtensa, ...) Which runs for nearly 3 hours and should never happen, because of [budget cuts](https://lupyuen.github.io/articles/ci3#disable-macos-and-windows-builds).

- Cause of Problem: There's a bug in the [Build Rules](https://github.com/apache/nuttx/actions/runs/11949743934/job/33309896880#step:3:136). I forgot to check for x86 PRs. (It works only for x86_64 PRs) I'll go fix this.

- The RISC-V Bug that appears in the CI Build: It has been flagged in nuttx-dashboard.org. I reported it here: <br> https://github.com/apache/nuttx/issues/14808

- Can we fix the RISC-V Bug? I'm not quite sure why `pytest`, QEMU and `expect` failed. I'll have to dig inside. (Maybe write an article about it)

**Comment by raiden00pl** [comment]
@W-M-R is this PR correct ? In the description you write about x86_64 but you modified x86

**Comment by W-M-R** [comment]
> the description you write about x86_64 but you modified x86

Sorry，https://github.com/apache/nuttx/pull/14900 ，this is the real x86-64 modification, and this patch is x86
Fortunately, except for the error in the previous modification, the actual architecture is supported

**Pull request merged**
