### PR TITLE
sim/lua: enable luv module by default

### PR DESCRIPTION
**Pull request by XuNeo**
## Summary

Enable luv(libuv lua binding) module in sim:lua config

## Impact
No.
## Testing

Tested the config locally, and luv basic function works as expected.

### CODE REVIEW

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by XuNeo** [comment]
CI failed due to luv compile warning. 
Fixed [here](https://github.com/apache/nuttx-apps/pull/1453).

**Comment by xiaoxiang781216** [comment]
Please rebase to the last mater to fix ci broken.

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by xiaoxiang781216** [comment]
@XuNeo Should we enable all lua module?

**Comment by XuNeo** [comment]
> @XuNeo Should we enable all lua module?

Sure.  Only `luv` module has been upstreamed. Other modules will come later when I'm sure they are at least functional.

**Pull request merged**
