### PR TITLE
boards/sparc: add initial support of s698pm-dkit board

### PR DESCRIPTION
**Pull request by zouboan**
## Summary
add initial support of s698pm-dkit board to put arch/sparc/s698pm into ci protect
s698pm-dkit is a s698pm development board it has:
1. on board 8MB SRAM;
2. on board 16MB FLASH;
3. on board 256MB DDR2;
4. on board 1MB SPI FLASH;
5. on board 2KB I2C EEPROM;
6. 100M ethernet;
7. two spacewire bus;
8. two can bus;
9. two 1553b bus;
10. four uart interface;
11. one DSU interface;
12. one USB HOST;
13. ten GPIO interface;
14. TM/TC interface.
## Impact
boards
## Testing
s698pm-dkit board smp
Screenshot from 2022-11-24 22-25-57

### CODE REVIEW

**Comment by acassis** [comment]
Hi @zouboan I visited INPE last week, they have some projects using Sparc, but it is based on LEON2: https://flickr.com/photos/79703543@N00/52511348812/

**Comment by zouboan** [comment]
Hi Alan, both AT697 and BM3803 based on LEON2, they almost the same

**Comment by xiaoxiang781216** [comment]
@zouboan you need run ./tools/refresh.sh --silent to fix ci error.

**Comment by zouboan** [comment]
Thanks very much for your advice！ @xiaoxiang781216

**Comment by xiaoxiang781216** [comment]
@zouboan it's better to squash the second patch into the first one by:
git rebase --interactive HEAD~2
and change pick to squash for the second change.

**Comment by zouboan** [comment]
done @xiaoxiang781216

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by hartmannathan** [comment]
Where can I find more information about this board? Who is the vendor?

**Comment by xiaoxiang781216** [comment]
@zouboan could you provide some info to @hartmannathan ?

**Comment by hartmannathan** [comment]
> Where can I find more information about this board? Who is the vendor?

Hi, just for clarity, I'm not looking to buy one; I'm asking for documentation / release notes purposes. Thanks!

**Comment by zouboan** [comment]
Sorry delayed your question because of my daily works @xiaoxiang781216 @hartmannathan
S698PM is a SPARC-V8 based 32-bit multi-core processor SOC by Zhuhai Orbita Aerospace Science & Technology Co., Ltd. The chip can be widely used in aerospace, industrial control, its production using the current 0.18-micron CMOS process maturity. The chip integrates a standard IEEE-754 based on 64-bit floating point processing unit. 100M ethernet; The chip also integrates two Spacewire bus controller, two CAN bus controller, two 1553b bus controller,four uart controller, one USB HOST controller; The S698PM-DKIT is a development board also by Orbita Aerospace Science & Technology Co., Ltd. There are 8MB on board  SRAM, 16MB on board  FLASH,  256MB  on board  DDR2, 1MB on board  SPI FLASH, 2KB on board  I2C EEPROM;100M ethernet interface, two Spacewire bus interface,  two CAN bus interface, two 1553b bus interface, four uart interface, one DSU interface, one USB HOST interface, ten GPIO interface,TM/TC interface. Unfortunately, there is only Chinese manual both S698PM and S698PM-DKIT.

**Comment by hartmannathan** [comment]
@zouboan thank you for the detailed description! Out of curiosity, does the Spacewire bus interface work on NuttX? (Is it seen like a regular serial port for example?) If not, do you plan to add support for that in the future?

**Comment by zouboan** [comment]
@hartmannathan Hi, if there's any one try to use Spacewire bus on S698PM, I'm glad to add support of S698PM's Spacewire drivers

**Pull request merged**
