### PR TITLE
coredump: add architecture-specific registers dump, including NVIC an…

### PR DESCRIPTION
**Pull request by gneworld**
## Summary
add architecture-specific registers dump, including NVIC and MPU

## Impact
coredump

### CODE REVIEW

**Comment by nuttxpr** [comment]
[**\[Experimental Bot, please feedback here\]**](https://github.com/search?q=repo%3Aapache%2Fnuttx+13552&type=issues)



**No, this PR does not meet the NuttX requirements.**

**Missing Information:**

* **Summary:**
    *  Lacks a clear explanation of why the change is necessary. Is it a fix, update, or new feature? 
    *  Needs more detail on the functional part of the code being changed and how the change works. Be specific about the registers being dumped and the mechanism used.
* **Impact:**
    *  While "coredump" is mentioned, it's unclear how this change impacts the user, build process, hardware, documentation, security, or compatibility. Address each impact category with specific details.
* **Testing:**
    * The "Testing" section is entirely empty. Provide:
        * Details about your build host(s) and target(s).
        *  "Before" and "after" testing logs demonstrating the change's effect.

**Recommendations for Improvement:**

1. **Expand the Summary:**  Clearly state the problem this PR solves or the enhancement it provides. Explain the technical details of the change (e.g., "This PR adds a new function to `arch/arm/src/xxx/xxx.c` that dumps the contents of ARM Cortex-M NVIC and MPU registers to the console during a coredump.").
2. **Address All Impact Categories:**  For each impact category, provide a "YES" or "NO" answer. If "YES", explain the impact in detail. For example:
    *  **Impact on user:** YES. Users will now see NVIC and MPU register values in coredump output, aiding in debugging.
    *  **Impact on documentation:** YES. The coredump documentation needs to be updated to describe the new register dump information.
3. **Provide Thorough Testing Information:** Specify your build host operating system, CPU architecture, compiler, and version. List the target architecture, board, and configuration used for testing. Include relevant "before" and "after" logs to demonstrate the change.

By providing the missing information and following the recommendations, you'll make your PR much stronger and easier for the NuttX maintainers to review and merge.

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by lupyuen** [comment]
Sorry @GUIDINGLI I think [coredump.h](https://github.com/apache/nuttx/pull/14262/files#diff-2eb1883c9a5d24fe74f8e114591c808b0bda11c407d3f2c851560d7d357a4dc6) might be breaking the `other` build:
```text
Configuration/Tool: teensy-2.0/nsh
In file included from /github/workspace/sources/nuttx/include/nuttx/coredump.h:35:0,
                 from /github/workspace/sources/nuttx/sched/misc/coredump.h:28,
                 from ./init/nx_bringup.c:54:
/github/workspace/sources/nuttx/include/nuttx/elf.h:31:22: fatal error: arch/elf.h: No such file or directory
```
https://github.com/apache/nuttx/actions/runs/11338970256/job/31533042367?pr=14282

**Comment by masayuki2009** [comment]
> Sorry @GUIDINGLI I think [coredump.h](https://github.com/apache/nuttx/pull/14262/files#diff-2eb1883c9a5d24fe74f8e114591c808b0bda11c407d3f2c851560d7d357a4dc6) might be breaking the other build:

I noticed that qemu-i486:nsh has the same error.

**Comment by xiaoxiang781216** [comment]
it's strange that ci doesn't catch this problem. @gneworld please fix the issue.

**Comment by lupyuen** [comment]
@xiaoxiang781216 The Labeler missed out a PR Label, which should trigger a full rebuilt of all targets. Here is the fix: https://github.com/apache/nuttx/pull/14288

**Pull request merged**
