### PR TITLE
drivers/usb: Fix the typo error in Kconfig

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
## Summary
Minor change

## Impact
usb Kconfig

## Testing
Pass CI

### CODE REVIEW

**Review by pkarashchenko — APPROVED** [review]

**Review by acassis — APPROVED** [review]

**Comment by pkarashchenko** [comment]
Seems some defconfigs should be normalized now

**Comment by xiaoxiang781216** [comment]
> Seems some defconfigs should be normalized now

Yes, fix it.

**Comment by pkarashchenko** [comment]
Still require some changes in `defconfig`s

**Comment by xiaoxiang781216** [comment]
Fix again.

**Pull request merged**
