### PR TITLE
arch/sim: Provide a dummy g_reg_offs for arm64

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
## Summary

to avoid the link error on M1/M2 MacOS

## Impact

M1/M2 macOS

## Testing

ci

### CODE REVIEW

**Comment by xiaoxiang781216** [comment]
@duduita could you try this patch?

**Comment by duduita** [comment]
I got the following error:
```
ld: warning: pointer not aligned at address 0x10006C5D2 ('_g_tcbinfo' + 18 from nuttx.rel)
ld: unaligned pointer(s) for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [nuttx] Error 1
make: *** [nuttx] Error 2
```

**Comment by xiaoxiang781216** [comment]
It may due to the fields before reg_off doesn't align on 8 bytes boundary, @anjiahao1 will provide a fix.

**Comment by duduita** [comment]
Many thanks, @xiaoxiang781216 @anjiahao1!

**Comment by masayuki2009** [comment]
g_reg_offs was introduced in https://github.com/apache/nuttx/pull/9859

**Comment by xiaoxiang781216** [comment]
replace with https://github.com/apache/nuttx/pull/11207

**Pull request closed without merging**
