### PR TITLE
gcov: Modify gcov's kconfig

### PR DESCRIPTION
**Pull request by W-M-R**
## Summary
1. Use CONFIG_LIB_GCOV_TOOLCHAIN_GNU or CONFIG_LIB_GCOV_TOOLCHAIN_CLANG to link the corresponding toolchain library,because different compilers require different libraries
2. Move gcov's kconfig from sched to libc/gcov as a separate functional module, similar to gdbstub
3. Later, the gcov implementation of gcc and clang with smaller code size may be merged, but their implementation cannot guarantee that every version of gcc or clang can be used, so this method is intended to retain the compiler implementation and the nuttx implementation that will be merged into libc/gcov later.
## Impact
Depend on  https://github.com/apache/nuttx-apps/pull/2805
## Testing
enable CONFIG_LIB_GCOV,CONFIG_SYSTEM_GCOV, and set the corresponding gcov compilation options and run gcov -d /data/xxx to get the detection data.

### CODE REVIEW

**Comment by W-M-R** [comment]
Later, the gcov implementation of gcc and clang with smaller code size may be merged, but their implementation cannot guarantee that every version of gcc or clang can be used, so this method is intended to retain the compiler implementation and the nuttx implementation that will be merged into libc/gcov later.

**Comment by W-M-R** [comment]
Since sim/kasan uses gcov, CI errors are caused by dependency changes. In addition, can we consider centralizing sim/kasan to kasan function detection and removing gcov?

**Comment by cederom** [comment]
This (closed?) PR is referenced by https://github.com/apache/nuttx-apps/pull/2805. What do we do? :-)

**Comment by cederom** [comment]
This (closed?) PR is referenced by https://github.com/apache/nuttx-apps/pull/2805 reopening :-)

**Pull request closed without merging**
