### PR TITLE
Fix the ci break

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
## Summary

- risc-v/esp32c3: Move .gitignore from common/src to common
  https://github.com/apache/nuttx/pull/7839
- ci: Exclude litex/arty_a7 from tools/ci/testlist/risc-v.dat 
   https://github.com/apache/nuttx/pull/7832
- tools/cibuild.sh: Move the installation directory from prebuilt to tools
- tools/cibuild.sh: Sync the installation between macOS and Ubuntu 
- workflow: Move ccache setting from build.yml to cibuild.sh 
  https://github.com/apache/nuttx/pull/7834

## Impact

- Skip litex/arty_a7 board
- Fix ccache error

## Testing
Pass CI

### CODE REVIEW

**Review by pkarashchenko — APPROVED** [review]

**Comment by xiaoxiang781216** [comment]
> @xiaoxiang781216 should we ignore macOS build failures?

I don't know why macOS build stuck, let' restart the build to try again.

**Comment by xiaoxiang781216** [comment]
@pkarashchenko I found the root cause why macOS stuck, it should work now.

**Comment by gustavonihei** [comment]
Sorry for all the trouble my latest PRs may have caused. 

But changing the prebuilt dir will bring back the #7636 issue.

The prebuilts should be isolated in their own out of tree dir, so that the GitHub action packs everything at the of the workflow.

**Comment by gustavonihei** [comment]
https://github.com/apache/nuttx/blob/61563d6004fe92ae50d567bc4f81c81f60d8c757/.github/workflows/build.yml#L201

We need to indicate to the GitHub Cache action the new path to be cached, which is now `./sources/tools`.

**Comment by xiaoxiang781216** [comment]
> https://github.com/apache/nuttx/blob/61563d6004fe92ae50d567bc4f81c81f60d8c757/.github/workflows/build.yml#L201
> 
> We need to indicate to the GitHub Cache action the new path to be cached, which is now `./sources/tools`.

@gustavonihei done.

**Comment by pkarashchenko** [comment]
AVR build fails

**Comment by xiaoxiang781216** [comment]
avr doesn't change, I can't understand why avr fail.

**Comment by xiaoxiang781216** [comment]
@pkarashchenko I remove hex generation from build, let's see what happen with the new change.

**Comment by pkarashchenko** [comment]
@xiaoxiang781216 please fill an issue for hex generation for AVR, so it is not forgotten

**Review by pkarashchenko — APPROVED** [review]

**Comment by pkarashchenko** [comment]
@xiaoxiang781216 somehow I can't merge this PR, because when I press merge button, I'm getting some OAuth error

**Comment by xiaoxiang781216** [comment]
It's strange, I can merge it.

**Comment by pkarashchenko** [comment]
@xiaoxiang781216 I just checked with another PR. This seems to be a mobile app issue since I can merge from a laptop, but not from GitHub Android app.

**Comment by xiaoxiang781216** [comment]
> @xiaoxiang781216 please fill an issue for hex generation for AVR, so it is not forgotten

Here: https://github.com/apache/nuttx/issues/7851

**Pull request merged**
