### PR TITLE
mmcsd: update cid reg layout

### PR DESCRIPTION
**Pull request by gneworld**
refer spec: https://www.jedec.org/sites/default/files/docs/JESD84-B51.pdf

### CODE REVIEW

**Comment by davids5** [comment]
@gneworld Please describe the testing you have done to insure this did not break any existing code.

**Comment by gneworld** [comment]
> @gneworld Please describe the testing you have done to insure this did not break any existing code.

I have make some tests on a wearable device configured with the KIOXIA_THGBMNG5D1LBAIK 4GB eMMC using the mmc-utils tool.

image

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by xiaoxiang781216** [comment]
@davids5 do you have more concern?

**Comment by davids5** [comment]
> @davids5 do you have more concern?

I was asking about  regression testing. Testing real HW (stm32, stm32h7) that uses SDMMC. to just verify this did not break anything.

**Comment by xiaoxiang781216** [comment]
> > @davids5 do you have more concern?
> 
> I was asking about regression testing. Testing real HW (stm32, stm32h7) that uses SDMMC. to just verify this did not break anything.

This patch fixes the code bug, and test with the device we are using, all looks good.
BTW, CID is only used to output log, so I don't expect any break will happen.
Do you think so?

**Comment by davids5** [comment]
@xiaoxiang781216 Ok

**Pull request merged**
