### PR TITLE
sim/lvgl_fb: upgrade to lvgl version v9

### PR DESCRIPTION
**Pull request by XuNeo**
## Summary

Upgrade simulator config for LVGL to version v9.

Limitations:
1. Should wait LVGL to release v9.0.1 to fix existing issues firstly.
2. cmake cannot handle `CONFIG_LV_TXT_BREAK_CHARS=" ,.;:-_)]}"` correctly, needs to config this option to `""`

## Impact

Existing lvgl application needs to follow latest lvgldemo to upgrade to LVGL v9.

## Testing
Locally test with sim:lvgl_fb

### CODE REVIEW

**Comment by acassis** [comment]
Amazing!!! @XuNeo

**Comment by acassis** [comment]
Please rebase to fix the CI issue

**Comment by XuNeo** [comment]
Rebased to master. CI will still fail because it needs to compile with https://github.com/apache/nuttx-apps/pull/2312.
Still waiting lvgl to release version v9.0.1.

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by xiaoxiang781216** [comment]
> Rebased to master. CI will still fail because it needs to compile with [apache/nuttx-apps#2312](https://github.com/apache/nuttx-apps/pull/2312). Still waiting lvgl to release version v9.0.1.

@XuNeo all other defconfig which use lvgl need update too.

**Comment by xiaoxiang781216** [comment]
@XuNeo is this patch ready for merging?

**Comment by XuNeo** [comment]
Yes, it's ready for merging. The removed color16 byte order swap issue should be fixed by driver in future.

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by XuNeo** [comment]
I have run `tools/refresh.sh` to update the changed `defconfig`, mainly to remove the unsupported `CONFIG_LV_COLOR_16_SWAP `. Fixed one config error in `esp32s2-kaluga-1:lvgl_ili9341`.

**Review by xiaoxiang781216 — APPROVED** [review]

**Pull request merged**
