### PR TITLE
Documentation: add NuttX-12.7.0 release notes

### PR DESCRIPTION
**Pull request by jerpelea**
## Summary
Add release notes for 12.7.0 release

NOTE
Ddue to the quality of commit titles new unsorted sections were added. 
If the titles and commit descriptions will improve those sections will disappear in future releases.

## Impact
Release

## Testing
CI

### CODE REVIEW

**Comment by nuttxpr** [comment]
[**\[Experimental Bot, please feedback here\]**](https://github.com/search?q=repo%3Aapache%2Fnuttx+13552&type=issues)



This PR appears to meet the basic NuttX requirements for a release notes update. Here's a breakdown:

**Meets Requirements:**

* **Summary:** Clearly states the purpose of the PR is to add release notes. The note about commit titles provides helpful context.
* **Impact:**  Correctly identifies this as a "Release" impact, signifying a documentation update for a specific NuttX version.
* **Testing:**  "CI" implies the PR will be validated through the Continuous Integration system, which is standard practice.

**Potential Improvements (Based on Limited Information):**

* **Testing (Specificity):** While "CI" is sufficient, providing more details about the specific CI checks relevant to release notes would be beneficial. This could include:
    * Confirmation that the release notes build correctly (e.g., format, links).
    * Mention any automated checks for completeness against the changelog or commit history. 

**Overall:** This PR seems aligned with NuttX requirements. Adding more specifics about the CI testing would further strengthen it.

**Comment by jerpelea** [comment]
@lupyuen they will be added to the release

**Comment by jerpelea** [comment]
@lupyuen 

https://github.com/apache/nuttx/pull/13788
https://github.com/apache/nuttx/pull/13789

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by cederom** [comment]
12.7 release?? did i miss anything? o_O

**Comment by lupyuen** [comment]
FYI [nuttx/releases/12.7](https://github.com/apache/nuttx/tree/releases/12.7) (https://github.com/apache/nuttx/commit/10e44f8915a4e4dc016f117bc75973750c7e3edf) was tested successfully with QEMU RISC-V and OSTest for [rv-virt:knsh64](https://gist.github.com/lupyuen/6023caef54365f61ed97d42b194444a5). Stress Test of rv-virt:knsh64 was also successful for [20 iterations](https://gist.github.com/lupyuen/dd8ed9e70dd60dad75c83fe1224817dc). Thanks! 🎉

**Pull request merged**
