### PR TITLE
arm/sama5: fix recursive dependency

### PR DESCRIPTION
**Pull request by anchao**
## Summary

arm/sama5: fix recursive dependency

```
arch/arm/src/sama5/Kconfig:819:error: recursive dependency detected!
For a resolution refer to Documentation/kbuild/kconfig-language.txt
subsection "Kconfig recursive dependency limitations"
arch/arm/src/sama5/Kconfig:819: choice <choice> contains symbol SAMA5_FLEXCOM0_USART
For a resolution refer to Documentation/kbuild/kconfig-language.txt
subsection "Kconfig recursive dependency limitations"
arch/arm/src/sama5/Kconfig:824: symbol SAMA5_FLEXCOM0_USART is part of choice SAMA5_FLEXCOM0_USART
For a resolution refer to Documentation/kbuild/kconfig-language.txt
subsection "Kconfig recursive dependency limitations"
arch/arm/src/sama5/Kconfig:824: symbol SAMA5_FLEXCOM0_USART is part of choice <choice>
```

Signed-off-by: chao an <anchao@xiaomi.com>

## Impact

N/A

## Testing

ci-check

### CODE REVIEW

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by TimJTi** [comment]
Since this was (undoubtedly) down to me, I'm wondering why the CI checks didn't fail for my PR?

(The lines in Kconfig are an erroneous leftover from my struggles to get the PR and my repo clone sorted...sorry!)

**Comment by anchao** [comment]
> Since this was (undoubtedly) down to me, I'm wondering why the CI checks didn't fail for my PR?
> 
> (The lines in Kconfig are an erroneous leftover from my struggles to get the PR and my repo clone sorted...sorry!)

It's ok, It seems CI doesn't check the return value of configure.sh(kconfig-conf), let's fix that.

**Comment by TimJTi** [comment]
> ...It seems CI doesn't check the return value of configure.sh(kconfig-conf), let's fix that.

What did you run to show the error, please? I can't imagine I didn't see it in the normal ruin of building/testing so would be good to know about it for the future :)

**Comment by TimJTi** [comment]
Thanks, appreciate you replying. I will make sure I do that in future (up until today I have used just one defconfig which has, I now realise, caused me lots of grief, so now have 1 per PR...so am more likely to see this now anyway)

**Pull request merged**
