### PR TITLE
sensor:Update sensor type

### PR DESCRIPTION
**Pull request by Otpvondoiats**
## Summary

1. Sort the existing sensor types and align them to aosp
2. Add sensor info to get structure, align parameters with aosp
3. Add some sensor types in aosp.

## Impact
n/a

## Testing

- Environment:

OS and Version: Ubuntu 20.04.6 LTS x86_64
GCC Version: 13.1.0
SIM:  ./tools/configure.sh sim:nsh

- Order:

./nuttx

### CODE REVIEW

**Comment by nuttxpr** [comment]
[**\[Experimental Bot, please feedback here\]**](https://github.com/search?q=repo%3Aapache%2Fnuttx+13552&type=issues)



The PR summary is somewhat informative but could be more specific. Mentioning specific sensor types or groups and the reasoning behind aligning with AOSP would make it stronger. 

However, the **major issue** is the **lack of detail in the Impact and Testing sections.** 

**Here's a breakdown of what's missing and how to improve:**

**Impact:**

* **Be specific.**  "n/a" isn't acceptable. Address **every** bullet point. Even if the answer is NO, state it explicitly (e.g., "Impact on build: NO"). 
* **For YES answers, provide details.**  
    * **New feature:** Which sensor types are added? What functionality do they enable?
    * **User impact:**  Will any existing APIs change? Will users need to modify their applications?
    * **Hardware impact:** Which architectures/boards are affected? Any new driver requirements?
    * **Documentation:** Is new documentation needed? Where is it located in the PR?
    * **Compatibility:** Any potential issues with older NuttX versions or other software that interacts with sensors?

**Testing:**

* **Insufficient information.** The provided details are too generic.
* **Be explicit about the changes.** What tests were run to verify the sensor sorting, info structure, and new sensor types?
* **Show before/after logs relevant to the changes.** Include snippets that demonstrate the problem being solved or the new functionality in action.
* **Test on real hardware if possible.**  Simulation is a good start, but testing on a real board relevant to the added sensor types strengthens the PR.

**In short, the PR currently doesn't meet the NuttX requirements due to the lack of detail in the Impact and Testing sections.** Providing specific and comprehensive information in these areas is crucial for reviewers to understand and approve the changes.

**Review by acassis — APPROVED** [review]

**Comment by acassis** [comment]
@Otpvondoiats @xiaoxiang781216 why is this error:

```
Configuration/Tool: sim/sqlite
2024-09-26 12:04:48
------------------------------------------------------------------------------------
  Cleaning...
  Configuring...
  Building NuttX...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 5633k    0 5633k    0     0  6005k      0 --:--:-- --:--:-- --:--:-- 5999k
100 9795k    0 9795k    0     0  5010k      0 --:--:--  0:00:01 --:--:-- 5010k
100 13.4M    0 13.4M    0     0  5445k      0 --:--:--  0:00:02 --:--:-- 5446k
configure: WARNING: Can't find Tcl configuration definitions
configure: WARNING: *** Without Tcl the regression tests cannot be executed ***
configure: WARNING: *** Consider using --with-tcl=... to define location of Tcl ***
make[4]: warning: -j0 forced in submake: resetting jobserver mode.
  Normalize sim/sqlite
```

**Comment by xiaoxiang781216** [comment]
> @Otpvondoiats @xiaoxiang781216 why is this error:
> 
> ```
> Configuration/Tool: sim/sqlite
> 2024-09-26 12:04:48
> ------------------------------------------------------------------------------------
>   Cleaning...
>   Configuring...
>   Building NuttX...
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
> 100 5633k    0 5633k    0     0  6005k      0 --:--:-- --:--:-- --:--:-- 5999k
> 100 9795k    0 9795k    0     0  5010k      0 --:--:--  0:00:01 --:--:-- 5010k
> 100 13.4M    0 13.4M    0     0  5445k      0 --:--:--  0:00:02 --:--:-- 5446k
> configure: WARNING: Can't find Tcl configuration definitions
> configure: WARNING: *** Without Tcl the regression tests cannot be executed ***
> configure: WARNING: *** Consider using --with-tcl=... to define location of Tcl ***
> make[4]: warning: -j0 forced in submake: resetting jobserver mode.
>   Normalize sim/sqlite
> ```

look like the ci temp failure, let's restart ci.

**Comment by cederom** [comment]
build errors :\

**Review by xiaoxiang781216 — APPROVED** [review]

**Pull request merged**
