### PR TITLE
lilygo_tbeam_lora_gps/gps: Enable GNSSUTILS_MINMEA_LIB for EXAMPLES_GPS

### PR DESCRIPTION
**Pull request by JianyuWang0623**
## Summary
- The board lilygo_tbeam_lora_gps/gps enables only EXAMPLES_GPS but not enable MINMEA.
- Log
```
  ./gps_main.c:33:10: fatal error: minmea/minmea.h: No such file or directory
     33 | #include <minmea/minmea.h>
        |          ^~~~~~~~~~~~~~~~~
  compilation terminated.
  ERROR: xtensa-esp32-elf-gcc failed: 1
         command: xtensa-esp32-elf-gcc -MT ./gps_main.c.github.workspace.sources.apps.examples.gps.o  -M '-fno-common' '-Wall' '-Wstrict-prototypes' '-Wshadow' '-Wundef' '-Wno-attributes' '-Wno-unknown-pragmas' '-Wno-psabi' '-Os' '-fno-strict-aliasing' '-fomit-frame-pointer' '-ffunction-sections' '-fdata-sections' '-mlongcalls' '-isystem' '/github/workspace/sources/nuttx/include' '-D__NuttX__' '-DNDEBUG' '-D__KERNEL__' '-Wno-cpp' '-Werror' '-I' '/github/workspace/sources/apps/include' ./gps_main.c
  gps_main.c:33:10: fatal error: minmea/minmea.h: No such file or directory
     33 | #include <minmea/minmea.h>
        |          ^~~~~~~~~~~~~~~~~
  compilation terminated.
```

## Impact
The board lilygo_tbeam_lora_gps:gps

## Testing
```
./tools/configure.sh -l lilygo_tbeam_lora_gps:gps
```
compilation ok, failed in link stage, need check CI result.

### CODE REVIEW

**Comment by JianyuWang0623** [comment]
depends on https://github.com/apache/nuttx-apps/pull/2584

**Review by lupyuen — APPROVED** [review]

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by JianyuWang0623** [comment]
Maybe `EXAMPLES_GPS` should depends on `GNSSUTILS_MINMEA_LIB`?

**Review by acassis — APPROVED** [review]

**Comment by acassis** [comment]
> Maybe `EXAMPLES_GPS` should depends on `GNSSUTILS_MINMEA_LIB`?

Please don't do it. "depends on" will hide the GPS Example and users will not know it exists

**Comment by JianyuWang0623** [comment]
> > Maybe `EXAMPLES_GPS` should depends on `GNSSUTILS_MINMEA_LIB`?
> 
> Please don't do it. "depends on" will hide the GPS Example and users will not know it exists

OK, Indeed

**Review by xiaoxiang781216 — APPROVED** [review]

**Pull request merged**
