### PR TITLE
implement read-write lock based on nxmutex

### LINKED ISSUE #6012: Low priority tasks interrupt high priority threads
By SystemView, I found some puzzling result,  low priority FOC main task interrupt high priority FOC control pthread as shown in the figure around  23.920536845s, the problem led to the failure to complete the control of this cycle.
My configuration:
     STM32F405RG
     CPU freq 168MHz
    FOC_PWM_FREQ=10000
    FOC_NOTIFIER_FREQ=10000
  
Context:  
     ISR34 - FOC ADC handler
     ISR76 - Aux ADC DMA handler (VBUS)
     ISR15 - SysTick
     ISR3  - Hard Fault
     pt-0x801ae29 - FOC control pthread (priority 255)
     foc task  - FOC main task, low priority work (priority 150)

image

### PR DESCRIPTION
**Pull request by zouboan**
## Summary
As suggested by @raiden00pl ， I create this PR try to fix #6012
but I feel my implementation was something dumb, and maybe the community has a better implementation，I create this PR  to get feedback from the community
## Impact
`filelist` operation
## Testing
customer boards

### CODE REVIEW

**Comment by acassis** [comment]
I think it is fine!
@pkarashchenko @gregory-nutt what do you think?

**Comment by zouboan** [comment]
There's a strange ci error, it doesn't seem to be related to this PR, I don't know why

**Comment by mu578** [comment]
failing to build, no suitable compiler found, all failed at configuration steps ; but no clear backlog of the hidden real problem.

**Comment by pkarashchenko** [comment]
I will take a look from Monday

**Comment by zouboan** [comment]
@mu578 Interestingly, other people's PR also have ` /usr/bin/bash: arm-nuttx-eabi-gcc: command not found` error in ci check Linux (arm-13), for example:
https://github.com/apache/nuttx/actions/runs/5492952477/jobs/10010805446?pr=9741#step:7:407
but ci passed

**Comment by mu578** [comment]
> @mu578 Interestingly, other people's PR also have ` /usr/bin/bash: arm-nuttx-eabi-gcc: command not found` error in ci check Linux (arm-13), for example:
> https://github.com/apache/nuttx/actions/runs/5492952477/jobs/10010805446?pr=9741#step:7:407
> but ci passed

yes I have noticed, while browsing issues since few days, that's the reason I did suspect a regression commit on configuration files, something like a mismatch arch between toolchain and target.

**Comment by pkarashchenko** [comment]
The real problem here is not the absence of a toolchain (that is only a warning), but
```
2023-07-09T10:22:02.1037278Z ====================================================================================
2023-07-09T10:22:02.1060293Z Configuration/Tool: lm3s6432-s2e/nsh,CONFIG_ARM_TOOLCHAIN_GNU_EABI
2023-07-09T10:22:02.1145810Z ------------------------------------------------------------------------------------
2023-07-09T10:22:02.1146739Z   Cleaning...
2023-07-09T10:22:04.9112245Z   Configuring...
2023-07-09T10:22:07.8326705Z   Disabling CONFIG_ARM_TOOLCHAIN_GNU_EABI
2023-07-09T10:22:07.8443690Z   Enabling CONFIG_ARM_TOOLCHAIN_GNU_EABI
2023-07-09T10:22:09.8983241Z   Building NuttX...
2023-07-09T10:22:52.9651725Z arm-none-eabi-ld: /github/workspace/sources/nuttx/nuttx section `.data' will not fit in region `flash'
2023-07-09T10:22:52.9656210Z arm-none-eabi-ld: region `flash' overflowed by 136 bytes
2023-07-09T10:22:52.9784684Z make[1]: *** [Makefile:189: nuttx] Error 1
2023-07-09T10:22:52.9790165Z make: *** [tools/Unix.mk:527: nuttx] Error 2
2023-07-09T10:22:52.9790786Z make: Target 'all' not remade because of errors.
```

**Comment by mu578** [comment]
need to find 136 bytes to eliminate then.

**Comment by zouboan** [comment]
@mu578 @pkarashchenko   I have changed read-write lock to be optional in Kconfig to eliminate ci error

**Comment by TaiJuWu** [comment]
Maybe it’s called rw_semaphore because there is a rw_spinlock in Linux.

**Comment by zouboan** [comment]
#6012 has a more efficient solution in #11125, so i close this PR

**Pull request closed without merging**
