### PR TITLE
ESP32 BLE Bugfix

### PR DESCRIPTION
**Pull request by pkarashchenko**
## Summary
Make ESP32 BLE mighty again

## Impact
Fix ESP32 BLE operation

## Testing
`esp32-devkitc:ble` with debug assertions enabled

### CODE REVIEW

**Comment by btashton** [comment]
@pkarashchenko  can you explain the double free? I fixed a lot of memory leak issues in the past here so I'm suspect of these removals. Also let's verify the hcisocket sim build still works if possible. I won't be able to test that for a couple weeks while traveling.

**Comment by pkarashchenko** [comment]
> @pkarashchenko can you explain the double free? I fixed a lot of memory leak issues in the past here so I'm suspect of these removals. Also let's verify the hcisocket sim build still works if possible. I won't be able to test that for a couple weeks while traveling.

I have a limited testing capabilities so only able to test with esp32 board. If you can advise on how to verify `hcisocket` I would appreciate.
The double free issue is next:
1. The buffer is allocated in `bt_receive` and passed to `hci_rx_work` via `g_lp_rxlist`.
2. `hci_rx_work` dequeue the buffer and call `hci_event`. In my case the call sequence was next: `hci_le_meta_event` -> `le_adv_report` with 1 report.
3. With the latest code the `hci_event` calls `bt_buf_release(buf);` before return and later the `bt_buf_release(buf);` was called at the end of while loop in `hci_event`, so buffer was released twice.

I found this by simply enabling the debug assertions and getting `_assert: Assertion failed : at file: bluetooth/bt_buf.c:392 task: lpwork 0x400d2510`

**Comment by pkarashchenko** [comment]
@btashton I think here is where it was added https://github.com/apache/nuttx/commit/c6947199b21#diff-775a19937e402f32f385386681c5c61338b6466ae6e5e6d139ad68fc6c157a01

**Comment by pkarashchenko** [comment]
@btashton I do not think that I'm undoing those changes. Just please see the obvious double release in `hci_rx_work` -> `while ((buf = bt_dequeue_bufwork(list)) != NULL)` -> `switch (buf->type)` -> `default:` -> `bt_buf_release(buf);` -> `bt_buf_release(buf);` at the end of `while ((buf = bt_dequeue_bufwork(list)) != NULL)`.

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by btashton** [comment]
> Can anybody from the team help me with HCI socket verification as I'm unfamiliar with what are the prerequisites to get that test done. Is it enough just a pure Linux system running SIM or I need some special HW?

All you should need is Linux and hci0 showing up in the list of Bluetooth devices. The doc I linked showed the capability you have to give the NuttX binary to be able to setup the socket. 

That said I tried to give this as good of a review as I could from mobile so I'm fine approving this and will test when I'm back with my computer.

**Review by btashton — APPROVED** [review]

**Pull request merged**
