### PR TITLE
fs/fs_epoll: add oneshot list to handle the EPOLLONESHOT correctly

### PR DESCRIPTION
**Pull request by CV-Bowen**
## Summary
https://github.com/apache/nuttx-apps/pull/1625 mentioned that nng can't work with epoll.
After analysis, the epoll do not handle the EPOLLONESHOT events correctly, the epoll node with events EPOLLONESHOT should be allowed to be reset by epoll_ctl(EPOLL_CTL_MOD) after notifed, but old implementation directly moved it to the free list, which is not corret.
In this PR, add a new oneshot list to solve this problem: the the epoll node with events EPOLLONESHOT will be added to the oneshot list after notified and move to setup list again after user call epoll_ctl(EPOLL_CTL_MOD) to reset it.

@jturnsek Could you take a look?

## Impact
epoll

## Testing
nng test in sim

### CODE REVIEW

**Comment by jturnsek** [comment]
@CV-Bowen It looks ok. NNG is rearming oneshot events, so this must be it.

**Comment by CV-Bowen** [comment]
> @CV-Bowen It looks ok. NNG is rearming oneshot events, so this must be it.

@jturnsek Thanks, @acassis Do you have more concern?

**Comment by jturnsek** [comment]
> so it's better to make epoll as the default setting

I would say no, because with small number of fds, poll should be more efficient. At least on Linux. It is the other way around when large number of fd used.

**Comment by CV-Bowen** [comment]
Could you merge this PR if no more comments? @pkarashchenko

**Pull request merged**
