### PR TITLE
driver/audio: low level reset must always succeed.

### PR DESCRIPTION
**Pull request by mks2183**
## Summary
    - considering simplicity and design assumption, the reset function must work without flaw.
      If it fails, there is no way to recover but to reset again. so checking return status does not
      bring additional benefit.
    
    - There is unnecessary switch inside switch which is making code not too readable
   
## Impact
    
     - There is no impact as it is mostly code style issue

## Testing

    - There is no testing done as it was not required for this minor fix.

### CODE REVIEW

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by mks2183** [comment]
Hi Sir @xiaoxiang781216 ,

Thanks for your review.

Regards,
Manish

**Comment by xiaoxiang781216** [comment]
> Hi Sir @xiaoxiang781216 ,
> 
> Thanks for your review.
> 

You are welcome, but please remove the merge patch from PR.

**Comment by mks2183** [comment]
Hi Sir @xiaoxiang781216 ,

I will remove merger patch from PR & will doc cherry-pick and then raise again. Sorry for this confusion.

Regards,
Manish

**Comment by mks2183** [comment]
Closing pull request as merge patch was there in branch so without making any confusion, the patch will be cherry-picked in new branch and I will again raise it

**Pull request closed without merging**
