### PR TITLE
fs: Define DT_xxx to number directly

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
## Summary

and map DTYPE_xxx to DT_xxx like other OS

## Impact

no real change

## Testing

Pass CI

### CODE REVIEW

**Review by pkarashchenko — APPROVED** [review]

**Comment by yamt** [comment]
what's the point of this change? are you going to remove DTYPE_xxx?

**Comment by xiaoxiang781216** [comment]
> what's the point of this change?

There is code which redefines DT_xxxx(e.g., http://www.aleph1.co.uk/gitweb/?p=yaffs2.git;a=blob;f=direct/yportenv.h;h=5a79f93583b963d715b0dee9a0b533363c1511e1;hb=HEAD#l52).  This change avoids the compiler generate the macro redefinition warning.

> are you going to remove DTYPE_xxx?

No.

**Comment by yamt** [comment]
> > what's the point of this change?
> 
> There is code which redefines DT_xxxx(e.g., http://www.aleph1.co.uk/gitweb/?p=yaffs2.git;a=blob;f=direct/yportenv.h;h=5a79f93583b963d715b0dee9a0b533363c1511e1;hb=HEAD#l52). This change avoids the compiler generate the macro redefinition warning.

why don't you disable CONFIG_YAFFS_PROVIDE_DEFS and use definitions for nuttx?

**Comment by xiaoxiang781216** [comment]
Since iattr  and ATTR_xxx isn't defined in nuttx.

**Comment by yamt** [comment]
> Since iattr and ATTR_xxx isn't defined in nuttx.

it's something you should provide as a part of nuttx glue logic, isn't it?

anyway, if yaffs2 is broken, i'd suggest to fix it instead.

**Comment by xiaoxiang781216** [comment]
> > Since iattr and ATTR_xxx isn't defined in nuttx.
> 
> it's something you should provide as a part of nuttx glue logic, isn't it?
> 

Sorry, I don't think so. If NuttX can make the change to more compatible with 3rd party library and without any side effect. Why not do it?

> anyway, if yaffs2 is broken, i'd suggest to fix it instead.

But it can compile without any warning with Linux which define these macros too since the compiler allow the same macro define multiple times if the late definition is same as earlier one.

**Comment by yamt** [comment]
> > > Since iattr and ATTR_xxx isn't defined in nuttx.
> > 
> > 
> > it's something you should provide as a part of nuttx glue logic, isn't it?
> 
> Sorry, I don't think so. If NuttX can make the change to more compatible with 3rd party library and without any side effect like this patch. Why not do it?
> 
> > anyway, if yaffs2 is broken, i'd suggest to fix it instead.
> 
> But it can compile without any warning with Linux which define these macros too since the compiler allow the same macro define multiple times if the late definition is same as earlier one.

for the most of macros in the file is defined as the following. i don't understand why these need to be different.
```
#ifndef XATTR_REPLACE
#define XATTR_REPLACE 2
#endif
```

**Comment by pkarashchenko** [comment]
@xiaoxiang781216 @yamt so what is the path to move forward here? I read that this change brings regression to `yaffs2` and the natural step seems to be reverting of a change and re-evaluating it to a new solution that covers broken cases.

**Comment by xiaoxiang781216** [comment]
Sorry, I don't see there is anything reason to revert this patch.

**Pull request merged**
