### PR TITLE
gpio: use small lock to protect configgpio

### PR DESCRIPTION
**Pull request by hujun260**
## Summary

gpio: use small lock to protect configgpio

reason:
We would like to replace the critical section with a small lock.

## Impact

gpio

## Testing
ci

### CODE REVIEW

**Comment by nuttxpr** [comment]
[**\[Experimental Bot, please feedback here\]**](https://github.com/search?q=repo%3Aapache%2Fnuttx+13552&type=issues)



No, this PR does not fully meet the NuttX requirements.  While it provides *some* information, it lacks crucial details.

Here's a breakdown of what's missing:

* **Summary:**  It mentions *what* is being changed (replacing a critical section with a small lock) but not *why* this is necessary.  What problem does this solve?  What are the benefits (e.g., performance improvement, reduced interrupt latency)?  It also lacks specifics on *how* the change is implemented.  Which functions are modified?  Are new functions introduced?  Are there any algorithm changes?  Finally, issue references are missing.

* **Impact:** The single word "gpio" is insufficient.  It needs to explicitly answer *all* the impact questions (user, build, hardware, documentation, security, compatibility) with "YES" or "NO" and provide descriptions where necessary. Even if the answer is "NO," it should still explicitly state "NO."  For example, "Impact on user: NO" or "Impact on hardware: YES (affects all platforms using GPIO)."

* **Testing:**  "ci" is not acceptable.  The PR needs to specify the *specific* build hosts and targets tested.  OS, CPU architecture, compiler, board, and configuration details are all required.  Critically, it's missing the **actual testing logs** before and after the change, which are essential for demonstrating that the change works as intended and doesn't introduce regressions.


In short, the PR needs substantially more detail to be acceptable.  It should clearly articulate the motivation, implementation, and impact of the change, along with thorough testing evidence.

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by anchao** [comment]
@hujun260 @xiaoxiang781216

Emm ... Do you think this code works properly? 

image

**Comment by lupyuen** [comment]
Sorry @hujun260 wonder if we missed out something for Tiva Spin Lock?
https://github.com/NuttX/nuttx/actions/runs/12370858664/job/34525845581#step:7:595
```text
Configuration/Tool: dk-tm4c129x/ipv6,CONFIG_ARM_TOOLCHAIN_GNU_EABI
chip/tm4c/tm4c_gpio.c: In function 'tiva_configgpio':
Error: chip/tm4c/tm4c_gpio.c:793:11: error: implicit declaration of function 'spin_lock_irqsave' [-Werror=implicit-function-declaration]
  793 |   flags = spin_lock_irqsave(&g_configgpio_lock);
      |           ^~~~~~~~~~~~~~~~~
Error: chip/tm4c/tm4c_gpio.c:844:3: error: implicit declaration of function 'spin_unlock_irqrestore' [-Werror=implicit-function-declaration]
  844 |   spin_unlock_irqrestore(&g_configgpio_lock, flags);
      |   ^~~~~~~~~~~~~~~~~~~~~~
```
More Tiva Spin Lock errors at NuttX Dashboard:
https://nuttx-dashboard.org/d/fe2bqg6uk7nr4a/build-logs-from-nuttx-build-farm?from=now-2d&to=now&timezone=browser&var-arch=$__all&var-subarch=$__all&var-board=$__all&var-config=$__all&var-group=arm-14&var-Filters=&__cf_chl_tk=iMcyDBki9HdNDQL8aX3EaEb47.pJs79A1d8oQT.A5Pc-1733459484-1.0.1.1-sNb9kVpXOg3kOHZEvTfrf9Z6j_CMoUsQnuwOU31abEE
Screenshot 2024-12-17 at 8 50 02 PM

**Comment by hujun260** [comment]
> Sorry @hujun260 wonder if we missed out something for Tiva Spin Lock? https://github.com/NuttX/nuttx/actions/runs/12370858664/job/34525845581#step:7:595
> 
> ```
> Configuration/Tool: dk-tm4c129x/ipv6,CONFIG_ARM_TOOLCHAIN_GNU_EABI
> chip/tm4c/tm4c_gpio.c: In function 'tiva_configgpio':
> Error: chip/tm4c/tm4c_gpio.c:793:11: error: implicit declaration of function 'spin_lock_irqsave' [-Werror=implicit-function-declaration]
>   793 |   flags = spin_lock_irqsave(&g_configgpio_lock);
>       |           ^~~~~~~~~~~~~~~~~
> Error: chip/tm4c/tm4c_gpio.c:844:3: error: implicit declaration of function 'spin_unlock_irqrestore' [-Werror=implicit-function-declaration]
>   844 |   spin_unlock_irqrestore(&g_configgpio_lock, flags);
>       |   ^~~~~~~~~~~~~~~~~~~~~~
> ```
> 
> More Tiva Spin Lock errors at NuttX Dashboard: https://nuttx-dashboard.org/d/fe2bqg6uk7nr4a/build-logs-from-nuttx-build-farm?from=now-2d&to=now&timezone=browser&var-arch=$__all&var-subarch=$__all&var-board=$__all&var-config=$__all&var-group=arm-14&var-Filters=&__cf_chl_tk=iMcyDBki9HdNDQL8aX3EaEb47.pJs79A1d8oQT.A5Pc-1733459484-1.0.1.1-sNb9kVpXOg3kOHZEvTfrf9Z6j_CMoUsQnuwOU31abEE Screenshot 2024-12-17 at 8 50 02 PM

https://github.com/apache/nuttx/pull/15240

**Pull request merged**
