### PR TITLE
cmake: update docker cmake to 3.26.0

### PR DESCRIPTION
**Pull request by raiden00pl**
## Summary
an attempt to fix broken `FetchContent_Declare()`
follow up to https://github.com/apache/nuttx/pull/9854

## Testing
CI

### CODE REVIEW

**Comment by acassis** [comment]
@xiaoxiang781216 is it possible to create an image already with cmake-format to avoid the pip error? (error #11 https://acassis.wordpress.com/2023/06/20/nuttx-ci-github-failures-list/ )

**Comment by xiaoxiang781216** [comment]
> @xiaoxiang781216 is it possible to create an image already with cmake-format to avoid the pip error? (error #11 https://acassis.wordpress.com/2023/06/20/nuttx-ci-github-failures-list/ )

It's possible if we create a dedicated docker image or reuse the one we used to build nuttx image.

**Comment by anchao** [comment]
> @xiaoxiang781216 is it possible to create an image already with cmake-format to avoid the pip error? (error #11 https://acassis.wordpress.com/2023/06/20/nuttx-ci-github-failures-list/ )

Hi @raiden00pl @acassis 
The cmake-format error has been resolved by PR https://github.com/apache/nuttx/pull/9864 , please rebase your code base and try again

**Comment by raiden00pl** [comment]
I'm opening this PR. 
Nordic configurations that use `FetchContent_Declare()` passed CI. 
This PR must be merged first before updating `testlist` files - the Docker image must be rebuild.

**Review by xiaoxiang781216 — APPROVED** [review]

**Pull request merged**
