### PR TITLE
mmcsd: add multi partitions support

### PR DESCRIPTION
**Pull request by gneworld**
## Summary

include boot0,boot1,gp1,gp2,gp3,gp4,rpmb

## Impact

mmcsd

## Testing
cortex M55

### CODE REVIEW

**Comment by nuttxpr** [comment]
[**\[Experimental Bot, please feedback here\]**](https://github.com/search?q=repo%3Aapache%2Fnuttx+13552&type=issues)



**No, this PR does not meet the NuttX requirements.** 

Here's why and how to improve it:

* **Missing Essential Information:** The provided description lacks crucial details needed for reviewers to understand and evaluate the changes.  

**How to Fix:**

1. **Expand the Summary:**
   * **Why is this change necessary?**  Clearly state the problem this PR addresses. Is it a bug fix, new feature, optimization, or something else?
   * **What part of the code is affected?** Be specific about the modules, files, or functions modified.
   * **How does it work?** Explain the technical details of your implementation.
   * **Link any relevant issues:** Connect your PR to existing issues on the NuttX and/or NuttX Apps repositories if applicable. This provides context and tracks progress.

2. **Complete the Impact Section:**
   * **Provide specific details for each "YES" answer.** For example, if there's an impact on the build process, explain what changes users need to make. 
   * **Be thorough.**  Even seemingly small changes can have unintended consequences. Consider all aspects listed in the requirements.

3. **Enhance the Testing Section:**
   * **Provide build host details:**  Specify the operating system, CPU architecture, and compiler version used for testing.
   * **Target details are insufficient:**  "cortex M55" is not enough information. Specify the exact board and configuration used.
   * **Include relevant log snippets:**  The current logs are placeholders. Include the *relevant* portions of your logs that demonstrate the problem before the change and the improvement after your change. 

**Example Improvement**

```
## Summary

This PR adds support for booting from SD/MMC devices on the Cortex-M55 platform.  It includes modifications to the boot loader stages (boot0, boot1) and the MMC/SD driver to enable loading the NuttX kernel from an SD card.

This change addresses [NuttX Issue #1234](https://github.com/apache/nuttx/issues/1234) which reported the inability to boot from SD cards on the M55.

## Impact

* **Is a new feature added?** YES - Support for booting from SD/MMC on Cortex-M55.
* **Impact on user:** YES - Users will need to configure their SD cards with a bootable NuttX image. Instructions on how to do this will be added to the documentation.
* **Impact on build:** NO
* **Impact on hardware:** YES - This specifically affects Cortex-M55 platforms and requires an SD/MMC card connected to the appropriate pins.
* **Impact on documentation:** YES - Documentation will be updated with instructions for booting from SD/MMC on the M55.
* **Impact on security:** NO 
* **Impact on compatibility:** NO
* **Anything else to consider:** N/A

## Testing

**Build Host:**
* OS: Ubuntu 20.04 LTS
* CPU: Intel Core i7-10700K
* Compiler: GCC 9.4.0

**Target:**
* Arch: Cortex-M55
* Board: [Name of your M55 board]
* Configuration: [Specify the board configuration used]

**Testing logs before change:**

```
[Relevant log output showing boot failure from SD card]
```

**Testing logs after change:**
```
[Relevant log output showing successful boot from SD card]
``` 
```

**Comment by gneworld** [comment]
image
can not reproduce ci error locally

**Comment by xiaoxiang781216** [comment]
@xuxin930 @cuiziwei1 please look

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by xuxin930** [comment]
> @xuxin930 @cuiziwei1 please look

@xiaoxiang781216 sure, let me clear this warning

**Comment by xuxin930** [comment]
> @xuxin930 @cuiziwei1 please look

@xiaoxiang781216 Toolchain.defs needs to be include before Config.mk in all boards, which means that the common judgment of GCC version in Config.mk will cause the Toolchain variables to not be seen.

It seems that Toolchain also needs to be defined in each arch. CC @cuiziwei1

**Review by GUIDINGLI — APPROVED** [review]

**Pull request merged**
