### PR TITLE
arm64:  Add support for FIQ interrupts

### PR DESCRIPTION
**Pull request by hujun260**
## Summary
To compile arm64 NuttX, use the following command:
 ./tools/configure.sh -l qemu-armv8a:nsh_fiq
To run，use the following command
 qemu-system-aarch64 -cpu cortex-a53 -nographic -machine virt,virtualization=on,gic-version=3 -net none -chardev stdio,id=con,mux=on -serial chardev:con -mon chardev=con,mode=readline -kernel ./nuttx

## Impact
none

## Testing
ok

### CODE REVIEW

**Review by jerpelea — APPROVED** [review]
please add commit message

**Comment by masayuki2009** [comment]
@hujun260 

Can you add a qemu configuration to test this PR?

**Comment by hujun260** [comment]
> @hujun260
> 
> Can you add a qemu configuration to test this PR?

 
To compile Arm64 NuttX, you can use the following command:
 ./tools/configure.sh -l qemu-armv8a:nsh

To run， you can use the following command:
 qemu-system-aarch64 -cpu cortex-a53 -nographic -machine virt,virtualization=on,gic-version=3 -net none -chardev stdio,id=con,mux=on -serial chardev:con -mon chardev=con,mode=readline -kernel ./nuttx

**Comment by hujun260** [comment]
> @hujun260
> 
> Can you add a qemu configuration to test this PR?

ok，use this boards/arm64/qemu/qemu-armv8a/configs/nsh_fiq/defconfig

**Review by acassis — APPROVED** [review]

**Pull request merged**
