### PR TITLE
Change nucleof429zi nsh defconfig

### PR DESCRIPTION
**Pull request by LuchianMihai**
## Summary
[nucleo-f4229zi](https://www.st.com/en/evaluation-tools/nucleo-f439zi.html#overview) board does not come with external ram.
Looking at netnsh config, these changes are also not present.

### CODE REVIEW

**Review by xiaoxiang781216 — APPROVED** [review]

**Review by jerpelea — COMMENTED** [review]
please update the title and add a commit message describing the need for the change
ex:
boards/arm/stm32/nucleo-f429zi: remove faulty nsh defconfig symbols 

[nucleo-f4229zi](https://www.st.com/en/evaluation-tools/nucleo-f439zi.html#overview) board does not come with external ram.
Looking at netnsh config, these changes are also not present.

**Comment by LuchianMihai** [comment]
> please update the title and add a commit message describing the need for the change ex: boards/arm/stm32/nucleo-f429zi: remove faulty nsh defconfig symbols
> 
> [nucleo-f4229zi](https://www.st.com/en/evaluation-tools/nucleo-f439zi.html#overview) board does not come with external ram. Looking at netnsh config, these changes are also not present.

I've saw this suggestion for the last couple PRs, Is there a guideline page somewhere?
Look like pattern for semantic commits, but with slashes instead colons.

**Comment by acassis** [comment]
> > please update the title and add a commit message describing the need for the change ex: boards/arm/stm32/nucleo-f429zi: remove faulty nsh defconfig symbols
> > [nucleo-f4229zi](https://www.st.com/en/evaluation-tools/nucleo-f439zi.html#overview) board does not come with external ram. Looking at netnsh config, these changes are also not present.
> 
> I've saw this suggestion for the last couple PRs, Is there a guideline page somewhere? Look like pattern for semantic commits, but with slashes instead colons.

Hi @LuchianMihai could you please include more details what kind of guideline are you looking for?

**Comment by LuchianMihai** [comment]
> > > please update the title and add a commit message describing the need for the change ex: boards/arm/stm32/nucleo-f429zi: remove faulty nsh defconfig symbols
> > > [nucleo-f4229zi](https://www.st.com/en/evaluation-tools/nucleo-f439zi.html#overview) board does not come with external ram. Looking at netnsh config, these changes are also not present.
> > 
> > 
> > I've saw this suggestion for the last couple PRs, Is there a guideline page somewhere? Look like pattern for semantic commits, but with slashes instead colons.
> 
> Hi @LuchianMihai could you please include more details what kind of guideline are you looking for?
Anything regarding commit message formatting. How the message should look like, or when/how to use the "boards/arm/stm32/nucleo-f429zi:" format

**Comment by acassis** [comment]
> > > > please update the title and add a commit message describing the need for the change ex: boards/arm/stm32/nucleo-f429zi: remove faulty nsh defconfig symbols
> > > > [nucleo-f4229zi](https://www.st.com/en/evaluation-tools/nucleo-f439zi.html#overview) board does not come with external ram. Looking at netnsh config, these changes are also not present.
> > > 
> > > 
> > > I've saw this suggestion for the last couple PRs, Is there a guideline page somewhere? Look like pattern for semantic commits, but with slashes instead colons.
> > 
> > 
> > Hi @LuchianMihai could you please include more details what kind of guideline are you looking for?
> 
> Anything regarding commit message formatting. How the message should look like, or when/how to use the "boards/arm/stm32/nucleo-f429zi:" format

Good, I'll add it here: https://nuttx.apache.org/docs/latest/contributing/making-changes.html#submitting-your-changes-to-nuttx

**Comment by jerpelea** [comment]
> > > > > please update the title and add a commit message describing the need for the change ex: boards/arm/stm32/nucleo-f429zi: remove faulty nsh defconfig symbols
> > > > > [nucleo-f4229zi](https://www.st.com/en/evaluation-tools/nucleo-f439zi.html#overview) board does not come with external ram. Looking at netnsh config, these changes are also not present.
> > > > 
> > > > 
> > > > I've saw this suggestion for the last couple PRs, Is there a guideline page somewhere? Look like pattern for semantic commits, but with slashes instead colons.
> > > 
> > > 
> > > Hi @LuchianMihai could you please include more details what kind of guideline are you looking for?
> > 
> > 
> > Anything regarding commit message formatting. How the message should look like, or when/how to use the "boards/arm/stm32/nucleo-f429zi:" format
> 
> Good, I'll add it here: https://nuttx.apache.org/docs/latest/contributing/making-changes.html#submitting-your-changes-to-nuttx

I'll add some explicit information that will help us generate the release notes

**Comment by LuchianMihai** [comment]
Can someone give me an hint why the pipelines are failing?

**Comment by xiaoxiang781216** [comment]
@LuchianMihai please run: ./tools/refresh.sh --silent nucleo-f429zi/nsh and merge the change into your patch.

**Pull request merged**
