### PR TITLE
nuttx/boards:init_array.* needs to be executed in order

### PR DESCRIPTION
**Pull request by bestvvstar**
## Summary
nuttx/boards:init_array.* needs to be executed in order and before init_array.

### CODE REVIEW

**Comment by acassis** [comment]
Hi @bestvvstar please supply more information in the commit log, what was the issue this PR is fixing? What was happening when the order wasn't respected?

**Comment by xiaoxiang781216** [comment]
> Hi @bestvvstar please supply more information in the commit log, what was the issue this PR is fixing? What was happening when the order wasn't respected?

__attribute__((init_priority(X))) may stop work:
https://stackoverflow.com/questions/3371968/attribute-init-priorityx-in-gcc

**Review by davids5 — CHANGES_REQUESTED** [review]
1) 2 entries seem redundant. 
2) SORT breaks priority.  Set by priority or link order. ( When the SORT keyword is used, the linker will sort the files or sections into ascending order by name before placing them in the output file.)
3) If it is not referenced why keep it at all?

This should not come in.

**Comment by xiaoxiang781216** [comment]
> 1. 2 entries seem redundant.

Do you mean init_array and init_array.*?
init_array could be removed.

> 2. SORT breaks priority.  Set by priority or link order. ( When the SORT keyword is used, the linker will sort the files or sections into ascending order by name before placing them in the output file.)

No, the patch fixes the priority issue instead, here is the output from gcc -Wl,-verbose:
```
  .init_array    :
  {
    PROVIDE_HIDDEN (__init_array_start = .);
    KEEP (*(SORT_BY_INIT_PRIORITY(.init_array.*) SORT_BY_INIT_PRIORITY(.ctors.*)))
    KEEP (*(.init_array EXCLUDE_FILE (*crtbegin.o *crtbegin?.o *crtend.o *crtend?.o ) .ctors))
    PROVIDE_HIDDEN (__init_array_end = .);
  }
  .fini_array    :
  {
    PROVIDE_HIDDEN (__fini_array_start = .);
    KEEP (*(SORT_BY_INIT_PRIORITY(.fini_array.*) SORT_BY_INIT_PRIORITY(.dtors.*)))
    KEEP (*(.fini_array EXCLUDE_FILE (*crtbegin.o *crtbegin?.o *crtend.o *crtend?.o ) .dtors))
    PROVIDE_HIDDEN (__fini_array_end = .);
  }
```
you can see the stock linker script add SORT_BY_INIT_PRIORITY. @cuiziweizw please change SORT to SORT_BY_INIT_PRIORITY.

> 3. If it is not referenced why keep it at all?
>

since nobody reference symbols in init_array section, the linker will remove all entries and related code from final image without KEEP. You can see the stock linker script contain KEEP too.

**Comment by davids5** [comment]
> > 1. 2 entries seem redundant.
> 
> Do you mean init_array and init_array.*? init_array could be removed.
> 
> > 2. SORT breaks priority.  Set by priority or link order. ( When the SORT keyword is used, the linker will sort the files or sections into ascending order by name before placing them in the output file.)
> 
> No, the patch fixes the priority issue instead, here is the output from gcc -Wl,-verbose:
> 
> ```
>   .init_array    :
>   {
>     PROVIDE_HIDDEN (__init_array_start = .);
>     KEEP (*(SORT_BY_INIT_PRIORITY(.init_array.*) SORT_BY_INIT_PRIORITY(.ctors.*)))
>     KEEP (*(.init_array EXCLUDE_FILE (*crtbegin.o *crtbegin?.o *crtend.o *crtend?.o ) .ctors))
>     PROVIDE_HIDDEN (__init_array_end = .);
>   }
>   .fini_array    :
>   {
>     PROVIDE_HIDDEN (__fini_array_start = .);
>     KEEP (*(SORT_BY_INIT_PRIORITY(.fini_array.*) SORT_BY_INIT_PRIORITY(.dtors.*)))
>     KEEP (*(.fini_array EXCLUDE_FILE (*crtbegin.o *crtbegin?.o *crtend.o *crtend?.o ) .dtors))
>     PROVIDE_HIDDEN (__fini_array_end = .);
>   }
> ```
> 
> you can see the stock linker script add SORT_BY_INIT_PRIORITY. @cuiziweizw please change SORT to SORT_BY_INIT_PRIORITY.
> 
> > 3. If it is not referenced why keep it at all?
> 
> since nobody reference symbols in init_array section, the linker will remove all entries and related code from final image without KEEP. You can see the stock linker script contain KEEP too.

@xiaoxiang781216 Thank you for digging into the details here.  

Is SORT_BY_INIT_PRIORITY portable? What is the default?

**Comment by xiaoxiang781216** [comment]
> @xiaoxiang781216 Thank you for digging into the details here.
> 
> Is SORT_BY_INIT_PRIORITY portable? What is the default?

Here has detailed explanation:
https://sourceware.org/binutils/docs-2.23.1/ld/Input-Section-Wildcards.html

**Comment by davids5** [comment]
> > @xiaoxiang781216 Thank you for digging into the details here.
> > Is SORT_BY_INIT_PRIORITY portable? What is the default?
> 
> Here has detailed explanation: https://sourceware.org/binutils/docs-2.23.1/ld/Input-Section-Wildcards.html

Did it bother you that `SORT is an alias for SORT_BY_NAME.` and you got the output you did?

**Comment by xiaoxiang781216** [comment]
> > > @xiaoxiang781216 Thank you for digging into the details here.
> > > Is SORT_BY_INIT_PRIORITY portable? What is the default?
> > 
> > 
> > Here has detailed explanation: https://sourceware.org/binutils/docs-2.23.1/ld/Input-Section-Wildcards.html
> 
> Did it bother you that `SORT is an alias for SORT_BY_NAME.` and you got the output you did?

Since we just use the simple index(e.g.,100, 101...), it's same either with SORT_BY_INIT_PRIORITY or SORT_BY_NAME(SORT). But, if you use the index with different length(e.g., 1, 10, 101...), the result may different. I would suggest that it's better to follow the suggestion by document to avoid wasting the time to debug the subtle error.

**Comment by xiaoxiang781216** [comment]
@davids5 please review again.

**Comment by xiaoxiang781216** [comment]
@bestvvstar please fix the conflict

**Review by xiaoxiang781216 — APPROVED** [review]

**Pull request merged**
