### PR TITLE
Adds support to W25Q20CL memory.

### PR DESCRIPTION
**Pull request by daniel-p-carvalho**
## Summary
Adds support to W25Q20CL memory.
## Impact
None
## Testing
Tested with W25Q20CL

### CODE REVIEW

**Review by xiaoxiang781216 — APPROVED** [review]

**Review by jerpelea — APPROVED** [review]
please add commit message

**Comment by daniel-p-carvalho** [comment]
Hi,
I don't understand what is wrong with the commit message. I think I didn't
leave the commit message  empty.

It shows

commit b09e0c7dd9663cb8a29f19c1374414570f9d262c (HEAD -> w25_2mbit,
origin/w25_2mbit)
Author: Daniel P. Carvalho ***@***.***>
Date:   Tue Nov 21 16:08:44 2023 -0300

    Adds support to W25Q20CL memory.


thanks

Daniel Pereira de Carvalho


Em qua., 22 de nov. de 2023 às 13:27, Alin Jerpelea <
***@***.***> escreveu:

**Review by jerpelea — COMMENTED** [review]
commits should have a title and a body 

ex:
"Adds support to W25Q20CL memory. 

some description about the patch in this case the memory
and general information about the fix "

**Comment by daniel-p-carvalho** [comment]
I will change the commit message and perform a rebase.

Thanks

**Review by hartmannathan — COMMENTED** [review]
LGTM, but please fix commit message as others pointed out. Thanks!

**Pull request merged**
