### PR TITLE
sched: move etc romfs mount from nsh to sched/init

### PR DESCRIPTION
**Pull request by fxysunshine**
## Summary

Usually the startup script is placed under /etc. The contents of the etc directory are compiled and linked with Nuttx binary in the form of romfs. After startup, it will be  mounted by Nsh.

etc is generated by the different boards, that use genromfs and xxd tools to generate and compile it into the Nuttx, for example: boards/arm/at32/at32f437-mini/tool/mkromfs.sh
The more common method is etc image generated from the content in the corresponding board/arch/board/board/src/etc directory, and added by Makefile for example: boards/sim/sim/sim/src/etc.

But in kernel/protected mode, Nuttx kernel and apps are run in different privileged/non-privileged mode or the isolated binarys, so as that nsh should use syscall to access Nuttx kernel by exported API. In this scenario, nsh can not mount the etc image content, because that is generated in board and as a part of Nuttx kernel.

changes:

- move etc romfs mount from nsh to Nuttx, but keep the script to parse and execute.
- move and rename the related CONFIG, move customized nsh_romfsimg.h to etc_romfs.c in boards, and no need declaration for romfs_img/romfs_img_len.

This commit changes and updates all configurations in Nuttx arch/board as much as possible,
but if any missing, please refer to the following simple guide:

- rename CONFIG_NSH_ROMFSETC to CONFIG_ETC_ROMFS, and delete CONFIG_NSH_ARCHROMFS in defconfig
- rename the etc romfs mount configs, for example CONFIG_NSH_FATDEVNO to CONFIG_ETC_FATDEVNO
- move customized nsh_romfsimg.h to etc_romfs.c in board/arch/board/board/src and no need declaration for romfs_img/romfs_img_len.
- delete default nsh_romfsimg.h, if ROMFSETC is enabled, should generate and compile etc_romfs.c in board/arch/board/board/src.

## Impact
all boards config, could break CI need correspond to https://github.com/apache/nuttx-apps/pull/2256

## Testing
qemu/sim

### CODE REVIEW

**Comment by xiaoxiang781216** [comment]
Please refresh boards/sim/sim/sim/configs/unionfs/defconfig @fxysunshine.

**Comment by fxysunshine** [comment]
> Please refresh boards/sim/sim/sim/configs/unionfs/defconfig @fxysunshine.

done

**Review by jerpelea — APPROVED** [review]

**Comment by davids5** [comment]
@fxysunshine This looks to be a massive breaking change.  What is the advantage of it?  What are all the implications it will have on downstream NuttX users.  What are all the steps thy will need to do to migrate to it?

**Comment by xiaoxiang781216** [comment]
> @fxysunshine This looks to be a massive breaking change. What is the advantage of it?

This change is to support the mount /etc in kernel/protected mode.

> What are all the implications it will have on downstream NuttX users. What are all the steps thy will need to do to migrate to it?

@fxysunshine please add a migration guide in commit message and pr.

**Comment by davids5** [comment]
@fxysunshine Why was this approach taken and why were all the build changes needed? Are thy needed? May be you could explain the Problem you are solving, and why this is a good solution.

**Comment by fxysunshine** [comment]
> @fxysunshine Why was this approach taken and why were all the build changes needed? Are thy needed? May be you could explain the Problem you are solving, and why this is a good solution.

@davids5 Thanks for your suggestions. Please refer to the problem and solution description in the updated commit and pr.

**Comment by davids5** [comment]
> > @fxysunshine Why was this approach taken and why were all the build changes needed? Are thy needed? May be you could explain the Problem you are solving, and why this is a good solution.
> 
> @davids5 Thanks for your suggestions. Please refer to the problem and solution description in the updated commit and pr.

@fxysunshine Thank you for the excellent  problem and solution description. This is super helpful!

**Comment by davids5** [comment]
@xiaoxiang781216 Do you know why CI is failing?

**Review by davids5 — APPROVED** [review]

**Review by jerpelea — APPROVED** [review]

**Review by acassis — APPROVED** [review]

**Comment by acassis** [comment]
@fxysunshine I'll merge it, but I think you need to update our Documentation/, because there a lot of reference to CONFIG_NSH_ROMFSETC etc...

**Comment by fxysunshine** [comment]
> @xiaoxiang781216 Do you know why CI is failing?
 @xiaoxiang781216 @davids5 
lack of the apps corresponding commit https://github.com/apache/nuttx-apps/pull/2256, could not pass case scanftest.

Temporary ignore to check scanftest result https://github.com/apache/nuttx/pull/11498/files#diff-8c28e250b38860383a1f2e7a7610574b2358da67d92b6d523474bf30cefcf013, can pass CI.

Can we merge the PR, and revert the temp change after https://github.com/apache/nuttx-apps/pull/2256 is merged?

**Comment by fxysunshine** [comment]
> @fxysunshine I'll merge it, but I think you need to update our Documentation/, because there a lot of reference to CONFIG_NSH_ROMFSETC etc...

Sure. 

> @fxysunshine I'll merge it, but I think you need to update our Documentation/, because there a lot of reference to CONFIG_NSH_ROMFSETC etc...

**Comment by xiaoxiang781216** [comment]
> > @xiaoxiang781216 Do you know why CI is failing?
> 
> @xiaoxiang781216 @davids5 lack of the apps corresponding commit [apache/nuttx-apps#2256](https://github.com/apache/nuttx-apps/pull/2256), could not pass case scanftest.
> 
> Temporary ignore to check scanftest result https://github.com/apache/nuttx/pull/11498/files#diff-8c28e250b38860383a1f2e7a7610574b2358da67d92b6d523474bf30cefcf013, can pass CI.
> 
> Can we merge the PR, and revert the temp change after [apache/nuttx-apps#2256](https://github.com/apache/nuttx-apps/pull/2256) is merged?

Done, please revert the temp change.

**Comment by jlaitine** [comment]
Hi all, @xiaoxiang781216 @acassis @jerpelea 

I just came accross this PR while trying to update the nuttx. Sorry to rant afterwards, I never noticed this before. This change just breaks all my configurations, and I think is wrong in many aspects

- This is conceptually wrong. NSH is an application, a shell (or a combined shell and busybox kind of app...). NSH should reside ON the file ROMFS filesystem. In the end, you don't really want to "mount the romdisk from the NSH" nor even use the NSH as an "sbin/init" app (even though this is what is currently being done)
- If we want a "common" mounting mechanism for "root" fs, we should have a separate simplified "init" in the kernel and NOT use NSH as an init process. You may just refer to other OSs (like linux). They are not using a shell to mount the root file system. This just doesn't make any sense!
- There was no issues previously. You can just call "romdisk_register" and mount the (sbin) from your board initialization code

For sure we could adapt to this change, but I feel that it is taking us, and the role of the NSH application into a wrong direction.

I strongly suggest re-considering this approach, for now I am just reverting this change in our own branches.

**Pull request merged**
