### PR TITLE
Imx9 uart cleanups and flow control

### PR DESCRIPTION
**Pull request by jlaitine**
## Summary

The driver was originally copied from imxrt platform, but while doing some more thorough testing there has been issues found.

This PR cleans up the imx9 lpuart driver code, fixes hardware flow control and enables using RX and TX fifos in interrupt mode.

## Impact

Only on imx9 lpuart

## Testing

Tested on custom imx9 hardware, using 6 uarts with different baud rates, flow control setups and dma setups.

### CODE REVIEW

**Comment by nuttxpr** [comment]
[**\[Experimental Bot, please feedback here\]**](https://github.com/search?q=repo%3Aapache%2Fnuttx+13552&type=issues)



The PR summary is adequate, but the remaining sections lack some details. Here's a breakdown and suggestions for improvement:

**Summary:**

* **Good:**  Clearly states the "why" (fixing issues found during testing) and the "what" (cleaning up driver code, fixing hardware flow control, enabling RX/TX FIFOs in interrupt mode). 
* **Could be improved:** Briefly mention the specific issues found during testing for better context.

**Impact:**

* **Needs improvement:** 
    *  While it mentions impact on imx9 lpuart, be more specific about the affected features or functionalities.
    *  Address all the bullet points mentioned in the requirements. Even if the answer is "NO," explicitly state it. 
    *  For example:
        *  Is new feature added? YES (RX/TX FIFO in interrupt mode)
        *  Is existing feature changed? YES (Hardware flow control fixed)
        *  Impact on user: YES (Users can now utilize hardware flow control and FIFO interrupt mode for LPUART)
        *  Impact on build: NO
        *  ... and so on for all the remaining bullet points.

**Testing:**

* **Needs significant improvement:**
    *  **Insufficient detail on build host:**  Specify the OS, CPU architecture, and compiler version used for testing.
    *  **Unclear target details:**  "custom imx9 hardware" is too vague. Provide the specific board name or model and the configurations used.
    *  **Missing logs:**  The "Testing logs before change" and "Testing logs after change" sections are empty. Include relevant log snippets demonstrating the issues before the fix and the correct behavior after the fix.

**To make this PR meet the NuttX requirements, you should:**

1. **Expand the "Impact" section** to address all bullet points with specific details, even if the answer is "NO."
2. **Provide comprehensive testing information:**
   * Specify your build host environment (OS, CPU, compiler).
   * Clearly identify your target hardware (board name/model, configuration).
   * Include relevant log snippets demonstrating the problem before and the solution after your changes. 

By providing this additional information, you make it much easier for reviewers to understand, evaluate, and ultimately merge your PR into the NuttX codebase.

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by PetervdPerk-NXP** [comment]
@jlaitine was flow control specifically broken for imx9 or for the LPUART driver in general?
Because we've tested LPUART flow control on the IMXRT platform, not sure why it wouldn't work on the IMX9.

**Comment by jlaitine** [comment]
> @jlaitine was flow control specifically broken for imx9 or for the LPUART driver in general? Because we've tested LPUART flow control on the IMXRT platform, not sure why it wouldn't work on the IMX9.

This was only for IMX9. The lpuart driver development did start from imxrt version, but it was quite heavily modified. We have a requirement of not only making direct copy of imxrt driver, but also inspect and remove all legacy which seems unnecessary. It is possible that errors crept in in that phase. In addition, the lpuart IP is seemingly different version - register definitions, fifo sizes etc differ. Also blocks around the LPUART IP are different; clocking, DMA engine, GPIO, muxing etc.

I am not working on IMXRT currently, whatever we considered that to be used for was replaced by an imx93 based system. We have a custom (PX4 enabled) HW running on IMX93, and are currently doing full testing for all the features. If there are any remaining issues left, we'll just fix those as well...

**Comment by PetervdPerk-NXP** [comment]
Thanks for the clarification, it was more that if there's was a regression with imxrt that would need fixing as well.

Since you're using PX4 did you use the serial_test to verify the UART connection and handshaking?

**Pull request merged**
