### PR TITLE
xtensa/sigdeliver: fix signal deliver when task is running on ther CPU

### PR DESCRIPTION
**Pull request by tmedicci**
## Summary

While delivering a signal to a task that is currently running on the other core (SMP-enabled), the xtensa_sig_deliver needs to leave the critical section first. This should use the interrupt state (PS register) of the previously saved registers from the moment that the other CPU was paused.

The Inter-Processor Interrupt that pauses the other CPU generates a level-1 interrupt which sets the PS.EXCM. This level-1 interrupt is treated as an Exception and the bit PS.EXCM bit is automatically reset on return from Exception. However, this is not the case here because we are changing the execution to the signal trampoline. Restoring the PS register with the PS.EXCM bit set would cause any other exception to deviate execution to the DEC (double exception vector), avoiding it to be treated correctly. According to Xtensa's ISA: "The process of taking an interrupt does not clear the interrupt request. The process does set PS.EXCM to 1, which disables level-1 interrupts in the interrupt handler. Typically, the PS.EXCM is reset to 0 by the handler, after it has set up the stack frame and masked the interrupt." Clean the saved PS.EXCM to 1) avoid an exception from being properly treated and 2) avoid interrupts to be masked while delivering the signal.

## Impact

This allows running tasks to receive a signal while they are running on the other core in an SMP-enabled environment.

## Testing

This behavior can be verified by selecting `EXAMPLES_ALARM` app. In order to force the task to be running, one could omit `usleep` on `alarm_main.c`. Prior to this commit, the application crashed while delivering the signal to the app.

### CODE REVIEW

**Comment by masayuki2009** [comment]
>It probably requires fixing for other architectures.

@tmedicci 
I applied the same changes to arch/arm/src/armv7-a/arm_sigdeliver.c locally and tested with sabre-6quad:smp on both qemu-7.1 and the sabre board, but the ostest crashed on both environments.

```
diff --git a/arch/arm/src/armv7-a/arm_sigdeliver.c b/arch/arm/src/armv7-a/arm_sigdeliver.c
index 856f216c0c..9b32e9b855 100644
--- a/arch/arm/src/armv7-a/arm_sigdeliver.c
+++ b/arch/arm/src/armv7-a/arm_sigdeliver.c
@@ -54,7 +54,6 @@
 void arm_sigdeliver(void)
 {
   struct tcb_s *rtcb = this_task();
-  uint32_t *regs = rtcb->xcp.saved_regs;

 #ifdef CONFIG_SMP
   /* In the SMP case, we must terminate the critical section while the signal
@@ -86,7 +85,7 @@ void arm_sigdeliver(void)

   do
     {
-      leave_critical_section(regs[REG_CPSR]);
+      leave_critical_section(rtcb->xcp.regs[REG_CPSR]);
     }
   while (rtcb->irqcount > 0);
 #endif /* CONFIG_SMP */
@@ -144,5 +143,5 @@ void arm_sigdeliver(void)
   /* Then restore the correct state for this thread of execution. */

   board_autoled_off(LED_SIGNAL);
-  arm_fullcontextrestore(regs);
+  arm_fullcontextrestore(rtcb->xcp.saved_regs);
 }


user_main: signal handler test 
sighand_test: Initializing semaphore to 0 
sighand_test: Starting waiter task 
sighand_test: Started waiter_main pid=175 
waiter_main: Waiter started 
waiter_main: Unmasking signal 17 
waiter_main: Registering signal handler 
waiter_main: oact.sigaction=0 oact.sa_flags=0 oact.sa_mask=0000000000000000 
waiter_main: Waiting on semaphore 
sighand_test: Signaling pid=175 with signo=17 sigvalue=42 
[CPU1] arm_prefetchabort: Prefetch abort. PC: 00100000 IFAR: 00100000 IFSR: 0000000d 
[CPU1] _assert: Current Version: NuttX 10.3.0 b2c8be28b1-dirty Mar 30 2023 11:38:58 arm 
[CPU1] _assert: Assertion failed panic: at file: armv7-a/arm_prefetchabort.c:134 task(CPU1): waiter 0x10812c19 
[CPU1] up_dump_register: R0: 00000001 R1: 00000000 R2: 10825bb0 R3: 00000001 
[CPU1] up_dump_register: R4: 00000000 R5: 00000000 R6: 00000000 FP: 00000001 
[CPU1] up_dump_register: R8: 00000000 SB: 00000000 SL: 00000000 R11: 00000000 
[CPU1] up_dump_register: IP: 00000000 SP: 10830eb8 LR: 10801aa9 PC: 00100000 
[CPU1] up_dump_register: CPSR: 200000d1 
[CPU1] dump_stack: IRQ Stack: 
[CPU1] dump_stack: sp: 0x10830ca0 
[CPU1] dump_stack: base: 0x108227a8 
[CPU1] dump_stack: size: 00002048 
[CPU1] dump_stack: ERROR: IRQ Stack pointer is not within the stack 
[CPU1] stack_dump: 0x10822f20: deadbeef deadbeef deadbeef deadbeef 00000001 10801ea1 108249e0 00000001 
[CPU1] stack_dump: 0x10822f40: 000001df 108249e3 108249e1 00000002 108249e2 10801a0b 00000001 108241a8 
[CPU1] stack_dump: 0x10822f60: 00000001 10801a69 00000001 108241a8 00000002 10800d57 10800d3d 10825bb0 
[CPU1] stack_dump: 0x10822f80: 10825bb0 10801b5f 10825bb0 1080123f 00000002 00000000 00000000 10800a71 
[CPU1] dump_stack: User Stack: 
[CPU1] dump_stack: sp: 0x10830eb8 
[CPU1] dump_stack: base: 0x1082f0d0 
[CPU1] dump_stack: size: 00008152 
[CPU1] stack_dump: 0x10830ea0: 00000000 00000000 00000000 00000000 00100000 200000d1 1082a1d0 00000001 
[CPU1] stack_dump: 0x10830ec0: 108241b0 108072a1 00000000 108242a8 1082a1d0 10806fd1 00000000 00000000 
[CPU1] stack_dump: 0x10830ee0: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 
[CPU1] stack_dump: 0x10830f00: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 
[CPU1] stack_dump: 0x10830f20: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 
[CPU1] stack_dump: 0x10830f40: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 
[CPU1] stack_dump: 0x10830f60: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 
[CPU1] stack_dump: 0x10830f80: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 
[CPU1] stack_dump: 0x10830fa0: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 
[CPU1] stack_dump: 0x10830fc0: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 10831020 
[CPU1] stack_dump: 0x10830fe0: 10806fd1 00000002 1082a254 10825bb0 00000000 108242a8 1082a1d0 108241b0 
[CPU1] stack_dump: 0x10831000: 00000001 00000000 00000000 00000000 00000000 00000000 10806fdc 200000ff 
[CPU1] stack_dump: 0x10831020: 108256f8 1082a1d0 0000005f 1080291b 00000000 00000000 00000000 1082f0c0 
[CPU1] stack_dump: 0x10831040: 00000000 1080294d 00000000 10812cad 00000000 00000000 00020000 00000000 
[CPU1] stack_dump: 0x10831060: 10812d35 fffdffff ffffffff 00000002 00000000 00000000 00000000 00000000 
[CPU1] stack_dump: 0x10831080: 00000000 00000000 10812c19 10812c19 00000001 108055ab 00000000 10802dd9 
[CPU1] show_tasks: PID GROUP CPU PRI POLICY TYPE NPX STATE EVENT SIGMASK STACKBASE STACKSIZE USED FILLED COMMAND 
[CPU1] show_tasks: ---- --- ---- --- -------- ------- --- ------- ---------- -------- 0x108227a8 2048 120 5.8% irq 
[CPU1] dump_task: 0 0 0 0 FIFO Kthread N-- Assigned 0000000000000000 0x10826518 1000 544 54.4% CPU0 IDLE 
[CPU1] dump_task: 1 1 1 0 FIFO Kthread N-- Assigned 0000000000000000 0x10825918 1000 664 66.4% CPU1 IDLE 
[CPU1] dump_task: 2 2 2 0 FIFO Kthread N-- Running 0000000000000000 0x10825d18 1000 664 66.4% CPU2 IDLE 
[CPU1] dump_task: 3 3 3 0 FIFO Kthread N-- Running 0000000000000000 0x10826118 1000 664 66.4% CPU3 IDLE 
[CPU1] dump_task: 4 4 0 192 RR Kthread --- Waiting Semaphore 0000000000000000 0x108282b8 1992 544 27.3% hpwork 0x10824b44 
[CPU1] dump_task: 5 5 0 100 RR Task --- Waiting Semaphore 0000000000000000 0x10828e90 2000 1432 71.6% nsh_main 
[CPU1] dump_task: 44 44 0 100 RR Task --- Waiting Semaphore 0000000000000000 0x10829998 2008 696 34.6% ostest 
[CPU1] dump_task: 45 45 0 100 RR Task --- Running 0000000000000000 0x1082d0f0 8112 800 9.8% ostest Arg1 Arg2 Arg3 Arg4 
[CPU1] dump_task: 175 175 1 100 RR Task --- Running 0000000000000000 0x1082f0d0 8152 1740 21.3% waiter 
```

**Comment by masayuki2009** [comment]
>I applied the same changes to arch/arm/src/armv7-a/arm_sigdeliver.c locally and tested with sabre-6quad:smp on both qemu-7.1 and the sabre board, but the ostest crashed on both environments.

Let me confirm if the issue is armv7-a specific or not.

**Comment by tmedicci** [comment]
Hi @masayuki2009 , 

Thanks for testing it on other architectures! 

On Xtensa, specifically, the crash occurs only when the task is executing on the other core. Possibly this is not the situation `ostest` tests because the `waiter_main` will be waiting for a semaphore. Although it's important to assure that `ostest` run properly.

I'd suggest you apply this patch on `nuttx-apps`:

```
diff --git a/examples/alarm/alarm_main.c b/examples/alarm/alarm_main.c
index 74c5e8fc60..fa8abf04cf 100644
--- a/examples/alarm/alarm_main.c
+++ b/examples/alarm/alarm_main.c
@@ -125,12 +125,6 @@ static int alarm_daemon(int argc, FAR char *argv[])
               g_alarm_received[i] = false;
             }
         }
-
-      /* Now wait a little while and poll again.  If a signal is received
-       * this should cause us to awken earlier.
-       */
-
-      usleep(500 * 1000L);
     }
 
 errout:
 ```
 
 That will force a core to run the task in an infinite loop and the signal handler would need to interrupt this task to deliver the singal. Build & run the `EXAMPLES_ALARM` app:
 
 ```
 nsh> alarm 2
alarm_daemon started
alarm_daemon: Running
Opening /dev/rtc0
Alarm 0 set in 2 seconds
nsh> alarm_daemon: alarm 0 received
 ```
 
This is the result on xtensa/esp32 after applying the patch on this MR. Prior to this, it was crashing while executing `up_irq_restore(flags)` on [`leave_critical_section`](https://github.com/apache/nuttx/blob/632d87ee71a6e7a6dd1ac768690cf481313befc4/sched/irq/irq_csection.c#L588) 

That makes sense for Xtensa: the original context (included would need to be restored only after all signal handling.

**Comment by masayuki2009** [comment]
@tmedicci 

I confirmed that the alarm example crashes on qemu-esp-develop-20220802 without this PR.

```
/home/ishikawa/opensource/QEMU/qemu-esp-develop-20220802/build/qemu-system-xtensa -nographic -machine esp32 -smp 2 -drive file=./nuttx/nuttx.merged.bin,if=mtd,format=raw
==2905475==WARNING: ASan doesn't fully support makecontext/swapcontext functions and may produce false positives in some cases!
Adding SPI flash device
ets Jul 29 2019 12:21:46

rst:0x1 (POWERON_RESET),boot:0x12 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:6604
ho 0 tail 12 room 4
load:0x40078000,len:14780
load:0x40080400,len:3792
entry 0x40080694
I (1013) boot: ESP-IDF v4.4 2nd stage bootloader
I (1026) boot: compile time 19:32:08
I (1047) boot: chip revision: 0
I (1061) boot.esp32: SPI Speed      : 40MHz
I (1063) boot.esp32: SPI Mode       : DIO
I (1064) boot.esp32: SPI Flash Size : 4MB
I (1088) boot: Enabling RNG early entropy source...
I (1120) boot: Partition Table:
I (1121) boot: ## Label            Usage          Type ST Offset   Length
I (1123) boot:  0 factory          factory app      00 00 00010000 00100000
I (1143) boot: End of partition table
I (1162) esp_image: segment 0: paddr=00010020 vaddr=3f400020 size=09538h ( 38200) map
I (1250) esp_image: segment 1: paddr=00019560 vaddr=3ffb3510 size=00260h (   608) load
I (1290) esp_image: segment 2: paddr=000197c8 vaddr=40080000 size=01e3ch (  7740) load
I (1339) esp_image: segment 3: paddr=0001b60c vaddr=50000000 size=00018h (    24) load
I (1374) esp_image: segment 4: paddr=0001b62c vaddr=00000000 size=049ech ( 18924) 
I (1433) esp_image: segment 5: paddr=00020020 vaddr=400d0020 size=1aab0h (109232) map
I (1612) boot: Loaded app from partition at offset 0x10000
I (1614) boot: Disabling RNG early entropy source...

NuttShell (NSH) NuttX-12.0.0
nsh> uname -a
NuttX 12.0.0 f468371332-dirty Mar 30 2023 21:50:53 xtensa esp32-devkitc
nsh> ps
  PID GROUP CPU PRI POLICY   TYPE    NPX STATE    EVENT     SIGMASK           STACK   USED  FILLED COMMAND
    0     0   0   0 FIFO     Kthread N-- Assigned           0000000000000000 003040 000792  26.0%  CPU0 IDLE
    1     1   1   0 FIFO     Kthread N-- Running            0000000000000000 003032 000432  14.2%  CPU1 IDLE
    2     2   0 100 RR       Task    --- Running            0000000000000000 003000 001656  55.2%  nsh_main
    3     3 --- 223 RR       Kthread --- Waiting  Semaphore 0000000000000000 001984 000360  18.1%  rt_timer
nsh> free
                   total       used       free    largest  nused  nfree
        Umem:     313472      15304     298168     175840     52      4
nsh> alarm 2
alarm_daemon started
alarm_daemon: Running
Opening /dev/rtc0
Alarm 0 set in 2 seconds
nsh> [CPU1] xtensa_panic: Unhandled Exception 1 task: alarm_daemon
[CPU1] _assert: Current Version: NuttX  12.0.0 f468371332-dirty Mar 30 2023 21:50:53 xtensa
[CPU1] _assert: Assertion failed panic: at file: common/xtensa_assert.c:84 task(CPU1): alarm_daemon 0x400e2590
[CPU1] up_dump_register:    PC: 400803c0    PS: 00060430
[CPU1] up_dump_register:    A0: 800d81ab    A1: 3ffe22f8    A2: 00060430    A3: 3ffe1900
[CPU1] up_dump_register:    A4: 00000001    A5: 3ffb03fa    A6: 00000000    A7: 3ffe2410
[CPU1] up_dump_register:    A8: 80081d65    A9: 3ffe22d8   A10: 00000000   A11: 00000002
[CPU1] up_dump_register:   A12: 3ffb03fc   A13: 3ffb0400   A14: 00060023   A15: 00060820
[CPU1] up_dump_register:   SAR: 0000001f CAUSE: 00000000 VADDR: 00000000
[CPU1] up_dump_register:  LBEG: 400d4aa8  LEND: 400d4abf  LCNT: 00000000
```

However, it seems that the alarm daemon does not receive any events with this PR.

```
NuttShell (NSH) NuttX-10.3.0
nsh> uname -a
NuttX 10.3.0 b2c8be28b1-dirty Mar 30 2023 21:42:55 xtensa esp32-devkitc
nsh> ps
  PID GROUP CPU PRI POLICY   TYPE    NPX STATE    EVENT     SIGMASK           STACK   USED  FILLED COMMAND
    0     0   0   0 FIFO     Kthread N-- Assigned           0000000000000000 003040 000768  25.2%  CPU0 IDLE
    1     1   1   0 FIFO     Kthread N-- Running            0000000000000000 003032 000432  14.2%  CPU1 IDLE
    2     2   0 100 RR       Task    --- Running            0000000000000000 003000 001896  63.2%  nsh_main
    3     3 --- 223 RR       Kthread --- Waiting  Semaphore 0000000000000000 001984 000360  18.1%  rt_timer
nsh> free
                   total       used       free    largest  nused  nfree
        Umem:     313472      15304     298168     175840     52      4
nsh> alarm 2
alarm_daemon started
alarm_daemon: Running
Opening /dev/rtc0
Alarm 0 set in 2 seconds
nsh> 
```

**Comment by tmedicci** [comment]
Hi @masayuki2009!

I was able to receive the alarm notification on QEMU on both versions (`qemu-esp-develop-20220802` and from `esp-develop` branch, which is the newest version).

The `alarm` example uses the RTC: maybe something is missing. Here it is my `defconfig`:
```
#
# This file is autogenerated: PLEASE DO NOT EDIT IT.
#
# You can use "make menuconfig" to make any modifications to the installed .config file.
# You can then do "make savedefconfig" to generate a new defconfig file that includes your
# modifications.
#
# CONFIG_ARCH_LEDS is not set
# CONFIG_NSH_ARGCAT is not set
# CONFIG_NSH_CMDOPT_HEXDUMP is not set
CONFIG_ARCH="xtensa"
CONFIG_ARCH_BOARD="esp32-devkitc"
CONFIG_ARCH_BOARD_COMMON=y
CONFIG_ARCH_BOARD_ESP32_DEVKITC=y
CONFIG_ARCH_CHIP="esp32"
CONFIG_ARCH_CHIP_ESP32=y
CONFIG_ARCH_CHIP_ESP32WROVER=y
CONFIG_ARCH_INTERRUPTSTACK=2048
CONFIG_ARCH_SETJMP_H=y
CONFIG_ARCH_STACKDUMP=y
CONFIG_ARCH_XTENSA=y
CONFIG_BOARD_LOOPSPERMSEC=16717
CONFIG_BUILTIN=y
CONFIG_DEBUG_ASSERTIONS=y
CONFIG_DEBUG_ASSERTIONS_EXPRESSION=y
CONFIG_DEBUG_FEATURES=y
CONFIG_DEBUG_FULLOPT=y
CONFIG_DEBUG_SYMBOLS=y
CONFIG_ESP32_QEMU_IMAGE=y
CONFIG_ESP32_RT_TIMER=y
CONFIG_ESP32_UART0=y
CONFIG_EXAMPLES_ALARM=y
CONFIG_EXAMPLES_HELLO=y
CONFIG_FS_PROCFS=y
CONFIG_HAVE_CXX=y
CONFIG_HAVE_CXXINITIALIZE=y
CONFIG_IDLETHREAD_STACKSIZE=3072
CONFIG_INIT_ENTRYPOINT="nsh_main"
CONFIG_INIT_STACKSIZE=3072
CONFIG_INTELHEX_BINARY=y
CONFIG_MM_REGIONS=4
CONFIG_NDEBUG=y
CONFIG_NSH_ARCHINIT=y
CONFIG_NSH_BUILTIN_APPS=y
CONFIG_NSH_DISABLE_DATE=y
CONFIG_NSH_FILEIOSIZE=512
CONFIG_NSH_LINELEN=64
CONFIG_NSH_READLINE=y
CONFIG_PREALLOC_TIMERS=4
CONFIG_RAM_SIZE=114688
CONFIG_RAM_START=0x20000000
CONFIG_READLINE_CMD_HISTORY=y
CONFIG_RR_INTERVAL=200
CONFIG_RTC=y
CONFIG_RTC_ALARM=y
CONFIG_RTC_DRIVER=y
CONFIG_RTC_HIRES=y
CONFIG_SMP=y
CONFIG_SMP_NCPUS=2
CONFIG_SPI=y
CONFIG_STACK_COLORATION=y
CONFIG_START_DAY=6
CONFIG_START_MONTH=12
CONFIG_START_YEAR=2011
CONFIG_SYSTEM_NSH=y
CONFIG_SYSTEM_SYSTEM=y
CONFIG_SYSTEM_TASKSET=y
CONFIG_TESTING_OSTEST=y
CONFIG_TESTING_SMP=y
CONFIG_UART0_SERIAL_CONSOLE=y
```

Please note that I'm testing with `alarm`'s patch applied (without `usleep`). 

Please, consider testing using my [merged binary](https://github.com/apache/nuttx/files/11112255/nuttx.merged.zip). Also, if you can send yours, I'll be glad to test it too.

**Comment by acassis** [comment]
Sorry, I just removed my comment, it was to arch/arm/src/armv7-m not arch/arm/src/armv7-a

**Comment by acassis** [comment]
I ran ostest on Spresense SMP:

```
Final memory usage:
VARIABLE  BEFORE   AFTER
======== ======== ========
arena      155328   155328
ordblks         1        9
mxordblk   14ef50   145ae8
uordblks     63d8     94e0
fordblks   14ef50   14be48
user_main: Exiting
ostest_main: Exiting with status 0
nsh> uname -a
NuttX 12.0.0 f468371332-dirty Mar 30 2023 12:13:33 arm spresense
nsh>
```

**Comment by masayuki2009** [comment]
@tmedicci 

>Please note that I'm testing with alarm's patch applied (without usleep).

Yes, I confirmed that I applied the alarm's patch.

>The alarm example uses the RTC: maybe something is missing. Here it is my defconfig:

I've just tried your defconfig but the alarm still does not work as expected.

>Please, consider testing using my [merged binary](https://github.com/apache/nuttx/files/11112255/nuttx.merged.zip). Also, if you can send yours, I'll be glad to test it too.

I've just confirmed that your nuttx.merged.bin works with qemu.

By the way, could you tell me the compiler version?
I've been using the following version.

```
$ xtensa-esp32-elf-gcc --version
xtensa-esp32-elf-gcc (crosstool-NG esp-2021r2-patch5) 8.4.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by tmedicci** [comment]
> @tmedicci
> 
> > Please note that I'm testing with alarm's patch applied (without usleep).
> 
> Yes, I confirmed that I applied the alarm's patch.
> 
> > The alarm example uses the RTC: maybe something is missing. Here it is my defconfig:
> 
> I've just tried your defconfig but the alarm still does not work as expected.
> 
> > Please, consider testing using my [merged binary](https://github.com/apache/nuttx/files/11112255/nuttx.merged.zip). Also, if you can send yours, I'll be glad to test it too.
> 
> I've just confirmed that your nuttx.merged.bin works with qemu.
> 
> By the way, could you tell me the compiler version? I've been using the following version.
> 
> ```
> $ xtensa-esp32-elf-gcc --version
> xtensa-esp32-elf-gcc (crosstool-NG esp-2021r2-patch5) 8.4.0
> Copyright (C) 2018 Free Software Foundation, Inc.
> This is free software; see the source for copying conditions.  There is NO
> warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
> ```

Good point! I've been using the same used for our [CI](https://github.com/apache/nuttx/pull/8836):

```
xtensa-esp32-elf-gcc (crosstool-NG esp-12.2.0_20230208) 12.2.0
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by tmedicci** [comment]
Hi @masayuki2009 , 

Indeed, using the `xtensa-esp32-elf-gcc (crosstool-NG esp-2021r2-patch5) 8.4.0`, the signal is not delivered properly. Tested with QEMU and ESP32-DevKitC-v4.

It works with newest GCC:  `xtensa-esp32-elf-gcc (crosstool-NG esp-12.2.0_20230208) 12.2.0`

**Comment by pkarashchenko** [comment]
Do we know what is the difference in generated assembly on `8.4.0` vs `12.2.0`?

**Review by lucasssvaz — APPROVED** [review]

**Comment by acassis** [comment]
I tested the above modification after updating to arm-none-eabi-gcc 12.2.1 and now the event is happening even removing the delay in the alarm_main.c:

```
NuttShell (NSH) NuttX-12.0.0
nsh> ?
help usage:  help [-v] [<cmd>]

    .         cat       df        free      mount     rmdir     truncate  
    [         cd        dmesg     help      mv        set       uname     
    ?         cp        echo      hexdump   printf    sleep     umount    
    alias     cmp       env       kill      ps        source    unset     
    unalias   dirname   exec      ls        pwd       test      uptime    
    basename  date      exit      mkdir     reboot    time      usleep    
    break     dd        false     mkrd      rm        true      xd        

Builtin Apps:
    alarm    hello    nsh      ostest   sh       smp      taskset  
nsh> alarm 10
alarm_daemon started
alarm_daemon: Running
Opening /dev/rtc0
Alarm 0 set in 10 seconds
nsh> 
nsh> ps
  PID GROUP CPU PRI POLICY   TYPE    NPX STATE    EVENT     SIGMASK           STACK COMMAND
    0     0   0   0 FIFO     Kthread N-- Assigned           0000000000000000 001000 CPU0 IDLE
    1     1   1   0 FIFO     Kthread N-- Assigned           0000000000000000 001000 CPU1 IDLE
    3     3 --- 200 RR       Task    --- Waiting  MQ empty  0000000000000000 000976 cxd56_pm_tk
    4     4   0 100 RR       Task    --- Running            0000000000000000 002000 spresense_n
    6     6   1 100 RR       Task    --- Running            0000000000000000 002000 alarm_daemn
nsh> alarm_daemon: alarm 0 received

nsh>
```

**Comment by tmedicci** [comment]
> I tested the above modification after updating to arm-none-eabi-gcc 12.2.1 and now the event is happening even removing the delay in the alarm_main.c:
> 
> ```
> NuttShell (NSH) NuttX-12.0.0
> nsh> ?
> help usage:  help [-v] [<cmd>]
> 
>     .         cat       df        free      mount     rmdir     truncate  
>     [         cd        dmesg     help      mv        set       uname     
>     ?         cp        echo      hexdump   printf    sleep     umount    
>     alias     cmp       env       kill      ps        source    unset     
>     unalias   dirname   exec      ls        pwd       test      uptime    
>     basename  date      exit      mkdir     reboot    time      usleep    
>     break     dd        false     mkrd      rm        true      xd        
> 
> Builtin Apps:
>     alarm    hello    nsh      ostest   sh       smp      taskset  
> nsh> alarm 10
> alarm_daemon started
> alarm_daemon: Running
> Opening /dev/rtc0
> Alarm 0 set in 10 seconds
> nsh> 
> nsh> ps
>   PID GROUP CPU PRI POLICY   TYPE    NPX STATE    EVENT     SIGMASK           STACK COMMAND
>     0     0   0   0 FIFO     Kthread N-- Assigned           0000000000000000 001000 CPU0 IDLE
>     1     1   1   0 FIFO     Kthread N-- Assigned           0000000000000000 001000 CPU1 IDLE
>     3     3 --- 200 RR       Task    --- Waiting  MQ empty  0000000000000000 000976 cxd56_pm_tk
>     4     4   0 100 RR       Task    --- Running            0000000000000000 002000 spresense_n
>     6     6   1 100 RR       Task    --- Running            0000000000000000 002000 alarm_daemn
> nsh> alarm_daemon: alarm 0 received
> 
> nsh>
> ```

Just confirming: 

1) Did you apply the `EXAMPLES_APP` patch? (removing `usleep` to force the other core to run the `alarm_daemon`?)
2) Did you use the Spresense board, right? (armv7-m)
3) Is this the result after applying the same kind of approaching at `nuttx/arch/arm/src/armv7-m/arm_schedulesigaction.c`?
4) Using older versions of GCC, was the signal delivered?
5) Considering the newest version of the compiler, prior to applying this patch, does the firmware crash?

**Comment by acassis** [comment]
> > I tested the above modification after updating to arm-none-eabi-gcc 12.2.1 and now the event is happening even removing the delay in the alarm_main.c:
> > ```
> > NuttShell (NSH) NuttX-12.0.0
> > nsh> ?
> > help usage:  help [-v] [<cmd>]
> > 
> >     .         cat       df        free      mount     rmdir     truncate  
> >     [         cd        dmesg     help      mv        set       uname     
> >     ?         cp        echo      hexdump   printf    sleep     umount    
> >     alias     cmp       env       kill      ps        source    unset     
> >     unalias   dirname   exec      ls        pwd       test      uptime    
> >     basename  date      exit      mkdir     reboot    time      usleep    
> >     break     dd        false     mkrd      rm        true      xd        
> > 
> > Builtin Apps:
> >     alarm    hello    nsh      ostest   sh       smp      taskset  
> > nsh> alarm 10
> > alarm_daemon started
> > alarm_daemon: Running
> > Opening /dev/rtc0
> > Alarm 0 set in 10 seconds
> > nsh> 
> > nsh> ps
> >   PID GROUP CPU PRI POLICY   TYPE    NPX STATE    EVENT     SIGMASK           STACK COMMAND
> >     0     0   0   0 FIFO     Kthread N-- Assigned           0000000000000000 001000 CPU0 IDLE
> >     1     1   1   0 FIFO     Kthread N-- Assigned           0000000000000000 001000 CPU1 IDLE
> >     3     3 --- 200 RR       Task    --- Waiting  MQ empty  0000000000000000 000976 cxd56_pm_tk
> >     4     4   0 100 RR       Task    --- Running            0000000000000000 002000 spresense_n
> >     6     6   1 100 RR       Task    --- Running            0000000000000000 002000 alarm_daemn
> > nsh> alarm_daemon: alarm 0 received
> > 
> > nsh>
> > ```
> 
> Just confirming:
> 
>     1. Did you apply the `EXAMPLES_APP` patch? (removing `usleep` to force the other core to run the `alarm_daemon`?)
> 
>     2. Did you use the Spresense board, right? (armv7-m)
> 
>     3. Is this the result after applying the same kind of approaching at `nuttx/arch/arm/src/armv7-m/arm_schedulesigaction.c`?
> 
>     4. Using older versions of GCC, was the signal delivered?
> 
>     5. Considering the newest version of the compiler, prior to applying this patch, does the firmware crash?

Let's use Karnaugh Map to simply it! Hehehe

Using ARM gcc 12.2.1 the alarm example always works, not matter if the patch is applied or not, not matter if the alarm_main.c has the usleep() or not.

**Comment by acassis** [comment]
So, with arm-none-eabi-gcc 12.2.1 is issue never show up. As Gustavo said, maybe it could be some alignment issue caused by the compiler. But it is strange because all arches were affected.

**Comment by pkarashchenko** [comment]
@acassis @tmedicci so do we need this change at all?

**Comment by tmedicci** [comment]
Converted to Draft to run more testing!

**Comment by masayuki2009** [comment]
@tmedicci

>Yes, at least for xtensa.

I tried the following changes on spresense with arm-gcc 12.2

```
--- a/boards/arm/cxd56xx/spresense/configs/smp/defconfig
+++ b/boards/arm/cxd56xx/spresense/configs/smp/defconfig
@@ -28,14 +28,19 @@ CONFIG_CXD56_I2C=y
 CONFIG_CXD56_SPI4=y
 CONFIG_CXD56_SPI5=y
 CONFIG_CXD56_SPI=y
+CONFIG_DEBUG_ASSERTIONS=y
+CONFIG_DEBUG_ERROR=y
+CONFIG_DEBUG_FEATURES=y
 CONFIG_DEBUG_FULLOPT=y
 CONFIG_DEBUG_SYMBOLS=y
+CONFIG_EXAMPLES_ALARM=y
 CONFIG_EXAMPLES_HELLO=y
 CONFIG_FS_PROCFS=y
 CONFIG_FS_PROCFS_REGISTER=y
 CONFIG_HAVE_CXX=y
 CONFIG_HAVE_CXXINITIALIZE=y
 CONFIG_INIT_ENTRYPOINT="spresense_main"
+CONFIG_NDEBUG=y
 CONFIG_NSH_ARCHINIT=y
 CONFIG_NSH_BUILTIN_APPS=y
 CONFIG_NSH_READLINE=y
@@ -45,7 +50,10 @@ CONFIG_RAM_START=0x0d000000
 CONFIG_READLINE_CMD_HISTORY=y
 CONFIG_RR_INTERVAL=200
 CONFIG_RTC=y
+CONFIG_RTC_ALARM=y
 CONFIG_RTC_DRIVER=y
+CONFIG_RTC_FREQUENCY=32768
+CONFIG_RTC_HIRES=y
 CONFIG_SMP=y
 CONFIG_SMP_NCPUS=2
 CONFIG_SPI=y
```

```
--- a/examples/alarm/alarm_main.c
+++ b/examples/alarm/alarm_main.c
@@ -125,12 +125,6 @@ static int alarm_daemon(int argc, FAR char *argv[])
               g_alarm_received[i] = false;
             }
         }
-
-      /* Now wait a little while and poll again.  If a signal is received
-       * this should cause us to awken earlier.
-       */
-
-      usleep(500 * 1000L);
     }
```

However, I can not reproduce the crash that happened on esp32-devkitc (xtensa).

**Comment by tmedicci** [comment]
@masayuki2009 , @acassis , @lucasssvaz and @acassis : the PR was updated with an alternative (correct) fix for the problem. In fact, this a xtensa-specific behavior (other architectures aren't affected by this) and the proposal was explained in the commit's message, in the PR description, and in the code itself.

The same approach was used by the software interrupt in  https://github.com/apache/nuttx/blob/45394eb6dcd7d5c5ca651b8a28a038c3e3795536/arch/xtensa/src/common/xtensa_swint.c#L421

Could you please take a look at it?

**Review by lucasssvaz — APPROVED** [review]

**Comment by pkarashchenko** [comment]
Please rebase to fix CI

**Comment by tmedicci** [comment]
> Please rebase to fix CI

done!

**Review by pkarashchenko — APPROVED** [review]

**Pull request merged**
