### PR TITLE
riscv/qemu-rv: Add BUILD_PROTECTED target for rv-virt

### PR DESCRIPTION
**Pull request by pussuw**
## Summary
This adds BUILD_PROTECTED target for rv-virt (rv-virt:pnsh64). 
## Impact
Add a new test target for rv-virt.
## Testing
rv-virt:pnsh64 / rv-virt:nsh64

Note when using qemu:

The user-space binary must also be loaded, which can be done by adding ``-device loader,file=./nuttx_user.elf`` to the command line arguments.

### CODE REVIEW

**Comment by pussuw** [comment]
This is a partial fix for what was discussed here: https://github.com/apache/nuttx/pull/12435

Still, the child user SP and TP are not set correctly by riscv_vfork() i.e. when the child returns to user space, wrong register values are loaded to SP and TP via https://github.com/apache/nuttx/blob/c4efab7eea479e0477e79de75f2e083a1dec2bc1/arch/risc-v/src/common/riscv_exception_common.S#L234-L238

**Comment by xiaoxiang781216** [comment]
but @pussuw private function should before public function

**Comment by pussuw** [comment]
> but @pussuw private function should before public function

I'll fix. Declaring the prototype is not necessary, I'll just move the definition there.

**Review by xiaoxiang781216 — APPROVED** [review]

**Review by jerpelea — APPROVED** [review]
please add a commit message describing the change

**Review by xiaoxiang781216 — APPROVED** [review]

**Pull request merged**
