### PR TITLE
Interrupt nesting

### PR DESCRIPTION
**Pull request by wming-github**
## Summary
Provides interrupt nesting and zero-latency interrupt support for the ARM M core architecture, including: ARMV6-M ARMV7-M ARMV8-M
## Impact
Interrupt exception for arm m core architecture
## Testing
Validation enables different priority interrupts to be nested

### CODE REVIEW

**Comment by patacongo** [comment]
See Issue #1134

**Comment by xiaoxiang781216** [comment]
ping @davids5, could you give the feedback about my explanation?

**Review by davids5 — APPROVED** [review]

**Comment by davids5** [comment]
@xiaoxiang781216 Thank you for the explanation. I should have realized that if any driver already had priorities not set properly, it  would already cause crashes (IIRC @patacongo removed some of these inconsistent priorities  years ago in the Kinetis arch)

**Comment by xiaoxiang781216** [comment]
> @xiaoxiang781216 Thank you for the explanation. I should have realized that if any driver already had priorities not set properly, it would already cause crashes (IIRC @patacongo removed some of these inconsistent priorities years ago in the Kinetis arch)

Yes, it crashes before, but it mayn't crash now if the driver doesn't call any OS API directly.

**Pull request merged**
