### PR TITLE
tools/ci/docker/linux/Dockerfile: image cleaned of unnecessary folders

### PR DESCRIPTION
**Pull request by simbit18**
## Summary
Trying to reduce the size of the docker image, I found folders to be deleted.

- improved bloaty building.

- added rm -rf nuttx-tools

- added rm -rf renesas-tools

@xiaoxiang781216  @kassane For now, I have commented Swift from the  Dockerfile because the package is too large.
 
#13186

## Impact
There should be no impact.
## Testing
CI

### CODE REVIEW

**Comment by kassane** [comment]
> I have commented Swift from the Dockerfile

Exactly!

Perhaps it would be convenient to just use the official Swift images.
In this case, for embedded devices, Swift6 (experimental) may not be a priority.

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by simbit18** [comment]
@xiaoxiang781216 
the docker image has not been updated we currently use that one 
Published 22 days ago

https://github.com/apache/nuttx/actions/runs/10619683045

You can re-run jobs to see if it fix the problem.

**Comment by xiaoxiang781216** [comment]
OK, I retrigger it.

**Comment by simbit18** [comment]
@xiaoxiang781216 see https://github.com/apache/nuttx/actions/runs/10619683045/job/29437799464#step:7:1339

It looks like the error you're getting is due to an incomplete download. It will probably work fine if you just download it again.

**Pull request merged**
