### PR TITLE
sched: Add _NSIG, SIGFPE, SIGILL and SIGSEGV definition

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
## Summary

- sched: Add SIGFPE, SIGILL and SIGSEGV definition
- signal: add marco _NSIG

## Impact

new macro

## Testing

CI

### CODE REVIEW

**Review by acassis — APPROVED** [review]

**Comment by lucasssvaz** [comment]
In the Kconfig, signal 18 is called CONFIG_SIG_SEGA and in the header file it is CONFIG_SIG_SEGV. Is this on purpose ?

**Review by lucasssvaz — COMMENTED** [review]
In the Kconfig, signal 18 is called CONFIG_SIG_SEGA and in the header file it is CONFIG_SIG_SEGV. Is this on purpose ?

**Comment by xiaoxiang781216** [comment]
It's typo error, let me provide a patch fix it, thanks.

**Comment by xiaoxiang781216** [comment]
@lucasssvaz here is the fix: https://github.com/apache/nuttx/pull/8312

**Comment by lucasssvaz** [comment]
> @lucasssvaz here is the fix: #8312

Thanks!

**Pull request merged**
