### PR TITLE
minidumpserver: replace stackdump to stack_dump

### PR DESCRIPTION
**Pull request by GUIDINGLI**
## Summary

minidumpserver: replace stackdump to stack_dump

## Impact

debug tools: minidumpserver

## Testing

VELA

### CODE REVIEW

**Comment by acassis** [comment]
@GUIDINGLI how the new stack_dump() will interact with original arch xxx_stackdump()? All arches need to create a new xxx_stack_dump() to use stack_dump() from assert.c ? Could you please add a Documentation/ about it?

**Comment by xiaoxiang781216** [comment]
@anjiahao1 please update minidumpserver.py help document.

**Comment by xiaoxiang781216** [comment]
Let's merge this simple PR, @anjiahao1 will update the document later.

**Comment by xiaoxiang781216** [comment]
> @GUIDINGLI how the new stack_dump() will interact with original arch xxx_stackdump()? All arches need to create a new xxx_stack_dump() to use stack_dump() from assert.c ? Could you please add a Documentation/ about it?

@acassis here is the patch: https://github.com/apache/nuttx/pull/8142

The help message with the script contains the enough info to use this tool.

**Pull request merged**
