### PR TITLE
CI: add open_posix support on sim

### PR DESCRIPTION
**Pull request by ttnie**
Signed-off-by: nietingting <nietingting@xiaomi.com>

## Summary
add open_posix on sim ci
## Impact
ci
## Testing
test on local

### CODE REVIEW

**Comment by acassis** [comment]
@ttnie any idea why CI is failing? I restart the failing jobs and the issue remains.

**Comment by pkarashchenko** [comment]
I also see `warning: (SYSTEM_PING) selects NETUTILS_PING which has unmet direct dependencies (NET_ICMP)`

**Comment by pkarashchenko** [comment]
```
+ python3 -m pytest -m 'common or sim' ./ -B sim -P -L /github/workspace/sources/nuttx/boards/sim/sim/sim/configs/citest/logs/sim/sim -R sim -C --json=/github/workspace/sources/nuttx/boards/sim/sim/sim/configs/citest/logs/sim/sim/pytest.json
ERROR: usage: __main__.py [options] [file_or_dir] [file_or_dir] [...]
__main__.py: error: argument -P: expected one argument
```

**Comment by ttnie** [comment]
> @ttnie any idea why CI is failing? I restart the failing jobs and the issue remains.
from the failures, looks like the LTP build break. Which not reproduced on my local host.

**Comment by ttnie** [comment]
> t



> 
build citest bb, can't find the test image, so run case failed.

**Comment by ttnie** [comment]
> I also see `warning: (SYSTEM_PING) selects NETUTILS_PING which has unmet direct dependencies (NET_ICMP)`

I'll try locally

**Comment by xiaoxiang781216** [comment]
close, already add.

**Pull request closed without merging**
