### PR TITLE
tools: ARCHIVE uses the full path

### PR DESCRIPTION
**Pull request by Gary-Hobson**
## Summary
https://github.com/apache/nuttx/pull/8384
There is a better solution to this problem, it would be more generic to have ARCHIVE use the full path

### CODE REVIEW

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by zouboan** [comment]
it seems that Windows native build broken again:
`"AR (add): libapps.a    builtin_list.c.NuttX.apps.builtin.o exec_builtin.c.NuttX.apps.builtin.o       "
arm-none-eabi-ar rcs G:/NuttX/apps/builtin/G:\NuttX\apps\libapps.a G:/NuttX/apps/builtin/builtin_list.c.NuttX.apps.builtin.o G:/NuttX/apps/builtin/exec_builtin.c.NuttX.apps.builtin.o
arm-none-eabi-ar: G:/NuttX/apps/builtin/G:\NuttX\apps\libapps.a: Invalid argument
make[3]: *** [archive] 错误 1
make[3]: Leaving directory `G:/NuttX/apps/builtin'
make[3]: Entering directory `G:/NuttX/apps/examples/hello'
"AR (add): libapps.a        hello_main.c.NuttX.apps.examples.hello.o   "
arm-none-eabi-ar rcs G:/NuttX/apps/examples/hello/G:\NuttX\apps\libapps.a G:/NuttX/apps/examples/hello/hello_main.c.NuttX.apps.examples.hello.o
arm-none-eabi-ar: G:/NuttX/apps/examples/hello/G:\NuttX\apps\libapps.a: Invalid argument
make[3]: *** [archive] 错误 1
make[3]: Leaving directory `G:/NuttX/apps/examples/hello'
make[3]: Entering directory `G:/NuttX/apps/nshlib'
"AR (add): libapps.a    nsh_init.c.NuttX.apps.nshlib.o nsh_parse.c.NuttX.apps.nshlib.o nsh_console.c.NuttX.apps.nshlib.o nsh_script.c.NuttX.apps.nshlib.o nsh_system.c.NuttX.apps.nshlib.o nsh_command.c.NuttX.apps.nshlib.o nsh_fscmds.c.NuttX.apps.nshlib.o nsh_ddcmd.c.NuttX.apps.nshlib.o nsh_proccmds.c
.NuttX.apps.nshlib.o nsh_mmcmds.c.NuttX.apps.nshlib.o nsh_timcmds.c.NuttX.apps.nshlib.o nsh_envcmds.c.NuttX.apps.nshlib.o nsh_syscmds.c.NuttX.apps.nshlib.o nsh_dbgcmds.c.NuttX.apps.nshlib.o nsh_session.c.NuttX.apps.nshlib.o nsh_fsutils.c.NuttX.apps.nshlib.o nsh_builtin.c.NuttX.apps.nshlib.o nsh_mntc
mds.c.NuttX.apps.nshlib.o nsh_consolemain.c.NuttX.apps.nshlib.o nsh_printf.c.NuttX.apps.nshlib.o nsh_test.c.NuttX.apps.nshlib.o       "
arm-none-eabi-ar rcs G:/NuttX/apps/nshlib/G:\NuttX\apps\libapps.a G:/NuttX/apps/nshlib/nsh_init.c.NuttX.apps.nshlib.o G:/NuttX/apps/nshlib/nsh_parse.c.NuttX.apps.nshlib.o G:/NuttX/apps/nshlib/nsh_console.c.NuttX.apps.nshlib.o G:/NuttX/apps/nshlib/nsh_script.c.NuttX.apps.nshlib.o G:/NuttX/apps/nshlib
/nsh_system.c.NuttX.apps.nshlib.o G:/NuttX/apps/nshlib/nsh_command.c.NuttX.apps.nshlib.o G:/NuttX/apps/nshlib/nsh_fscmds.c.NuttX.apps.nshlib.o G:/NuttX/apps/nshlib/nsh_ddcmd.c.NuttX.apps.nshlib.o G:/NuttX/apps/nshlib/nsh_proccmds.c.NuttX.apps.nshlib.o G:/NuttX/apps/nshlib/nsh_mmcmds.c.NuttX.apps.nsh
lib.o G:/NuttX/apps/nshlib/nsh_timcmds.c.NuttX.apps.nshlib.o G:/NuttX/apps/nshlib/nsh_envcmds.c.NuttX.apps.nshlib.o G:/NuttX/apps/nshlib/nsh_syscmds.c.NuttX.apps.nshlib.o G:/NuttX/apps/nshlib/nsh_dbgcmds.c.NuttX.apps.nshlib.o G:/NuttX/apps/nshlib/nsh_session.c.NuttX.apps.nshlib.o G:/NuttX/apps/nshli
b/nsh_fsutils.c.NuttX.apps.nshlib.o G:/NuttX/apps/nshlib/nsh_builtin.c.NuttX.apps.nshlib.o G:/NuttX/apps/nshlib/nsh_mntcmds.c.NuttX.apps.nshlib.o G:/NuttX/apps/nshlib/nsh_consolemain.c.NuttX.apps.nshlib.o G:/NuttX/apps/nshlib/nsh_printf.c.NuttX.apps.nshlib.o G:/NuttX/apps/nshlib/nsh_test.c.NuttX.app
s.nshlib.o
arm-none-eabi-ar: G:/NuttX/apps/nshlib/G:\NuttX\apps\libapps.a: Invalid argument
make[3]: *** [archive] 错误 1
make[3]: Leaving directory `G:/NuttX/apps/nshlib'
make[3]: Entering directory `G:/NuttX/apps/platform'
"AR (add): libapps.a    dummy.c.NuttX.apps.platform.o       "
arm-none-eabi-ar rcs G:/NuttX/apps/platform/G:\NuttX\apps\libapps.a G:/NuttX/apps/platform/dummy.c.NuttX.apps.platform.o
arm-none-eabi-ar: G:/NuttX/apps/platform/G:\NuttX\apps\libapps.a: Invalid argument
make[3]: *** [archive] 错误 1
make[3]: Leaving directory `G:/NuttX/apps/platform'
make[3]: Entering directory `G:/NuttX/apps/system/nsh'
"AR (add): libapps.a        nsh_main.c.NuttX.apps.system.nsh.o sh_main.c.NuttX.apps.system.nsh.o   "
arm-none-eabi-ar rcs G:/NuttX/apps/system/nsh/G:\NuttX\apps\libapps.a G:/NuttX/apps/system/nsh/nsh_main.c.NuttX.apps.system.nsh.o G:/NuttX/apps/system/nsh/sh_main.c.NuttX.apps.system.nsh.o
arm-none-eabi-ar: G:/NuttX/apps/system/nsh/G:\NuttX\apps\libapps.a: Invalid argument
make[3]: *** [archive] 错误 1
make[3]: Leaving directory `G:/NuttX/apps/system/nsh'
make[3]: Entering directory `G:/NuttX/apps/system/readline'
"AR (add): libapps.a    readline.c.NuttX.apps.system.readline.o readline_fd.c.NuttX.apps.system.readline.o readline_common.c.NuttX.apps.system.readline.o       "
arm-none-eabi-ar rcs G:/NuttX/apps/system/readline/G:\NuttX\apps\libapps.a G:/NuttX/apps/system/readline/readline.c.NuttX.apps.system.readline.o G:/NuttX/apps/system/readline/readline_fd.c.NuttX.apps.system.readline.o G:/NuttX/apps/system/readline/readline_common.c.NuttX.apps.system.readline.o
arm-none-eabi-ar: G:/NuttX/apps/system/readline/G:\NuttX\apps\libapps.a: Invalid argument
make[3]: *** [archive] 错误 1
make[3]: Leaving directory `G:/NuttX/apps/system/readline'
make[2]: *** [G:\NuttX\apps\libapps.a] 错误 2
make[2]: Leaving directory `G:/NuttX/apps'
make[1]: *** [all] 错误 2`

**Comment by xiaoxiang781216** [comment]
@zouboan fix is here #8419. It's better to enable Windows CI at least for one board, otherwise nobody can ensure the change doesn't break the build system you care about.

**Comment by zouboan** [comment]
> @zouboan fix is here #8419. It's better to enable Windows CI at least for one board, otherwise nobody can ensure the change doesn't break the build system you care about.

Unfortunately, I have no idea about CI automatic deployment, i tried, but failed.

**Comment by hartmannathan** [comment]
> > @zouboan fix is here #8419. It's better to enable Windows CI at least for one board, otherwise nobody can ensure the change doesn't break the build system you care about.
> 
> Unfortunately, I have no idea about CI automatic deployment, i tried, but failed.

Agreed it's important to add CI for Windows. I don't have a Windows dev system currently but maybe it should be filed as an Issue so that anyone who is interested will know that this is available to do.

**Pull request merged**
