### PR TITLE
fs/inode: refresh tcb after each file sync() is completed

### PR DESCRIPTION
**Pull request by anchao**
## Summary

fs/inode: refresh tcb after each file sync() is completed

After tcb is destroyed, it is very dangerous to back reference tcb through file.
This commit will perform file operations while ensuring the validity of tcb during
fsync, with will avoid tcb check in each subsystem.

## Impact
N/A

## Testing

ci-check

### CODE REVIEW

**Comment by nuttxpr** [comment]
[**\[Experimental Bot, please feedback here\]**](https://github.com/search?q=repo%3Aapache%2Fnuttx+13552&type=issues)



This PR appears **incomplete** for a NuttX pull request based on the provided requirements.  Here's why:

* **Summary Lacks Details:**
    * **Why?** The "why" of the change is not explained. What problem does refreshing the TCB after each `sync()` solve? 
    * **How?** A high-level description of how the change is implemented is missing.
* **Impact Overly Simplified:** 
    * While marking everything as "N/A" might be technically correct, it's unlikely a code change has *zero* impact. Consider these carefully:
        * **Compatibility:** Does this change in `sync()` behavior potentially break existing applications that relied on the old behavior?
        * **Performance:** Does frequently refreshing the TCB introduce any performance overhead?
* **Testing Insufficient:**
    * **"ci-check" is not enough.** You need to provide concrete testing logs or commands demonstrating the issue before the change and the improvement after the change.
    * **Target Specificity:**  Which architectures and boards did you test on?

**To improve this PR:**

1. **Expand the Summary:** Explain the rationale, the specific problem being solved, and briefly outline the implementation approach.
2. **Review Impact Carefully:** Be thorough; even minor impacts should be mentioned.  For "NO" answers, a brief justification is helpful (e.g., "Impact on build: NO - Changes are localized to the `fs/inode` directory").
3. **Provide Detailed Testing Information:**
    * Include actual commands or steps to reproduce the issue before your change.
    * Show the output or logs demonstrating the problem.
    * Do the same for the fixed scenario, showcasing the improvement.
    * Be specific about the testing environment (host OS, compiler, target architecture, board configuration).

**Comment by acassis** [comment]
@anchao please include a commit log message with more info about this modification

**Comment by anchao** [comment]
> @anchao please include a commit log message with more info about this modification

Done, thanks @acassis

**Comment by anchao** [comment]
Ready for review now https://github.com/apache/nuttx/pull/15028#issuecomment-2516101632

**Review by Donny9 — APPROVED** [review]

**Review by xiaoxiang781216 — APPROVED** [review]

**Pull request merged**
