### PR TITLE
cmake:bugfix kconfig menu in cmake cannot be generated recursively

### PR DESCRIPTION
**Pull request by xuxin930**
## Summary

the ${MENUCONFIG} file in the output directory is enough, as invoking nuttx_generate_kconfig() will generate this file in the output directory.
Since we are collecting these files recursively,
the nuttx_generate_kconfig() function of the parent directory will be called after all the subdirectories' nuttx_generate_kconfig() functions have been invoked.

## Impact

This will correctly handle the situation where multiple directories need to generate kconfig menus.

## Testing

creating a multi-level directory scenario

```
# apps/dir1/
nuttx_add_subdirectory()

nuttx_generate_kconfig(MENUDESC "Level1")

# apps/dir1/dir2
nuttx_add_subdirectory()

nuttx_generate_kconfig(MENUDESC "Level2")

```

```
cmake -B build -DBOARD_CONFIG=nrf52832-dk:mcuboot_app -GNinja

cmake --build build -t menuconfig
```

The test results are normal and enter the multi-level menu

### CODE REVIEW

**Comment by xuxin930** [comment]
It seems that the missing CMakeLists in apps will cause the refresh check to fail. We need to add this part first :-(

**Comment by anchao** [comment]
Will this pull request cause Kconfig to be generated for all directories containing CMakeLists.txt/Makefile? In fact, makefile base does not support nested recursion. If multiple levels of directories are required, developers need to add nested logic to the subdirectories. This is mainly to avoid searching for Makefile/CMakeLists.txt files that are not related to nuttx. You can try Makefile base and then evaluate the benefits of this change.

**Comment by xuxin930** [comment]
> Will this pull request cause Kconfig to be generated for all directories containing CMakeLists.txt/Makefile? In fact, makefile base does not support nested recursion. If multiple levels of directories are required, developers need to add nested logic to the subdirectories. This is mainly to avoid searching for Makefile/CMakeLists.txt files that are not related to nuttx. You can try Makefile base and then evaluate the benefits of this change.

hi @anchao In my testing, this does not cause the unnecessary directories you are worried about to be added.
This is because, if you add directories recursively, there is a prerequisite that `MENUDESC` has been generated in the `CMAKE_BINARY` directory.
This means that the inner layer must be entered through the outer layer calling `nuttx_generate_kconfig`, that is, it must be entered by nuttx's code.

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by lupyuen** [comment]
Sorry @xuxin930: `sim:rtptools` seems to be have a defconfig problem. Do we need to run [tools/refresh.sh](https://lupyuen.github.io/articles/pr#appendix-nuttx-configuration-files) to fix this?
```text
Cmake in present: sim/rtptools
  Building NuttX...
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   boards/sim/sim/sim/configs/rtptools/defconfig
```
https://github.com/NuttX/nuttx/actions/runs/11889195806/job/33125380576#step:7:258

**Comment by xuxin930** [comment]
> Sorry @xuxin930: `sim:rtptools` seems to have a CMake defconfig problem. Do we need to run [tools/refresh.sh](https://lupyuen.github.io/articles/pr#appendix-nuttx-configuration-files) to fix this?
> 
> ```
> Cmake in present: sim/rtptools
>   Building NuttX...
> On branch master
> Your branch is up to date with 'origin/master'.
> 
> Changes not staged for commit:
>   (use "git add <file>..." to update what will be committed)
>   (use "git restore <file>..." to discard changes in working directory)
> 	modified:   boards/sim/sim/sim/configs/rtptools/defconfig
> ```
> 
> https://github.com/NuttX/nuttx/actions/runs/11889195806/job/33125380576#step:7:258

hi @lupyuen lets add missing apps CMakeLists.  im doing now

**Comment by xuxin930** [comment]
> Sorry @xuxin930: `sim:rtptools` seems to have a CMake defconfig problem. Do we need to run [tools/refresh.sh](https://lupyuen.github.io/articles/pr#appendix-nuttx-configuration-files) to fix this?
> 
> ```
> Cmake in present: sim/rtptools
>   Building NuttX...
> On branch master
> Your branch is up to date with 'origin/master'.
> 
> Changes not staged for commit:
>   (use "git add <file>..." to update what will be committed)
>   (use "git restore <file>..." to discard changes in working directory)
> 	modified:   boards/sim/sim/sim/configs/rtptools/defconfig
> ```
> 
> https://github.com/NuttX/nuttx/actions/runs/11889195806/job/33125380576#step:7:258

hi @lupyuen  try this one https://github.com/apache/nuttx-apps/pull/2860

**Pull request merged**
