### PR TITLE
sched_lock: we can remove these sched_lock,

### PR DESCRIPTION
**Pull request by hujun260**
## Summary

purpose:
1 sched_lock is very time-consuming, and reducing its invocations can improve performance.
2 sched_lock is prone to misuse, and narrowing its scope of use is to prevent people from referencing incorrect code and using it

test:
We can use qemu for testing.
compiling
make distclean -j20; ./tools/configure.sh -l qemu-armv8a:nsh_smp ;make -j20
running
qemu-system-aarch64 -cpu cortex-a53 -smp 4 -nographic -machine virt,virtualization=on,gic-version=3 -net none -chardev stdio,id=con,mux=on -serial chardev:con -mon chardev=con,mode=readline -kernel ./nuttx

We have also tested this patch on other ARM hardware platforms.

### CODE REVIEW

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by masayuki2009** [comment]
@hujun260 

Please describe which configurations and applications you tested in the description.

**Comment by hujun260** [comment]
purpose:
1 sched_lock is very time-consuming, and reducing its invocations can improve performance.
2 sched_lock is prone to misuse, and narrowing its scope of use is to prevent people from referencing incorrect code and using it

test:
We can use qemu for testing.
compiling
make distclean -j20; ./tools/configure.sh -l qemu-armv8a:nsh_smp ;make -j20
running
qemu-system-aarch64 -cpu cortex-a53 -smp 4 -nographic -machine virt,virtualization=on,gic-version=3 -net none -chardev stdio,id=con,mux=on -serial chardev:con -mon chardev=con,mode=readline -kernel ./nuttx

We have also tested this patch on other ARM hardware platforms.

**Comment by xiaoxiang781216** [comment]
We found that NuttX SMP performance is poor compared with some commercial RTOS(e.g. ThreadX), but SMP performance is very important for our new project. @hujun260 take half year to improve SMP performance, and the result looks well. @masayuki2009 could you review this series patchset again? More complex patch will come to in the next couple week.

**Comment by masayuki2009** [comment]
@xiaoxiang781216 @hujun260 
I'll try this PR later today.

**Comment by masayuki2009** [comment]
@hujun260 
As long as I checked the commit, you replaced sched_lock with critical section in syslog_intbuffer.c.
So please divide the PR into two separate commits like the following.


```
drivers: syslog: Replace sched_lock with critical section in syslog_flush_intbuffer()
...
```

```
sched: misc: Remove sched_lock in _assert()
...
```

**Comment by acassis** [comment]
@hujun260 @xiaoxiang781216 how are you doing benchmarks for SMP on NuttX? I saw there is a testing/smp that could help on that, but some questions we need to raise:

1) Is testing/smp app enough to test SMP performance? (This app seems to be used only for conformity, not to benchmarking)

2) How to compare NuttX SMP performance against other RTOSes? Are we comparing orange vs apple?
2.1) Is there a same application that could run on those RTOSes? i.e. benchmarks/coremark ?

3) Do you have some document comparing NuttX SMP performance evolution?

**Review by acassis — COMMENTED** [review]
Please fix this CI error:
Remove Gerrit Change-ID's before submitting upstream

This line: Change-Id: I8731daeab0030a19159ede94377b86b724a62484 needs to be removed

**Pull request merged**
