### PR TITLE
MPU update

### PR DESCRIPTION
**Pull request by crafcat7**
## Summary
In the current NuttX MPU implementation, it is not possible to reconfigure a region that has already been set. Therefore, the purpose of this MPU upgrade is to enhance the ability of NuttX MPU to more accurately adjust the region.

The main interfaces are
```
void mpu_modify_region(unsigned int region, uinptr_t base, size_t size, uint32_t flags);
void mpu_clear_region(unsigned int region).
```

And change the g_region at the beginning to a bitmap to indicate whether each region has been allocated or not.

## Impact
update mpu for:
armv7m
armv8m
armv7r
arm64
xtensa

## Testing
Local test pass

### CODE REVIEW

**Comment by PetervdPerk-NXP** [comment]
What's the flash usage and ram usage impact?
Lots of MCU's use an MPU only on startup, I see there are usecases for making it dynamic. 
But I really would like to know the cost of it.

**Comment by crafcat7** [comment]
> What's the flash usage and ram usage impact? Lots of MCU's use an MPU only on startup, I see there are usecases for making it dynamic. But I really would like to know the cost of it.

I am happy to introduce this MPU upgrade:

1. The memory usage is the same as before because no memory application is used.
2. The usage logic is compatible with the original method, so the previous flash configuration is also allowed.

Among these three changes, the main one is to adjust the allocation method of g_region. This is a change from simply representing each region with a number to using each bit to indicate whether the region is allocated.

We also add an interface to initialize the mpu through the static table(mpu_initialize).

During the adjustment process, I noticed that many boards were configured by initializing the configuration through mpu_configure_region. My logic is to return it from void -> unsigned int type value. If we do not plan to adjust the region range later, we do not need to save the return value. The return value represents the currently configured region segment.

By holding the region info, we can modify the properties of this region/free this region.

However, please note that some platforms do not support overlap (such as armv8m), which may cause unexpected errors. Therefore, when configuring, you need to consider whether the configuration of each region will overlap.

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by xiaoxiang781216** [comment]
@crafcat7 please build a board with and without the modification and attach the result.

**Comment by crafcat7** [comment]
Before patch
```
   text    data     bss     dec     hex filename
1623860  743972  248428 2616260  27ebc4 nuttx

nsh> free
                   total       used       free    maxused    maxfree  nused  nfree
        Umem:     593848     295056     298792     297240     298016    886      4
```
After patch
```
   text    data     bss     dec     hex filename
1623920  743968  248428 2616316  27ebfc nuttx

nsh> free
                   total       used       free    maxused    maxfree  nused  nfree
        Umem:     593848     294976     298872     297136     296680    887      2
```

**Comment by xiaoxiang781216** [comment]
> What's the flash usage and ram usage impact? Lots of MCU's use an MPU only on startup, I see there are usecases for making it dynamic. But I really would like to know the cost of it.

@PetervdPerk-NXP the impact is minor:
delta
```
   text    data     bss     dec     hex filename
   60      -4         0        56       38   nuttx
```
The new api is required to protect userspace task in protected build.

**Comment by xiaoxiang781216** [comment]
@crafcat7 please rebase the patch

**Comment by crafcat7** [comment]
> @crafcat7 please rebase the patch

Done

**Pull request merged**
