### PR TITLE
circbuf: Move from mm/circbuf to libs/libc/misc

### PR DESCRIPTION
**Pull request by XuNeo**
## Summary

so that it can be used by userspace program.

## Impact

Need to update headers manually. 
All code in repository have been updated.
```patch
-#include <nuttx/mm/circbuf.h>
+#include <nuttx/circbuf.h>
```
## Testing

CI build pass.

### CODE REVIEW

**Comment by XuNeo** [comment]
CI report warning here:

Error: /home/runner/work/nuttx/nuttx/nuttx/arch/arm/src/phy62xx/uart.c:961:22: error: Mixed case identifier found

```
  uart_Ctx_t *priv = (uart_Ctx_t *)dev->priv;
```

**Comment by xiaoxiang781216** [comment]
@XuNeo please fix the conflict and ci error.

**Comment by XuNeo** [comment]
CI is still failing on `Error: /home/runner/work/nuttx/nuttx/nuttx/arch/arm/src/phy62xx/uart.c:895:2: error: Mixed case identifier found`, which is not introduced from this PR.

Please suggest what should we do.

**Comment by xiaoxiang781216** [comment]
> CI is still failing on `Error: /home/runner/work/nuttx/nuttx/nuttx/arch/arm/src/phy62xx/uart.c:895:2: error: Mixed case identifier found`, which is not introduced from this PR.
> 
> Please suggest what should we do.

let's ignore "Mixed case identifier found" warning, but the build error must be fixed before merging:
https://github.com/apache/nuttx/actions/runs/11207973668/job/31151011503?pr=13848

**Pull request merged**
