### PR TITLE
SMP: Fix issues of return values of nxsched_add_readytorun()

### PR DESCRIPTION
**Pull request by szsam**
## Summary
Fix issues of return values of nxsched_add_readytorun()

## Testing
sabre-6quad:smp

### CODE REVIEW

**Comment by masayuki2009** [comment]
@szsam 

Please describe how to reproduce the issue.
Also, please describe the configurations you tested.

**Comment by acassis** [comment]
> @szsam I tried this PR with sabre-6quad:smp (qemu-8.2.0)
> 
> ```
> $ /home/ishikawa/opensource/QEMU/qemu-8.2.0/build/qemu-system-arm -semihosting -M sabrelite -m 1024 -smp 4 -kernel nuttx -nographic
> 
> NuttShell (NSH) NuttX-12.0.0
> nsh> ps
>   PID GROUP CPU PRI POLICY   TYPE    NPX STATE    EVENT     SIGMASK           STACK   USED  FILLED COMMAND
>     0     0   0   0 FIFO     Kthread   - Assigned           0000000000000000 001008 000560  55.5%  CPU0 IDLE
>     1     1   1   0 FIFO     Kthread   - Running            0000000000000000 001008 000664  65.8%  CPU1 IDLE
>     2     2   2   0 FIFO     Kthread   - Running            0000000000000000 001008 000664  65.8%  CPU2 IDLE
>     3     3   3   0 FIFO     Kthread   - Running            0000000000000000 001008 000664  65.8%  CPU3 IDLE
>     4     4 --- 192 RR       Kthread   - Waiting  Semaphore 0000000000000000 001984 000432  21.7%  hpwork 0x1082766c 0x10827680
>     5     5   0 100 RR       Task      - Running            0000000000000000 002008 001248  62.1%  nsh_main
> nsh> help
> help usage:  help [-v] [<cmd>]
> 
>     .           cp          exit        mkdir       rmdir       umount      
>     [           cmp         expr        mkrd        set         unset       
>     ?           dirname     false       mount       sleep       uptime      
>     alias       dd          fdinfo      mv          source      usleep      
>     unalias     df          free        pidof       test        xd          
>     basename    dmesg       help        printf      time        
>     break       echo        hexdump     ps          true        
>     cat         env         kill        pwd         truncate    
>     cd          exec        ls          rm          uname       
> 
> Builtin Apps:
>     sh          ostest      hello       smp         
>     getprime    taskset     nsh         
> nsh> hello
> Hello, World!!
> [CPU1] arm_undefinedinsn: Undefined instruction at 0xffffffff
> [CPU1] _assert: Current Version: NuttX  12.0.0 62854450c0 Apr  2 2024 22:06:59 arm
> [CPU1] _assert: Assertion failed panic: at file: :0 task(CPU1): nsh_main process: nsh_main 0x10807421
> [CPU1] up_dump_register: R0: 00000002 R1: 10829ca8 R2: 1082b570  R3: 1082b570
> [CPU1] up_dump_register: R4: 1082aae8 R5: 10829c08 R6: 10825f0c  FP: 00000001
> [CPU1] up_dump_register: R8: 0000005f SB: 00000001 SL: 1082a6d4 R11: 00000004
> [CPU1] up_dump_register: IP: 00000006 SP: 1082a638 LR: 10807295  PC: ffffffff
> [CPU1] up_dump_register: CPSR: 108019e9
> [CPU1] dump_stack: User Stack:
> [CPU1] dump_stack:   base: 0x1082a000
> [CPU1] dump_stack:   size: 00002008
> [CPU1] dump_stack:     sp: 0x1082a638
> [CPU1] stack_dump: 0x1082a618: 00000001 0000005f 00000001 1082a6d4 00000004 00000006 ffffffff 108019e9
> [CPU1] stack_dump: 0x1082a638: 00000000 1082aae8 10826dec 10801acf 00000000 1082aae8 2000005f 1082aa90
> [CPU1] stack_dump: 0x1082a658: ffffffff 00000000 00000000 1082a6d4 00000004 10802421 00000001 1082a808
> [CPU1] stack_dump: 0x1082a678: 00000000 1082aa90 ffffffff 10808c05 0000005f 1082a808 1082aa90 00000000
> [CPU1] stack_dump: 0x1082a698: ffffffff 1082a808 1082aa90 00000001 00000000 10808271 00000000 1080563b
> [CPU1] stack_dump: 0x1082a6b8: 00000201 10822f2c 1082aa96 10804fbf 10829f08 00000000 00000000 00000000
> [CPU1] stack_dump: 0x1082a6d8: 10829f08 1082a727 00000001 1082aa90 00000000 00000000 00000000 00000000
> [CPU1] stack_dump: 0x1082a6f8: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
> [CPU1] stack_dump: 0x1082a718: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
> [CPU1] stack_dump: 0x1082a738: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
> [CPU1] stack_dump: 0x1082a758: 1082a808 1082a808 10823009 1082aa90 00000001 00000000 00000000 00000000
> [CPU1] stack_dump: 0x1082a778: 00000000 108075c3 1082a808 00000001 00000001 1082a808 00000001 10829fe8
> [CPU1] stack_dump: 0x1082a798: 00000000 1080747b 00000001 10829fe8 10829fe8 1080744d 00000001 00000064
> [CPU1] stack_dump: 0x1082a7b8: 10829fe8 10807421 00000001 10805801 10829c08 10803663 00000000 00000000
> [CPU1] stack_dump: 0x1082a7d8: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
> [CPU1] dump_tasks:    PID GROUP   CPU PRI POLICY   TYPE    NPX STATE   EVENT      SIGMASK          STACKBASE  STACKSIZE      USED   FILLED    COMMAND
> [CPU1] dump_tasks:   ----   ---  ---- --- -------- ------- --- ------- ---------- ---------------- 0x10824500      2048       120     5.8%    irq
> [CPU1] dump_task:       0     0     0   0 FIFO     Kthread - Assigned           0000000000000000 0x108282d8      1008       560    55.5%    CPU0 IDLE
> [CPU1] dump_task:       1     1     1   0 FIFO     Kthread - Assigned           0000000000000000 0x10823110      1008       664    65.8%    CPU1 IDLE
> [CPU1] dump_task:       2     2     2   0 FIFO     Kthread - Running            0000000000000000 0x10823510      1008       664    65.8%    CPU2 IDLE
> [CPU1] dump_task:       3     3     3   0 FIFO     Kthread - Running            0000000000000000 0x10823910      1008       664    65.8%    CPU3 IDLE
> [CPU1] dump_task:       4     4     0 192 RR       Kthread - Waiting Semaphore  0000000000000000 0x10829440      1984       432    21.7%    hpwork 0x1082766c 0x10827680
> [CPU1] dump_task:       5     5     1 100 RR       Task    - Running            0000000000000000 0x1082a000      2008      1540    76.6%    nsh_main
> [CPU1] dump_task:       6     6     0 100 RR       Task    - Running            0000000000000000 0x1082aed8      2016       456    22.6%    hello
> ```

@masayuki2009 if you try same test just reverting his commit does the issue disappear? What is at LR 10807295 ? It seems like PC is moving to position -1 (0xffffffff)

**Comment by masayuki2009** [comment]
> > @szsam I tried this PR with sabre-6quad:smp (qemu-8.2.0)
> > ```
> > $ /home/ishikawa/opensource/QEMU/qemu-8.2.0/build/qemu-system-arm -semihosting -M sabrelite -m 1024 -smp 4 -kernel nuttx -nographic
> > 
> > NuttShell (NSH) NuttX-12.0.0
> > nsh> ps
> >   PID GROUP CPU PRI POLICY   TYPE    NPX STATE    EVENT     SIGMASK           STACK   USED  FILLED COMMAND
> >     0     0   0   0 FIFO     Kthread   - Assigned           0000000000000000 001008 000560  55.5%  CPU0 IDLE
> >     1     1   1   0 FIFO     Kthread   - Running            0000000000000000 001008 000664  65.8%  CPU1 IDLE
> >     2     2   2   0 FIFO     Kthread   - Running            0000000000000000 001008 000664  65.8%  CPU2 IDLE
> >     3     3   3   0 FIFO     Kthread   - Running            0000000000000000 001008 000664  65.8%  CPU3 IDLE
> >     4     4 --- 192 RR       Kthread   - Waiting  Semaphore 0000000000000000 001984 000432  21.7%  hpwork 0x1082766c 0x10827680
> >     5     5   0 100 RR       Task      - Running            0000000000000000 002008 001248  62.1%  nsh_main
> > nsh> help
> > help usage:  help [-v] [<cmd>]
> > 
> >     .           cp          exit        mkdir       rmdir       umount      
> >     [           cmp         expr        mkrd        set         unset       
> >     ?           dirname     false       mount       sleep       uptime      
> >     alias       dd          fdinfo      mv          source      usleep      
> >     unalias     df          free        pidof       test        xd          
> >     basename    dmesg       help        printf      time        
> >     break       echo        hexdump     ps          true        
> >     cat         env         kill        pwd         truncate    
> >     cd          exec        ls          rm          uname       
> > 
> > Builtin Apps:
> >     sh          ostest      hello       smp         
> >     getprime    taskset     nsh         
> > nsh> hello
> > Hello, World!!
> > [CPU1] arm_undefinedinsn: Undefined instruction at 0xffffffff
> > [CPU1] _assert: Current Version: NuttX  12.0.0 62854450c0 Apr  2 2024 22:06:59 arm
> > [CPU1] _assert: Assertion failed panic: at file: :0 task(CPU1): nsh_main process: nsh_main 0x10807421
> > [CPU1] up_dump_register: R0: 00000002 R1: 10829ca8 R2: 1082b570  R3: 1082b570
> > [CPU1] up_dump_register: R4: 1082aae8 R5: 10829c08 R6: 10825f0c  FP: 00000001
> > [CPU1] up_dump_register: R8: 0000005f SB: 00000001 SL: 1082a6d4 R11: 00000004
> > [CPU1] up_dump_register: IP: 00000006 SP: 1082a638 LR: 10807295  PC: ffffffff
> > [CPU1] up_dump_register: CPSR: 108019e9
> > [CPU1] dump_stack: User Stack:
> > [CPU1] dump_stack:   base: 0x1082a000
> > [CPU1] dump_stack:   size: 00002008
> > [CPU1] dump_stack:     sp: 0x1082a638
> > [CPU1] stack_dump: 0x1082a618: 00000001 0000005f 00000001 1082a6d4 00000004 00000006 ffffffff 108019e9
> > [CPU1] stack_dump: 0x1082a638: 00000000 1082aae8 10826dec 10801acf 00000000 1082aae8 2000005f 1082aa90
> > [CPU1] stack_dump: 0x1082a658: ffffffff 00000000 00000000 1082a6d4 00000004 10802421 00000001 1082a808
> > [CPU1] stack_dump: 0x1082a678: 00000000 1082aa90 ffffffff 10808c05 0000005f 1082a808 1082aa90 00000000
> > [CPU1] stack_dump: 0x1082a698: ffffffff 1082a808 1082aa90 00000001 00000000 10808271 00000000 1080563b
> > [CPU1] stack_dump: 0x1082a6b8: 00000201 10822f2c 1082aa96 10804fbf 10829f08 00000000 00000000 00000000
> > [CPU1] stack_dump: 0x1082a6d8: 10829f08 1082a727 00000001 1082aa90 00000000 00000000 00000000 00000000
> > [CPU1] stack_dump: 0x1082a6f8: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
> > [CPU1] stack_dump: 0x1082a718: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
> > [CPU1] stack_dump: 0x1082a738: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
> > [CPU1] stack_dump: 0x1082a758: 1082a808 1082a808 10823009 1082aa90 00000001 00000000 00000000 00000000
> > [CPU1] stack_dump: 0x1082a778: 00000000 108075c3 1082a808 00000001 00000001 1082a808 00000001 10829fe8
> > [CPU1] stack_dump: 0x1082a798: 00000000 1080747b 00000001 10829fe8 10829fe8 1080744d 00000001 00000064
> > [CPU1] stack_dump: 0x1082a7b8: 10829fe8 10807421 00000001 10805801 10829c08 10803663 00000000 00000000
> > [CPU1] stack_dump: 0x1082a7d8: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
> > [CPU1] dump_tasks:    PID GROUP   CPU PRI POLICY   TYPE    NPX STATE   EVENT      SIGMASK          STACKBASE  STACKSIZE      USED   FILLED    COMMAND
> > [CPU1] dump_tasks:   ----   ---  ---- --- -------- ------- --- ------- ---------- ---------------- 0x10824500      2048       120     5.8%    irq
> > [CPU1] dump_task:       0     0     0   0 FIFO     Kthread - Assigned           0000000000000000 0x108282d8      1008       560    55.5%    CPU0 IDLE
> > [CPU1] dump_task:       1     1     1   0 FIFO     Kthread - Assigned           0000000000000000 0x10823110      1008       664    65.8%    CPU1 IDLE
> > [CPU1] dump_task:       2     2     2   0 FIFO     Kthread - Running            0000000000000000 0x10823510      1008       664    65.8%    CPU2 IDLE
> > [CPU1] dump_task:       3     3     3   0 FIFO     Kthread - Running            0000000000000000 0x10823910      1008       664    65.8%    CPU3 IDLE
> > [CPU1] dump_task:       4     4     0 192 RR       Kthread - Waiting Semaphore  0000000000000000 0x10829440      1984       432    21.7%    hpwork 0x1082766c 0x10827680
> > [CPU1] dump_task:       5     5     1 100 RR       Task    - Running            0000000000000000 0x1082a000      2008      1540    76.6%    nsh_main
> > [CPU1] dump_task:       6     6     0 100 RR       Task    - Running            0000000000000000 0x1082aed8      2016       456    22.6%    hello
> > ```
> 
> @masayuki2009 if you try same test just reverting his commit does the issue disappear? What is at LR 10807295 ? It seems like PC is moving to position -1 (0xffffffff)

Yes. It works without this PR.

**Comment by szsam** [comment]
`doswitch` should always be `false` if `cpu != me`. The code in master is correct.

However, `doswitch` is still uninitialized if no context switch occurs and `cpu == me`.

@masayuki2009  I modified my PR. It no longer crashes.

**Comment by pkarashchenko** [comment]
Seems reasonable. @masayuki2009 please take a look

**Comment by masayuki2009** [comment]
I've just confirmed that the latest PR works.

**Pull request merged**
