### PR TITLE
libs/libc/stdlib: update BSD 4 -> 3 clause license headers.

### PR DESCRIPTION
**Pull request by jerpelea**
## Summary

remove the advertising clause
3. All advertising materials mentioning features or use of this software must
display the following acknowledgement: This product includes software
developed by the University of California, Berkeley and its contributors.

permitted by Berkley amendment
https://ipira.berkeley.edu/sites/default/files/amendment_of_4-clause_bsd_software_license.pdf

following example from NETBSD and OPENBSD
https://github.com/NetBSD/src/commit/eb7c1594f145c931049e1fd9eb056a5987e87e59
https://github.com/openbsd/src/commit/6580fee3295c971a919cc04bfc3598c5f8bcd2b1

## Impact

LICENSE

## Testing

CI

### CODE REVIEW

**Comment by xiaoxiang781216** [comment]
@jerpelea where do you identify the code is BSD-4, not BSD?
BTW, qsort/bsearh is used in many places, we need replace with alternate implementation, instead removing it.

**Comment by yamt** [comment]
> ## Summary
> 
> The BSD-4 Clause may cause issues with comercial products and should be avoided
> 
>     3. All advertising materials mentioning features or use of this software must display the following acknowledgement: This product includes software developed by the University of California, Berkeley and its contributors.

iirc, the UCB has retroactively removed the clause.
cf. https://gnats.netbsd.org/cgi-bin/query-pr-single.pl?number=22280

depending of the history of these files (i dunno. @gregory-nutt do you remember?)
we can probably just update the license as NetBSD and other BSD derivatives did.

at the worst case, we can re-fork from the recent versions of BSDs.

**Comment by yamt** [comment]
> @jerpelea where do you identify the code is BSD-4, not BSD?

these files themselves have copies of the notice.

**Comment by jerpelea** [comment]
@yamt we can not remove the clause in our code. It is better to fork a newer copy or replace to avoid possible issues

**Comment by jerpelea** [comment]
> > @jerpelea where do you identify the code is BSD-4, not BSD?
> 
> these files themselves have copies of the notice.

unfortunately this is not enough

**Comment by yamt** [comment]
> @yamt we can not remove the clause in our code. It is better to fork a newer copy or replace to avoid possible issues

even if the author (UCB) says ok? why not?

**Comment by yamt** [comment]
> > > @jerpelea where do you identify the code is BSD-4, not BSD?
> > 
> > 
> > these files themselves have copies of the notice.
> 
> unfortunately this is not enough

i was just replying to @xiaoxiang781216 's question.

**Comment by yamt** [comment]
anyway, regardless of the licenses, it's probably a good idea to re-fork from the latest versions
because our qsort seems to lack a few important fixes done in BSDs.

**Comment by jerpelea** [comment]
> anyway, regardless of the licenses, it's probably a good idea to re-fork from the latest versions because our qsort seems to lack a few important fixes done in BSDs.

can you take care of it ?

**Comment by cederom** [comment]
Hello world :-) Here is the FreeBSD src repo with the functions:

https://cgit.freebsd.org/src/tree/lib/libc/stdlib

1. `bsearch`: 
* NuttX: https://github.com/apache/nuttx/blob/master/libs/libc/stdlib/lib_bsearch.c.
* FreeBSD: https://cgit.freebsd.org/src/tree/lib/libc/stdlib/bsearch.c.
* FreeBSD manpage: https://man.freebsd.org/cgi/man.cgi?query=bsearch.
* FreeBSD version has 3 clause BSD license (`SPDX-License-Identifier: BSD-3-Clause`), seems compatible, may need some minor tweak if we do not need block `bsearch_b()` variant and to use old param names + documentation, but these may come handy?

2. `qsort`:
* NuttX: https://github.com/apache/nuttx/blob/master/libs/libc/stdlib/lib_qsort.c.
* FreeBSD: https://cgit.freebsd.org/src/tree/lib/libc/stdlib/qsort.c
* FreeBSD manpage: https://man.freebsd.org/cgi/man.cgi?query=qsort.
* FreeBSD version has 3 clause BSD license (`SPDX-License-Identifier: BSD-3-Clause`), seems compatible, may need some minor tweak if we do not updated implementation / variants + documentation, but these may come handy?

**Review by cederom — CHANGES_REQUESTED** [review]
Thank you @jerpelea :-) As CI testing reveals this change will break lots of things, we need to replace existing problematic functions with updated compatible and required license ones, I have provided examples from FreeBSD src that already have the SPDX License Identifiers set to BSD-3-Clause :-)

**Comment by yamt** [comment]
> > anyway, regardless of the licenses, it's probably a good idea to re-fork from the latest versions because our qsort seems to lack a few important fixes done in BSDs.
> 
> can you take care of it ?

maybe.
but it's a "sooner or later" item for me.

**Comment by patacongo** [comment]
_[I posted this hours ago via email, but it didn't make it]_

Wouldn't it make sense to add a BSD 4-clause selection to the configuratioin? It should include a warning that selection of the option will cause violation of newer GPL licenses and will require some advertising.

Yes, BSD 4-clause cannot be linked with current GPL.  That is GPL forbids linking with any other license that has additional requirements beyond GPL (such as the advertising clause).

[I thought UC Berkeley had waived that clause, but perhaps that is not the case.  We talked about this extensively when we became Apache and out mentor assured us that there was no issue.  Revisiting those old discussions of 2019-2020 would be worthwhile.

**Comment by yamt** [comment]
> > > @cederom: Thank you @jerpelea :-) As CI testing reveals this change will break lots of things, we need to replace existing problematic functions with updated compatible and required license ones, I have provided examples from FreeBSD src that already have the SPDX License Identifiers set to BSD-3-Clause :-)
> > 
> > 
> > @yamt: talking about SPDX, there is a dedicated -UC one for the UCB license: https://spdx.org/licenses/preview/BSD-4-Clause-UC.html because it's effectively same as BSD-3-Clause. read the "Notes" section if you are interested.
> 
> Thanks @yamt but the 3rd advertising clause is still here and what I understand this is the main problem and concern not to enforce such advertising on end-users?

i don't see why you (@cederom and @jerpelea) think it a problem after the statement from UCB.

**Comment by yamt** [comment]
> [I thought UC Berkeley had waived that clause,

it's my understanding.

**Comment by cederom** [comment]
If the BSD 4 -> 3 clause is legal then we could only rewrite the license header without touching the code and this is perfect situation.. we just need some official legal statement citation for instance this one: https://ipira.berkeley.edu/sites/default/files/amendment_of_4-clause_bsd_software_license.pdf :-)

**Comment by jerpelea** [comment]
> > > anyway, regardless of the licenses, it's probably a good idea to re-fork from the latest versions because our qsort seems to lack a few important fixes done in BSDs.
> > 
> > 
> > can you take care of it ?
> 
> maybe. but it's a "sooner or later" item for me.

this is a blocker for the release

**Comment by jerpelea** [comment]
> If the BSD 4 -> 3 clause is legal then we could only rewrite the license header without touching the code and this is perfect situation.. we just need some official legal statement citation for instance this one: https://ipira.berkeley.edu/sites/default/files/amendment_of_4-clause_bsd_software_license.pdf :-)

Do you have time to fork and adapt the new code?

**Comment by yamt** [comment]
> > > > anyway, regardless of the licenses, it's probably a good idea to re-fork from the latest versions because our qsort seems to lack a few important fixes done in BSDs.
> > > 
> > > 
> > > can you take care of it ?
> > 
> > 
> > maybe. but it's a "sooner or later" item for me.
> 
> this is a blocker for the release

porting latest fixes (what my comment above was about)
and solving the license "issue" (which is not really an issue as far as understand)
are two separate topic i guess.
the release blocker is the latter, not former, right?

**Comment by yamt** [comment]
> > If the BSD 4 -> 3 clause is legal then we could only rewrite the license header without touching the code and this is perfect situation.. we just need some official legal statement citation for instance this one: https://ipira.berkeley.edu/sites/default/files/amendment_of_4-clause_bsd_software_license.pdf :-)
> 
> Do you have time to fork and adapt the new code?

why don't you just update the license?
it would be safer and thus more appropriate for a last-minute change for a release.

**Comment by cederom** [comment]
> > @cederom: If the BSD 4 -> 3 clause is legal then we could only rewrite the license header without touching the code and this is perfect situation.. we just need some official legal statement citation for instance this one: https://ipira.berkeley.edu/sites/default/files/amendment_of_4-clause_bsd_software_license.pdf :-)
> 
> @jerpelea: Do you have time to fork and adapt the new code?

I will update the license header to 3 clause.. in a minute it will be ready :-)

We may update the code after a release is made to have more time for testing ok? :-)

**Comment by jerpelea** [comment]
@cederom @yamt @patacongo  I replicated and documented the license change. 

The license should be fine now 

Thanks for doing the research and provide feedback.

**Comment by jerpelea** [comment]
> > > @cederom: If the BSD 4 -> 3 clause is legal then we could only rewrite the license header without touching the code and this is perfect situation.. we just need some official legal statement citation for instance this one: https://ipira.berkeley.edu/sites/default/files/amendment_of_4-clause_bsd_software_license.pdf :-)
> > 
> > 
> > @jerpelea: Do you have time to fork and adapt the new code?
> 
> I will update the license header to 3 clause.. in a minute it will be ready :-)
> 
> We may update the code after a release is made to have more time for testing ok? :-)
> 
> Update: I can see @jerpelea already updated, thanks Alin! :-)

please unblock the review

**Review by cederom — APPROVED** [review]
Thank you @jerpelea :-)

This BSD 4 -> 3 clause license update is legal according to:  https://ipira.berkeley.edu/sites/default/files/amendment_of_4-clause_bsd_software_license.pdf:

> January 13, 2012
> (..)
> Effective immediately, licensees and distributors are no longer required to
> include the acknowledgement within advertising materials. Accordingly, the
> advertising clause 3 of the original 4-clause BSD license for any and all software
> officially licensed by UC Berkeley, is hereby deleted in its entirety.
> Michael Katz
> Executive Director
> Intellectual Property and Industry Research Alliances
> University of California, Berkeley

**Review by yamt — APPROVED** [review]
i guess it's better to update the PR title as well.

**Review by xiaoxiang781216 — APPROVED** [review]

**Pull request merged**
