### PR TITLE
binfmt_loadmodule.c: Look for executables from PWD, if not found from PATH

### PR DESCRIPTION
**Pull request by pussuw**
## Summary

This expands the search for executables to the current working directory, if the executable is not found from PATH.

Why do this?

Starting processes now works similarly when envpaths are not used, in which case the inode search procedure peeks into PWD via inode_search -> _inode_getcwd.

This is just a user experience enhancement.
## Impact
Tiny, only when CONFIG_LIBC_ENVPATH=y and executable is not in PATH
## Testing
Target with file applications and CONFIG_LIBC_ENVPATH=y

### CODE REVIEW

**Comment by pussuw** [comment]
> @pussuw so, with this modification, if hello is not in the PATH, but it is in the local directory, it be executed, even if we don't call ./hello explicitly? That is it?

Exactly yes. The reason I did the change is because it works differently depending on CONFIG_LIBC_ENVPATH=y/n.

With CONFIG_LIBC_ENVPATH=n the `inode_search `procedure looks for the file in CWD. With CONFIG_LIBC_ENVPATH=y only PATH is used. After this change both work like it did with CONFIG_LIBC_ENVPATH=n.

Did not look at standards if using both PATH and CWD to find executables is legal. If not, then CONFIG_LIBC_ENVPATH=n behavior is wrong and needs to change (when using fileapps). Maybe this should not be merged before a we've had a discussion about it.

**Comment by pussuw** [comment]
Btw, does ./hello work with nsh ? I don't think it parses . as the CWD, i.e. it does not work with relative paths, only paths in PATH and absolute paths from the fs root ?

**Comment by acassis** [comment]
> Btw, does ./hello work with nsh ? I don't think it parses . as the CWD, i.e. it does not work with relative paths, only paths in PATH and absolute paths from the fs root ?

Good point, currently ./hello is not supported. It is something we need to fix.

But I think running an executable from current directory by default should be avoided (for security reasons)

There are some references here:
https://askubuntu.com/questions/1260013/why-does-a-out-work-but-a-out-doesnt

**Comment by pussuw** [comment]
> > Btw, does ./hello work with nsh ? I don't think it parses . as the CWD, i.e. it does not work with relative paths, only paths in PATH and absolute paths from the fs root ?
> 
> Good point, currently ./hello is not supported. It is something we need to fix.
> 
> But I think running an executable from current directory by default should be avoided (for security reasons)
> 
> There are some references here: https://askubuntu.com/questions/1260013/why-does-a-out-work-but-a-out-doesnt

Thanks for the reference. I'll take a look at POSIX tomorrow, it is what defines how the shell should work. Either way, something is not working like it should right now :)

**Comment by pussuw** [comment]
Yes, this patch is 100% in violation with POSIX.

Also, running CONFIG_NSH_FILE_APPS=y when CONFIG_LIBC_ENVPATH=n is 100% in violation with POSIX, because running programs from CWD works without the ./ notation in this configuration.

Also, what I'm trying to do here is easily done by adding . to path, so in addition to being a standards violation, it is also completely redundant.

**Pull request closed without merging**
