### PR TITLE
stdio/va_format: move non-standard structure va_format to nuttx/streams.h

### PR DESCRIPTION
**Pull request by Donny9**
## Summary
stdio/va_format: move non-standard structure va_format to nuttx/streams.h
## Impact
N/A
## Testing
local compile

### CODE REVIEW

**Comment by nuttxpr** [comment]
[**\[Experimental Bot, please feedback here\]**](https://github.com/search?q=repo%3Aapache%2Fnuttx+13552&type=issues)



**No, this PR does not meet the NuttX Requirements.**

**Missing Information:**

* **Summary:**
    * Lacks a clear explanation of why the change is necessary. Is it a bug fix, code cleanup, performance improvement, etc.?
    * Needs more details on how the change works. Simply stating that a structure is being moved is insufficient. Explain the reasoning and implications.
* **Impact:**
    * While marking all sections as "N/A" might be technically correct, it's crucial to elaborate and justify why there's no impact in any area.  For instance, even moving a structure could have implications on backward compatibility.
* **Testing:**
    * "Local compile" is insufficient testing. Provide specific details:
       * Build Host(s) OS, CPU architecture, compiler version.
       * Target(s): Architecture (e.g., simulator, real hardware), board, configuration.
    * Include relevant testing logs *before* and *after* the change to demonstrate the problem being solved or the functionality being added.

**Recommendations:**

1. **Expand the Summary:**  Explain the motivation for the change and its technical details comprehensively.
2. **Address Impact Carefully:** Even if there's no apparent impact, explain why. For example, "This change only affects internal code structure and has no impact on the public API, build process, or hardware compatibility."
3. **Provide Detailed Testing Information:** List specific build hosts and targets, and include relevant log snippets to demonstrate the change's effect.

**Review by xiaoxiang781216 — APPROVED** [review]

**Review by jerpelea — CHANGES_REQUESTED** [review]
please add commit messages which describe the change and why is it needed

**Review by jerpelea — APPROVED** [review]

**Comment by cederom** [comment]
Yes we need increase PR descriptions quality.. bot was created to help.. you can .. wait was there this nice copy-paste section where all sections were filled in already before @lupyuen ? :-)

**Comment by Donny9** [comment]
> please add commit messages which describe the change and why is it needed

I have explained clearly enough in the commit message. Please read carefully. va_format is not a standard structure and cannot be placed in standard stdio files.

**Comment by pkarashchenko** [comment]
Please provide link to nuttx-apps PR as well.

**Comment by Donny9** [comment]
> Please provide link to nuttx-apps PR as well.

https://github.com/apache/nuttx-apps/pull/2600 Done~

**Comment by xiaoxiang781216** [comment]
@Donny9 please fix the build error
```
github/workspace/sources/apps/system/adb/adb_main.c: In function 'adb_log_impl':
Error: /github/workspace/sources/apps/system/adb/adb_main.c:46:20: error: storage size of 'vaf' isn't known
   46 |   struct va_format vaf;
      |                    ^~~
```

**Comment by pkarashchenko** [comment]
Need to re-push the change to get actual apps version in the build

**Pull request merged**
