### PR TITLE
Remove OK macro from the code base

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
## Summary

let's use ERROR and OK from types.h instead, follow the change https://github.com/apache/nuttx/pull/8397

## Impact

Minor

## Testing

CI

### CODE REVIEW

**Comment by pkarashchenko** [comment]
I see where `OK` macro is removed, but failed to find where `ERROR` macro is removed

**Comment by xiaoxiang781216** [comment]
Here https://github.com/apache/nuttx-apps/pull/1527

**Comment by pkarashchenko** [comment]
So let's update commit message and this PR description to "remove OK...." if ERROR is removed in apps repo

**Review by jerpelea — APPROVED** [review]

**Comment by xiaoxiang781216** [comment]
Done.

**Review by pkarashchenko — APPROVED** [review]

**Pull request merged**
