### PR TITLE
STM32 Nucleo: warning: #warning "Default Flash Configuration Used"

### PR DESCRIPTION
**Pull request by spi3ex**
## Summary

https://cwiki.apache.org/confluence/display/NUTTX/Configuration+Variables 
F412ZG has 1028 KB Flash.

## Impact

In file included from chip/stm32_flash.c:38:
chip/stm32f20xxf40xx_flash.c:51:4: warning: #warning "Default Flash Configuration Used - See Override Flash Size Designator" [-Wcpp]
   51 | #  warning "Default Flash Configuration Used - See Override Flash Size Designator"
      |    ^~~~~~~

## Testing

Fixed the Warning, Successful build without warnings on `nucleo-f412zg:nsh`

### CODE REVIEW

**Review by jerpelea — APPROVED** [review]

**Comment by spi3ex** [comment]
Hi @xiaoxiang781216 , @acassis looks like there was an error with the build, Can you please retrigger the build once again. or the specific build-only.
```
Configuration/Tool: sim/duktape
[1645](https://github.com/apache/nuttx/actions/runs/4202802379/jobs/7291464125#step:7:1646)
------------------------------------------------------------------------------------
[1646](https://github.com/apache/nuttx/actions/runs/4202802379/jobs/7291464125#step:7:1647)
  Cleaning...
[1647](https://github.com/apache/nuttx/actions/runs/4202802379/jobs/7291464125#step:7:1648)
  Configuring...
[1648](https://github.com/apache/nuttx/actions/runs/4202802379/jobs/7291464125#step:7:1649)
  Building NuttX...
[1649](https://github.com/apache/nuttx/actions/runs/4202802379/jobs/7291464125#step:7:1650)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[1650](https://github.com/apache/nuttx/actions/runs/4202802379/jobs/7291464125#step:7:1651)
                                 Dload  Upload   Total   Spent    Left  Speed
[1651](https://github.com/apache/nuttx/actions/runs/4202802379/jobs/7291464125#step:7:1652)

[1652](https://github.com/apache/nuttx/actions/runs/4202802379/jobs/7291464125#step:7:1653)
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
[1653](https://github.com/apache/nuttx/actions/runs/4202802379/jobs/7291464125#step:7:1654)
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
[1654](https://github.com/apache/nuttx/actions/runs/4202802379/jobs/7291464125#step:7:1655)

[1655](https://github.com/apache/nuttx/actions/runs/4202802379/jobs/7291464125#step:7:1656)
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
[1656](https://github.com/apache/nuttx/actions/runs/4202802379/jobs/7291464125#step:7:1657)
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
[1657](https://github.com/apache/nuttx/actions/runs/4202802379/jobs/7291464125#step:7:1658)
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
[1658](https://github.com/apache/nuttx/actions/runs/4202802379/jobs/7291464125#step:7:1659)
  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0
[1659](https://github.com/apache/nuttx/actions/runs/4202802379/jobs/7291464125#step:7:1660)
  0     0    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--     0
[1660](https://github.com/apache/nuttx/actions/runs/4202802379/jobs/7291464125#step:7:1661)
100   212  100   212    0     0     36      0  0:00:05  0:00:05 --:--:--    41
[1661](https://github.com/apache/nuttx/actions/runs/4202802379/jobs/7291464125#step:7:1662)
100   212  100   212    0     0     36      0  0:00:05  0:00:05 --:--:--    51
[1662](https://github.com/apache/nuttx/actions/runs/4202802379/jobs/7291464125#step:7:1663)
**tar: Error opening archive: Unrecognized archive format**
[1663](https://github.com/apache/nuttx/actions/runs/4202802379/jobs/7291464125#step:7:1664)
make[3]: *** [duktape] Error 1
[1664](https://github.com/apache/nuttx/actions/runs/4202802379/jobs/7291464125#step:7:1665)
make[3]: Target `context' not remade because of errors.
[1665](https://github.com/apache/nuttx/actions/runs/4202802379/jobs/7291464125#step:7:1666)
make[2]: *** [/Users/runner/work/nuttx/nuttx/sources/apps/interpreters/duktape_context] Error 2
[1666](https://github.com/apache/nuttx/actions/runs/4202802379/jobs/7291464125#step:7:1667)
make[2]: Target `context_all' not remade because of errors.
[1667](https://github.com/apache/nuttx/actions/runs/4202802379/jobs/7291464125#step:7:1668)
make[1]: *** [context] Error 2
[1668](https://github.com/apache/nuttx/actions/runs/4202802379/jobs/7291464125#step:7:1669)
make: *** [/Users/runner/work/nuttx/nuttx/sources/apps/.context] Error 2
[1669](https://github.com/apache/nuttx/actions/runs/4202802379/jobs/7291464125#step:7:1670)
make: Target `all' not remade because of errors.
```

**Comment by spi3ex** [comment]
#8564

**Comment by xiaoxiang781216** [comment]
Ok, let's wait the new run.

**Comment by xiaoxiang781216** [comment]
The ci is till broken falsely. Let's ignore it and merge this simple change.

**Pull request merged**
