### PR TITLE
sched: Rename DEBUG_TCBINFO to ARCH_HAVE_TCBINFO

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
## Summary

since the linker can remove g_tcbinfo, if no code really reference it

## Impact

gdb debugging

## Testing

ci

### CODE REVIEW

**Comment by acassis** [comment]
@Ouss4 , @gustavonihei I think you both wrote/worked this/in file

**Comment by patacongo** [comment]
> @Ouss4 , @gustavonihei I think you both wrote/worked this/in file (arch/xtensa/src/common/xtensa_tcbinfo.c)

The point that @xiaoxiang781216 is making is that the are just data definitions in a static library.  It doesn't need to be built conditionally because it will not be drawn into the build from the library if it is not referenced by anything.  Nothing else is changed.

**Review by patacongo — APPROVED** [review]

**Review by jerpelea — APPROVED** [review]

**Comment by xiaoxiang781216** [comment]
> > @Ouss4 , @gustavonihei I think you both wrote/worked this/in file (arch/xtensa/src/common/xtensa_tcbinfo.c)
> 
> The point that @xiaoxiang781216 is making is that the are just data definitions in a static library. It doesn't need to be built conditionally because it will not be drawn into the build from the library if it is not referenced by anything. Nothing else is changed.
> 
> There are a few additional changes here that don't related to the title or description.
> 
> * Corrects a register name

These changes are moved to https://github.com/apache/nuttx/pull/9859.

> * Removes TCB_STACK_OFF and TCB_STACK_SIZE_OFF (unused?)

Good catch! it's fixed by https://github.com/apache/nuttx/pull/9878. Both fields are used to support TRACE32 thread awareness debugging.

**Comment by xiaoxiang781216** [comment]
> > @Ouss4 , @gustavonihei I think you both wrote/worked this/in file (arch/xtensa/src/common/xtensa_tcbinfo.c)
> 
> The point that @xiaoxiang781216 is making is that the are just data definitions in a static library. It doesn't need to be built conditionally because it will not be drawn into the build from the library if it is not referenced by anything. Nothing else is changed.
> 
> There are a few additional changes here that don't related to the title or description.
> 
> * Corrects a register name

These changes are moved to https://github.com/apache/nuttx/pull/9859.

> * Removes TCB_STACK_OFF and TCB_STACK_SIZE_OFF (unused?)

**Review by jerpelea — APPROVED** [review]

**Review by anjiahao1 — APPROVED** [review]

**Pull request merged**
