### PR TITLE
arch/risc-v: Enable -msave-restore when CONFIG_DEBUG_FULLOPT is selected

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
## Summary

Do use smaller but slower prologue and epilogue code that uses library function calls.

## Impact

generate smaller image size

### CODE REVIEW

**Review by pkarashchenko — APPROVED** [review]

**Comment by pkarashchenko** [comment]
@pussuw could you please review?

**Comment by pussuw** [comment]
Looks good, but I think this extreme size optimization at the expense of performance should be optional. I for example enable size optimizations for both code size and execution speed.

**Comment by masayuki2009** [comment]
@xiaoxiang781216 
I noticed that rv-virt:knsh64 crashes on boot.
It seems the assertion happened.

```
$ /home/ishikawa/opensource/QEMU/qemu-7.1/build/qemu-system-riscv64 -semihosting -nographic -cpu rv64 -smp 8 -M virt,aclint=on -bios none -kernel nuttx
ABC[    0.036000] _assert: Current Version: NuttX  3.6.1 5426acb3b3 Jun 22 2023 18:08:19 risc-v
[    0.037000] _assert: Assertion failed panic: at file: machine/risc-v/arch_elf.c:590 task: Idle Task 0x800016a8
[    0.038000] up_dump_register: EPC: 0000000080001caa
[    0.038000] up_dump_register: A0: 0000000080200f30 A1: 000000000000024e A2: 0000000080015450 A3: 0000000000000000
[    0.039000] up_dump_register: A4: 00000000800185f4 A5: 0000000000000000 A6: 0000000080206cf8 A7: fffffffffffffff8
[    0.040000] up_dump_register: T0: 0000000080001c7a T1: ffffffffffffffe0 T2: 0000000000000020 T3: 00000000c0101584
[    0.041000] up_dump_register: T4: 00000000c0101578 T5: 00000000000000ff T6: 000000000000000f
[    0.042000] up_dump_register: S0: 0000000000000000 S1: 0000000080200b28 S2: 0000000080201770 S3: 0000000080015450
[    0.042000] up_dump_register: S4: 00000000800185d8 S5: 000000000000024e S6: 0000000000000000 S7: 0000000000000007
[    0.043000] up_dump_register: S8: 00000000000001c0 S9: 0000000000000003 S10: 0000000000001a69 S11: 0000000000000003
[    0.044000] up_dump_register: SP: 0000000080206790 FP: 0000000000000000 TP: 0000000000000000 RA: 0000000080001caa
[    0.045000] dump_stack: User Stack:
[    0.045000] dump_stack:   base: 0x80206030
[    0.045000] dump_stack:   size: 00003024
[    0.046000] dump_stack:     sp: 0x80206790
[    0.046000] stack_dump: 0x80206780: 80206790 00000000 80001da2 00000000 00000002 00000000 80000620 00000000
[    0.047000] stack_dump: 0x802067a0: 800082ca 00000000 802068a0 00000000 001113c8 00000000 7474754e 00000058
[    0.048000] stack_dump: 0x802067c0: 80007fce 00000000 ffffffb0 ffff00ff 00000020 00000000 8020d720 00000000
[    0.048000] stack_dump: 0x802067e0: 80206c00 00000000 80206c00 362e3300 8000312e 00000000 8020d750 00000000
[    0.049000] stack_dump: 0x80206800: 34356a38 63613632 33623362 6e754a20 20323220 33323032 3a383120 313a3830
[    0.050000] stack_dump: 0x80206820: 80200039 00000000 80206a38 00000000 80200238 73697200 00762d63 00000000
[    0.051000] stack_dump: 0x80206840: 802088a0 00000000 80206a38 00000000 000001c0 00000000 00000007 00000000
[    0.052000] stack_dump: 0x80206860: 00000000 00000000 80209750 00000000 8020a810 00000000 80208a80 00000000
[    0.052000] stack_dump: 0x80206880: 8020a858 00000000 80208a40 00000000 c000b4a3 00000000 80006776 00000000
[    0.053000] stack_dump: 0x802068a0: c000b4a3 00000000 80013eba 00000000 8020a810 00000000 80208a80 00000000
[    0.054000] stack_dump: 0x802068c0: 8020a858 00000000 80208a40 00000000 80206998 00000000 800103a2 00000000
[    0.054000] stack_dump: 0x802068e0: 00000000 00000000 00000000 00000000 ffffffff ffff0000 00001800 00000000
[    0.055000] stack_dump: 0x80206900: 80200b28 00001800 80209740 00000000 80209740 00000000 80209700 00000000
[    0.056000] stack_dump: 0x80206920: 80206998 00000000 00000000 00000000 00000000 00000000 00000000 00000000
[    0.056000] stack_dump: 0x80206940: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
[    0.057000] stack_dump: 0x80206960: 00000000 00000000 00000000 00000000 00000000 00000000 80208830 00000000
[    0.058000] stack_dump: 0x80206980: 00000000 00000000 80010042 00000000 802086d0 00000000 c0000000 00000000
[    0.059000] stack_dump: 0x802069a0: c0101000 00000000 0000b648 00000000 00000584 00000000 00000008 00000000
[    0.060000] stack_dump: 0x802069c0: 00000008 00000000 00310920 00000000 464c457f 00010102 00000000 00000000
[    0.060000] stack_dump: 0x802069e0: 00f30001 00000001 000000c4 00000000 00000000 00000000 0030fbe0 00000000
[    0.061000] stack_dump: 0x80206a00: 00000001 00000040 00400000 00340035 802088c0 00000000 80209690 00000000
[    0.062000] stack_dump: 0x80206a20: 80209610 00000000 00000000 00000000 00330032 00000020 00000001 000f7880
[    0.063000] stack_dump: 0x80206a40: 802086d0 00000000 802088a0 00000000 00000000 00000000 800158b0 00000000
[    0.063000] stack_dump: 0x80206a60: 80208830 00000000 80200258 00000000 fffffffe ffffffff 80010a0e 00000000
[    0.064000] stack_dump: 0x80206a80: 00000000 00000000 00000000 00000000 80206b60 00000000 800158b0 00000000
[    0.065000] stack_dump: 0x80206aa0: 800158b0 00000000 80208830 00000000 00000000 00000000 80010a70 00000000
[    0.066000] stack_dump: 0x80206ac0: 80208830 00000000 00000000 00000000 00000000 00000000 00000000 00000000
[    0.066000] stack_dump: 0x80206ae0: 80206b60 00000000 800158b0 00000000 80206b68 00000000 80208830 00000000
[    0.067000] stack_dump: 0x80206b00: fffffff4 ffffffff 8000ff64 00000000 00000000 00000000 00000000 00000000
[    0.068000] stack_dump: 0x80206b20: 00000000 00000000 00000000 00000000 00000000 00000000 80200b18 00000000
[    0.069000] stack_dump: 0x80206b40: 80201784 00000000 00000064 00000000 00000c00 00000000 80001944 00000000
[    0.069000] stack_dump: 0x80206b60: 00000000 00000000 80016400 00000000 00000000 00000000 00000c00 00000000
[    0.070000] stack_dump: 0x80206b80: 80201784 00000000 80201788 00000000 80200b28 00000000 80001878 00000000
[    0.071000] stack_dump: 0x80206ba0: 80400000 00000000 00400000 00000000 00000000 00000000 00000000 00000000
[    0.071000] stack_dump: 0x80206bc0: 00000000 00000000 00000000 00000000 00000000 00000000 800008a0 00000000
[    0.072000] stack_dump: 0x80206be0: 00000000 00000000 80000948 00000000 00000000 00000000 8000004c 00000000
[    0.073000] show_tasks:    PID GROUP PRI POLICY   TYPE    NPX STATE   EVENT      SIGMASK          STACKBASE  STACKSIZE      USED   FILLED    COMMAND
[    0.074000] show_tasks:   ----   --- --- -------- ------- --- ------- ---------- -------- 0x802002b0      2048      2040    99.6%!   irq
[    0.075000] dump_task:       0     0   0 FIFO     Kthread N-- Running            0000000000000000 0x80206030      3024      2232    73.8%    Idle Task
[    0.075000] dump_task:       1     1 100 RR       Kthread --- Waiting Unlock     0000000000000000 0x8020a060      1952       264    13.5%    lpwork 0x802014e8
```

**Comment by pkarashchenko** [comment]
@xiaoxiang781216 maybe it is reasonable to keep it as a part of `CONFIG_DEBUG_OPTLEVEL`? Seems like `CONFIG_DEBUG_CUSTOMOPT` already provides needed level of flexibility.

**Comment by xiaoxiang781216** [comment]
> @xiaoxiang781216 maybe it is reasonable to keep it as a part of `CONFIG_DEBUG_OPTLEVEL`? Seems like `CONFIG_DEBUG_CUSTOMOPT` already provides needed level of flexibility.

But the default value of CONFIG_DEBUG_OPTLEVEL give to "-O2"

**Comment by pkarashchenko** [comment]
> > @xiaoxiang781216 maybe it is reasonable to keep it as a part of `CONFIG_DEBUG_OPTLEVEL`? Seems like `CONFIG_DEBUG_CUSTOMOPT` already provides needed level of flexibility.
> 
> But the default value of CONFIG_DEBUG_OPTLEVEL give to "-O2"

No. I do not mean to change default value, but let `-msave-restore` be a part or `defconfig` file and set based on project configuration needs.

**Comment by xiaoxiang781216** [comment]
Ok, let's close this PR.

**Pull request closed without merging**
