### PR TITLE
tools/ci/platforms/darwin.sh: fix mkdir: wamrc: File exists

### PR DESCRIPTION
**Pull request by simbit18**
## Summary
mkdir wamrc -> mkdir -p wamrc
## Testing
github

### CODE REVIEW

**Comment by acassis** [comment]
It still failing here

**Comment by xiaoxiang781216** [comment]
@simbit18 could you fix the ci break ASAP? otherwise we have to revert https://github.com/apache/nuttx/pull/11676 first.

**Comment by simbit18** [comment]
@xiaoxiang781216 revert #11676

**Comment by xiaoxiang781216** [comment]
> @xiaoxiang781216 revert #11676

@simbit18 where the patch?

**Comment by simbit18** [comment]
@xiaoxiang781216  restored old version #11826

**Comment by simbit18** [comment]
@xiaoxiang781216 it seems that with the old cibuild.sh the problem still remains

**Comment by xiaoxiang781216** [comment]
https://github.com/apache/nuttx/actions/runs/8076972534/job/22066439073?pr=11202 make ci broken, https://github.com/apache/nuttx-apps/pull/2322 could fix it.

**Comment by xiaoxiang781216** [comment]
This patch is also needed to fix this broken:
https://github.com/apache/nuttx-apps/actions/runs/8124456719/job/22205978030?pr=2322

**Review by xiaoxiang781216 — APPROVED** [review]

**Pull request merged**
