### PR TITLE
Make more fs API available when CONFIG_DISABLE_MOUNTPOINT isn't enabled

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
## Summary

Fix the issue found by https://github.com/apache/nuttx-apps/pull/1559:

- fs: Don't guard fsync with CONFIG_DISABLE_MOUNTPOINT
- fs: Don't guard ftruncate with CONFIG_DISABLE_MOUNTPOINT
- fs: Don't guard rename with CONFIG_DISABLE_MOUNTPOINT 

## Impact

Minor

## Testing

CI

### CODE REVIEW

**Comment by acassis** [comment]
@xiaoxiang781216 why fsync is needed after his modifcation to fread/fwrite/* to read/write/* ?

Since previous mofication was decreasing the firmware size by some KBs, could you please get the new size after including fsync by default?

**Comment by acassis** [comment]
Still failing:
```
inode/fs_files.c: In function 'task_fssync':
Error: inode/fs_files.c:122:15: error: implicit declaration of function 'file_fsync'; did you mean 'file_fstat'? [-Werror=implicit-function-declaration]
  122 |               file_fsync(filep);
      |               ^~~~~~~~~~
      |               file_fstat
cc1: all warnings being treated as errors
make[1]: *** [Makefile:80: fs_files.o] Error 1
vfs/fs_fsync.c: In function 'file_fsync':
Error: vfs/fs_fsync.c:66:47: error: 'union inode_ops_u' has no member named 'i_mops'; did you mean 'i_ops'?
   66 |       if (INODE_IS_MOUNTPT(inode) && inode->u.i_mops &&
      |                                               ^~~~~~
      |                                               i_ops
Error: vfs/fs_fsync.c:67:20: error: 'union inode_ops_u' has no member named 'i_mops'; did you mean 'i_ops'?
   67 |           inode->u.i_mops->sync)
      |                    ^~~~~~
      |                    i_ops
Error: vfs/fs_fsync.c:71:27: error: 'union inode_ops_u' has no member named 'i_mops'; did you mean 'i_ops'?
   71 |           return inode->u.i_mops->sync(filep);
      |                           ^~~~~~
      |                           i_ops
 ```

**Comment by xiaoxiang781216** [comment]
> @xiaoxiang781216 why fsync is needed after his modifcation to fread/fwrite/* to read/write/* ?
> 

Since @no1wudi map fflush to fsync. But since fflush just flush the buffer in sdio layer to vfs layer, it's enough to only remove fflush.

> Since previous mofication was decreasing the firmware size by some KBs, could you please get the new size after including fsync by default?

Th3 size reported by @no1wudi should already include the consumption from fsync, otherwise we can't get the final image. Thanks you point out fsync issue, the size will decrease more:). @no1wudi please report the new size after removing fflush in https://github.com/apache/nuttx-apps/pull/1559.

**Comment by xiaoxiang781216** [comment]
> 

Done.

**Review by anchao — APPROVED** [review]

**Review by GUIDINGLI — APPROVED** [review]

**Pull request merged**
