### PR TITLE
Fix config repeat define in include deconfig mode

### PR DESCRIPTION
**Pull request by yezhonghui2024**
*Note: Please adhere to [Contributing Guidelines](https://github.com/apache/nuttx/blob/master/CONTRIBUTING.md).*

## Summary

we should process repeat define CONFIG when used #include “XXX/deconfig” mode

## Impact

*Update this section, where applicable, on how change affects users,
 build process, hardware, documentation, security, compatibility, etc.*

## Testing

*Update this section with details on how did you verify the change,
 what Host was used for build (OS, CPU, compiler, ..), what Target was
 used for verification (arch, board:config, ..), etc. Providing build
 and runtime logs from before and after change is highly appreciated.*

### CODE REVIEW

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by cederom** [comment]
Hello world :-)

There is a report of problem after this change @yezhonghui2024, details below, please let us know if you can repeat on Debian 12 with sed 4.9 and if this need a fix? :-)


```
slo@slolin:~/Sources/ccv5-env/nuttx$ git bisect good
27685aa179ad7608394fb8a97e11ef532888a75d is the first bad commit
commit 27685aa179ad7608394fb8a97e11ef532888a75d
Author: yezhonghui <yezhonghui@xiaomi.com>
Date:   Tue Sep 24 20:05:27 2024 +0800

    Fix config repeat define in include deconfig mode

    Signed-off-by: yezhonghui <yezhonghui@xiaomi.com>

tools/process_config.sh | 2 ++
1 file changed, 2 insertions(+)


../product/tools/configure-nuttx.sh
  Copy files
sed: -e expression n°1, caractère 11: caractères inutiles après la commande
sed: -e expression n°1, caractère 16: commande inconnue: « O »
sed: -e expression n°1, caractère 17: caractères inutiles après la commande
sed: -e expression n°1, caractère 14: commande inconnue: « S »
sed: -e expression n°1, caractère 11: caractères inutiles après la commande
sed: -e expression n°1, caractère 13: commande inconnue: « O »
sed: -e expression n°1, caractère 17: commande inconnue: « O »
sed: -e expression n°1, caractère 11: commande inconnue: « m »
sed: -e expression n°1, caractère 14: commande inconnue: « Z »
sed: -e expression n°1, caractère 15: commande inconnue: « O »
  Select CONFIG_HOST_LINUX=y

```

**Comment by xiaoxiang781216** [comment]
@cederom  which defconfig is used? I try the master branch sim:nsh with sed 4.9 without problem:
```
xiaoxiang@LAPTOP-MCMVB0JB:~/backup/os/nuttx/nuttx$ ./tools/configure.sh sim:nsh
  Copy files
  Select CONFIG_HOST_LINUX=y
  Refreshing...
CP: arch/dummy/Kconfig to /home/xiaoxiang/backup/os/nuttx/nuttx/arch/dummy/dummy_kconfig
CP: boards/dummy/Kconfig to /home/xiaoxiang/backup/os/nuttx/nuttx/boards/dummy/dummy_kconfig
LN: platform/board to /home/xiaoxiang/backup/os/nuttx/apps/platform/dummy
LN: include/arch to arch/sim/include
LN: include/arch/board to /home/xiaoxiang/backup/os/nuttx/nuttx/boards/sim/sim/sim/include
LN: drivers/platform to /home/xiaoxiang/backup/os/nuttx/nuttx/drivers/dummy
LN: include/arch/chip to /home/xiaoxiang/backup/os/nuttx/nuttx/arch/sim/include/sim
LN: arch/sim/src/chip to /home/xiaoxiang/backup/os/nuttx/nuttx/arch/sim/src/sim
LN: arch/sim/src/board to /home/xiaoxiang/backup/os/nuttx/nuttx/boards/sim/sim/sim/src
mkkconfig in /home/xiaoxiang/backup/os/nuttx/apps/audioutils
mkkconfig in /home/xiaoxiang/backup/os/nuttx/apps/benchmarks
mkkconfig in /home/xiaoxiang/backup/os/nuttx/apps/boot
mkkconfig in /home/xiaoxiang/backup/os/nuttx/apps/canutils
mkkconfig in /home/xiaoxiang/backup/os/nuttx/apps/crypto
mkkconfig in /home/xiaoxiang/backup/os/nuttx/apps/database
mkkconfig in /home/xiaoxiang/backup/os/nuttx/apps/examples/mcuboot
mkkconfig in /home/xiaoxiang/backup/os/nuttx/apps/examples/module
mkkconfig in /home/xiaoxiang/backup/os/nuttx/apps/examples/rust
mkkconfig in /home/xiaoxiang/backup/os/nuttx/apps/examples/sotest
mkkconfig in /home/xiaoxiang/backup/os/nuttx/apps/examples
mkkconfig in /home/xiaoxiang/backup/os/nuttx/apps/fsutils
mkkconfig in /home/xiaoxiang/backup/os/nuttx/apps/games
mkkconfig in /home/xiaoxiang/backup/os/nuttx/apps/graphics
mkkconfig in /home/xiaoxiang/backup/os/nuttx/apps/industry
mkkconfig in /home/xiaoxiang/backup/os/nuttx/apps/inertial
mkkconfig in /home/xiaoxiang/backup/os/nuttx/apps/interpreters/luamodules
mkkconfig in /home/xiaoxiang/backup/os/nuttx/apps/interpreters
mkkconfig in /home/xiaoxiang/backup/os/nuttx/apps/logging
mkkconfig in /home/xiaoxiang/backup/os/nuttx/apps/lte
mkkconfig in /home/xiaoxiang/backup/os/nuttx/apps/math
mkkconfig in /home/xiaoxiang/backup/os/nuttx/apps/mlearning
mkkconfig in /home/xiaoxiang/backup/os/nuttx/apps/netutils
mkkconfig in /home/xiaoxiang/backup/os/nuttx/apps/sdr
mkkconfig in /home/xiaoxiang/backup/os/nuttx/apps/system
mkkconfig in /home/xiaoxiang/backup/os/nuttx/apps/testing/arch
mkkconfig in /home/xiaoxiang/backup/os/nuttx/apps/testing/cxx
mkkconfig in /home/xiaoxiang/backup/os/nuttx/apps/testing/drivers
mkkconfig in /home/xiaoxiang/backup/os/nuttx/apps/testing/fs
mkkconfig in /home/xiaoxiang/backup/os/nuttx/apps/testing/libc
mkkconfig in /home/xiaoxiang/backup/os/nuttx/apps/testing/mm
mkkconfig in /home/xiaoxiang/backup/os/nuttx/apps/testing/sched
mkkconfig in /home/xiaoxiang/backup/os/nuttx/apps/testing
mkkconfig in /home/xiaoxiang/backup/os/nuttx/apps/videoutils
mkkconfig in /home/xiaoxiang/backup/os/nuttx/apps/wireless/bluetooth
mkkconfig in /home/xiaoxiang/backup/os/nuttx/apps/wireless/ieee802154
mkkconfig in /home/xiaoxiang/backup/os/nuttx/apps/wireless
mkkconfig in /home/xiaoxiang/backup/os/nuttx/apps
Loaded configuration '.config'
Configuration saved to '.config'
xiaoxiang@LAPTOP-MCMVB0JB:~/backup/os/nuttx/nuttx$ 
xiaoxiang@LAPTOP-MCMVB0JB:~/backup/os/nuttx/nuttx$ sed --version
sed (GNU sed) 4.9-dirty
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Jay Fenlason, Tom Lord, Ken Pizzini,
Paolo Bonzini, Jim Meyering, and Assaf Gordon.

This sed program was built with SELinux support.
SELinux is disabled on this system.

GNU sed home page: <https://www.gnu.org/software/sed/>.
General help using GNU software: <https://www.gnu.org/gethelp/>.
E-mail bug reports to: <bug-sed@gnu.org>.
```

**Comment by cederom** [comment]
* It's a stm32f429 cpu, so you have all the stm32 "common" board stuff inbetween.
*host is debian 12 or wsl.
* the problem happen just when running configure.sh, we've observed this on several developer machines.
* I think you should have a few custom boards on your build farm.

**Comment by xiaoxiang781216** [comment]
> * It's a stm32f429 cpu, so you have all the stm32 "common" board stuff inbetween.
>   *host is debian 12 or wsl.

I use wsl.

> * the problem happen just when running configure.sh, we've observed this on several developer machines.
> * I think you should have a few custom boards on your build farm.

we use the custom board in production, never saw this error before.

**Comment by cederom** [comment]
Thank you @xiaoxiang781216 :-)

**Review by jerpelea — COMMENTED** [review]
no commit message !

**Pull request merged**
