### PR TITLE
Shorter TCP's RTO setting by default

### PR DESCRIPTION
**Pull request by ethanlcz**

### CODE REVIEW

**Comment by xiaoxiang781216** [comment]
@ethanlcz please rebase your patch to ensure https://github.com/apache/nuttx/pull/7772 is included.

**Comment by ethanlcz** [comment]
> @ethanlcz please rebase your patch to ensure #7772 is included.

done

**Comment by xiaoxiang781216** [comment]
Please rebase agian.

**Comment by ethanlcz** [comment]
> @ethanlcz The TCP layer may be used on slow Layer 1 connections and the RTO should remain as it is defined.

I aggree that for slow Layer 1 connections the RTO should be longer. But I think most of the widely used IoT devices (e.g. home IoT devices、wearable devices、smart speakers) are based on the highly throughput network. And default value should be set for the most widely used scenarios. Base on this scenario, I think it is better to shorter the RTO default setting.
How do you think?

**Pull request closed without merging**
