### PR TITLE
arch/sim: Replace uart_[xmit|recv]chars_dma with uart_dma[txavail|rxfree]

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
## Summary

to follow the original dma design

## Impact

sim

## Testing

sim:nsh

### CODE REVIEW

**Comment by raiden00pl** [comment]
This is a breaking change for people who use sim for testing UART communication in non-DMA mode. It is not always possible to enable DMA for UART on real hardware, and sim target should allow you to test such an option. I don't think removing this option is a good idea, but enabling DMA by default is probably OK (but still a breaking change).

Ideally, this should be controlled per sim UART device (eg. DMA on UART0, no-DMA on UART1). I was working on something like this but haven't had a chance to get it ready for upstream.

**Comment by xiaoxiang781216** [comment]
> This is a breaking change for people who use sim for testing UART communication in non-DMA mode. It is not always possible to enable DMA for UART on real hardware, and sim target should allow you to test such an option. 

So, you want to learn how non DMA work on simulator? 

> I don't think removing this option is a good idea, but enabling DMA by default is probably OK (but still a breaking change).
> 

Why is it a breaking change except to demo how to write non DMA driver?

> Ideally, this should be controlled per sim UART device (eg. DMA on UART0, no-DMA on UART1). I was working on something like this but haven't had a chance to get it ready for upstream.

**Comment by raiden00pl** [comment]
> So, you want to learn how non DMA work on simulator?

That's one thing. Another thing is to test communication protocols based on UART where the NuttX sim target is used as a part of the communication network.

> Why is it a breaking change except to demo how to write non DMA driver?

If the user previously expected DMA to be disabled by default (send data byte by byte) and has integration tests based on the simulator (communication with external UART devices), then enabling DMA may affect this. A well-written communication handler should deal with this properly, but there is a possibility that some code will be broken and it is worth mentioning.

**Comment by xiaoxiang781216** [comment]
> > So, you want to learn how non DMA work on simulator?
> 
> That's one thing. Another thing is to test communication protocols based on UART where the NuttX sim target is used as a part of the communication network.
> 
> > Why is it a breaking change except to demo how to write non DMA driver?
> 
> If the user previously expected DMA to be disabled by default (send data byte by byte) and has integration tests based on the simulator (communication with external UART devices), then enabling DMA may affect this. A well-written communication handler should deal with this properly, but there is a possibility that some code will be broken and it is worth mentioning.

Here is my thought:

1. The wire format is always same (each byte with the same bits) regardless the output is drived by DMA or code, so if the device break with this change, the root cause like the timing issue which should be fixed always.
2. Since sim uart driver is just a simple wrapper on top of(Linux tty driver) through file handle, we can't control how Linux serial driver work(DMA v.s. PIO).

Item 2 is the major reason why I remove the non-DMA support, since it's natural to map dma read/write to host file read/write and is impossible to control the byte/bit timing from userspace.

**Review by pkarashchenko — APPROVED** [review]
I think that is fine to use DMA path for SIM from functional perspective. Only the question about learning perspective is left. I mean that I see only learning value from currently used approach.

**Comment by raiden00pl** [comment]
I see now that both the non-DMA and DMA UART on sim sends bytes as one data chunk, no byte-by-byte. Either it used to work differently or it was my local changes in UART host implementation. 

But I still see no reason to remove non-DMA, if only for consistency with other archs or as an option to test the upper-half serial driver without DMA support.

**Comment by xiaoxiang781216** [comment]
> I see now that both the non-DMA and DMA UART on sim sends bytes as one data chunk, no byte-by-byte. Either it used to work differently or it was my local changes in UART host implementation.
> 
> But I still see no reason to remove non-DMA, if only for consistency with other archs or as an option to test the upper-half serial driver without DMA support.

No DMA doesn't make sense for sim since host tty device always work in buffer mode from userspace. I am afraid that keeping No DMA just confuse the user, but I remove the last patch anyway. Please take a look.

**Comment by patacongo** [comment]
Would you ever want to re-direct serial I/O to some other character device.  We often need to do that on real hardware that does not support serial DMA.  Would we not support that on the simulator?

**Comment by xiaoxiang781216** [comment]
> Would you ever want to re-direct serial I/O to some other character device. 

Yes, this is how uart driver on sim implemented.

> We often need to do that on real hardware that does not support serial DMA. Would we not support that on the simulator?
> 

But since it's on sim, we don't(can't) touch the hardware register directly, instead perform I/O through the regulator file I/O:
https://github.com/apache/nuttx/blob/master/arch/sim/src/sim/posix/sim_hostuart.c
https://github.com/apache/nuttx/blob/master/arch/sim/src/sim/sim_uart.c
So it's host serial driver which convert file I/O to DMA or PIO, not sim serial driver.

> Someone in the past worked on the simulator to support real USB devices via libusb. Would we never want to support a real CDC/ACM console either?
> 

Yes, but it isn't other serial driver which actually doesn't support dma yet:
https://github.com/apache/nuttx/blob/master/drivers/usbdev/cdcacm.c#L256-L283
The feature already implemented by @zyfeier:
https://github.com/apache/nuttx/pull/8646

> I believe that only a uart device driver could be used if only serial DMA is support. That DMA is not compatible with any other device.

But it isn't true, the serial driver frameworks support the mix of DMA and non DMA at the same time.

**Review by raiden00pl — APPROVED** [review]
@xiaoxiang781216 please update PR description and title before merge

**Comment by xiaoxiang781216** [comment]
Done.

**Pull request merged**
