### PR TITLE
arch/riscv: add T-HEAD CSR mapping

### PR DESCRIPTION
**Pull request by inochisa**
Add T-HEAD CSR mapping file. This allow user to access T-HEAD CSR in the way of #12117.

### CODE REVIEW

**Comment by simbit18** [comment]
@inochisa the CI failed due to network instability, you can push the change again.

https://github.com/apache/nuttx/actions/runs/8641783421/job/23691936554?pr=12125#step:7:1832
fatal: unable to access 'https://github.com/espressif/esp-hal-3rdparty.git/': Failed to connect to github.com port 443 after 133553 ms: Connection timed out

**Comment by pkarashchenko** [comment]
I restarted CI

**Comment by inochisa** [comment]
@pkarashchenko Thanks.

**Comment by acassis** [comment]
@pkarashchenko I think we should change our CI to retry connecting when these instability issues occur

**Comment by pkarashchenko** [comment]
I'm not an expert here. Probably we should do this if possible

**Review by xiaoxiang781216 — APPROVED** [review]

**Pull request merged**
