### PR TITLE
arch/stm32h5: Add ethernet hardware support files

### PR DESCRIPTION
**Pull request by stbenn**
This commit adds files in preperation of adding ethernet drivers for the STM32H563 and Nucleo-H563ZI board. It also modifies the pinmap to include ethernet pins (and cleaned up leftover comments from L5 file), as well as add those pins to the board.h for the nucleo-h563zi.

Files added:
  - arch/arm/src/stm32h5/hardware/stm32_ethernet.h
  - arch/arm/src/stm32h5/hardware/stm32_sbs.h
    - Not fully implemented, just register necessary for ethernet driver.

*Note: Please adhere to [Contributing Guidelines](https://github.com/apache/nuttx/blob/master/CONTRIBUTING.md).*

## Summary

These additions are to support the future addition of an ethernet driver for the STM32H563/H573 chips. This aims to add most of the necessary pre-processor defines and pin mappings necessary to port the ethernet driver from the stm32h7 to the stm32h5. The naming conventions mirror those in the h7 implementation, since these share ethernet peripheral IP.

A large number of the line changes in this PR are from removing unused comments in the pin map file. 

## Testing

After adding the files, no build errors occurred when building the nucleo-h563zi:nsh configuration. 

Host OS: Ubuntu 24.04 on WSL 2 (Windows 11)
Compiler: arm-none-eabi-gcc (15:13.2.rel1-2) 13.2.1 20231009

Target:
- Arch: STM32H5
- Chip: STM32H563ZIT6U
- Board: Nucleo-H563ZI
- Config: nucleo-h563zi:nsh

### CODE REVIEW

**Comment by stbenn** [comment]
Not quite sure why this could cause a failure in the pytest testing on the sabre-6quad. Is there some hidden dependency with the test that I am unaware of?

**Comment by xiaoxiang781216** [comment]
> Not quite sure why this could cause a failure in the pytest testing on the sabre-6quad. Is there some hidden dependency with the test that I am unaware of?

should be fixed by: https://github.com/apache/nuttx-apps/pull/2829. let me retrigger the ci

**Comment by stbenn** [comment]
@xiaoxiang781216 I see it is still failing, so I did some tests locally with the docker container. This is the log for arm-02 from the master commit this PR is based on (ed8bfdd2) : [docker-ed8bfdd2-arm02.log](https://github.com/user-attachments/files/17679429/docker-ed8bfdd2-arm02.log)

And here is the log for arm-02 on this branch: [eth-pr-arm02.log](https://github.com/user-attachments/files/17679463/eth-pr-arm02.log)

I hope this can possibly help diagnose the problem!

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by xiaoxiang781216** [comment]
> @xiaoxiang781216 I see it is still failing, so I did some tests locally with the docker container. This is the log for arm-02 from the master commit this PR is based on ([ed8bfdd](https://github.com/apache/nuttx/commit/ed8bfdd26a373b5af65fec880542599bdea1685b)) : [docker-ed8bfdd2-arm02.log](https://github.com/user-attachments/files/17679429/docker-ed8bfdd2-arm02.log)
> 
> And here is the log for arm-02 on this branch: [eth-pr-arm02.log](https://github.com/user-attachments/files/17679463/eth-pr-arm02.log)
> 
> I hope this can possibly help diagnose the problem!
> 
> Edit: Rebasing the PR to the newest master might help the issue. I rebased and pushed the branch

fixed by https://github.com/apache/nuttx/pull/14705

**Pull request merged**
