### PR TITLE
Add EtherCAT support on xmc4800-relax

### PR DESCRIPTION
**Pull request by Rdk-T**
## Summary

The xmc4800 board is a variant of the xmc4700 board whose main added feature is the EtherCAT module on it.
This PR add the support to use the EtherCAT module with NuttX.
It setup the pin configuration, the port configuration and enable the PLLUSB needed for the feature. 
An entry in the kconfig has been added to disable the enabling of the EtherCAT. It's on by default since it's the main purpose of this board.

## Impact
N / A

## Testing

Tested on the XMC4800 relax kit and on a second custom board  using the xmc4800.

### CODE REVIEW

**Comment by xiaoxiang781216** [comment]
@Rdk-T did you port the usespace ethercat library?

**Comment by Rdk-T** [comment]
@xiaoxiang781216  Hi, I didn't port the userspace EtherCAT library, this library is a master library and I intend to use the board as a slave.
I'm working with the underdevelopment KickCAT library.

**Comment by xiaoxiang781216** [comment]
> @xiaoxiang781216 Hi, I didn't port the userspace EtherCAT library, this library is a master library and I intend to use the board as a slave. I'm working with the underdevelopment KickCAT library.

so, you will add the porting to apps/?

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by Rdk-T** [comment]
@xiaoxiang781216 Hi, for the context with @leducp we are the main maintainers of the project KickCAT (https://github.com/leducp/KickCAT). KickCAT already provide a master implementation of the EtherCAT norm. The slave implementation is underdevelopment. 
In KickCAT an example using the XMC4800 and NuttX is used to test the slave stack.

We don't know well the functioning of the NuttX apps/. Is it possible to provide an app which uses an external lib in the project ?

We are not closed to provide an example in the apps, it's just not planned at the moment.

**Comment by xiaoxiang781216** [comment]
Here is the example to integrate the 3rd party library: https://github.com/apache/nuttx-apps/tree/master/canutils/lely-canopen

**Pull request merged**
