### PR TITLE
cpu:  in smp pthread_cancel occasionally deadlock

### PR DESCRIPTION
**Pull request by hujun260**
pthread_cancel may block forever
## Summary
In smp when cpu0 calls up_cpu_resume to release the cpu1 lock, another locked cpu1 did not execute immediately, and soon cpu0 called up_cpu_resume again,  now cpu1 unable to respond to the interrupt at this time, resulting in a deadlock. Our solution is to restore cpu1 execution from asynchronous to synchronous to ensure that cpu1 is restored.

## Impact
none

## Testing
ostest

### CODE REVIEW

**Comment by hujun260** [comment]
@xiaoxiang781216  please trigger ci.

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by masayuki2009** [comment]
@hujun260 

I think that 'cpu: ' in the commit log is too generic and would lead to misunderstanding.
My recommendation is to use 'arm64: ' instead.

```
commit 6063c0516e9899230d6de9e1c9ac8ca1bfbd0143 (tag: nuttx-20230424-015132)
Author: hujun5 <hujun5@xiaomi.com>
Date:   Fri Apr 7 17:11:33 2023 +0800

    cpu: in SMP pthread_cancel occasionally deadlock
    
    In smp when cpu0 calls up_cpu_resume to release the cpu1 lock, another locked cpu1 did not execute immediately,
    and soon cpu0 called up_cpu_resume again, now cpu1 unable to respond to the interrupt at this time, resulting in a deadlock.
    Our solution is to restore cpu1 execution from asynchronous to synchronous to ensure that cpu1 is restored.
    
    Signed-off-by: hujun5 <hujun5@xiaomi.com>
```

**Comment by hujun260** [comment]
> @hujun260
> 
> I think that 'cpu: ' in the commit log is too generic and would lead to misunderstanding. My recommendation is to use 'arm64: ' instead.
> 
> ```
> commit 6063c0516e9899230d6de9e1c9ac8ca1bfbd0143 (tag: nuttx-20230424-015132)
> Author: hujun5 <hujun5@xiaomi.com>
> Date:   Fri Apr 7 17:11:33 2023 +0800
> 
>     cpu: in SMP pthread_cancel occasionally deadlock
>     
>     In smp when cpu0 calls up_cpu_resume to release the cpu1 lock, another locked cpu1 did not execute immediately,
>     and soon cpu0 called up_cpu_resume again, now cpu1 unable to respond to the interrupt at this time, resulting in a deadlock.
>     Our solution is to restore cpu1 execution from asynchronous to synchronous to ensure that cpu1 is restored.
>     
>     Signed-off-by: hujun5 <hujun5@xiaomi.com>
> ```

The deadlock problem caused by up_cpu_resume widely exists in the SMP mode. My patch only fixes the problem under the arm64 architecture, and other architecture repair methods are similar

**Comment by hujun260** [comment]
> @hujun260
> 
> I think that 'cpu: ' in the commit log is too generic and would lead to misunderstanding. My recommendation is to use 'arm64: ' instead.
> 
> ```
> commit 6063c0516e9899230d6de9e1c9ac8ca1bfbd0143 (tag: nuttx-20230424-015132)
> Author: hujun5 <hujun5@xiaomi.com>
> Date:   Fri Apr 7 17:11:33 2023 +0800
> 
>     cpu: in SMP pthread_cancel occasionally deadlock
>     
>     In smp when cpu0 calls up_cpu_resume to release the cpu1 lock, another locked cpu1 did not execute immediately,
>     and soon cpu0 called up_cpu_resume again, now cpu1 unable to respond to the interrupt at this time, resulting in a deadlock.
>     Our solution is to restore cpu1 execution from asynchronous to synchronous to ensure that cpu1 is restored.
>     
>     Signed-off-by: hujun5 <hujun5@xiaomi.com>
> ```

You are right, I will pay attention next time.

**Comment by masayuki2009** [comment]
>In smp when cpu0 calls up_cpu_resume to release the cpu1 lock, another locked cpu1 did not execute immediately, and soon cpu0 called up_cpu_resume again, now cpu1 unable to respond to the interrupt at this time, resulting in a deadlock. Our solution is to restore cpu1 execution from asynchronous to synchronous to ensure that cpu1 is restored.

@hujun260 
Could you tell us how to reproduce the issue with the ostest?

**Comment by hujun260** [comment]
> > In smp when cpu0 calls up_cpu_resume to release the cpu1 lock, another locked cpu1 did not execute immediately, and soon cpu0 called up_cpu_resume again, now cpu1 unable to respond to the interrupt at this time, resulting in a deadlock. Our solution is to restore cpu1 execution from asynchronous to synchronous to ensure that cpu1 is restored.
> 
> @hujun260 Could you tell us how to reproduce the issue with the ostest?

I found that this issue is in the test case pthread_rwlock_cancel_test(), where pthread_cancel() will get stuck.
The replication method is to start multiple qemu and conduct stress testing. 
There is a certain probability that it will occur,
and the analysis conclusion is that the CPU cannot respond to interrupts, resulting in a deadlock.

**Pull request merged**
