### PR TITLE
Revert "enable O_CLOEXEC explicit"

### PR DESCRIPTION
**Pull request by masayuki2009**
Reverts apache/nuttx#10758 since rv-virt:knsh64 crashed at boot.

### CODE REVIEW

**Comment by gneworld** [comment]
@masayuki2009 
How should I reproduce your issue？

image

**Comment by masayuki2009** [comment]
>@masayuki2009
>How should I reproduce your issue？

Please read nuttx/boards/risc-v/qemu-rv/rv-virt/README.txt for the build.

**Comment by gneworld** [comment]
@masayuki2009

**Comment by gneworld** [comment]
@masayuki2009 

image

**Comment by gneworld** [comment]
@masayuki2009 

I have found the root cause of this issue and am working on fixing it as soon as possible. Please wait for a moment, sorry for any inconvenience~


b56e43db-ba06-4285-8c6b-acf4ce5c89a3

**Comment by xiaoxiang781216** [comment]
@masayuki2009 could you review the fix here: https://github.com/apache/nuttx/pull/10779?

**Comment by masayuki2009** [comment]
>@masayuki2009 could you review the fix here: https://github.com/apache/nuttx/pull/10779?

Let me close this issue since the PR fixes the issue.

**Pull request closed without merging**
