### PR TITLE
libc: Refine the arc4random_buf implementation

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
*Note: Please adhere to [Contributing Guidelines](https://github.com/apache/nuttx/blob/master/CONTRIBUTING.md).*

## Summary

fill the buffer with getrandom instead random pool and move the implementation to from crypto to libc

## Impact

Make arc4random_buf always available

## Testing

ci

### CODE REVIEW

**Comment by nuttxpr** [comment]
[**\[Experimental Bot, please feedback here\]**](https://github.com/search?q=repo%3Aapache%2Fnuttx+13552&type=issues)



**No, this PR does not fully meet the NuttX requirements.**

**Missing Information:**

* **Summary:**
    * Lacks a clear explanation of *why* the change from `random pool` to `getrandom` is necessary. What problem does it solve? 
    *  Needs more detail on the functional code changes. "move the implementation from crypto to libc" is vague. Be specific about functions or modules impacted. 
* **Impact:**
    *  While "Make arc4random_buf always available" is a result, explain *how* this impacts users or the system. Is there a performance difference? Why is this availability important?
    *  The impact sections are largely incomplete. Address *all* points (build, hardware, documentation, security, compatibility) with either "NO" or a "YES" + explanation.
* **Testing:**
    * "ci" is insufficient. Provide actual build host and target details as requested.
    *  "Testing logs before/after" are missing entirely. Show evidence of the problem the PR fixes AND that it now works as intended. 

**Recommendations:**

1. **Expand the Summary:**  Clearly articulate the problem and solution. Provide specific code-level details.
2. **Complete Impact Assessment:** Address all impact points. Even if the answer is "NO", state it explicitly. 
3. **Provide Detailed Testing Information:** Include build host/target specifics and relevant logs demonstrating the change's effect.

**By providing this missing information, your PR will be much stronger and easier for reviewers to understand and approve.**

**Review by anchao — APPROVED** [review]

**Comment by acassis** [comment]
@xiaoxiang781216 maybe we need to update the random number generation Documentation/ to explain that up_rngbuf() now is used to fill the randomness pool

**Review by cederom — CHANGES_REQUESTED** [review]
Thank you @xiaoxiang781216 :-) Build errors :-) + documentation update needed? :-)

**Comment by xiaoxiang781216** [comment]
> @xiaoxiang781216 maybe we need to update the random number generation Documentation/ to explain that up_rngbuf() now is used to fill the randomness pool

but we don't have any document which describe random pool.

**Comment by xiaoxiang781216** [comment]
> Thank you @xiaoxiang781216 :-) Build errors :-) + documentation update needed? :-)

fixed.

**Comment by cederom** [comment]
> > @acassis: @xiaoxiang781216 maybe we need to update the random number generation Documentation/ to explain that up_rngbuf() now is used to fill the randomness pool
> 
> @xiaoxiang781216: but we don't have any document which describe random pool.

Okay then nothing to update :-P But I agree some documentation would be nice to have here (different task), random is important, for instance would random work without hardware entropy generator and with software implementation with `arc4random` and how that impacts security (i.e. mbedtls)? :-)

**Comment by acassis** [comment]
@xiaoxiang781216 @cederom exactly! How to integrate HW RNG, how to use pseudo random generator without HW RNG, etc

**Comment by cederom** [comment]
Okay, TODO added in Issue https://github.com/apache/nuttx/issues/14511 :-)

**Comment by lupyuen** [comment]
Sorry @xiaoxiang781216: The arm-04 build is failing at the NuttX Mirror Repo, wonder if it's because of this PR? Thanks!
```text
Configuration/Tool: lc823450-xgevk/krndis,CONFIG_ARM_TOOLCHAIN_GNU_EABI
arm-none-eabi-ld: /github/workspace/sources/nuttx/staging//libc.a(lib_arc4random.o): in function `arc4random_buf':
/github/workspace/sources/nuttx/libs/libc/stdlib/lib_arc4random.c:111:(.text.arc4random_buf+0x26): undefined reference to `clock_systime_ticks'
```
https://github.com/NuttX/nuttx/actions/runs/11540264972/job/32129220872#step:7:101

**Comment by xiaoxiang781216** [comment]
Fix here: https://github.com/apache/nuttx/pull/14523

**Pull request merged**
