### PR TITLE
build: Fix Toolchain.cmake for CONFIG_SIM_ASAN enabled

### PR DESCRIPTION
**Pull request by Jasinsky**
Hello NuttX community :)

This commit adds missing add_link_options to specify sanitizers also during linking stage.
Similar situation as my previous PR (https://github.com/apache/nuttx/pull/12856) - makefile based build was working, CMake failed during linking stage.

## Summary

Sanitizers flags should be specified during link stage as well.

## Impact

Hard to estimate.

## Testing

Local fiddling around sim:asan build using CMake + Ninja generator.

### CODE REVIEW

**Comment by Jasinsky** [comment]
@acassis @anchao - for your visiblity.
Thanks :)

**Comment by Jasinsky** [comment]
Shall we also do something about enabling these builds in CI/CD i.e. - modifying sim-01.dat by adding in boards build by CMake section?
```
# Boards build by CMake
...
```

**Comment by anchao** [comment]
> Shall we also do something about enabling these builds in CI/CD i.e. - modifying sim-01.dat by adding in boards build by CMake section?
> 
> ```
> # Boards build by CMake
> ...
> ```

Sure, please migrate the sim/asan configuration to CMake build.

**Review by anchao — APPROVED** [review]
LGTM

**Review by xiaoxiang781216 — APPROVED** [review]

**Pull request merged**
