### PR TITLE
sim: add sqlite configuration

### PR DESCRIPTION
**Pull request by Gary-Hobson**
## Summary
Add sqlite based on sim/minibasic configuration

## Impact
Since hostfs does not support FIOC_FILEPATH, it cannot currently be used in hostfs

## Testing
```
nsh> cd tmp
nsh> ls
/tmp:

nsh> sqlite3 test.db
SQLite version 3.45.1 2024-01-30 16:01:20
Enter ".help" for usage hints.
sqlite> 

 CREATE TABLE COMPANY(
   ID INT PRIMARY KEY     sqlite> (x1...> NOT NULL,
   NAME           TEXT    NOT NULL,
   AGE            (x1...> (x1...> INT     NOT NULL,
   ADDRESS        CHAR(50),
   SALARY         (x1...> (x1...> REAL
);(x1...> 

sqlite> .schema COMPANY
CREATE TABLE COMPANY(
   ID INT PRIMARY KEY     NOT NULL,
   NAME           TEXT    NOT NULL,
   AGE            INT     NOT NULL,
   ADDRESS        CHAR(50),
   SALARY         REAL
);
sqlite> .quit
sqlite> 
nsh> 
nsh> ls -l
/tmp:
 -rwxrwxrwx       12288 test.db
```

### CODE REVIEW

**Review by acassis — APPROVED** [review]

**Review by acassis — CHANGES_REQUESTED** [review]
Please include the Summary execution example as a board config entry here: https://nuttx.apache.org/docs/latest/platforms/sim/sim/boards/sim/index.html

**Comment by acassis** [comment]
ping @Gary-Hobson

**Comment by Gary-Hobson** [comment]
> ping @Gary-Hobson

Documentation has been added, but this PR still needs to wait for https://github.com/apache/nuttx/pull/12303 to be merged, but it also depends on 2396
Documentation has been added, but this PR still needs to wait for fff to be merged, however it still depends on https://github.com/apache/nuttx-apps/pull/2396

If there are no other problems with CI, it can be merged tomorrow.

**Comment by xiaoxiang781216** [comment]
> ## Impact
> Since hostfs does not support FIOC_FILEPATH, it cannot currently be used in hostfs
> 

Please upstream the patch which make hostfs support FIOC_FILEPATH.

**Pull request merged**
