### PR TITLE
USB: Add usb fs driver for userspace transfer

### PR DESCRIPTION
**Pull request by zyfeier**
## Summary

Add usb_fs driver so that userspace can directly transfer USB packets through the EP node.
ADB, Fastboot, MTP will use usb_fs, these class driver only need to provide the descriptor information and register the usb_fs device.

This PR depends on https://github.com/spiriou/microADB/pull/36.

## Impact

microADB device change from /dev/adb0 to /dev/adb0/ep1 and dev/adb0/ep2

## Testing

sim:usbdev and bes board usb adb

### CODE REVIEW

**Comment by acassis** [comment]
@spiriou please take a look!

**Comment by spiriou** [comment]
> @spiriou please take a look!

I'm not sure to understand how this PR would change the way EP are exposed to apps.
I can only see USB descriptors refactoring here. Can you share more details?

**Comment by zyfeier** [comment]
> > @spiriou please take a look!
> 
> I'm not sure to understand how this PR would change the way EP are exposed to apps. I can only see USB descriptors refactoring here. Can you share more details?

The patch has been updated, please take a look.

**Comment by xiaoxiang781216** [comment]
> > @spiriou please take a look!
> 
> I'm not sure to understand how this PR would change the way EP are exposed to apps. I can only see USB descriptors refactoring here. Can you share more details?

@spiriou the major change is:

1. Move the common code to usbdev_fs, so all pass-through driver(e.g. adb, fastboot, mtp) can share the implementation.
2. Split dev/adb0 to /dev/adb0/ep0 and /dev/adb0/ep1 since many usb driver has more than two data endpoint.

**Comment by xiaoxiang781216** [comment]
> > @spiriou please take a look!
> 
> I'm not sure to understand how this PR would change the way EP are exposed to apps. I can only see USB descriptors refactoring here. Can you share more details?

@spiriou the major change is:

1. Move the common code to usbdev_fs, so all pass-through driver(e.g. adb, fastboot, mtp) can share the implementation.
2. Split dev/adb0 to /dev/adb0/ep0 and /dev/adb0/ep1 since usb interface may have more than two data endpoints.

**Comment by spiriou** [comment]
> > > @spiriou please take a look!
> > 
> > 
> > I'm not sure to understand how this PR would change the way EP are exposed to apps. I can only see USB descriptors refactoring here. Can you share more details?
> 
> @spiriou the major change is:
> 
> 1. Move the common code to usbdev_fs, so all pass-through driver(e.g. adb, fastboot, mtp) can share the implementation.
> 2. Split dev/adb0 to /dev/adb0/ep0 and /dev/adb0/ep1 since many usb driver has more than two data endpoint.

I'm not against this change although I feel like a char device with a single file descriptor makes more sense to interact with the ADB device endpoints, compared to 2 (ie. 1 file descriptor for read operations and another one for write operations). The ADB driver is very similar to the CDC ACM in terms of "userspace" interactions.

I'll merge the change [https://github.com/spiriou/microADB/pull/36](https://github.com/spiriou/microADB/pull/36) once this PR is in.

**Review by xiaoxiang781216 — APPROVED** [review]

**Pull request merged**
