### PR TITLE
include/nuttx.h: replace all the align macros to nuttx version

### PR DESCRIPTION
**Pull request by CV-Bowen**
## Summary
1. add IS_ALIGNED()  definitions for NuttX;
2. replace all the ALIGN_UP() and ALIGN_DOWN() to use common align implementation;

## Impact
Only code refactore

## Testing
CI

### CODE REVIEW

**Comment by CV-Bowen** [comment]
CI Failed, because the macro `ALIGN_UP` redefined with 3rdparty code.
@acassis Could you take a look at this? Maybe we need modify the codes in esp-hal-3rdparty?
```
chip/esp-hal-3rdparty/components/bootloader_support/src/esp_image_format.c:45: error: "ALIGN_UP" redefined [-Werror]
   45 | #define ALIGN_UP(num, align) (((num) + ((align) - 1)) & ~((align) - 1))
      | 
In file included from /Users/runner/work/nuttx/nuttx/sources/nuttx/include/arch/irq.h:36,
                 from /Users/runner/work/nuttx/nuttx/sources/nuttx/include/nuttx/irq.h:37,
                 from /Users/runner/work/nuttx/nuttx/sources/nuttx/include/nuttx/fs/fs.h:43,
                 from /Users/runner/work/nuttx/nuttx/sources/nuttx/include/stdio.h:34,
                 from /Users/runner/work/nuttx/nuttx/sources/nuttx/arch/xtensa/src/chip/esp-hal-3rdparty/components/esp_common/include/esp_err.h:10,
                 from /Users/runner/work/nuttx/nuttx/sources/nuttx/arch/xtensa/src/chip/esp-hal-3rdparty/components/esp_hw_support/include/esp_intr_alloc.h:11,
                 from /Users/runner/work/nuttx/nuttx/sources/nuttx/arch/xtensa/src/chip/esp-hal-3rdparty/components/esp_hw_support/include/esp_cpu.h:20,
                 from chip/esp-hal-3rdparty/components/bootloader_support/src/esp_image_format.c:8:
/Users/runner/work/nuttx/nuttx/sources/nuttx/include/nuttx/nuttx.h:49: note: this is the location of the previous definition
   49 | #  define ALIGN_UP(x,a)        (((x) + ((a) - 1)) & ~((a) - 1))
      | 
cc1: all warnings being treated as errors
make[1]: *** [chip/esp-hal-3rdparty/components/bootloader_support/src/esp_image_format.o] Error 1
make[1]: Target `libarch.a' not remade because of errors.
make: *** [arch/xtensa/src/libarch.a] Error 2
make: Target `all' not remade because of errors.
/Users/runner/work/nuttx/nuttx/sources/nuttx/tools/testbuild.sh: line 378: /Users/runner/work/nuttx/nuttx/sources/nuttx/../nuttx/nuttx.manifest: No such file or directory
  Normalize esp32-devkitc/wifi
```

**Comment by acassis** [comment]
@tmedicci could you please consider adding a #ifndef ALIGN_UP to wrap the definition?

**Comment by CV-Bowen** [comment]
@tmedicci Hello, could you help us to modify the code? Or this is also an opensoure repo and I can crate PR to do fix this re-definition issue?

**Comment by CV-Bowen** [comment]
Deleted the branch by mistake, restore.

**Review by xiaoxiang781216 — APPROVED** [review]

**Review by GUIDINGLI — APPROVED** [review]

**Pull request merged**
