### PR TITLE
nuttx: mics fixes found during code review

### PR DESCRIPTION
**Pull request by pkarashchenko**
## Summary
Mics fixes found during code review

## Impact
N/A

## Testing
Pass CI

### CODE REVIEW

**Review by acassis — APPROVED** [review]

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by pkarashchenko** [comment]
@xiaoxiang781216 I introduced a compilation issue for some of RISC-V ESP32 boards. I'll try to fix this ASAP as I didn't notice that some bits manipulation macro are available only for xtensa version of ESP32

**Comment by pkarashchenko** [comment]
https://github.com/apache/nuttx/pull/10643 should fix compilation. Let's wait RISC-V CI to finish

**Comment by xiaoxiang781216** [comment]
> #10643 should fix compilation. Let's wait RISC-V CI to finish

We need fix the remaining macOS ci failure ASAP to avoid merging the patch with ci failure since it's too easy to make the mistake.

**Comment by pkarashchenko** [comment]
Maybe I can create a patch for the existing version of libuv instead of doing an upgrade?

**Comment by xiaoxiang781216** [comment]
> Maybe I can create a patch for the existing version of libuv instead of doing an upgrade?

The current libuv(1.42.0) was released at Jul 23, 2021, it's time to upgrade to the last stable release(v.1.46.0). @no1wudi already prepare the patch here: https://github.com/apache/nuttx-apps/pull/2066

**Comment by pkarashchenko** [comment]
Yes, but CI still can't pass

**Comment by xiaoxiang781216** [comment]
It can be fixed quickly. The major block issue is how to fix libcxx build error

**Pull request merged**
