### PR TITLE
kasan: Complete the creation of global variable shadow areas during c…

### PR DESCRIPTION
**Pull request by 0528Mike**
…ompilation

Implement out-of-bounds detection of global variable access, only modified to support arm, arm64 and sim

## Summary
Global variable out-of-bounds detection optimization practices
## Testing
The test has been successful and the program will be submitted to the app

### CODE REVIEW

**Comment by 0528Mike** [comment]
why this check is failed, how can I reproduce this error locally?

**Comment by xiaoxiang781216** [comment]
https://github.com/apache/nuttx/actions/runs/8278875678/job/22652132468?pr=11917
```
./tools/checkpatch.sh -g HEAD~...HEAD
```

**Comment by xiaoxiang781216** [comment]
@0528Mike please fix python script error reported here:
https://github.com/apache/nuttx/actions/runs/8291098297/job/22690319748?pr=11917

**Comment by 0528Mike** [comment]
> @0528Mike please fix python script error reported here: https://github.com/apache/nuttx/actions/runs/8291098297/job/22690319748?pr=11917

OK, due to personal reason，I will check the python scripts in two days, clear the errors and submit them.

**Comment by W-Mai** [comment]
`camke -GNinja -DNUTTX_APPS_DIR=../apps -DBOARD_CONFIG=sim:posix_test ..`

I tested `sim:posix` locally and got such an error.

```bash
/opt/homebrew/Cellar/llvm/17.0.6/bin/clang -Wstrict-prototypes -g -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.4.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names  CMakeFiles/nuttx.dir/arch/sim/src/sim/posix/sim_hostirq.c.o CMakeFiles/nuttx.dir/arch/sim/src/sim/posix/sim_hostmemory.c.o CMakeFiles/nuttx.dir/arch/sim/src/sim/posix/sim_hostmisc.c.o CMakeFiles/nuttx.dir/arch/sim/src/sim/posix/sim_hosttime.c.o CMakeFiles/nuttx.dir/arch/sim/src/sim/posix/sim_hostuart.c.o CMakeFiles/nuttx.dir/arch/sim/src/sim/posix/sim_testset.c.o CMakeFiles/nuttx.dir/arch/sim/src/sim/posix/sim_hostfs.c.o CMakeFiles/nuttx.dir/empty.c.o -o nuttx  nuttx.rel  -lpthread  -lz  -lc++abi  -lm && :
Undefined symbols for architecture arm64:
  "_g_allsyms", referenced from:
      _main in nuttx.rel
      _main in nuttx.rel
      _main in nuttx.rel
      _main in nuttx.rel
      _main in nuttx.rel
      _main in nuttx.rel
  "_g_nallsyms", referenced from:
      _main in nuttx.rel
      _main in nuttx.rel
      _main in nuttx.rel
      _main in nuttx.rel
      _main in nuttx.rel
ld: symbol(s) not found for architecture arm64
```

If there is a problem with the generation of the elf file, resulting in an error in the parsing of the python script, it makes sensible.

**Pull request closed without merging**
